SET AAA(CCCRRRAAA)  'All areas'                         
                                                        
/                                                       
HSTAN_A1
HSTAN_A2
WINDIA_A1
WINDIA_A2                                         
/;                                                      
                                                        
                                                        
                                           
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
