TABLE AGKN1(GGG,AAA)
                                                         HSTAN_A1        HSTAN_A2        WINDIA_A1       WINDIA_A2
GNR_PV_SUN_LS-4-MW_Y-2020                                1                               1
GNR_WT_WIND_ON_LS_Y-2020                                 1                               1
GNR_CC_NGAS_CND_E-59_LS-100-MW_Y-2020                    1                               1
GNR_ES_ELEC_BAT-LITHIO-PEAK_E-86_Y-20-29                 1                               1
GNR_BO_ELEC_E-99_LS-10-MW-FEED_Y-2020                                    1                               1
GNR_BO_WOODCHI_E-117_LS-6-MW-FEED_Y-2020                                 1                               1
GNR_BO_NGAS_E-105_SS-500-KW_Y-2020                                       1                               1
GNR_ST_NGAS_EXT_E-47_LS-400-MW_Y-2020                                    1                               1
GNR_ENG_NGAS_BP_E-47_Y-2020                                              1                               1
GNR_ST_WOODCHI_BP_E-29_LS-600-MW-FEED_Y-2020                             1                               1
GNR_HS_HEAT_WTR-TANK_LS_E-95_Y-2010                                      1                               1
;



AGKN(AAA,GGG)=YES$AGKN1(GGG,AAA);


