SET AGKNDISC(AAA,G) "Areas for possible location of new technologies taking discrete capacity size investments"                                            
/                                                                                                                                                          
DK2_NoDH                                                                                                         .    GNR_ES_ELEC_BAT-LITHIO_E-97_Y-30-50  
NO2_A1                                                                                                           .    GNR_ENG_BGAS_CND_E-45_Y-2030         
SE4_large                                                                                                        .    GNR_BO_ELEC_E-99_LS-10-MW-FEED_Y-2020
/;                                                                                                                                                         
