SET AGKNDISCSIZESET    "Set of possible sizes for discrete capacity investments in technologies" 
 /                                                                                               
AGKNDISCSIZE1                                                                                    
AGKNDISCSIZE2                                                                                    
AGKNDISCSIZE3                                                                                    
/;                                                                                               
