SET AGKNDISC(AAA,G) "Areas for possible location of new technologies taking discrete capacity size investments"                                            
/                                                                                                                                                          
/;                                                                                                                                                         
