PARAMETER AGKNDISCDATA(G,AGKNDISCSIZESET,AGKNDISCDATASET) "Technology investment data for discrete capacity size investments" ;                                               
TABLE AGKNDISCDATA(G,AGKNDISCSIZESET,AGKNDISCDATASET) "Technology investment data for discrete capacity size investments"                                                     
;                                                                                                                                                                             
