PARAMETER AGKNDISCDATA(G,AGKNDISCSIZESET,AGKNDISCDATASET) "Technology investment data for discrete capacity size investments" ;                                               
TABLE AGKNDISCDATA(G,AGKNDISCSIZESET,AGKNDISCDATASET) "Technology investment data for discrete capacity size investments"                                                     
                                                                                                                                 AGKNDISCSIZE AGKNDISCINVCOST AGKNDISCGOMFCOST
*                                                                                                                                MW           MMoney          kMoney/MW       
GNR_ES_ELEC_BAT-LITHIO_E-97_Y-30-50.AGKNDISCSIZE1                                                                                10           10.2            30              
GNR_ENG_BGAS_CND_E-45_Y-2030.AGKNDISCSIZE2                                                                                       12           100             50              
GNR_BO_ELEC_E-99_LS-10-MW-FEED_Y-2020.AGKNDISCSIZE3                                                                              18           100             100             
;                                                                                                                                                                             
