PARAMETER TERTIARY_RESERVES(YYY,RRR) 'Tertiary reserve requirement in each hour (MW)'
/                                
2016.DK1     90                             
2016.DK2     90                             
2016.FIN     90                             
2016.DE4-E   90                             
2016.DE4-N   90                             
2016.DE4-S   90                             
2016.DE4-W   90                             
2016.NL      90                             
2016.NO1     90                             
2016.NO2     90                             
2016.NO3     90                             
2016.NO4     90                             
2016.NO5     90                             
2016.SE1     90                             
2016.SE2     90                             
2016.SE3     90                             
2016.SE4     90                             
2016.UK      90                             
2016.EE      90                             
2016.LV      90                             
2016.LT      90                             
2016.PL      90                             
2016.BE      90                             
2016.FR      90                             
                                 
/;                               
TERTIARY_RESERVES(Y,IR)= TERTIARY_RESERVES('2016',IR) ;