PARAMETER FCRUP(YYY,CCCRRRAAA) 'FCR up regulation requirement in each hour (MW)'
/
2016.DK1                  25
2016.DK2                 123
2016.FINLAND             397
2016.GERMANY             632
2016.NETHERLANDS         136
2016.NORWAY              563
2016.SWEDEN              642
2016.UNITED_KINGDOM     1800
2016.ESTONIA             233
2016.LATVIA              233
2016.LITHUANIA           233
2016.POLAND              165
2016.BELGIUM             101
2016.FRANCE              586

/;

FCRUP(Y,CCCRRRAAA)= FCRUP('2016',CCCRRRAAA) ;
