PARAMETER ANNUITYC(CCC) 'Transforms investment to annual payment (fraction)'       
* Thus, for instance, an investment of 100, paid over 20 years,                    
* at the end of the year assuming an interest rate of 5%,                          
* will imply an annual payment of 8.02,                                            
* hence, ANNUITYC should in this case have the value 0.0802.                       
* Unit: (none).                                                                    
* The present value 0.094 corressponds to 20 years and 7%                          
/                                                                                  
GERMANY                                                                      0.094 
DENMARK                                                                      0.094 
FINLAND                                                                      0.094 
NETHERLANDS                                                                  0.094 
NORWAY                                                                       0.094 
SWEDEN                                                                       0.094 
UNITED_KINGDOM                                                               0.094 
ESTONIA                                                                      0.094 
LATVIA                                                                       0.094 
LITHUANIA                                                                    0.094 
POLAND                                                                       0.094 
ITALY                                                                        0.094 
SWITZERLAND                                                                  0.094 
AUSTRIA                                                                      0.094 
CZECH_REPUBLIC                                                               0.094 
SPAIN                                                                        0.094 
PORTUGAL                                                                     0.094 
SLOVAKIA                                                                     0.094 
HUNGARY                                                                      0.094 
SLOVENIA                                                                     0.094 
CROATIA                                                                      0.094 
ROMANIA                                                                      0.094 
BULGARIA                                                                     0.094 
GREECE                                                                       0.094 
IRELAND                                                                      0.094 
LUXEMBOURG                                                                   0.094 
ALBANIA                                                                      0.094 
MONTENEGRO                                                                   0.094 
NORTH_MACEDONIA                                                              0.094 
BOSNIA_AND_HERZEGOVINA                                                       0.094 
SERBIA                                                                       0.094 
TURKEY                                                                       0.094 
MALTA                                                                        0.094 
CYPRUS                                                                       0.094 
                                                                                   
/;                                                                                 
