PARAMETER ANNUITYC(CCC) 'Transforms investment to annual payment (fraction)'       
* Thus, for instance, an investment of 100, paid over 20 years,                    
* at the end of the year assuming an interest rate of 5%,                          
* will imply an annual payment of 8.02,                                            
* hence, ANNUITYC should in this case have the value 0.0802.                       
* Unit: (none).                                                                    
* The present value 0.094 corressponds to 20 years and 7%                          
/                                                                                  
DENMARK                                                                      0.094 
NORWAY                                                                       0.094 
                                                                                   
/;                                                                                 
