PARAMETER ANNUITYCG(CCC,GGG) 'Transforms investment to annual payment (fraction)'
;                                                                                
ANNUITYCG(CCC,GGG)=0.094;                                                        
                                                                                 
                                                                                 
