SET AREA_AGGREGATION(AAA,A_ALIAS)        'Areas to aggregate'        
/                                                                    
DK1_Medium                         .(   DK1_MedSmall          )      
DK2_Medium                         .(   DK2_MedSmall          )      
DK1_Small                          .(   DK1_Rural             )      
DK2_Small                          .(   DK2_Rural             )      
EE_Tallinn                         .(   EE_Parnu                     
                                        EE_Tartu              )      
EE_Enefit                          .(   EE_Kohtla_Jarve              
                                         EE_Rural                    
                                         EE_Sillamae                 
                                         EE_Urban             )      
LT_KauU                            .(   LT_KlaU                      
                                        LT_VilU               )      
LT_Other_DH                        .(   LT_Panevezys                 
                                        LT_Rural              )      
LV_Other_DH                        .(   LT_SiaU               )      
/;                                                                   
                                                                     
                                                                     
                                                                     
