SET C(CCC)  'Countries in the simulation' 
/                                         
*ALBANIA                                  
AUSTRIA                                  
BELGIUM                                   
*BOSNIA_AND_HERZEGOVINA                   
*BULGARIA                                 
*CROATIA                                  
*CYPRUS                                   
*CZECH_REPUBLIC                           
DENMARK                                   
ESTONIA                                   
FINLAND                                   
FRANCE                                   
GERMANY                                   
*GREECE                                   
*HUNGARY                                  
IRELAND                                  
ITALY                                    
LATVIA                                    
LITHUANIA                                 
*LUXEMBOURG                               
*MALTA                                    
*MONTENEGRO                               
NETHERLANDS                               
*NORTH_MACEDONIA                          
NORWAY                                    
POLAND                                    
PORTUGAL                                 
*ROMANIA                                  
*SERBIA                                   
*SLOVAKIA                                 
*SLOVENIA                                 
SPAIN                                    
SWEDEN                                    
SWITZERLAND                              
*TURKEY                                   
UNITED_KINGDOM                            
/;                                        
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                          
