* All sets that are related to Geographical resolution                                                    
                                                                                                          
SET CCCRRRAAA                                               'All geographical entities (CCC + RRR + AAA)' 
/                                                                                                         
* Countries:                                                                                              
HYDROSTAN
WINDIA                                                                                                   
                                                                                                          
                                                                                                          
* Regions:                                                                                                
HSTAN_R1
WINDIA_R1                                                                                                          
                                                                                                          
* Areas:                                                                                                  
HSTAN_A1
HSTAN_A2
WINDIA_A1
WINDIA_A2
/;                                                                                                        
                                                                                                          
