* All sets that are related to Geographical resolution     
                                                           
SET CCCRRRAAA 'All geographical entities (CCC + RRR + AAA)'
/                                                          
* Countries:                                               
NORWAY                                                     
DENMARK                                                    
                                                           
* Regions:                                                 
DK1                                                        
DK2                                                        
NO1                                                        
NO2                                                        
NO3                                                        
NO4                                                        
NO5                                                        
                                                           
                                                           
                                                           
                                                           
                                                           
* Areas:                                                   
NO1_A1                                                     
NO1_A2                                                     
NO1_A3                                                     
NO2_A1                                                     
NO2_A2                                                     
NO3_A1                                                     
NO3_A2                                                     
NO3_A3                                                     
NO4_A1                                                     
NO4_A2                                                     
NO5_A1                                                     
NO5_A2                                                     
DK1_Large                                                  
DK1_Rural                                                  
DK1_Medium                                                 
DK2_Large                                                  
DK2_Rural                                                  
DK2_Medium                                                 
DK2_MedSmall                                               
DK1_Small                                                  
DK1_MedSmall                                               
DK2_Small                                                  
DK2_NoDH                                                   
DK1_NoDH                                                   
DK1_Offshore                                               
DK2_Offshore                                               
DK2_VRE-OFF1_20-30                                         
DK1_VRE-OFF1_20-30                                         
NO3_VRE-OFF1_20-30                                         
NO4_VRE-OFF1_20-30                                         
NO2_VRE-OFF1_20-30                                         
NO5_VRE-OFF1_20-30                                         
DK2_VRE-OFF1_30-40                                         
DK1_VRE-OFF1_30-40                                         
NO3_VRE-OFF1_30-40                                         
NO4_VRE-OFF1_30-40                                         
NO2_VRE-OFF1_30-40                                         
NO5_VRE-OFF1_30-40                                         
DK2_VRE-OFF1_40-50                                         
DK1_VRE-OFF1_40-50                                         
NO3_VRE-OFF1_40-50                                         
NO4_VRE-OFF1_40-50                                         
NO2_VRE-OFF1_40-50                                         
NO5_VRE-OFF1_40-50                                         
DK2_VRE-OFF1_50                                            
DK1_VRE-OFF1_50                                            
NO3_VRE-OFF1_50                                            
NO4_VRE-OFF1_50                                            
NO2_VRE-OFF1_50                                            
NO5_VRE-OFF1_50                                            
DK1_VRE-ONS_20-30                                          
DK2_VRE-ONS_20-30                                          
NO1_VRE-ONS_20-30                                          
NO2_VRE-ONS_20-30                                          
NO3_VRE-ONS_20-30                                          
NO4_VRE-ONS_20-30                                          
DK1_VRE-ONS_30-40                                          
DK2_VRE-ONS_30-40                                          
NO1_VRE-ONS_30-40                                          
NO2_VRE-ONS_30-40                                          
NO3_VRE-ONS_30-40                                          
NO4_VRE-ONS_30-40                                          
DK1_VRE-ONS_40-50                                          
DK2_VRE-ONS_40-50                                          
NO1_VRE-ONS_40-50                                          
NO2_VRE-ONS_40-50                                          
NO3_VRE-ONS_40-50                                          
NO4_VRE-ONS_40-50                                          
DK1_VRE-ONS_50                                             
DK2_VRE-ONS_50                                             
NO1_VRE-ONS_50                                             
NO2_VRE-ONS_50                                             
NO3_VRE-ONS_50                                             
NO4_VRE-ONS_50                                             
NO5_VRE-ONS_20-30                                          
NO5_VRE-ONS_30-40                                          
NO5_VRE-ONS_40-50                                          
NO5_VRE-ONS_50                                             
DK1_VRE-ONS_SP277-HH100                                    
DK2_VRE-ONS_SP277-HH100                                    
NO1_VRE-ONS_SP277-HH100                                    
NO2_VRE-ONS_SP277-HH100                                    
NO3_VRE-ONS_SP277-HH100                                    
NO4_VRE-ONS_SP277-HH100                                    
NO5_VRE-ONS_SP277-HH100                                    
                                                           
/;                                                         
