* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       01_5
* Range:       $A$1:$C$22
* -----------------------------------------------------
SET CCCRRR(CCC,RRR) "Regions in countries"                      
/                                                               
DENMARK                                                .    DK2 
DENMARK                                                .    DK1 
FINLAND                                                .    FIN 
GERMANY                                                .    Ger 
NETHERLANDS                                            .    Ne  
ESTONIA                                                .    EE  
LATVIA                                                 .    LV  
LITHUANIA                                              .    LT  
POLAND                                                 .    PL  
NORWAY                                                 .    NO1 
NORWAY                                                 .    NO2 
NORWAY                                                 .    NO3 
NORWAY                                                 .    NO4 
NORWAY                                                 .    NO5 
SWEDEN                                                 .    SE1 
SWEDEN                                                 .    SE2 
SWEDEN                                                 .    SE3 
SWEDEN                                                 .    SE4 
UNITED_KINGDOM                                         .    UK  
/;                                                              
* -----------------------------------------------------
