SET CCS_G(GGG) "Generation technology with CCS"            
/                                                          
GNR_BO_NGASCCS_E-105_MS-5-MW_Y-2020                        
GNR_BO_NGASCCS_E-106_MS-5-MW_Y-2030                        
GNR_BO_NGASCCS_E-106_MS-5-MW_Y-2040                        
GNR_BO_NGASCCS_E-106_MS-5-MW_Y-2050                        
GNR_CC_NGASCCS_BP_E-51_SS-10-MW_Y-2020                     
GNR_CC_NGASCCS_BP_E-53_SS-10-MW_Y-2030                     
GNR_CC_NGASCCS_BP_E-54_SS-10-MW_Y-2040                     
GNR_CC_NGASCCS_BP_E-55_SS-10-MW_Y-2050                     
GNR_CC_NGASCCS_CND_E-51_SS-10-MW_Y-2020                    
GNR_CC_NGASCCS_CND_E-53_SS-10-MW_Y-2030                    
GNR_CC_NGASCCS_CND_E-54_SS-10-MW_Y-2040                    
GNR_CC_NGASCCS_CND_E-55_SS-10-MW_Y-2050                    
GNR_CC_NGASCCS_CND_E-59_LS-100-MW_Y-2020                   
GNR_CC_NGASCCS_CND_E-61_LS-100-MW_Y-2030                   
GNR_CC_NGASCCS_CND_E-62_LS-100-MW_Y-2040                   
GNR_CC_NGASCCS_CND_E-63_LS-100-MW_Y-2050                   
GNR_CC_NGASCCS_EXT_E-59_LS-100-MW_Y-2020                   
GNR_CC_NGASCCS_EXT_E-61_LS-100-MW_Y-2030                   
GNR_CC_NGASCCS_EXT_E-62_LS-100-MW_Y-2040                   
GNR_CC_NGASCCS_EXT_E-63_LS-100-MW_Y-2050                   
GNR_ENG_NGASCCS_BP_E-47_Y-2020                             
GNR_ENG_NGASCCS_BP_E-48_Y-2030                             
GNR_ENG_NGASCCS_BP_E-49_Y-2040                             
GNR_ENG_NGASCCS_BP_E-50_Y-2050                             
GNR_ENG_NGASCCS_CND_E-47_Y-2020                            
GNR_ENG_NGASCCS_CND_E-48_Y-2030                            
GNR_ENG_NGASCCS_CND_E-49_Y-2040                            
GNR_ENG_NGASCCS_CND_E-50_Y-2050                            
GNR_GT_NGASCCS_BP_E-37_SS-5-MW_Y-2020                      
GNR_GT_NGASCCS_BP_E-39_SS-5-MW_Y-2030                      
GNR_GT_NGASCCS_BP_E-40_SS-5-MW_Y-2040                      
GNR_GT_NGASCCS_BP_E-40_SS-5-MW_Y-2050                      
GNR_GT_NGASCCS_BP_E-42_LS-40-MW_Y-2020                     
GNR_GT_NGASCCS_BP_E-43_LS-40-MW_Y-2030                     
GNR_GT_NGASCCS_BP_E-44_LS-40-MW_Y-2040                     
GNR_GT_NGASCCS_BP_E-44_LS-40-MW_Y-2050                     
GNR_GT_NGASCCS_CND_E-37_SS-5-MW_Y-2020                     
GNR_GT_NGASCCS_CND_E-39_SS-5-MW_Y-2030                     
GNR_GT_NGASCCS_CND_E-40_SS-5-MW_Y-2040                     
GNR_GT_NGASCCS_CND_E-40_SS-5-MW_Y-2050                     
GNR_GT_NGASCCS_CND_E-42_LS-40-MW_Y-2020                    
GNR_GT_NGASCCS_CND_E-43_LS-40-MW_Y-2030                    
GNR_GT_NGASCCS_CND_E-44_LS-40-MW_Y-2040                    
GNR_GT_NGASCCS_CND_E-44_LS-40-MW_Y-2050                    
GNR_IND-DF_NGASCCS_E-100_MS-3-MW_Y-2020                    
GNR_IND-BO_NGASCCS_E-93_MS-20-MW_Y-2020                    
GNR_IND-BO_NGASCCS_E-94_MS-20-MW_Y-2030                    
GNR_IND-BO_NGASCCS_E-95_MS-20-MW_Y-2040                    
GNR_IND-BO_NGASCCS_E-96_MS-20-MW_Y-2050                    
GNR_ST_NGASCCS_CND_E-47_LS-400-MW_Y-2020                   
GNR_ST_NGASCCS_EXT_E-47_LS-400-MW_Y-2020                   
GNR_ST_NGASCCS_BP_E-7_MS-15-MW_Y-2020                      
$ifi %HYDROGEN%==yes GNR_STEAM-REFORMING-CCS_E-70_Y-2020   
/;                                                         
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
