SET GGCOMB(GGG,IGGGALIAS) 'Pair of combination technologies'
/
GNR_BO_NGAS_E-100                                            .    GNR_BO_NGAS_E-100_CT-BGAS-UP
GNR_BO_NGAS_E-100                                            .    GNR_BO_NGAS_E-100_CT-TGAS-UP
GNR_BO_NGAS_E-100                                            .    GNR_BO_NGAS_E-100_CT-BGAS-H2
GNR_BO_NGAS_E-100                                            .    GNR_BO_NGAS_E-100_CT-TGAS-H2
/;
