SET GGG  'All combination technologies'       
/                                             
ACHEMA1_ST_NGAS_EXT_CT-BIONG                  
ACHEMA2_ST_NGAS_EXT_CT-BIONG                  
ALYTUS_ENG_NGAS_BP_CT-BIONG                   
GNR_BO_NGAS_E-100_CT-BIONG                    
GNR_BO_NGAS_E-101_CT-BIONG                    
GNR_BO_NGAS_E-102_CT-BIONG                    
GNR_BO_NGAS_E-103_CT-BIONG                    
GNR_BO_NGAS_E-104_CT-BIONG                    
GNR_BO_NGAS_E-105_CT-BIONG                    
GNR_BO_NGAS_E-105_MS-5-MW_Y-2020_CT-BIONG     
GNR_BO_NGAS_E-106_MS-5-MW_Y-2030_CT-BIONG     
GNR_BO_NGAS_E-106_MS-5-MW_Y-2040_CT-BIONG     
GNR_BO_NGAS_E-106_MS-5-MW_Y-2050_CT-BIONG     
GNR_BO_NGAS_E-80_CT-BIONG                     
GNR_BO_NGAS_E-85_CT-BIONG                     
GNR_BO_NGAS_E-90_CT-BIONG                     
GNR_BO_NGAS_E-97_CT-BIONG                     
GNR_BO_NGAS_E-98_CT-BIONG                     
GNR_BO_NGAS_E-99_CT-BIONG                     
GNR_CC_NGAS_BP_CB-100_CT-BIONG                
GNR_CC_NGAS_BP_CB-110_CT-BIONG                
GNR_CC_NGAS_BP_CB-90_CT-BIONG                 
GNR_CC_NGAS_BP_E-18_CT-BIONG                  
GNR_CC_NGAS_BP_E-30_CT-BIONG                  
GNR_CC_NGAS_BP_E-39_CT-BIONG                  
GNR_CC_NGAS_BP_E-42_CT-BIONG                  
GNR_CC_NGAS_BP_E-51_SS-10-MW_Y-2020_CT-BIONG  
GNR_CC_NGAS_BP_E-53_CT-BIONG                  
GNR_CC_NGAS_BP_E-53_SS-10-MW_Y-2030_CT-BIONG  
GNR_CC_NGAS_BP_E-54_SS-10-MW_Y-2040_CT-BIONG  
GNR_CC_NGAS_BP_E-55_CT-BIONG                  
GNR_CC_NGAS_BP_E-55_SS-10-MW_Y-2050_CT-BIONG  
GNR_CC_NGAS_BP_E-57_CT-BIONG                  
GNR_CC_NGAS_BP_E-59_CT-BIONG                  
GNR_CC_NGAS_CND_E-38_CT-BIONG                 
GNR_CC_NGAS_CND_E-42_CT-BIONG                 
GNR_CC_NGAS_CND_E-43_CT-BIONG                 
GNR_CC_NGAS_CND_E-47_CT-BIONG                 
GNR_CC_NGAS_CND_E-51_CT-BIONG                 
GNR_CC_NGAS_CND_E-51_SS-10-MW_Y-2020_CT-BIONG 
GNR_CC_NGAS_CND_E-52_CT-BIONG                 
GNR_CC_NGAS_CND_E-53_SS-10-MW_Y-2030_CT-BIONG 
GNR_CC_NGAS_CND_E-54_SS-10-MW_Y-2040_CT-BIONG 
GNR_CC_NGAS_CND_E-55_SS-10-MW_Y-2050_CT-BIONG 
GNR_CC_NGAS_CND_E-56_CT-BIONG                 
GNR_CC_NGAS_CND_E-57_CT-BIONG                 
GNR_CC_NGAS_CND_E-58_CT-BIONG                 
GNR_CC_NGAS_CND_E-59_LS-100-MW_Y-2020_CT-BIONG
GNR_CC_NGAS_CND_E-61_LS-100-MW_Y-2030_CT-BIONG
GNR_CC_NGAS_CND_E-62_LS-100-MW_Y-2040_CT-BIONG
GNR_CC_NGAS_CND_E-63_LS-100-MW_Y-2050_CT-BIONG
GNR_CC_NGAS_EXT_E-59_LS-100-MW_Y-2020_CT-BIONG
GNR_CC_NGAS_EXT_E-61_CT-BIONG                 
GNR_CC_NGAS_EXT_E-61_LS-100-MW_Y-2030_CT-BIONG
GNR_CC_NGAS_EXT_E-62_LS-100-MW_Y-2040_CT-BIONG
GNR_CC_NGAS_EXT_E-63_LS-100-MW_Y-2050_CT-BIONG
GNR_ENG_NGAS_BP_CB-100_CT-BIONG               
GNR_ENG_NGAS_BP_E-33_CT-BIONG                 
GNR_ENG_NGAS_BP_E-34_CT-BIONG                 
GNR_ENG_NGAS_BP_E-35_CT-BIONG                 
GNR_ENG_NGAS_BP_E-36_CT-BIONG                 
GNR_ENG_NGAS_BP_E-37_CT-BIONG                 
GNR_ENG_NGAS_BP_E-38_CT-BIONG                 
GNR_ENG_NGAS_BP_E-39_CT-BIONG                 
GNR_ENG_NGAS_BP_E-40_CT-BIONG                 
GNR_ENG_NGAS_BP_E-41_CT-BIONG                 
GNR_ENG_NGAS_BP_E-42_CT-BIONG                 
GNR_ENG_NGAS_BP_E-43_CT-BIONG                 
GNR_ENG_NGAS_BP_E-44_CT-BIONG                 
GNR_ENG_NGAS_BP_E-45_CT-BIONG                 
GNR_ENG_NGAS_BP_E-46_CT-BIONG                 
GNR_ENG_NGAS_BP_E-47_CT-BIONG                 
GNR_ENG_NGAS_BP_E-47_Y-2020_CT-BIONG          
GNR_ENG_NGAS_BP_E-48_Y-2030_CT-BIONG          
GNR_ENG_NGAS_BP_E-49_Y-2040_CT-BIONG          
GNR_ENG_NGAS_BP_E-50_Y-2050_CT-BIONG          
GNR_ENG_NGAS_CND_E-41_CT-BIONG                
GNR_ENG_NGAS_CND_E-44_CT-BIONG                
GNR_ENG_NGAS_CND_E-46_CT-BIONG                
GNR_ENG_NGAS_CND_E-47_Y-2020_CT-BIONG         
GNR_ENG_NGAS_CND_E-48_Y-2030_CT-BIONG         
GNR_ENG_NGAS_CND_E-49_Y-2040_CT-BIONG         
GNR_ENG_NGAS_CND_E-50_Y-2050_CT-BIONG         
GNR_ENG_NGAS_EXT_E-43_CT-BIONG                
GNR_ENG_NGAS_EXT_E-44_CT-BIONG                
GNR_GT_NGAS_BP_CB-150_CT-BIONG                
GNR_GT_NGAS_BP_CB-30_CT-BIONG                 
GNR_GT_NGAS_BP_CB-40_CT-BIONG                 
GNR_GT_NGAS_BP_CB-470_CT-BIONG                
GNR_GT_NGAS_BP_CB-50_CT-BIONG                 
GNR_GT_NGAS_BP_CB-60_CT-BIONG                 
GNR_GT_NGAS_BP_CB-70_CT-BIONG                 
GNR_GT_NGAS_BP_CB-80_CT-BIONG                 
GNR_GT_NGAS_BP_CB-90_CT-BIONG                 
GNR_GT_NGAS_BP_E-27_CT-BIONG                  
GNR_GT_NGAS_BP_E-28_CT-BIONG                  
GNR_GT_NGAS_BP_E-29_CT-BIONG                  
GNR_GT_NGAS_BP_E-30_CT-BIONG                  
GNR_GT_NGAS_BP_E-31_CT-BIONG                  
GNR_GT_NGAS_BP_E-32_CT-BIONG                  
GNR_GT_NGAS_BP_E-33_CT-BIONG                  
GNR_GT_NGAS_BP_E-36_CT-BIONG                  
GNR_GT_NGAS_BP_E-37_CT-BIONG                  
GNR_GT_NGAS_BP_E-37_SS-5-MW_Y-2020_CT-BIONG   
GNR_GT_NGAS_BP_E-38_CT-BIONG                  
GNR_GT_NGAS_BP_E-39_CT-BIONG                  
GNR_GT_NGAS_BP_E-39_SS-5-MW_Y-2030_CT-BIONG   
GNR_GT_NGAS_BP_E-40_SS-5-MW_Y-2040_CT-BIONG   
GNR_GT_NGAS_BP_E-40_SS-5-MW_Y-2050_CT-BIONG   
GNR_GT_NGAS_BP_E-41_CT-BIONG                  
GNR_GT_NGAS_BP_E-42_CT-BIONG                  
GNR_GT_NGAS_BP_E-42_LS-40-MW_Y-2020_CT-BIONG  
GNR_GT_NGAS_BP_E-43_CT-BIONG                  
GNR_GT_NGAS_BP_E-43_LS-40-MW_Y-2030_CT-BIONG  
GNR_GT_NGAS_BP_E-44_CT-BIONG                  
GNR_GT_NGAS_BP_E-44_LS-40-MW_Y-2040_CT-BIONG  
GNR_GT_NGAS_BP_E-44_LS-40-MW_Y-2050_CT-BIONG  
GNR_GT_NGAS_BP_E-47_CT-BIONG                  
GNR_GT_NGAS_CND_E-31_CT-BIONG                 
GNR_GT_NGAS_CND_E-32_CT-BIONG                 
GNR_GT_NGAS_CND_E-33_CT-BIONG                 
GNR_GT_NGAS_CND_E-35_CT-BIONG                 
GNR_GT_NGAS_CND_E-37_SS-5-MW_Y-2020_CT-BIONG  
GNR_GT_NGAS_CND_E-38_CT-BIONG                 
GNR_GT_NGAS_CND_E-39_SS-5-MW_Y-2030_CT-BIONG  
GNR_GT_NGAS_CND_E-40_CT-BIONG                 
GNR_GT_NGAS_CND_E-40_SS-5-MW_Y-2040_CT-BIONG  
GNR_GT_NGAS_CND_E-40_SS-5-MW_Y-2050_CT-BIONG  
GNR_GT_NGAS_CND_E-41_CT-BIONG                 
GNR_GT_NGAS_CND_E-42_LS-40-MW_Y-2020_CT-BIONG 
GNR_GT_NGAS_CND_E-43_LS-40-MW_Y-2030_CT-BIONG 
GNR_GT_NGAS_CND_E-44_LS-40-MW_Y-2040_CT-BIONG 
GNR_GT_NGAS_CND_E-44_LS-40-MW_Y-2050_CT-BIONG 
GNR_IND-ST_NGAS_BP_CB-30_CT-BIONG             
GNR_ST_GAS_BP-E15_CT-BIONG                    
GNR_ST_NGAS_BP_CB-130_CT-BIONG                
GNR_ST_NGAS_BP_CB-40_CT-BIONG                 
GNR_ST_NGAS_BP_CB-50_CT-BIONG                 
GNR_ST_NGAS_BP_CB-90_CT-BIONG                 
GNR_ST_NGAS_BP_E-15_CT-BIONG                  
GNR_ST_NGAS_BP_E-28_CT-BIONG                  
GNR_ST_NGAS_BP_E-31_CT-BIONG                  
GNR_ST_NGAS_BP_E-33_CT-BIONG                  
GNR_ST_NGAS_BP_E-37_CT-BIONG                  
GNR_ST_NGAS_BP_E-38_CT-BIONG                  
GNR_ST_NGAS_BP_E-39_CT-BIONG                  
GNR_ST_NGAS_BP_E-42_CT-BIONG                  
GNR_ST_NGAS_CND_E-36_CT-BIONG                 
GNR_ST_NGAS_CND_E-38_CT-BIONG                 
GNR_ST_NGAS_CND_E-39_CT-BIONG                 
GNR_ST_NGAS_CND_E-40_CT-BIONG                 
GNR_ST_NGAS_CND_E-47_LS-400-MW_Y-2020_CT-BIONG
GNR_ST_NGAS_CON_E-38_CT-BIONG                 
GNR_ST_NGAS_EXT_E-24_CT-BIONG                 
GNR_ST_NGAS_EXT_E-31_CT-BIONG                 
GNR_ST_NGAS_EXT_E-36_CT-BIONG                 
GNR_ST_NGAS_EXT_E-39_CT-BIONG                 
GNR_ST_NGAS_EXT_E-40_CT-BIONG                 
GNR_ST_NGAS_EXT_E-47_CT-BIONG                 
GNR_ST_NGAS_EXT_E-47_LS-400-MW_Y-2020_CT-BIONG
GORZ-4_ST_NGAS_BP_CT-BIONG                    
IRU_ST_NGAS_BP_CT-BIONG                       
NOWA-1_ST_NGAS_BP_CT-BIONG                    
ORESUND_CC_NGAS_EXT_CT-BIONG                  
RIGA-TEC1_BO_NGAS_HO_CT-BIONG                 
RIGA-TEC2_BO_NGAS_HO_CT-BIONG                 
RIGA-TEC2_CC_NGAS_BP_CT-BIONG                 
RIGA-TEC2_CC_NGAS_EXT_CT-BIONG                
RZES-2_ST_NGAS_BP_CT-BIONG                    
VUOSAARIB_CC_NGAS_EXT_CT-BIONG                
ZIEL-1_ST_NGAS_BP_CT-BIONG                    
ZIEL-3_ST_NGAS_BP_CT-BIONG                    
BIAL-4_ST_COAL_CND_CT-WP                      
BIEL-4_ST_COAL_BP_CT-WP                       
CHOR2-1_ST_COAL_BP_CT-WP                      
CORZ-3_ST_COAL_EXT_CT-WP                      
CZEC-1_ST_COAL_EXT_CT-WP                      
DOLN-1_ST_COAL_EXT_CT-WP                      
DOLN-2_ST_COAL_CND_CT-WP                      
GDAN2-1_ST_COAL_BP_CT-WP                      
GNR_BO_COAL_E-100_CT-WP                       
GNR_BO_COAL_E-76_CT-WP                        
GNR_BO_COAL_E-80_CT-WP                        
GNR_BO_COAL_E-90_CT-WP                        
GNR_BO_COAL_E-91_CT-WP                        
GNR_CC_COAL_BP_E-27_CT-WP                     
GNR_CC_COAL_BP_E-46_CT-WP                     
GNR_CC_COAL_BP_E-47_CT-WP                     
GNR_CC_COAL_BP_E-49_CT-WP                     
GNR_IND-ST_COAL_BP_CB-30_CT-WP                
GNR_ST_COAL_BP_CB-130_CT-WP                   
GNR_ST_COAL_BP_CB-40_CT-WP                    
GNR_ST_COAL_BP_CB-50_CT-WP                    
GNR_ST_COAL_BP_CB-80_CT-WP                    
GNR_ST_COAL_BP_E-15_CT-WP                     
GNR_ST_COAL_BP_E-32_CT-WP                     
GNR_ST_COAL_BP_E-33_CT-WP                     
GNR_ST_COAL_BP_E-34_CT-WP                     
GNR_ST_COAL_BP_E-35_CT-WP                     
GNR_ST_COAL_BP_E-36_CT-WP                     
GNR_ST_COAL_BP_E-37_CT-WP                     
GNR_ST_COAL_BP_E-38_CT-WP                     
GNR_ST_COAL_BP_E-39_CT-WP                     
GNR_ST_COAL_BP_E-40_CT-WP                     
GNR_ST_COAL_BP_E-41_CT-WP                     
GNR_ST_COAL_BP_E-42_CT-WP                     
GNR_ST_COAL_BP_E-43_CT-WP                     
GNR_ST_COAL_BP_E-44_CT-WP                     
GNR_ST_COAL_CND_E-33_CT-WP                    
GNR_ST_COAL_CND_E-35_CT-WP                    
GNR_ST_COAL_CND_E-37_CT-WP                    
GNR_ST_COAL_CND_E-38_CT-WP                    
GNR_ST_COAL_CND_E-40_CT-WP                    
GNR_ST_COAL_CND_E-44_CT-WP                    
GNR_ST_COAL_CND_E-45_CT-WP                    
GNR_ST_COAL_CND_E-46_CT-WP                    
GNR_ST_COAL_CND_E-49_LS-400-MW_Y-2020_CT-WP   
GNR_ST_COAL_CND_E-52_LS-400-MW_Y-2030_CT-WP   
GNR_ST_COAL_CND_E-53_LS-400-MW_Y-2040_CT-WP   
GNR_ST_COAL_CND_E-54_LS-400-MW_Y-2050_CT-WP   
GNR_ST_COAL_EXT_E-35_CT-WP                    
GNR_ST_COAL_EXT_E-36_CT-WP                    
GNR_ST_COAL_EXT_E-37_CT-WP                    
GNR_ST_COAL_EXT_E-38_CT-WP                    
GNR_ST_COAL_EXT_E-39_CT-WP                    
GNR_ST_COAL_EXT_E-40_CT-WP                    
GNR_ST_COAL_EXT_E-41_CT-WP                    
GNR_ST_COAL_EXT_E-42_CT-WP                    
GNR_ST_COAL_EXT_E-43_CT-WP                    
GNR_ST_COAL_EXT_E-44_CT-WP                    
GNR_ST_COAL_EXT_E-47_CT-WP                    
GNR_ST_COAL_EXT_E-49_LS-400-MW_Y-2020_CT-WP   
GNR_ST_COAL_EXT_E-52_LS-400-MW_Y-2030_CT-WP   
GNR_ST_COAL_EXT_E-53_LS-400-MW_Y-2040_CT-WP   
GNR_ST_COAL_EXT_E-54_LS-400-MW_Y-2050_CT-WP   
JAWO2-1_ST_COAL_BP_CT-WP                      
KARO-1_ST_COAL_EXT_CT-WP                      
KARO-2_ST_COAL_BP_CT-WP                       
KATO_ST_COAL_BP_CT-WP                         
KOZI-1_ST_COAL_EXT_CT-WP                      
KOZI-2_ST_COAL_CND_CT-WP                      
KRLEG-1_ST_COAL_BP_CT-WP                      
KRLEG-3_ST_COAL_EXT_CT-WP                     
LAZI-1_ST_COAL_EXT_CT-WP                      
LAZI-2_ST_COAL_CND_CT-WP                      
LAZI-6_ST_COAL_CND_CT-WP                      
LINKOPING_ST_COAL_EXT_CT-WP                   
MIEC_ST_COAL_EXT_CT-WP                        
NA1_IND-ST_COAL_EXT_CT-WP                     
NA2y3_ST_COAL_EXT_CT-WP                       
OPOL-1_ST_COAL_CND_CT-WP                      
OSTRB-1_ST_COAL_CND_CT-WP                     
POLA-2_ST_COAL_CND_CT-WP                      
RYBN-1_ST_COAL_EXT_CT-WP                      
RYBN-2_ST_COAL_CND_CT-WP                      
SIEK-1_ST_COAL_BP_CT-WP                       
SIEK-1_ST_COAL_EXT_CT-WP                      
SIEK-8_ST_COAL_EXT_CT-WP                      
SIER-1_ST_COAL_BP_CT-WP                       
SKAW-1_ST_COAL_BP_CT-WP                       
SZCZ-1_ST_COAL_BP_CT-WP                       
TURO-1_ST_COAL_BP_CT-WP                       
TYCH_ST_COAL_BP_CT-WP                         
VARTAN6_ST_COAL_EXT_CT-WP                     
ZABR-1_ST_COAL_EXT_CT-WP                      
ZABR-2_ST_COAL_EXT_CT-WP                      
ZABR-3_ST_COAL_BP_CT-WP                       
ZERA-7_ST_COAL_EXT_CT-WP                      
ZERA-8_ST_COAL_EXT_CT-WP                      
ZIEL-2_ST_COAL_BP_CT-WP                       
ZIEL-4_ST_COAL_BP_CT-WP                       
BIAL-4_ST_COAL_CND_CT-WC                      
BIEL-4_ST_COAL_BP_CT-WC                       
CHOR2-1_ST_COAL_BP_CT-WC                      
CORZ-3_ST_COAL_EXT_CT-WC                      
CZEC-1_ST_COAL_EXT_CT-WC                      
DOLN-1_ST_COAL_EXT_CT-WC                      
DOLN-2_ST_COAL_CND_CT-WC                      
GDAN2-1_ST_COAL_BP_CT-WC                      
GNR_BO_COAL_E-100_CT-WC                       
GNR_BO_COAL_E-76_CT-WC                        
GNR_BO_COAL_E-80_CT-WC                        
GNR_BO_COAL_E-90_CT-WC                        
GNR_BO_COAL_E-91_CT-WC                        
GNR_CC_COAL_BP_E-27_CT-WC                     
GNR_CC_COAL_BP_E-46_CT-WC                     
GNR_CC_COAL_BP_E-47_CT-WC                     
GNR_CC_COAL_BP_E-49_CT-WC                     
GNR_IND-ST_COAL_BP_CB-30_CT-WC                
GNR_ST_COAL_BP_CB-130_CT-WC                   
GNR_ST_COAL_BP_CB-40_CT-WC                    
GNR_ST_COAL_BP_CB-50_CT-WC                    
GNR_ST_COAL_BP_CB-80_CT-WC                    
GNR_ST_COAL_BP_E-15_CT-WC                     
GNR_ST_COAL_BP_E-32_CT-WC                     
GNR_ST_COAL_BP_E-33_CT-WC                     
GNR_ST_COAL_BP_E-34_CT-WC                     
GNR_ST_COAL_BP_E-35_CT-WC                     
GNR_ST_COAL_BP_E-36_CT-WC                     
GNR_ST_COAL_BP_E-37_CT-WC                     
GNR_ST_COAL_BP_E-38_CT-WC                     
GNR_ST_COAL_BP_E-39_CT-WC                     
GNR_ST_COAL_BP_E-40_CT-WC                     
GNR_ST_COAL_BP_E-41_CT-WC                     
GNR_ST_COAL_BP_E-42_CT-WC                     
GNR_ST_COAL_BP_E-43_CT-WC                     
GNR_ST_COAL_BP_E-44_CT-WC                     
GNR_ST_COAL_CND_E-33_CT-WC                    
GNR_ST_COAL_CND_E-35_CT-WC                    
GNR_ST_COAL_CND_E-37_CT-WC                    
GNR_ST_COAL_CND_E-38_CT-WC                    
GNR_ST_COAL_CND_E-40_CT-WC                    
GNR_ST_COAL_CND_E-44_CT-WC                    
GNR_ST_COAL_CND_E-45_CT-WC                    
GNR_ST_COAL_CND_E-46_CT-WC                    
GNR_ST_COAL_CND_E-49_LS-400-MW_Y-2020_CT-WC   
GNR_ST_COAL_CND_E-52_LS-400-MW_Y-2030_CT-WC   
GNR_ST_COAL_CND_E-53_LS-400-MW_Y-2040_CT-WC   
GNR_ST_COAL_CND_E-54_LS-400-MW_Y-2050_CT-WC   
GNR_ST_COAL_EXT_E-35_CT-WC                    
GNR_ST_COAL_EXT_E-36_CT-WC                    
GNR_ST_COAL_EXT_E-37_CT-WC                    
GNR_ST_COAL_EXT_E-38_CT-WC                    
GNR_ST_COAL_EXT_E-39_CT-WC                    
GNR_ST_COAL_EXT_E-40_CT-WC                    
GNR_ST_COAL_EXT_E-41_CT-WC                    
GNR_ST_COAL_EXT_E-42_CT-WC                    
GNR_ST_COAL_EXT_E-43_CT-WC                    
GNR_ST_COAL_EXT_E-44_CT-WC                    
GNR_ST_COAL_EXT_E-47_CT-WC                    
GNR_ST_COAL_EXT_E-49_LS-400-MW_Y-2020_CT-WC   
GNR_ST_COAL_EXT_E-52_LS-400-MW_Y-2030_CT-WC   
GNR_ST_COAL_EXT_E-53_LS-400-MW_Y-2040_CT-WC   
GNR_ST_COAL_EXT_E-54_LS-400-MW_Y-2050_CT-WC   
JAWO2-1_ST_COAL_BP_CT-WC                      
KARO-1_ST_COAL_EXT_CT-WC                      
KARO-2_ST_COAL_BP_CT-WC                       
KATO_ST_COAL_BP_CT-WC                         
KOZI-1_ST_COAL_EXT_CT-WC                      
KOZI-2_ST_COAL_CND_CT-WC                      
KRLEG-1_ST_COAL_BP_CT-WC                      
KRLEG-3_ST_COAL_EXT_CT-WC                     
LAZI-1_ST_COAL_EXT_CT-WC                      
LAZI-2_ST_COAL_CND_CT-WC                      
LAZI-6_ST_COAL_CND_CT-WC                      
LINKOPING_ST_COAL_EXT_CT-WC                   
MIEC_ST_COAL_EXT_CT-WC                        
NA1_IND-ST_COAL_EXT_CT-WC                     
NA2y3_ST_COAL_EXT_CT-WC                       
OPOL-1_ST_COAL_CND_CT-WC                      
OSTRB-1_ST_COAL_CND_CT-WC                     
POLA-2_ST_COAL_CND_CT-WC                      
RYBN-1_ST_COAL_EXT_CT-WC                      
RYBN-2_ST_COAL_CND_CT-WC                      
SIEK-1_ST_COAL_BP_CT-WC                       
SIEK-1_ST_COAL_EXT_CT-WC                      
SIEK-8_ST_COAL_EXT_CT-WC                      
SIER-1_ST_COAL_BP_CT-WC                       
SKAW-1_ST_COAL_BP_CT-WC                       
SZCZ-1_ST_COAL_BP_CT-WC                       
TURO-1_ST_COAL_BP_CT-WC                       
TYCH_ST_COAL_BP_CT-WC                         
VARTAN6_ST_COAL_EXT_CT-WC                     
ZABR-1_ST_COAL_EXT_CT-WC                      
ZABR-2_ST_COAL_EXT_CT-WC                      
ZABR-3_ST_COAL_BP_CT-WC                       
ZERA-7_ST_COAL_EXT_CT-WC                      
ZERA-8_ST_COAL_EXT_CT-WC                      
ZIEL-2_ST_COAL_BP_CT-WC                       
ZIEL-4_ST_COAL_BP_CT-WC                       
BIAL-4_ST_COAL_CND_CT-STRAW                   
BIEL-4_ST_COAL_BP_CT-STRAW                    
CHOR2-1_ST_COAL_BP_CT-STRAW                   
CORZ-3_ST_COAL_EXT_CT-STRAW                   
CZEC-1_ST_COAL_EXT_CT-STRAW                   
DOLN-1_ST_COAL_EXT_CT-STRAW                   
DOLN-2_ST_COAL_CND_CT-STRAW                   
GDAN2-1_ST_COAL_BP_CT-STRAW                   
GNR_BO_COAL_E-100_CT-STRAW                    
GNR_BO_COAL_E-76_CT-STRAW                     
GNR_BO_COAL_E-80_CT-STRAW                     
GNR_BO_COAL_E-90_CT-STRAW                     
GNR_BO_COAL_E-91_CT-STRAW                     
GNR_CC_COAL_BP_E-27_CT-STRAW                  
GNR_CC_COAL_BP_E-46_CT-STRAW                  
GNR_CC_COAL_BP_E-47_CT-STRAW                  
GNR_CC_COAL_BP_E-49_CT-STRAW                  
GNR_IND-ST_COAL_BP_CB-30_CT-STRAW             
GNR_ST_COAL_BP_CB-130_CT-STRAW                
GNR_ST_COAL_BP_CB-40_CT-STRAW                 
GNR_ST_COAL_BP_CB-50_CT-STRAW                 
GNR_ST_COAL_BP_CB-80_CT-STRAW                 
GNR_ST_COAL_BP_E-15_CT-STRAW                  
GNR_ST_COAL_BP_E-32_CT-STRAW                  
GNR_ST_COAL_BP_E-33_CT-STRAW                  
GNR_ST_COAL_BP_E-34_CT-STRAW                  
GNR_ST_COAL_BP_E-35_CT-STRAW                  
GNR_ST_COAL_BP_E-36_CT-STRAW                  
GNR_ST_COAL_BP_E-37_CT-STRAW                  
GNR_ST_COAL_BP_E-38_CT-STRAW                  
GNR_ST_COAL_BP_E-39_CT-STRAW                  
GNR_ST_COAL_BP_E-40_CT-STRAW                  
GNR_ST_COAL_BP_E-41_CT-STRAW                  
GNR_ST_COAL_BP_E-42_CT-STRAW                  
GNR_ST_COAL_BP_E-43_CT-STRAW                  
GNR_ST_COAL_BP_E-44_CT-STRAW                  
GNR_ST_COAL_CND_E-33_CT-STRAW                 
GNR_ST_COAL_CND_E-35_CT-STRAW                 
GNR_ST_COAL_CND_E-37_CT-STRAW                 
GNR_ST_COAL_CND_E-38_CT-STRAW                 
GNR_ST_COAL_CND_E-40_CT-STRAW                 
GNR_ST_COAL_CND_E-44_CT-STRAW                 
GNR_ST_COAL_CND_E-45_CT-STRAW                 
GNR_ST_COAL_CND_E-46_CT-STRAW                 
GNR_ST_COAL_CND_E-49_LS-400-MW_Y-2020_CT-STRAW
GNR_ST_COAL_CND_E-52_LS-400-MW_Y-2030_CT-STRAW
GNR_ST_COAL_CND_E-53_LS-400-MW_Y-2040_CT-STRAW
GNR_ST_COAL_CND_E-54_LS-400-MW_Y-2050_CT-STRAW
GNR_ST_COAL_EXT_E-35_CT-STRAW                 
GNR_ST_COAL_EXT_E-36_CT-STRAW                 
GNR_ST_COAL_EXT_E-37_CT-STRAW                 
GNR_ST_COAL_EXT_E-38_CT-STRAW                 
GNR_ST_COAL_EXT_E-39_CT-STRAW                 
GNR_ST_COAL_EXT_E-40_CT-STRAW                 
GNR_ST_COAL_EXT_E-41_CT-STRAW                 
GNR_ST_COAL_EXT_E-42_CT-STRAW                 
GNR_ST_COAL_EXT_E-43_CT-STRAW                 
GNR_ST_COAL_EXT_E-44_CT-STRAW                 
GNR_ST_COAL_EXT_E-47_CT-STRAW                 
GNR_ST_COAL_EXT_E-49_LS-400-MW_Y-2020_CT-STRAW
GNR_ST_COAL_EXT_E-52_LS-400-MW_Y-2030_CT-STRAW
GNR_ST_COAL_EXT_E-53_LS-400-MW_Y-2040_CT-STRAW
GNR_ST_COAL_EXT_E-54_LS-400-MW_Y-2050_CT-STRAW
JAWO2-1_ST_COAL_BP_CT-STRAW                   
KARO-1_ST_COAL_EXT_CT-STRAW                   
KARO-2_ST_COAL_BP_CT-STRAW                    
KATO_ST_COAL_BP_CT-STRAW                      
KOZI-1_ST_COAL_EXT_CT-STRAW                   
KOZI-2_ST_COAL_CND_CT-STRAW                   
KRLEG-1_ST_COAL_BP_CT-STRAW                   
KRLEG-3_ST_COAL_EXT_CT-STRAW                  
LAZI-1_ST_COAL_EXT_CT-STRAW                   
LAZI-2_ST_COAL_CND_CT-STRAW                   
LAZI-6_ST_COAL_CND_CT-STRAW                   
LINKOPING_ST_COAL_EXT_CT-STRAW                
MIEC_ST_COAL_EXT_CT-STRAW                     
NA1_IND-ST_COAL_EXT_CT-STRAW                  
NA2y3_ST_COAL_EXT_CT-STRAW                    
OPOL-1_ST_COAL_CND_CT-STRAW                   
OSTRB-1_ST_COAL_CND_CT-STRAW                  
POLA-2_ST_COAL_CND_CT-STRAW                   
RYBN-1_ST_COAL_EXT_CT-STRAW                   
RYBN-2_ST_COAL_CND_CT-STRAW                   
SIEK-1_ST_COAL_BP_CT-STRAW                    
SIEK-1_ST_COAL_EXT_CT-STRAW                   
SIEK-8_ST_COAL_EXT_CT-STRAW                   
SIER-1_ST_COAL_BP_CT-STRAW                    
SKAW-1_ST_COAL_BP_CT-STRAW                    
SZCZ-1_ST_COAL_BP_CT-STRAW                    
TURO-1_ST_COAL_BP_CT-STRAW                    
TYCH_ST_COAL_BP_CT-STRAW                      
VARTAN6_ST_COAL_EXT_CT-STRAW                  
ZABR-1_ST_COAL_EXT_CT-STRAW                   
ZABR-2_ST_COAL_EXT_CT-STRAW                   
ZABR-3_ST_COAL_BP_CT-STRAW                    
ZERA-7_ST_COAL_EXT_CT-STRAW                   
ZERA-8_ST_COAL_EXT_CT-STRAW                   
ZIEL-2_ST_COAL_BP_CT-STRAW                    
ZIEL-4_ST_COAL_BP_CT-STRAW                    
$ifi not %INDUSTRY%==yes $goto noindustry     
GNR_BO_NGAS_E-75_PHH_Y-2020_CT_BIONG          
GNR_BO_NGAS_E-76_PHH_Y-2030_CT_BIONG          
GNR_BO_NGAS_E-76_PHH_Y-2040_CT_BIONG          
GNR_BO_NGAS_E-77_PHH_Y-2050_CT_BIONG          
GNR_BO_NGAS_E-85_PHL_Y-2020_CT_BIONG          
GNR_BO_NGAS_E-86_PHL_Y-2030_CT_BIONG          
GNR_BO_NGAS_E-86_PHL_Y-2040_CT_BIONG          
GNR_BO_NGAS_E-86_PHL_Y-2050_CT_BIONG          
$label noindustry                             
/;                                            
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
