SET GGCOMB(GGG,IGGGALIAS) 'Pair of combination technologies'
/
GCND_NATGAS1                                                 .    GCND_NATGAS1_BUP
GCND_NATGAS2                                                 .    GCND_NATGAS2_BUP
GCND_NATGAS3                                                 .    GCND_NATGAS3_BUP
GCND_NATGAS4                                                 .    GCND_NATGAS4_BUP
GEXT_NATGAS_ORESUND                                          .    GEXT_NATGAS_ORESUND_BUP
GEXT_NATGAS_NOKIA                                            .    GEXT_NATGAS_NOKIA_BUP
GEXT_NATGAS_MERTANIEMI                                       .    GEXT_NATGAS_MERTANIEMI_BUP
GEXT_NATGAS_TAMPERE                                          .    GEXT_NATGAS_TAMPERE_BUP
GEXT_NATGAS_VOUSAARI                                         .    GEXT_NATGAS_VOUSAARI_BUP
GEXT_NATGAS_AVEDORE                                          .    GEXT_NATGAS_AVEDORE_BUP
GEXT_NATGAS_SKERBEK                                          .    GEXT_NATGAS_SKERBEK_BUP
GEXT_NATGAS                                                  .    GEXT_NATGAS_BUP
GBPR_NATGAS_RYA                                              .    GBPR_NATGAS_RYA_BUP
GBPR_NATGAS_SE4EL                                            .    GBPR_NATGAS_SE4EL_BUP
GBPR_NATGAS_GOT                                              .    GBPR_NATGAS_GOT_BUP
GBPR_NATGAS_MAL                                              .    GBPR_NATGAS_MAL_BUP
GBPR_NATGAS_40                                               .    GBPR_NATGAS_40_BUP
GBPR_NATGAS_50                                               .    GBPR_NATGAS_50_BUP
GBPR_NATGAS_100                                              .    GBPR_NATGAS_100_BUP
GBPR_NATGAS_VOUSAARI                                         .    GBPR_NATGAS_VOUSAARI_BUP
GBPR_NATGAS_FINEL                                            .    GBPR_NATGAS_FINEL_BUP
GBPR_NATGAS_SUOMENOJA2                                       .    GBPR_NATGAS_SUOMENOJA2_BUP
GBPR_NATGAS_GASAREA                                          .    GBPR_NATGAS_GASAREA_BUP
GBPR_NATGAS_SUOMENOJA                                        .    GBPR_NATGAS_SUOMENOJA_BUP
GBPR_NATGAS_MARTINLAAKSOGT                                   .    GBPR_NATGAS_MARTINLAAKSOGT_BUP
GBPR_NATGAS                                                  .    GBPR_NATGAS_BUP
GHOB_NATGAS                                                  .    GHOB_NATGAS_BUP
GBPR_NATGAS_IND                                              .    GBPR_NATGAS_IND _BUP
GBPR_NATGAS1                                                 .    GBPR_NATGAS1_BUP
GBPR_NATGAS2                                                 .    GBPR_NATGAS2_BUP
GBPR_NATGAS3                                                 .    GBPR_NATGAS3_BUP
GCND_NATGAS1_1                                               .    GCND_NATGAS1_1_BUP
GCND_NATGAS1_2                                               .    GCND_NATGAS1_2_BUP
GCND_NATGAS1_3                                               .    GCND_NATGAS1_3_BUP
GCND_NATGAS2_1                                               .    GCND_NATGAS2_1_BUP
GCND_NATGAS2_2                                               .    GCND_NATGAS2_2_BUP
GCND_NATGAS2_3                                               .    GCND_NATGAS2_3_BUP
GCND_NATGAS3_1                                               .    GCND_NATGAS3_1_BUP
GCND_NATGAS3_2                                               .    GCND_NATGAS3_2_BUP
GCND_NATGAS3_3                                               .    GCND_NATGAS3_3_BUP
GCND_NATGAS4_1                                               .    GCND_NATGAS4_1_BUP
GCND_NATGAS4_2                                               .    GCND_NATGAS4_2_BUP
GCND_NATGAS4_3                                               .    GCND_NATGAS4_3_BUP
ST-BP-Iru-2-OG                                               .    ST-BP-Iru-2-OG_BUP
ST-Ext-Iru-1-OG                                              .    ST-Ext-Iru-1-OG_BUP
DH-Old-G-EE                                                  .    DH-Old-G-EE   _BUP
DH-Old-O-EE                                                  .    DH-Old-O-EE   _BUP
GEXT_NATGAS_IRU1                                             .    GEXT_NATGAS_IRU1_BUP
GBPR_NATGAS_IRU2                                             .    GBPR_NATGAS_IRU2_BUP
GEXT_NATGAS_EE_SMALL                                         .    GEXT_NATGAS_EE_SMALL_BUP
GE-BP-LV-G                                                   .    GE-BP-LV-G_BUP
Rigas_TEC-1-GT                                               .    Rigas_TEC-1-GT_BUP
Rigas_TEC-1-ST                                               .    Rigas_TEC-1-ST_BUP
Rigas_TEC-2-CC                                               .    Rigas_TEC-2-CC_BUP
ST-BP-IM-G                                                   .    ST-BP-IM-G_BUP
ST-BP-LV-OG                                                  .    ST-BP-LV-OG_BUP
AchemaCHP                                                    .    AchemaCHP_BUP
KaunasCHP                                                    .    KaunasCHP_BUP
LithuanianCCGT                                               .    LithuanianCCGT_BUP
LithuanianPP                                                 .    LithuanianPP_BUP
OrlenCHP                                                     .    OrlenCHP_BUP
PanevezysCHP                                                 .    PanevezysCHP_BUP
VilniusCHP3                                                  .    VilniusCHP3_BUP
ST-Cond-LM-F1-Gfree                                          .    ST-Cond-LM-F1-Gfree_BUP
GBPR_OTHERGAS_IND                                            .    GBPR_OTHERGAS_IND_BUP
GCND-NG                                                      .    GCND-NG_BUP
GBPR-NATGAS                                                  .    GBPR-NATGAS_BUP
SteamTur-CON-NG-10_19                                        .    SteamTur-CON-NG-10_19_BUP
SteamTur-CON-NG-20_50                                        .    SteamTur-CON-NG-20_50_BUP
SteamTur-EXT-NG-10_19                                        .    SteamTur-EXT-NG-10_19_BUP
SteamTur-EXT-NG-20_50                                        .    SteamTur-EXT-NG-20_50_BUP
GasTur-CON-NG-10_19                                          .    GasTur-CON-NG-10_19_BUP
GasTur-CON-NG-20                                             .    GasTur-CON-NG-20_BUP
GasTur-EXT-NG-10_19                                          .    GasTur-EXT-NG-10_19_BUP
GasTur-EXT-NG-20                                             .    GasTur-EXT-NG-20_BUP
GasTurCC-CON-NG-10_19                                        .    GasTurCC-CON-NG-10_19_BUP
GasTurCC-CON-NG-20_29                                        .    GasTurCC-CON-NG-20_29_BUP
GasTurCC-CON-NG-30_49                                        .    GasTurCC-CON-NG-30_49_BUP
GasTurCC-CON-NG-50                                           .    GasTurCC-CON-NG-50_BUP
GasTurCC-EXT-NG-10_19                                        .    GasTurCC-EXT-NG-10_19_BUP
GasTurCC-EXT-NG-20_29                                        .    GasTurCC-EXT-NG-20_29_BUP
GasTurCC-EXT-NG-30_49                                        .    GasTurCC-EXT-NG-30_49_BUP
GasTurCC-EXT-NG-50                                           .    GasTurCC-EXT-NG-50_BUP
GasTurCC-BP-NG-10_19                                         .    GasTurCC-BP-NG-10_19_BUP
GasTurCC-BP-NG-20                                            .    GasTurCC-BP-NG-20_BUP
Engine-NG-10_19                                              .    Engine-NG-10_19_BUP
Engine-NG-20_29                                              .    Engine-NG-20_29_BUP
Engine-NG-30_49                                              .    Engine-NG-30_49_BUP
Engine-NG-50                                                 .    Engine-NG-50_BUP
Boiler-NG                                                    .    Boiler-NG_BUP
HO-B1-NG                                                     .    HO-B1-NG_BUP
HO-IND1-NG                                                   .    HO-IND1-NG_BUP
HCVSMV_ST_B8_NG                                              .    HCVSMV_ST_B8_NG_BUP
CC-B9-NGn                                                    .    CC-B9-NGn_BUP
ST-B8-NG                                                     .    ST-B8-NG_BUP
HO-B8-NG                                                     .    HO-B8-NG_BUP
DE_HO-NG                                                     .    DE_HO-NG_BUP
DE_HO-NG-TempFix                                             .    DE_HO-NG-TempFix_BUP
DE-COND-GAS-0-00                                             .    DE-COND-GAS-0-00_BUP
DE-COND-GAS-101-00                                           .    DE-COND-GAS-101-00_BUP
DE-KWK-GAS-CC-91                                             .    DE-KWK-GAS-CC-91_BUP
DE-KWK-GAS-GT-00                                             .    DE-KWK-GAS-GT-00_BUP
DE-KWK-GAS-IC-00                                             .    DE-KWK-GAS-IC-00_BUP
DE-KWK-GAS-ST-00                                             .    DE-KWK-GAS-ST-00_BUP
DE-COND-GAS-CC-0-91                                          .    DE-COND-GAS-CC-0-91_BUP
DE-KWK-GAS-CC-00                                             .    DE-KWK-GAS-CC-00_BUP
DK_CA_Aab_Boiler_NG                                          .    DK_CA_Aab_Boiler_NG_BUP
DK_CA_Aab_Engine_NG                                          .    DK_CA_Aab_Engine_NG_BUP
DK_CA_Aab_DEC_Boiler_NG                                      .    DK_CA_Aab_DEC_Boiler_NG_BUP
DK_CA_Aab_DEC_Engine_NG                                      .    DK_CA_Aab_DEC_Engine_NG_BUP
DK_CA_Aab_DEC_GasTur-NG                                      .    DK_CA_Aab_DEC_GasTur-NG_BUP
DK_CA_Aal_Boiler_NG                                          .    DK_CA_Aal_Boiler_NG_BUP
DK_CA_Aal_Engine_NG                                          .    DK_CA_Aal_Engine_NG_BUP
DK_CA_Aal_DEC_Boiler_NG                                      .    DK_CA_Aal_DEC_Boiler_NG_BUP
DK_CA_Aal_DEC_Engine_NG                                      .    DK_CA_Aal_DEC_Engine_NG_BUP
DK_CA_Aal_DEC_GasTur-NG                                      .    DK_CA_Aal_DEC_GasTur-NG_BUP
DK_CA_Aarhus_Boiler_NG                                       .    DK_CA_Aarhus_Boiler_NG_BUP
DK_CA_Aarhus_Engine_NG                                       .    DK_CA_Aarhus_Engine_NG_BUP
DK_CA_Aarhus_DEC_Boiler_NG                                   .    DK_CA_Aarhus_DEC_Boiler_NG_BUP
DK_CA_Aarhus_DEC_Engine_NG                                   .    DK_CA_Aarhus_DEC_Engine_NG_BUP
DK_CA_Esb_Boiler_NG                                          .    DK_CA_Esb_Boiler_NG_BUP
DK_CA_Esb_Engine_NG                                          .    DK_CA_Esb_Engine_NG_BUP
DK_CA_Esb_DEC_Boiler_NG                                      .    DK_CA_Esb_DEC_Boiler_NG_BUP
DK_CA_Esb_DEC_Engine_NG                                      .    DK_CA_Esb_DEC_Engine_NG_BUP
DK_CA_Esb_DEC_GasTur-NG                                      .    DK_CA_Esb_DEC_GasTur-NG_BUP
DK_CA_Hern_Boiler_NG                                         .    DK_CA_Hern_Boiler_NG_BUP
DK_CA_Hern_Engine_NG                                         .    DK_CA_Hern_Engine_NG_BUP
DK_CA_Hern_DEC_Boiler_NG                                     .    DK_CA_Hern_DEC_Boiler_NG_BUP
DK_CA_Hern_DEC_Engine_NG                                     .    DK_CA_Hern_DEC_Engine_NG_BUP
DK_CA_Hern_DEC_GasTur-NG                                     .    DK_CA_Hern_DEC_GasTur-NG_BUP
DK_CA_Kal_Boiler_NG                                          .    DK_CA_Kal_Boiler_NG_BUP
DK_CA_Kal_Engine_NG                                          .    DK_CA_Kal_Engine_NG_BUP
DK_CA_Kal_GasTur_CND_NG                                      .    DK_CA_Kal_GasTur_CND_NG_BUP
DK_CA_Kal_DEC_Boiler_NG                                      .    DK_CA_Kal_DEC_Boiler_NG_BUP
DK_CA_Kal_DEC_Engine_NG                                      .    DK_CA_Kal_DEC_Engine_NG_BUP
DK_CA_KBH_Boiler_NG                                          .    DK_CA_KBH_Boiler_NG_BUP
DK_CA_KBH_Engine_NG                                          .    DK_CA_KBH_Engine_NG_BUP
DK_CA_KBH_GasTur-NG                                          .    DK_CA_KBH_GasTur-NG_BUP
DK_CA_KBH_DEC_Boiler_NG                                      .    DK_CA_KBH_DEC_Boiler_NG_BUP
DK_CA_KBH_DEC_Engine_NG                                      .    DK_CA_KBH_DEC_Engine_NG_BUP
DK_CA_KBH_DEC_GasTur-NG                                      .    DK_CA_KBH_DEC_GasTur-NG_BUP
DK_CA_Odense_Boiler_NG                                       .    DK_CA_Odense_Boiler_NG_BUP
DK_CA_Odense_Engine_NG                                       .    DK_CA_Odense_Engine_NG_BUP
DK_CA_Odense_DEC_Boiler_NG                                   .    DK_CA_Odense_DEC_Boiler_NG_BUP
DK_CA_Odense_DEC_Engine_NG                                   .    DK_CA_Odense_DEC_Engine_NG_BUP
DK_CA_Odense_DEC_GasTur-NG                                   .    DK_CA_Odense_DEC_GasTur-NG_BUP
DK_CA_Randers_Boiler_NG                                      .    DK_CA_Randers_Boiler_NG_BUP
DK_CA_Randers_Engine_NG                                      .    DK_CA_Randers_Engine_NG_BUP
DK_CA_Randers_DEC_Boiler_NG                                  .    DK_CA_Randers_DEC_Boiler_NG_BUP
DK_CA_Randers_DEC_Engine_NG                                  .    DK_CA_Randers_DEC_Engine_NG_BUP
DK_CA_Randers_DEC_GasTur-NG                                  .    DK_CA_Randers_DEC_GasTur-NG_BUP
DK_CA_Roenne_DEC_Boiler_NG                                   .    DK_CA_Roenne_DEC_Boiler_NG_BUP
DK_CA_TVIS_Boiler_NG                                         .    DK_CA_TVIS_Boiler_NG_BUP
DK_CA_TVIS_GasTurCC-NG                                       .    DK_CA_TVIS_GasTurCC-NG_BUP
DK_CA_TVIS_GasTur-NG                                         .    DK_CA_TVIS_GasTur-NG_BUP
DK_CA_TVIS_DEC_Boiler_NG                                     .    DK_CA_TVIS_DEC_Boiler_NG_BUP
DK_CA_TVIS_DEC_Engine_CND_NG                                 .    DK_CA_TVIS_DEC_Engine_CND_NG_BUP
DK_CA_TVIS_DEC_Engine_NG                                     .    DK_CA_TVIS_DEC_Engine_NG_BUP
DK_CA_Vestfrb_DEC_Boiler_NG                                  .    DK_CA_Vestfrb_DEC_Boiler_NG_BUP
DK_CA_Vestfrb_DEC_Engine_NG                                  .    DK_CA_Vestfrb_DEC_Engine_NG_BUP
DK_CA_Vestfrb_DEC_GasTur-NG                                  .    DK_CA_Vestfrb_DEC_GasTur-NG_BUP
DK2_DTU_Boiler_NG                                            .    DK2_DTU_Boiler_NG_BUP
DK2_DTU_GasTur-NG                                            .    DK2_DTU_GasTur-NG_BUP
DK_MA_Hil_Boiler_NG                                          .    DK_MA_Hil_Boiler_NG_BUP
DK_MA_Hil_Engine_NG                                          .    DK_MA_Hil_Engine_NG_BUP
DK_MA_Hil_GasTur-NG                                          .    DK_MA_Hil_GasTur-NG_BUP
DK_MA_Hil_DEC_Boiler_NG                                      .    DK_MA_Hil_DEC_Boiler_NG_BUP
DK_MA_Hil_DEC_Engine_NG                                      .    DK_MA_Hil_DEC_Engine_NG_BUP
DK_MA_Hjoerring_Boiler_NG                                    .    DK_MA_Hjoerring_Boiler_NG_BUP
DK_MA_Hjoerring_Engine_NG                                    .    DK_MA_Hjoerring_Engine_NG_BUP
DK_MA_Hjoerring_GasTur-NG                                    .    DK_MA_Hjoerring_GasTur-NG_BUP
DK_MA_Holst_Boiler_NG                                        .    DK_MA_Holst_Boiler_NG_BUP
DK_MA_Holst_DEC_Boiler_NG                                    .    DK_MA_Holst_DEC_Boiler_NG_BUP
DK_MA_Holst_DEC_Engine_NG                                    .    DK_MA_Holst_DEC_Engine_NG_BUP
DK_MA_Holst_DEC_GasTur-NG                                    .    DK_MA_Holst_DEC_GasTur-NG_BUP
DK_MA_Horsens_Boiler_NG                                      .    DK_MA_Horsens_Boiler_NG_BUP
DK_MA_Horsens_DEC_Boiler_NG                                  .    DK_MA_Horsens_DEC_Boiler_NG_BUP
DK_MA_Horsens_DEC_Engine_NG                                  .    DK_MA_Horsens_DEC_Engine_NG_BUP
DK_MA_NrdOstSj_Boiler_NG                                     .    DK_MA_NrdOstSj_Boiler_NG_BUP
DK_MA_NrdOstSj_Engine_NG                                     .    DK_MA_NrdOstSj_Engine_NG_BUP
DK_MA_NrdOstSj_GasTur-NG                                     .    DK_MA_NrdOstSj_GasTur-NG_BUP
DK_MA_NrdOstSj_DEC_Engine_NG                                 .    DK_MA_NrdOstSj_DEC_Engine_NG_BUP
DK_MA_Silk_Boiler_NG                                         .    DK_MA_Silk_Boiler_NG_BUP
DK_MA_Silk_GasTur-NG                                         .    DK_MA_Silk_GasTur-NG_BUP
DK_MA_Sndborg_Boiler_NG                                      .    DK_MA_Sndborg_Boiler_NG_BUP
DK_MA_Sndborg_DEC_Boiler_NG                                  .    DK_MA_Sndborg_DEC_Boiler_NG_BUP
DK_MA_Sndborg_DEC_Engine_NG                                  .    DK_MA_Sndborg_DEC_Engine_NG_BUP
DK_MA_Viborg_Boiler_NG                                       .    DK_MA_Viborg_Boiler_NG_BUP
DK_MA_Viborg_Engine_NG                                       .    DK_MA_Viborg_Engine_NG_BUP
DK_MA_Viborg_GasTur-NG                                       .    DK_MA_Viborg_GasTur-NG_BUP
DK_MA_Viborg_DEC_Boiler_NG                                   .    DK_MA_Viborg_DEC_Boiler_NG_BUP
DK_MA_Viborg_DEC_Engine_NG                                   .    DK_MA_Viborg_DEC_Engine_NG_BUP
DK_MAM_Aars_Boiler_NG                                        .    DK_MAM_Aars_Boiler_NG_BUP
DK_MAM_Aars_Engine_NG                                        .    DK_MAM_Aars_Engine_NG_BUP
DK_MAM_Aars_DEC_Boiler_NG                                    .    DK_MAM_Aars_DEC_Boiler_NG_BUP
DK_MAM_Aars_DEC_Engine_NG                                    .    DK_MAM_Aars_DEC_Engine_NG_BUP
DK_MAM_Aars_DEC_GasTur-NG                                    .    DK_MAM_Aars_DEC_GasTur-NG_BUP
DK_MAM_Frdhavn_Boiler_NG                                     .    DK_MAM_Frdhavn_Boiler_NG_BUP
DK_MAM_Frdhavn_GasTur-NG                                     .    DK_MAM_Frdhavn_GasTur-NG_BUP
DK_MAM_Frdhavn_DEC_Boiler_NG                                 .    DK_MAM_Frdhavn_DEC_Boiler_NG_BUP
DK_MAM_Frdhavn_DEC_Engine_NG                                 .    DK_MAM_Frdhavn_DEC_Engine_NG_BUP
DK_MAM_Had_Boiler_NG                                         .    DK_MAM_Had_Boiler_NG_BUP
DK_MAM_Had_Engine_NG                                         .    DK_MAM_Had_Engine_NG_BUP
DK_MAM_Had_DEC_Boiler_NG                                     .    DK_MAM_Had_DEC_Boiler_NG_BUP
DK_MAM_Had_DEC_Engine_NG                                     .    DK_MAM_Had_DEC_Engine_NG_BUP
DK_MAM_Hammel_DEC_Boiler_NG                                  .    DK_MAM_Hammel_DEC_Boiler_NG_BUP
DK_MAM_Hammel_DEC_Engine_NG                                  .    DK_MAM_Hammel_DEC_Engine_NG_BUP
DK_MAM_Hobro_Boiler_NG                                       .    DK_MAM_Hobro_Boiler_NG_BUP
DK_MAM_Hobro_Engine_NG                                       .    DK_MAM_Hobro_Engine_NG_BUP
DK_MAM_Hobro_DEC_Boiler_NG                                   .    DK_MAM_Hobro_DEC_Boiler_NG_BUP
DK_MAM_Hobro_DEC_Engine_NG                                   .    DK_MAM_Hobro_DEC_Engine_NG_BUP
DK_MAM_Naestved_Boiler_NG                                    .    DK_MAM_Naestved_Boiler_NG_BUP
DK_MAM_Naestved_Engine_NG                                    .    DK_MAM_Naestved_Engine_NG_BUP
DK_MAM_Naestved_DEC_Boiler_NG                                .    DK_MAM_Naestved_DEC_Boiler_NG_BUP
DK_MAM_Naestved_DEC_Engine_NG                                .    DK_MAM_Naestved_DEC_Engine_NG_BUP
DK_MAM_NrAlslev_Boiler_NG                                    .    DK_MAM_NrAlslev_Boiler_NG_BUP
DK_MAM_Nyborg_Boiler_NG                                      .    DK_MAM_Nyborg_Boiler_NG_BUP
DK_MAM_Nyborg_GasTur-NG                                      .    DK_MAM_Nyborg_GasTur-NG_BUP
DK_MAM_Nyk_Boiler_NG                                         .    DK_MAM_Nyk_Boiler_NG_BUP
DK_MAM_Nyk_DEC_Boiler_NG                                     .    DK_MAM_Nyk_DEC_Boiler_NG_BUP
DK_MAM_Skagen_Boiler_NG                                      .    DK_MAM_Skagen_Boiler_NG_BUP
DK_MAM_Skagen_Engine_NG                                      .    DK_MAM_Skagen_Engine_NG_BUP
DK_MAM_Skagen_GasTur-NG                                      .    DK_MAM_Skagen_GasTur-NG_BUP
DK_MAM_Slagelse_Boiler_NG                                    .    DK_MAM_Slagelse_Boiler_NG_BUP
DK_MAM_Slagelse_DEC_Boiler_NG                                .    DK_MAM_Slagelse_DEC_Boiler_NG_BUP
DK_MAM_Slagelse_DEC_Engine_NG                                .    DK_MAM_Slagelse_DEC_Engine_NG_BUP
DK_MAM_Svend_Boiler_NG                                       .    DK_MAM_Svend_Boiler_NG_BUP
DK_MAM_Svend_Engine_NG                                       .    DK_MAM_Svend_Engine_NG_BUP
DK_MAM_Svend_DEC_Boiler_NG                                   .    DK_MAM_Svend_DEC_Boiler_NG_BUP
DK_MAM_Svend_DEC_Engine_NG                                   .    DK_MAM_Svend_DEC_Engine_NG_BUP
DK_MAM_Thisted_Boiler_NG                                     .    DK_MAM_Thisted_Boiler_NG_BUP
DK_MAM_Thisted_Engine_NG                                     .    DK_MAM_Thisted_Engine_NG_BUP
DK_MAM_Thisted_DEC_Boiler_NG                                 .    DK_MAM_Thisted_DEC_Boiler_NG_BUP
DK_MAM_Thisted_DEC_Engine_NG                                 .    DK_MAM_Thisted_DEC_Engine_NG_BUP
GT_CND_NG_2020                                               .    GT_CND_NG_2020_BUP
GT_CND_NG_2025                                               .    GT_CND_NG_2025_BUP
GT_CND_NG_2030                                               .    GT_CND_NG_2030_BUP
GTCC_EXT_NG_2020                                             .    GTCC_EXT_NG_2020_BUP
GTCC_EXT_NG_2025                                             .    GTCC_EXT_NG_2025_BUP
GTCC_EXT_NG_2030                                             .    GTCC_EXT_NG_2030_BUP
GTCC_BP_NG_2020                                              .    GTCC_BP_NG_2020_BUP
GTCC_BP_NG_2025                                              .    GTCC_BP_NG_2025_BUP
GTCC_BP_NG_2030                                              .    GTCC_BP_NG_2030_BUP
ENG_EXT_NG_2020                                              .    ENG_EXT_NG_2020_BUP
ENG_EXT_NG_2025                                              .    ENG_EXT_NG_2025_BUP
ENG_EXT_NG_2030                                              .    ENG_EXT_NG_2030_BUP
BO_NG_2020                                                   .    BO_NG_2020_BUP
BO_NG_2025                                                   .    BO_NG_2025_BUP
BO_NG_2030                                                   .    BO_NG_2030_BUP
GCND_NATGAS1                                                 .    GCND_NATGAS1_TUP
GCND_NATGAS2                                                 .    GCND_NATGAS2_TUP
GCND_NATGAS3                                                 .    GCND_NATGAS3_TUP
GCND_NATGAS4                                                 .    GCND_NATGAS4_TUP
GEXT_NATGAS_ORESUND                                          .    GEXT_NATGAS_ORESUND_TUP
GEXT_NATGAS_NOKIA                                            .    GEXT_NATGAS_NOKIA_TUP
GEXT_NATGAS_MERTANIEMI                                       .    GEXT_NATGAS_MERTANIEMI_TUP
GEXT_NATGAS_TAMPERE                                          .    GEXT_NATGAS_TAMPERE_TUP
GEXT_NATGAS_VOUSAARI                                         .    GEXT_NATGAS_VOUSAARI_TUP
GEXT_NATGAS_AVEDORE                                          .    GEXT_NATGAS_AVEDORE_TUP
GEXT_NATGAS_SKERBEK                                          .    GEXT_NATGAS_SKERBEK_TUP
GEXT_NATGAS                                                  .    GEXT_NATGAS_TUP
GBPR_NATGAS_RYA                                              .    GBPR_NATGAS_RYA_TUP
GBPR_NATGAS_SE4EL                                            .    GBPR_NATGAS_SE4EL_TUP
GBPR_NATGAS_GOT                                              .    GBPR_NATGAS_GOT_TUP
GBPR_NATGAS_MAL                                              .    GBPR_NATGAS_MAL_TUP
GBPR_NATGAS_40                                               .    GBPR_NATGAS_40_TUP
GBPR_NATGAS_50                                               .    GBPR_NATGAS_50_TUP
GBPR_NATGAS_100                                              .    GBPR_NATGAS_100_TUP
GBPR_NATGAS_VOUSAARI                                         .    GBPR_NATGAS_VOUSAARI_TUP
GBPR_NATGAS_FINEL                                            .    GBPR_NATGAS_FINEL_TUP
GBPR_NATGAS_SUOMENOJA2                                       .    GBPR_NATGAS_SUOMENOJA2_TUP
GBPR_NATGAS_GASAREA                                          .    GBPR_NATGAS_GASAREA_TUP
GBPR_NATGAS_SUOMENOJA                                        .    GBPR_NATGAS_SUOMENOJA_TUP
GBPR_NATGAS_MARTINLAAKSOGT                                   .    GBPR_NATGAS_MARTINLAAKSOGT_TUP
GBPR_NATGAS                                                  .    GBPR_NATGAS_TUP
GHOB_NATGAS                                                  .    GHOB_NATGAS_TUP
GBPR_NATGAS_IND                                              .    GBPR_NATGAS_IND_TUP
GBPR_NATGAS1                                                 .    GBPR_NATGAS1_TUP
GBPR_NATGAS2                                                 .    GBPR_NATGAS2_TUP
GBPR_NATGAS3                                                 .    GBPR_NATGAS3_TUP
GCND_NATGAS1_1                                               .    GCND_NATGAS1_1_TUP
GCND_NATGAS1_2                                               .    GCND_NATGAS1_2_TUP
GCND_NATGAS1_3                                               .    GCND_NATGAS1_3_TUP
GCND_NATGAS2_1                                               .    GCND_NATGAS2_1_TUP
GCND_NATGAS2_2                                               .    GCND_NATGAS2_2_TUP
GCND_NATGAS2_3                                               .    GCND_NATGAS2_3_TUP
GCND_NATGAS3_1                                               .    GCND_NATGAS3_1_TUP
GCND_NATGAS3_2                                               .    GCND_NATGAS3_2_TUP
GCND_NATGAS3_3                                               .    GCND_NATGAS3_3_TUP
GCND_NATGAS4_1                                               .    GCND_NATGAS4_1_TUP
GCND_NATGAS4_2                                               .    GCND_NATGAS4_2_TUP
GCND_NATGAS4_3                                               .    GCND_NATGAS4_3_TUP
ST-BP-Iru-2-OG                                               .    ST-BP-Iru-2-OG_TUP
ST-Ext-Iru-1-OG                                              .    ST-Ext-Iru-1-OG_TUP
DH-Old-G-EE                                                  .    DH-Old-G-EE_TUP
DH-Old-O-EE                                                  .    DH-Old-O-EE_TUP
GEXT_NATGAS_IRU1                                             .    GEXT_NATGAS_IRU1_TUP
GBPR_NATGAS_IRU2                                             .    GBPR_NATGAS_IRU2_TUP
GEXT_NATGAS_EE_SMALL                                         .    GEXT_NATGAS_EE_SMALL_TUP
GE-BP-LV-G                                                   .    GE-BP-LV-G_TUP
Rigas_TEC-1-GT                                               .    Rigas_TEC-1-GT_TUP
Rigas_TEC-1-ST                                               .    Rigas_TEC-1-ST_TUP
Rigas_TEC-2-CC                                               .    Rigas_TEC-2-CC_TUP
ST-BP-IM-G                                                   .    ST-BP-IM-G_TUP
ST-BP-LV-OG                                                  .    ST-BP-LV-OG_TUP
AchemaCHP                                                    .    AchemaCHP_TUP
KaunasCHP                                                    .    KaunasCHP_TUP
LithuanianCCGT                                               .    LithuanianCCGT_TUP
LithuanianPP                                                 .    LithuanianPP_TUP
OrlenCHP                                                     .    OrlenCHP_TUP
PanevezysCHP                                                 .    PanevezysCHP_TUP
VilniusCHP3                                                  .    VilniusCHP3_TUP
ST-Cond-LM-F1-Gfree                                          .    ST-Cond-LM-F1-Gfree_TUP
GBPR_OTHERGAS_IND                                            .    GBPR_OTHERGAS_IND_TUP
GCND-NG                                                      .    GCND-NG_TUP
GBPR-NATGAS                                                  .    GBPR-NATGAS_TUP
SteamTur-CON-NG-10_19                                        .    SteamTur-CON-NG-10_19_TUP
SteamTur-CON-NG-20_50                                        .    SteamTur-CON-NG-20_50_TUP
SteamTur-EXT-NG-10_19                                        .    SteamTur-EXT-NG-10_19_TUP
SteamTur-EXT-NG-20_50                                        .    SteamTur-EXT-NG-20_50_TUP
GasTur-CON-NG-10_19                                          .    GasTur-CON-NG-10_19_TUP
GasTur-CON-NG-20                                             .    GasTur-CON-NG-20_TUP
GasTur-EXT-NG-10_19                                          .    GasTur-EXT-NG-10_19_TUP
GasTur-EXT-NG-20                                             .    GasTur-EXT-NG-20_TUP
GasTurCC-CON-NG-10_19                                        .    GasTurCC-CON-NG-10_19_TUP
GasTurCC-CON-NG-20_29                                        .    GasTurCC-CON-NG-20_29_TUP
GasTurCC-CON-NG-30_49                                        .    GasTurCC-CON-NG-30_49_TUP
GasTurCC-CON-NG-50                                           .    GasTurCC-CON-NG-50_TUP
GasTurCC-EXT-NG-10_19                                        .    GasTurCC-EXT-NG-10_19_TUP
GasTurCC-EXT-NG-20_29                                        .    GasTurCC-EXT-NG-20_29_TUP
GasTurCC-EXT-NG-30_49                                        .    GasTurCC-EXT-NG-30_49_TUP
GasTurCC-EXT-NG-50                                           .    GasTurCC-EXT-NG-50_TUP
GasTurCC-BP-NG-10_19                                         .    GasTurCC-BP-NG-10_19_TUP
GasTurCC-BP-NG-20                                            .    GasTurCC-BP-NG-20_TUP
Engine-NG-10_19                                              .    Engine-NG-10_19_TUP
Engine-NG-20_29                                              .    Engine-NG-20_29_TUP
Engine-NG-30_49                                              .    Engine-NG-30_49_TUP
Engine-NG-50                                                 .    Engine-NG-50_TUP
Boiler-NG                                                    .    Boiler-NG_TUP
HO-B1-NG                                                     .    HO-B1-NG_TUP
HO-IND1-NG                                                   .    HO-IND1-NG_TUP
HCVSMV_ST_B8_NG                                              .    HCVSMV_ST_B8_NG_TUP
CC-B9-NGn                                                    .    CC-B9-NGn_TUP
ST-B8-NG                                                     .    ST-B8-NG_TUP
HO-B8-NG                                                     .    HO-B8-NG_TUP
DE_HO-NG                                                     .    DE_HO-NG_TUP
DE_HO-NG-TempFix                                             .    DE_HO-NG-TempFix_TUP
DE-COND-GAS-0-00                                             .    DE-COND-GAS-0-00_TUP
DE-COND-GAS-101-00                                           .    DE-COND-GAS-101-00_TUP
DE-KWK-GAS-CC-91                                             .    DE-KWK-GAS-CC-91_TUP
DE-KWK-GAS-GT-00                                             .    DE-KWK-GAS-GT-00_TUP
DE-KWK-GAS-IC-00                                             .    DE-KWK-GAS-IC-00_TUP
DE-KWK-GAS-ST-00                                             .    DE-KWK-GAS-ST-00_TUP
DE-COND-GAS-CC-0-91                                          .    DE-COND-GAS-CC-0-91_TUP
DE-KWK-GAS-CC-00                                             .    DE-KWK-GAS-CC-00_TUP
DK_CA_Aab_Boiler_NG                                          .    DK_CA_Aab_Boiler_NG_TUP
DK_CA_Aab_Engine_NG                                          .    DK_CA_Aab_Engine_NG_TUP
DK_CA_Aab_DEC_Boiler_NG                                      .    DK_CA_Aab_DEC_Boiler_NG_TUP
DK_CA_Aab_DEC_Engine_NG                                      .    DK_CA_Aab_DEC_Engine_NG_TUP
DK_CA_Aab_DEC_GasTur-NG                                      .    DK_CA_Aab_DEC_GasTur-NG_TUP
DK_CA_Aal_Boiler_NG                                          .    DK_CA_Aal_Boiler_NG_TUP
DK_CA_Aal_Engine_NG                                          .    DK_CA_Aal_Engine_NG_TUP
DK_CA_Aal_DEC_Boiler_NG                                      .    DK_CA_Aal_DEC_Boiler_NG_TUP
DK_CA_Aal_DEC_Engine_NG                                      .    DK_CA_Aal_DEC_Engine_NG_TUP
DK_CA_Aal_DEC_GasTur-NG                                      .    DK_CA_Aal_DEC_GasTur-NG_TUP
DK_CA_Aarhus_Boiler_NG                                       .    DK_CA_Aarhus_Boiler_NG_TUP
DK_CA_Aarhus_Engine_NG                                       .    DK_CA_Aarhus_Engine_NG_TUP
DK_CA_Aarhus_DEC_Boiler_NG                                   .    DK_CA_Aarhus_DEC_Boiler_NG_TUP
DK_CA_Aarhus_DEC_Engine_NG                                   .    DK_CA_Aarhus_DEC_Engine_NG_TUP
DK_CA_Esb_Boiler_NG                                          .    DK_CA_Esb_Boiler_NG_TUP
DK_CA_Esb_Engine_NG                                          .    DK_CA_Esb_Engine_NG_TUP
DK_CA_Esb_DEC_Boiler_NG                                      .    DK_CA_Esb_DEC_Boiler_NG_TUP
DK_CA_Esb_DEC_Engine_NG                                      .    DK_CA_Esb_DEC_Engine_NG_TUP
DK_CA_Esb_DEC_GasTur-NG                                      .    DK_CA_Esb_DEC_GasTur-NG_TUP
DK_CA_Hern_Boiler_NG                                         .    DK_CA_Hern_Boiler_NG_TUP
DK_CA_Hern_Engine_NG                                         .    DK_CA_Hern_Engine_NG_TUP
DK_CA_Hern_DEC_Boiler_NG                                     .    DK_CA_Hern_DEC_Boiler_NG_TUP
DK_CA_Hern_DEC_Engine_NG                                     .    DK_CA_Hern_DEC_Engine_NG_TUP
DK_CA_Hern_DEC_GasTur-NG                                     .    DK_CA_Hern_DEC_GasTur-NG_TUP
DK_CA_Kal_Boiler_NG                                          .    DK_CA_Kal_Boiler_NG_TUP
DK_CA_Kal_Engine_NG                                          .    DK_CA_Kal_Engine_NG_TUP
DK_CA_Kal_GasTur_CND_NG                                      .    DK_CA_Kal_GasTur_CND_NG_TUP
DK_CA_Kal_DEC_Boiler_NG                                      .    DK_CA_Kal_DEC_Boiler_NG_TUP
DK_CA_Kal_DEC_Engine_NG                                      .    DK_CA_Kal_DEC_Engine_NG_TUP
DK_CA_KBH_Boiler_NG                                          .    DK_CA_KBH_Boiler_NG_TUP
DK_CA_KBH_Engine_NG                                          .    DK_CA_KBH_Engine_NG_TUP
DK_CA_KBH_GasTur-NG                                          .    DK_CA_KBH_GasTur-NG_TUP
DK_CA_KBH_DEC_Boiler_NG                                      .    DK_CA_KBH_DEC_Boiler_NG_TUP
DK_CA_KBH_DEC_Engine_NG                                      .    DK_CA_KBH_DEC_Engine_NG_TUP
DK_CA_KBH_DEC_GasTur-NG                                      .    DK_CA_KBH_DEC_GasTur-NG_TUP
DK_CA_Odense_Boiler_NG                                       .    DK_CA_Odense_Boiler_NG_TUP
DK_CA_Odense_Engine_NG                                       .    DK_CA_Odense_Engine_NG_TUP
DK_CA_Odense_DEC_Boiler_NG                                   .    DK_CA_Odense_DEC_Boiler_NG_TUP
DK_CA_Odense_DEC_Engine_NG                                   .    DK_CA_Odense_DEC_Engine_NG_TUP
DK_CA_Odense_DEC_GasTur-NG                                   .    DK_CA_Odense_DEC_GasTur-NG_TUP
DK_CA_Randers_Boiler_NG                                      .    DK_CA_Randers_Boiler_NG_TUP
DK_CA_Randers_Engine_NG                                      .    DK_CA_Randers_Engine_NG_TUP
DK_CA_Randers_DEC_Boiler_NG                                  .    DK_CA_Randers_DEC_Boiler_NG_TUP
DK_CA_Randers_DEC_Engine_NG                                  .    DK_CA_Randers_DEC_Engine_NG_TUP
DK_CA_Randers_DEC_GasTur-NG                                  .    DK_CA_Randers_DEC_GasTur-NG_TUP
DK_CA_Roenne_DEC_Boiler_NG                                   .    DK_CA_Roenne_DEC_Boiler_NG_TUP
DK_CA_TVIS_Boiler_NG                                         .    DK_CA_TVIS_Boiler_NG_TUP
DK_CA_TVIS_GasTurCC-NG                                       .    DK_CA_TVIS_GasTurCC-NG_TUP
DK_CA_TVIS_GasTur-NG                                         .    DK_CA_TVIS_GasTur-NG_TUP
DK_CA_TVIS_DEC_Boiler_NG                                     .    DK_CA_TVIS_DEC_Boiler_NG_TUP
DK_CA_TVIS_DEC_Engine_CND_NG                                 .    DK_CA_TVIS_DEC_Engine_CND_NG_TUP
DK_CA_TVIS_DEC_Engine_NG                                     .    DK_CA_TVIS_DEC_Engine_NG_TUP
DK_CA_Vestfrb_DEC_Boiler_NG                                  .    DK_CA_Vestfrb_DEC_Boiler_NG_TUP
DK_CA_Vestfrb_DEC_Engine_NG                                  .    DK_CA_Vestfrb_DEC_Engine_NG_TUP
DK_CA_Vestfrb_DEC_GasTur-NG                                  .    DK_CA_Vestfrb_DEC_GasTur-NG_TUP
DK2_DTU_Boiler_NG                                            .    DK2_DTU_Boiler_NG_TUP
DK2_DTU_GasTur-NG                                            .    DK2_DTU_GasTur-NG_TUP
DK_MA_Hil_Boiler_NG                                          .    DK_MA_Hil_Boiler_NG_TUP
DK_MA_Hil_Engine_NG                                          .    DK_MA_Hil_Engine_NG_TUP
DK_MA_Hil_GasTur-NG                                          .    DK_MA_Hil_GasTur-NG_TUP
DK_MA_Hil_DEC_Boiler_NG                                      .    DK_MA_Hil_DEC_Boiler_NG_TUP
DK_MA_Hil_DEC_Engine_NG                                      .    DK_MA_Hil_DEC_Engine_NG_TUP
DK_MA_Hjoerring_Boiler_NG                                    .    DK_MA_Hjoerring_Boiler_NG_TUP
DK_MA_Hjoerring_Engine_NG                                    .    DK_MA_Hjoerring_Engine_NG_TUP
DK_MA_Hjoerring_GasTur-NG                                    .    DK_MA_Hjoerring_GasTur-NG_TUP
DK_MA_Holst_Boiler_NG                                        .    DK_MA_Holst_Boiler_NG_TUP
DK_MA_Holst_DEC_Boiler_NG                                    .    DK_MA_Holst_DEC_Boiler_NG_TUP
DK_MA_Holst_DEC_Engine_NG                                    .    DK_MA_Holst_DEC_Engine_NG_TUP
DK_MA_Holst_DEC_GasTur-NG                                    .    DK_MA_Holst_DEC_GasTur-NG_TUP
DK_MA_Horsens_Boiler_NG                                      .    DK_MA_Horsens_Boiler_NG_TUP
DK_MA_Horsens_DEC_Boiler_NG                                  .    DK_MA_Horsens_DEC_Boiler_NG_TUP
DK_MA_Horsens_DEC_Engine_NG                                  .    DK_MA_Horsens_DEC_Engine_NG_TUP
DK_MA_NrdOstSj_Boiler_NG                                     .    DK_MA_NrdOstSj_Boiler_NG_TUP
DK_MA_NrdOstSj_Engine_NG                                     .    DK_MA_NrdOstSj_Engine_NG_TUP
DK_MA_NrdOstSj_GasTur-NG                                     .    DK_MA_NrdOstSj_GasTur-NG_TUP
DK_MA_NrdOstSj_DEC_Engine_NG                                 .    DK_MA_NrdOstSj_DEC_Engine_NG_TUP
DK_MA_Silk_Boiler_NG                                         .    DK_MA_Silk_Boiler_NG_TUP
DK_MA_Silk_GasTur-NG                                         .    DK_MA_Silk_GasTur-NG_TUP
DK_MA_Sndborg_Boiler_NG                                      .    DK_MA_Sndborg_Boiler_NG_TUP
DK_MA_Sndborg_DEC_Boiler_NG                                  .    DK_MA_Sndborg_DEC_Boiler_NG_TUP
DK_MA_Sndborg_DEC_Engine_NG                                  .    DK_MA_Sndborg_DEC_Engine_NG_TUP
DK_MA_Viborg_Boiler_NG                                       .    DK_MA_Viborg_Boiler_NG_TUP
DK_MA_Viborg_Engine_NG                                       .    DK_MA_Viborg_Engine_NG_TUP
DK_MA_Viborg_GasTur-NG                                       .    DK_MA_Viborg_GasTur-NG_TUP
DK_MA_Viborg_DEC_Boiler_NG                                   .    DK_MA_Viborg_DEC_Boiler_NG_TUP
DK_MA_Viborg_DEC_Engine_NG                                   .    DK_MA_Viborg_DEC_Engine_NG_TUP
DK_MAM_Aars_Boiler_NG                                        .    DK_MAM_Aars_Boiler_NG_TUP
DK_MAM_Aars_Engine_NG                                        .    DK_MAM_Aars_Engine_NG_TUP
DK_MAM_Aars_DEC_Boiler_NG                                    .    DK_MAM_Aars_DEC_Boiler_NG_TUP
DK_MAM_Aars_DEC_Engine_NG                                    .    DK_MAM_Aars_DEC_Engine_NG_TUP
DK_MAM_Aars_DEC_GasTur-NG                                    .    DK_MAM_Aars_DEC_GasTur-NG_TUP
DK_MAM_Frdhavn_Boiler_NG                                     .    DK_MAM_Frdhavn_Boiler_NG_TUP
DK_MAM_Frdhavn_GasTur-NG                                     .    DK_MAM_Frdhavn_GasTur-NG_TUP
DK_MAM_Frdhavn_DEC_Boiler_NG                                 .    DK_MAM_Frdhavn_DEC_Boiler_NG_TUP
DK_MAM_Frdhavn_DEC_Engine_NG                                 .    DK_MAM_Frdhavn_DEC_Engine_NG_TUP
DK_MAM_Had_Boiler_NG                                         .    DK_MAM_Had_Boiler_NG_TUP
DK_MAM_Had_Engine_NG                                         .    DK_MAM_Had_Engine_NG_TUP
DK_MAM_Had_DEC_Boiler_NG                                     .    DK_MAM_Had_DEC_Boiler_NG_TUP
DK_MAM_Had_DEC_Engine_NG                                     .    DK_MAM_Had_DEC_Engine_NG_TUP
DK_MAM_Hammel_DEC_Boiler_NG                                  .    DK_MAM_Hammel_DEC_Boiler_NG_TUP
DK_MAM_Hammel_DEC_Engine_NG                                  .    DK_MAM_Hammel_DEC_Engine_NG_TUP
DK_MAM_Hobro_Boiler_NG                                       .    DK_MAM_Hobro_Boiler_NG_TUP
DK_MAM_Hobro_Engine_NG                                       .    DK_MAM_Hobro_Engine_NG_TUP
DK_MAM_Hobro_DEC_Boiler_NG                                   .    DK_MAM_Hobro_DEC_Boiler_NG_TUP
DK_MAM_Hobro_DEC_Engine_NG                                   .    DK_MAM_Hobro_DEC_Engine_NG_TUP
DK_MAM_Naestved_Boiler_NG                                    .    DK_MAM_Naestved_Boiler_NG_TUP
DK_MAM_Naestved_Engine_NG                                    .    DK_MAM_Naestved_Engine_NG_TUP
DK_MAM_Naestved_DEC_Boiler_NG                                .    DK_MAM_Naestved_DEC_Boiler_NG_TUP
DK_MAM_Naestved_DEC_Engine_NG                                .    DK_MAM_Naestved_DEC_Engine_NG_TUP
DK_MAM_NrAlslev_Boiler_NG                                    .    DK_MAM_NrAlslev_Boiler_NG_TUP
DK_MAM_Nyborg_Boiler_NG                                      .    DK_MAM_Nyborg_Boiler_NG_TUP
DK_MAM_Nyborg_GasTur-NG                                      .    DK_MAM_Nyborg_GasTur-NG_TUP
DK_MAM_Nyk_Boiler_NG                                         .    DK_MAM_Nyk_Boiler_NG_TUP
DK_MAM_Nyk_DEC_Boiler_NG                                     .    DK_MAM_Nyk_DEC_Boiler_NG_TUP
DK_MAM_Skagen_Boiler_NG                                      .    DK_MAM_Skagen_Boiler_NG_TUP
DK_MAM_Skagen_Engine_NG                                      .    DK_MAM_Skagen_Engine_NG_TUP
DK_MAM_Skagen_GasTur-NG                                      .    DK_MAM_Skagen_GasTur-NG_TUP
DK_MAM_Slagelse_Boiler_NG                                    .    DK_MAM_Slagelse_Boiler_NG_TUP
DK_MAM_Slagelse_DEC_Boiler_NG                                .    DK_MAM_Slagelse_DEC_Boiler_NG_TUP
DK_MAM_Slagelse_DEC_Engine_NG                                .    DK_MAM_Slagelse_DEC_Engine_NG_TUP
DK_MAM_Svend_Boiler_NG                                       .    DK_MAM_Svend_Boiler_NG_TUP
DK_MAM_Svend_Engine_NG                                       .    DK_MAM_Svend_Engine_NG_TUP
DK_MAM_Svend_DEC_Boiler_NG                                   .    DK_MAM_Svend_DEC_Boiler_NG_TUP
DK_MAM_Svend_DEC_Engine_NG                                   .    DK_MAM_Svend_DEC_Engine_NG_TUP
DK_MAM_Thisted_Boiler_NG                                     .    DK_MAM_Thisted_Boiler_NG_TUP
DK_MAM_Thisted_Engine_NG                                     .    DK_MAM_Thisted_Engine_NG_TUP
DK_MAM_Thisted_DEC_Boiler_NG                                 .    DK_MAM_Thisted_DEC_Boiler_NG_TUP
DK_MAM_Thisted_DEC_Engine_NG                                 .    DK_MAM_Thisted_DEC_Engine_NG_TUP
GT_CND_NG_2020                                               .    GT_CND_NG_2020_TUP
GT_CND_NG_2025                                               .    GT_CND_NG_2025_TUP
GT_CND_NG_2030                                               .    GT_CND_NG_2030_TUP
GTCC_EXT_NG_2020                                             .    GTCC_EXT_NG_2020_TUP
GTCC_EXT_NG_2025                                             .    GTCC_EXT_NG_2025_TUP
GTCC_EXT_NG_2030                                             .    GTCC_EXT_NG_2030_TUP
GTCC_BP_NG_2020                                              .    GTCC_BP_NG_2020_TUP
GTCC_BP_NG_2025                                              .    GTCC_BP_NG_2025_TUP
GTCC_BP_NG_2030                                              .    GTCC_BP_NG_2030_TUP
ENG_EXT_NG_2020                                              .    ENG_EXT_NG_2020_TUP
ENG_EXT_NG_2025                                              .    ENG_EXT_NG_2025_TUP
ENG_EXT_NG_2030                                              .    ENG_EXT_NG_2030_TUP
BO_NG_2020                                                   .    BO_NG_2020_TUP
BO_NG_2025                                                   .    BO_NG_2025_TUP
BO_NG_2030                                                   .    BO_NG_2030_TUP
GCND_NATGAS1                                                 .    GCND_NATGAS1_BH2
GCND_NATGAS2                                                 .    GCND_NATGAS2_BH2
GCND_NATGAS3                                                 .    GCND_NATGAS3_BH2
GCND_NATGAS4                                                 .    GCND_NATGAS4_BH2
GEXT_NATGAS_ORESUND                                          .    GEXT_NATGAS_ORESUND_BH2
GEXT_NATGAS_NOKIA                                            .    GEXT_NATGAS_NOKIA_BH2
GEXT_NATGAS_MERTANIEMI                                       .    GEXT_NATGAS_MERTANIEMI_BH2
GEXT_NATGAS_TAMPERE                                          .    GEXT_NATGAS_TAMPERE_BH2
GEXT_NATGAS_VOUSAARI                                         .    GEXT_NATGAS_VOUSAARI_BH2
GEXT_NATGAS_AVEDORE                                          .    GEXT_NATGAS_AVEDORE_BH2
GEXT_NATGAS_SKERBEK                                          .    GEXT_NATGAS_SKERBEK_BH2
GEXT_NATGAS                                                  .    GEXT_NATGAS_BH2
GBPR_NATGAS_RYA                                              .    GBPR_NATGAS_RYA_BH2
GBPR_NATGAS_SE4EL                                            .    GBPR_NATGAS_SE4EL_BH2
GBPR_NATGAS_GOT                                              .    GBPR_NATGAS_GOT_BH2
GBPR_NATGAS_MAL                                              .    GBPR_NATGAS_MAL_BH2
GBPR_NATGAS_40                                               .    GBPR_NATGAS_40_BH2
GBPR_NATGAS_50                                               .    GBPR_NATGAS_50_BH2
GBPR_NATGAS_100                                              .    GBPR_NATGAS_100_BH2
GBPR_NATGAS_VOUSAARI                                         .    GBPR_NATGAS_VOUSAARI_BH2
GBPR_NATGAS_FINEL                                            .    GBPR_NATGAS_FINEL_BH2
GBPR_NATGAS_SUOMENOJA2                                       .    GBPR_NATGAS_SUOMENOJA2_BH2
GBPR_NATGAS_GASAREA                                          .    GBPR_NATGAS_GASAREA_BH2
GBPR_NATGAS_SUOMENOJA                                        .    GBPR_NATGAS_SUOMENOJA_BH2
GBPR_NATGAS_MARTINLAAKSOGT                                   .    GBPR_NATGAS_MARTINLAAKSOGT_BH2
GBPR_NATGAS                                                  .    GBPR_NATGAS_BH2
GHOB_NATGAS                                                  .    GHOB_NATGAS_BH2
GBPR_NATGAS_IND                                              .    GBPR_NATGAS_IND_BH2
GBPR_NATGAS1                                                 .    GBPR_NATGAS1_BH2
GBPR_NATGAS2                                                 .    GBPR_NATGAS2_BH2
GBPR_NATGAS3                                                 .    GBPR_NATGAS3_BH2
GCND_NATGAS1_1                                               .    GCND_NATGAS1_1_BH2
GCND_NATGAS1_2                                               .    GCND_NATGAS1_2_BH2
GCND_NATGAS1_3                                               .    GCND_NATGAS1_3_BH2
GCND_NATGAS2_1                                               .    GCND_NATGAS2_1_BH2
GCND_NATGAS2_2                                               .    GCND_NATGAS2_2_BH2
GCND_NATGAS2_3                                               .    GCND_NATGAS2_3_BH2
GCND_NATGAS3_1                                               .    GCND_NATGAS3_1_BH2
GCND_NATGAS3_2                                               .    GCND_NATGAS3_2_BH2
GCND_NATGAS3_3                                               .    GCND_NATGAS3_3_BH2
GCND_NATGAS4_1                                               .    GCND_NATGAS4_1_BH2
GCND_NATGAS4_2                                               .    GCND_NATGAS4_2_BH2
GCND_NATGAS4_3                                               .    GCND_NATGAS4_3_BH2
ST-BP-Iru-2-OG                                               .    ST-BP-Iru-2-OG_BH2
ST-Ext-Iru-1-OG                                              .    ST-Ext-Iru-1-OG_BH2
DH-Old-G-EE                                                  .    DH-Old-G-EE_BH2
DH-Old-O-EE                                                  .    DH-Old-O-EE_BH2
GEXT_NATGAS_IRU1                                             .    GEXT_NATGAS_IRU1_BH2
GBPR_NATGAS_IRU2                                             .    GBPR_NATGAS_IRU2_BH2
GEXT_NATGAS_EE_SMALL                                         .    GEXT_NATGAS_EE_SMALL_BH2
GE-BP-LV-G                                                   .    GE-BP-LV-G_BH2
Rigas_TEC-1-GT                                               .    Rigas_TEC-1-GT_BH2
Rigas_TEC-1-ST                                               .    Rigas_TEC-1-ST_BH2
Rigas_TEC-2-CC                                               .    Rigas_TEC-2-CC_BH2
ST-BP-IM-G                                                   .    ST-BP-IM-G_BH2
ST-BP-LV-OG                                                  .    ST-BP-LV-OG_BH2
AchemaCHP                                                    .    AchemaCHP_BH2
KaunasCHP                                                    .    KaunasCHP_BH2
LithuanianCCGT                                               .    LithuanianCCGT_BH2
LithuanianPP                                                 .    LithuanianPP_BH2
OrlenCHP                                                     .    OrlenCHP_BH2
PanevezysCHP                                                 .    PanevezysCHP_BH2
VilniusCHP3                                                  .    VilniusCHP3_BH2
ST-Cond-LM-F1-Gfree                                          .    ST-Cond-LM-F1-Gfree_BH2
GBPR_OTHERGAS_IND                                            .    GBPR_OTHERGAS_IND_BH2
GCND-NG                                                      .    GCND-NG_BH2
GBPR-NATGAS                                                  .    GBPR-NATGAS_BH2
SteamTur-CON-NG-10_19                                        .    SteamTur-CON-NG-10_19_BH2
SteamTur-CON-NG-20_50                                        .    SteamTur-CON-NG-20_50_BH2
SteamTur-EXT-NG-10_19                                        .    SteamTur-EXT-NG-10_19_BH2
SteamTur-EXT-NG-20_50                                        .    SteamTur-EXT-NG-20_50_BH2
GasTur-CON-NG-10_19                                          .    GasTur-CON-NG-10_19_BH2
GasTur-CON-NG-20                                             .    GasTur-CON-NG-20_BH2
GasTur-EXT-NG-10_19                                          .    GasTur-EXT-NG-10_19_BH2
GasTur-EXT-NG-20                                             .    GasTur-EXT-NG-20_BH2
GasTurCC-CON-NG-10_19                                        .    GasTurCC-CON-NG-10_19_BH2
GasTurCC-CON-NG-20_29                                        .    GasTurCC-CON-NG-20_29_BH2
GasTurCC-CON-NG-30_49                                        .    GasTurCC-CON-NG-30_49_BH2
GasTurCC-CON-NG-50                                           .    GasTurCC-CON-NG-50_BH2
GasTurCC-EXT-NG-10_19                                        .    GasTurCC-EXT-NG-10_19_BH2
GasTurCC-EXT-NG-20_29                                        .    GasTurCC-EXT-NG-20_29_BH2
GasTurCC-EXT-NG-30_49                                        .    GasTurCC-EXT-NG-30_49_BH2
GasTurCC-EXT-NG-50                                           .    GasTurCC-EXT-NG-50_BH2
GasTurCC-BP-NG-10_19                                         .    GasTurCC-BP-NG-10_19_BH2
GasTurCC-BP-NG-20                                            .    GasTurCC-BP-NG-20_BH2
Engine-NG-10_19                                              .    Engine-NG-10_19_BH2
Engine-NG-20_29                                              .    Engine-NG-20_29_BH2
Engine-NG-30_49                                              .    Engine-NG-30_49_BH2
Engine-NG-50                                                 .    Engine-NG-50_BH2
Boiler-NG                                                    .    Boiler-NG_BH2
HO-B1-NG                                                     .    HO-B1-NG_BH2
HO-IND1-NG                                                   .    HO-IND1-NG_BH2
HCVSMV_ST_B8_NG                                              .    HCVSMV_ST_B8_NG_BH2
CC-B9-NGn                                                    .    CC-B9-NGn_BH2
ST-B8-NG                                                     .    ST-B8-NG_BH2
HO-B8-NG                                                     .    HO-B8-NG_BH2
DE_HO-NG                                                     .    DE_HO-NG_BH2
DE_HO-NG-TempFix                                             .    DE_HO-NG-TempFix_BH2
DE-COND-GAS-0-00                                             .    DE-COND-GAS-0-00_BH2
DE-COND-GAS-101-00                                           .    DE-COND-GAS-101-00_BH2
DE-KWK-GAS-CC-91                                             .    DE-KWK-GAS-CC-91_BH2
DE-KWK-GAS-GT-00                                             .    DE-KWK-GAS-GT-00_BH2
DE-KWK-GAS-IC-00                                             .    DE-KWK-GAS-IC-00_BH2
DE-KWK-GAS-ST-00                                             .    DE-KWK-GAS-ST-00_BH2
DE-COND-GAS-CC-0-91                                          .    DE-COND-GAS-CC-0-91_BH2
DE-KWK-GAS-CC-00                                             .    DE-KWK-GAS-CC-00_BH2
DK_CA_Aab_Boiler_NG                                          .    DK_CA_Aab_Boiler_NG_BH2
DK_CA_Aab_Engine_NG                                          .    DK_CA_Aab_Engine_NG_BH2
DK_CA_Aab_DEC_Boiler_NG                                      .    DK_CA_Aab_DEC_Boiler_NG_BH2
DK_CA_Aab_DEC_Engine_NG                                      .    DK_CA_Aab_DEC_Engine_NG_BH2
DK_CA_Aab_DEC_GasTur-NG                                      .    DK_CA_Aab_DEC_GasTur-NG_BH2
DK_CA_Aal_Boiler_NG                                          .    DK_CA_Aal_Boiler_NG_BH2
DK_CA_Aal_Engine_NG                                          .    DK_CA_Aal_Engine_NG_BH2
DK_CA_Aal_DEC_Boiler_NG                                      .    DK_CA_Aal_DEC_Boiler_NG_BH2
DK_CA_Aal_DEC_Engine_NG                                      .    DK_CA_Aal_DEC_Engine_NG_BH2
DK_CA_Aal_DEC_GasTur-NG                                      .    DK_CA_Aal_DEC_GasTur-NG_BH2
DK_CA_Aarhus_Boiler_NG                                       .    DK_CA_Aarhus_Boiler_NG_BH2
DK_CA_Aarhus_Engine_NG                                       .    DK_CA_Aarhus_Engine_NG_BH2
DK_CA_Aarhus_DEC_Boiler_NG                                   .    DK_CA_Aarhus_DEC_Boiler_NG_BH2
DK_CA_Aarhus_DEC_Engine_NG                                   .    DK_CA_Aarhus_DEC_Engine_NG_BH2
DK_CA_Esb_Boiler_NG                                          .    DK_CA_Esb_Boiler_NG_BH2
DK_CA_Esb_Engine_NG                                          .    DK_CA_Esb_Engine_NG_BH2
DK_CA_Esb_DEC_Boiler_NG                                      .    DK_CA_Esb_DEC_Boiler_NG_BH2
DK_CA_Esb_DEC_Engine_NG                                      .    DK_CA_Esb_DEC_Engine_NG_BH2
DK_CA_Esb_DEC_GasTur-NG                                      .    DK_CA_Esb_DEC_GasTur-NG_BH2
DK_CA_Hern_Boiler_NG                                         .    DK_CA_Hern_Boiler_NG_BH2
DK_CA_Hern_Engine_NG                                         .    DK_CA_Hern_Engine_NG_BH2
DK_CA_Hern_DEC_Boiler_NG                                     .    DK_CA_Hern_DEC_Boiler_NG_BH2
DK_CA_Hern_DEC_Engine_NG                                     .    DK_CA_Hern_DEC_Engine_NG_BH2
DK_CA_Hern_DEC_GasTur-NG                                     .    DK_CA_Hern_DEC_GasTur-NG_BH2
DK_CA_Kal_Boiler_NG                                          .    DK_CA_Kal_Boiler_NG_BH2
DK_CA_Kal_Engine_NG                                          .    DK_CA_Kal_Engine_NG_BH2
DK_CA_Kal_GasTur_CND_NG                                      .    DK_CA_Kal_GasTur_CND_NG_BH2
DK_CA_Kal_DEC_Boiler_NG                                      .    DK_CA_Kal_DEC_Boiler_NG_BH2
DK_CA_Kal_DEC_Engine_NG                                      .    DK_CA_Kal_DEC_Engine_NG_BH2
DK_CA_KBH_Boiler_NG                                          .    DK_CA_KBH_Boiler_NG_BH2
DK_CA_KBH_Engine_NG                                          .    DK_CA_KBH_Engine_NG_BH2
DK_CA_KBH_GasTur-NG                                          .    DK_CA_KBH_GasTur-NG_BH2
DK_CA_KBH_DEC_Boiler_NG                                      .    DK_CA_KBH_DEC_Boiler_NG_BH2
DK_CA_KBH_DEC_Engine_NG                                      .    DK_CA_KBH_DEC_Engine_NG_BH2
DK_CA_KBH_DEC_GasTur-NG                                      .    DK_CA_KBH_DEC_GasTur-NG_BH2
DK_CA_Odense_Boiler_NG                                       .    DK_CA_Odense_Boiler_NG_BH2
DK_CA_Odense_Engine_NG                                       .    DK_CA_Odense_Engine_NG_BH2
DK_CA_Odense_DEC_Boiler_NG                                   .    DK_CA_Odense_DEC_Boiler_NG_BH2
DK_CA_Odense_DEC_Engine_NG                                   .    DK_CA_Odense_DEC_Engine_NG_BH2
DK_CA_Odense_DEC_GasTur-NG                                   .    DK_CA_Odense_DEC_GasTur-NG_BH2
DK_CA_Randers_Boiler_NG                                      .    DK_CA_Randers_Boiler_NG_BH2
DK_CA_Randers_Engine_NG                                      .    DK_CA_Randers_Engine_NG_BH2
DK_CA_Randers_DEC_Boiler_NG                                  .    DK_CA_Randers_DEC_Boiler_NG_BH2
DK_CA_Randers_DEC_Engine_NG                                  .    DK_CA_Randers_DEC_Engine_NG_BH2
DK_CA_Randers_DEC_GasTur-NG                                  .    DK_CA_Randers_DEC_GasTur-NG_BH2
DK_CA_Roenne_DEC_Boiler_NG                                   .    DK_CA_Roenne_DEC_Boiler_NG_BH2
DK_CA_TVIS_Boiler_NG                                         .    DK_CA_TVIS_Boiler_NG_BH2
DK_CA_TVIS_GasTurCC-NG                                       .    DK_CA_TVIS_GasTurCC-NG_BH2
DK_CA_TVIS_GasTur-NG                                         .    DK_CA_TVIS_GasTur-NG_BH2
DK_CA_TVIS_DEC_Boiler_NG                                     .    DK_CA_TVIS_DEC_Boiler_NG_BH2
DK_CA_TVIS_DEC_Engine_CND_NG                                 .    DK_CA_TVIS_DEC_Engine_CND_NG_BH2
DK_CA_TVIS_DEC_Engine_NG                                     .    DK_CA_TVIS_DEC_Engine_NG_BH2
DK_CA_Vestfrb_DEC_Boiler_NG                                  .    DK_CA_Vestfrb_DEC_Boiler_NG_BH2
DK_CA_Vestfrb_DEC_Engine_NG                                  .    DK_CA_Vestfrb_DEC_Engine_NG_BH2
DK_CA_Vestfrb_DEC_GasTur-NG                                  .    DK_CA_Vestfrb_DEC_GasTur-NG_BH2
DK2_DTU_Boiler_NG                                            .    DK2_DTU_Boiler_NG_BH2
DK2_DTU_GasTur-NG                                            .    DK2_DTU_GasTur-NG_BH2
DK_MA_Hil_Boiler_NG                                          .    DK_MA_Hil_Boiler_NG_BH2
DK_MA_Hil_Engine_NG                                          .    DK_MA_Hil_Engine_NG_BH2
DK_MA_Hil_GasTur-NG                                          .    DK_MA_Hil_GasTur-NG_BH2
DK_MA_Hil_DEC_Boiler_NG                                      .    DK_MA_Hil_DEC_Boiler_NG_BH2
DK_MA_Hil_DEC_Engine_NG                                      .    DK_MA_Hil_DEC_Engine_NG_BH2
DK_MA_Hjoerring_Boiler_NG                                    .    DK_MA_Hjoerring_Boiler_NG_BH2
DK_MA_Hjoerring_Engine_NG                                    .    DK_MA_Hjoerring_Engine_NG_BH2
DK_MA_Hjoerring_GasTur-NG                                    .    DK_MA_Hjoerring_GasTur-NG_BH2
DK_MA_Holst_Boiler_NG                                        .    DK_MA_Holst_Boiler_NG_BH2
DK_MA_Holst_DEC_Boiler_NG                                    .    DK_MA_Holst_DEC_Boiler_NG_BH2
DK_MA_Holst_DEC_Engine_NG                                    .    DK_MA_Holst_DEC_Engine_NG_BH2
DK_MA_Holst_DEC_GasTur-NG                                    .    DK_MA_Holst_DEC_GasTur-NG_BH2
DK_MA_Horsens_Boiler_NG                                      .    DK_MA_Horsens_Boiler_NG_BH2
DK_MA_Horsens_DEC_Boiler_NG                                  .    DK_MA_Horsens_DEC_Boiler_NG_BH2
DK_MA_Horsens_DEC_Engine_NG                                  .    DK_MA_Horsens_DEC_Engine_NG_BH2
DK_MA_NrdOstSj_Boiler_NG                                     .    DK_MA_NrdOstSj_Boiler_NG_BH2
DK_MA_NrdOstSj_Engine_NG                                     .    DK_MA_NrdOstSj_Engine_NG_BH2
DK_MA_NrdOstSj_GasTur-NG                                     .    DK_MA_NrdOstSj_GasTur-NG_BH2
DK_MA_NrdOstSj_DEC_Engine_NG                                 .    DK_MA_NrdOstSj_DEC_Engine_NG_BH2
DK_MA_Silk_Boiler_NG                                         .    DK_MA_Silk_Boiler_NG_BH2
DK_MA_Silk_GasTur-NG                                         .    DK_MA_Silk_GasTur-NG_BH2
DK_MA_Sndborg_Boiler_NG                                      .    DK_MA_Sndborg_Boiler_NG_BH2
DK_MA_Sndborg_DEC_Boiler_NG                                  .    DK_MA_Sndborg_DEC_Boiler_NG_BH2
DK_MA_Sndborg_DEC_Engine_NG                                  .    DK_MA_Sndborg_DEC_Engine_NG_BH2
DK_MA_Viborg_Boiler_NG                                       .    DK_MA_Viborg_Boiler_NG_BH2
DK_MA_Viborg_Engine_NG                                       .    DK_MA_Viborg_Engine_NG_BH2
DK_MA_Viborg_GasTur-NG                                       .    DK_MA_Viborg_GasTur-NG_BH2
DK_MA_Viborg_DEC_Boiler_NG                                   .    DK_MA_Viborg_DEC_Boiler_NG_BH2
DK_MA_Viborg_DEC_Engine_NG                                   .    DK_MA_Viborg_DEC_Engine_NG_BH2
DK_MAM_Aars_Boiler_NG                                        .    DK_MAM_Aars_Boiler_NG_BH2
DK_MAM_Aars_Engine_NG                                        .    DK_MAM_Aars_Engine_NG_BH2
DK_MAM_Aars_DEC_Boiler_NG                                    .    DK_MAM_Aars_DEC_Boiler_NG_BH2
DK_MAM_Aars_DEC_Engine_NG                                    .    DK_MAM_Aars_DEC_Engine_NG_BH2
DK_MAM_Aars_DEC_GasTur-NG                                    .    DK_MAM_Aars_DEC_GasTur-NG_BH2
DK_MAM_Frdhavn_Boiler_NG                                     .    DK_MAM_Frdhavn_Boiler_NG_BH2
DK_MAM_Frdhavn_GasTur-NG                                     .    DK_MAM_Frdhavn_GasTur-NG_BH2
DK_MAM_Frdhavn_DEC_Boiler_NG                                 .    DK_MAM_Frdhavn_DEC_Boiler_NG_BH2
DK_MAM_Frdhavn_DEC_Engine_NG                                 .    DK_MAM_Frdhavn_DEC_Engine_NG_BH2
DK_MAM_Had_Boiler_NG                                         .    DK_MAM_Had_Boiler_NG_BH2
DK_MAM_Had_Engine_NG                                         .    DK_MAM_Had_Engine_NG_BH2
DK_MAM_Had_DEC_Boiler_NG                                     .    DK_MAM_Had_DEC_Boiler_NG_BH2
DK_MAM_Had_DEC_Engine_NG                                     .    DK_MAM_Had_DEC_Engine_NG_BH2
DK_MAM_Hammel_DEC_Boiler_NG                                  .    DK_MAM_Hammel_DEC_Boiler_NG_BH2
DK_MAM_Hammel_DEC_Engine_NG                                  .    DK_MAM_Hammel_DEC_Engine_NG_BH2
DK_MAM_Hobro_Boiler_NG                                       .    DK_MAM_Hobro_Boiler_NG_BH2
DK_MAM_Hobro_Engine_NG                                       .    DK_MAM_Hobro_Engine_NG_BH2
DK_MAM_Hobro_DEC_Boiler_NG                                   .    DK_MAM_Hobro_DEC_Boiler_NG_BH2
DK_MAM_Hobro_DEC_Engine_NG                                   .    DK_MAM_Hobro_DEC_Engine_NG_BH2
DK_MAM_Naestved_Boiler_NG                                    .    DK_MAM_Naestved_Boiler_NG_BH2
DK_MAM_Naestved_Engine_NG                                    .    DK_MAM_Naestved_Engine_NG_BH2
DK_MAM_Naestved_DEC_Boiler_NG                                .    DK_MAM_Naestved_DEC_Boiler_NG_BH2
DK_MAM_Naestved_DEC_Engine_NG                                .    DK_MAM_Naestved_DEC_Engine_NG_BH2
DK_MAM_NrAlslev_Boiler_NG                                    .    DK_MAM_NrAlslev_Boiler_NG_BH2
DK_MAM_Nyborg_Boiler_NG                                      .    DK_MAM_Nyborg_Boiler_NG_BH2
DK_MAM_Nyborg_GasTur-NG                                      .    DK_MAM_Nyborg_GasTur-NG_BH2
DK_MAM_Nyk_Boiler_NG                                         .    DK_MAM_Nyk_Boiler_NG_BH2
DK_MAM_Nyk_DEC_Boiler_NG                                     .    DK_MAM_Nyk_DEC_Boiler_NG_BH2
DK_MAM_Skagen_Boiler_NG                                      .    DK_MAM_Skagen_Boiler_NG_BH2
DK_MAM_Skagen_Engine_NG                                      .    DK_MAM_Skagen_Engine_NG_BH2
DK_MAM_Skagen_GasTur-NG                                      .    DK_MAM_Skagen_GasTur-NG_BH2
DK_MAM_Slagelse_Boiler_NG                                    .    DK_MAM_Slagelse_Boiler_NG_BH2
DK_MAM_Slagelse_DEC_Boiler_NG                                .    DK_MAM_Slagelse_DEC_Boiler_NG_BH2
DK_MAM_Slagelse_DEC_Engine_NG                                .    DK_MAM_Slagelse_DEC_Engine_NG_BH2
DK_MAM_Svend_Boiler_NG                                       .    DK_MAM_Svend_Boiler_NG_BH2
DK_MAM_Svend_Engine_NG                                       .    DK_MAM_Svend_Engine_NG_BH2
DK_MAM_Svend_DEC_Boiler_NG                                   .    DK_MAM_Svend_DEC_Boiler_NG_BH2
DK_MAM_Svend_DEC_Engine_NG                                   .    DK_MAM_Svend_DEC_Engine_NG_BH2
DK_MAM_Thisted_Boiler_NG                                     .    DK_MAM_Thisted_Boiler_NG_BH2
DK_MAM_Thisted_Engine_NG                                     .    DK_MAM_Thisted_Engine_NG_BH2
DK_MAM_Thisted_DEC_Boiler_NG                                 .    DK_MAM_Thisted_DEC_Boiler_NG_BH2
DK_MAM_Thisted_DEC_Engine_NG                                 .    DK_MAM_Thisted_DEC_Engine_NG_BH2
GT_CND_NG_2020                                               .    GT_CND_NG_2020_BH2
GT_CND_NG_2025                                               .    GT_CND_NG_2025_BH2
GT_CND_NG_2030                                               .    GT_CND_NG_2030_BH2
GTCC_EXT_NG_2020                                             .    GTCC_EXT_NG_2020_BH2
GTCC_EXT_NG_2025                                             .    GTCC_EXT_NG_2025_BH2
GTCC_EXT_NG_2030                                             .    GTCC_EXT_NG_2030_BH2
GTCC_BP_NG_2020                                              .    GTCC_BP_NG_2020_BH2
GTCC_BP_NG_2025                                              .    GTCC_BP_NG_2025_BH2
GTCC_BP_NG_2030                                              .    GTCC_BP_NG_2030_BH2
ENG_EXT_NG_2020                                              .    ENG_EXT_NG_2020_BH2
ENG_EXT_NG_2025                                              .    ENG_EXT_NG_2025_BH2
ENG_EXT_NG_2030                                              .    ENG_EXT_NG_2030_BH2
BO_NG_2020                                                   .    BO_NG_2020_BH2
BO_NG_2025                                                   .    BO_NG_2025_BH2
BO_NG_2030                                                   .    BO_NG_2030_BH2
GCND_NATGAS1                                                 .    GCND_NATGAS1_TH2
GCND_NATGAS2                                                 .    GCND_NATGAS2_TH2
GCND_NATGAS3                                                 .    GCND_NATGAS3_TH2
GCND_NATGAS4                                                 .    GCND_NATGAS4_TH2
GEXT_NATGAS_ORESUND                                          .    GEXT_NATGAS_ORESUND_TH2
GEXT_NATGAS_NOKIA                                            .    GEXT_NATGAS_NOKIA_TH2
GEXT_NATGAS_MERTANIEMI                                       .    GEXT_NATGAS_MERTANIEMI_TH2
GEXT_NATGAS_TAMPERE                                          .    GEXT_NATGAS_TAMPERE_TH2
GEXT_NATGAS_VOUSAARI                                         .    GEXT_NATGAS_VOUSAARI_TH2
GEXT_NATGAS_AVEDORE                                          .    GEXT_NATGAS_AVEDORE_TH2
GEXT_NATGAS_SKERBEK                                          .    GEXT_NATGAS_SKERBEK_TH2
GEXT_NATGAS                                                  .    GEXT_NATGAS_TH2
GBPR_NATGAS_RYA                                              .    GBPR_NATGAS_RYA_TH2
GBPR_NATGAS_SE4EL                                            .    GBPR_NATGAS_SE4EL_TH2
GBPR_NATGAS_GOT                                              .    GBPR_NATGAS_GOT_TH2
GBPR_NATGAS_MAL                                              .    GBPR_NATGAS_MAL_TH2
GBPR_NATGAS_40                                               .    GBPR_NATGAS_40_TH2
GBPR_NATGAS_50                                               .    GBPR_NATGAS_50_TH2
GBPR_NATGAS_100                                              .    GBPR_NATGAS_100_TH2
GBPR_NATGAS_VOUSAARI                                         .    GBPR_NATGAS_VOUSAARI_TH2
GBPR_NATGAS_FINEL                                            .    GBPR_NATGAS_FINEL_TH2
GBPR_NATGAS_SUOMENOJA2                                       .    GBPR_NATGAS_SUOMENOJA2_TH2
GBPR_NATGAS_GASAREA                                          .    GBPR_NATGAS_GASAREA_TH2
GBPR_NATGAS_SUOMENOJA                                        .    GBPR_NATGAS_SUOMENOJA_TH2
GBPR_NATGAS_MARTINLAAKSOGT                                   .    GBPR_NATGAS_MARTINLAAKSOGT_TH2
GBPR_NATGAS                                                  .    GBPR_NATGAS_TH2
GHOB_NATGAS                                                  .    GHOB_NATGAS_TH2
GBPR_NATGAS_IND                                              .    GBPR_NATGAS_IND_TH2
GBPR_NATGAS1                                                 .    GBPR_NATGAS1_TH2
GBPR_NATGAS2                                                 .    GBPR_NATGAS2_TH2
GBPR_NATGAS3                                                 .    GBPR_NATGAS3_TH2
GCND_NATGAS1_1                                               .    GCND_NATGAS1_1_TH2
GCND_NATGAS1_2                                               .    GCND_NATGAS1_2_TH2
GCND_NATGAS1_3                                               .    GCND_NATGAS1_3_TH2
GCND_NATGAS2_1                                               .    GCND_NATGAS2_1_TH2
GCND_NATGAS2_2                                               .    GCND_NATGAS2_2_TH2
GCND_NATGAS2_3                                               .    GCND_NATGAS2_3_TH2
GCND_NATGAS3_1                                               .    GCND_NATGAS3_1_TH2
GCND_NATGAS3_2                                               .    GCND_NATGAS3_2_TH2
GCND_NATGAS3_3                                               .    GCND_NATGAS3_3_TH2
GCND_NATGAS4_1                                               .    GCND_NATGAS4_1_TH2
GCND_NATGAS4_2                                               .    GCND_NATGAS4_2_TH2
GCND_NATGAS4_3                                               .    GCND_NATGAS4_3_TH2
ST-BP-Iru-2-OG                                               .    ST-BP-Iru-2-OG_TH2
ST-Ext-Iru-1-OG                                              .    ST-Ext-Iru-1-OG_TH2
DH-Old-G-EE                                                  .    DH-Old-G-EE_TH2
DH-Old-O-EE                                                  .    DH-Old-O-EE_TH2
GEXT_NATGAS_IRU1                                             .    GEXT_NATGAS_IRU1_TH2
GBPR_NATGAS_IRU2                                             .    GBPR_NATGAS_IRU2_TH2
GEXT_NATGAS_EE_SMALL                                         .    GEXT_NATGAS_EE_SMALL_TH2
GE-BP-LV-G                                                   .    GE-BP-LV-G_TH2
Rigas_TEC-1-GT                                               .    Rigas_TEC-1-GT_TH2
Rigas_TEC-1-ST                                               .    Rigas_TEC-1-ST_TH2
Rigas_TEC-2-CC                                               .    Rigas_TEC-2-CC_TH2
ST-BP-IM-G                                                   .    ST-BP-IM-G_TH2
ST-BP-LV-OG                                                  .    ST-BP-LV-OG_TH2
AchemaCHP                                                    .    AchemaCHP_TH2
KaunasCHP                                                    .    KaunasCHP_TH2
LithuanianCCGT                                               .    LithuanianCCGT_TH2
LithuanianPP                                                 .    LithuanianPP_TH2
OrlenCHP                                                     .    OrlenCHP_TH2
PanevezysCHP                                                 .    PanevezysCHP_TH2
VilniusCHP3                                                  .    VilniusCHP3_TH2
ST-Cond-LM-F1-Gfree                                          .    ST-Cond-LM-F1-Gfree_TH2
GBPR_OTHERGAS_IND                                            .    GBPR_OTHERGAS_IND_TH2
GCND-NG                                                      .    GCND-NG_TH2
GBPR-NATGAS                                                  .    GBPR-NATGAS_TH2
SteamTur-CON-NG-10_19                                        .    SteamTur-CON-NG-10_19_TH2
SteamTur-CON-NG-20_50                                        .    SteamTur-CON-NG-20_50_TH2
SteamTur-EXT-NG-10_19                                        .    SteamTur-EXT-NG-10_19_TH2
SteamTur-EXT-NG-20_50                                        .    SteamTur-EXT-NG-20_50_TH2
GasTur-CON-NG-10_19                                          .    GasTur-CON-NG-10_19_TH2
GasTur-CON-NG-20                                             .    GasTur-CON-NG-20_TH2
GasTur-EXT-NG-10_19                                          .    GasTur-EXT-NG-10_19_TH2
GasTur-EXT-NG-20                                             .    GasTur-EXT-NG-20_TH2
GasTurCC-CON-NG-10_19                                        .    GasTurCC-CON-NG-10_19_TH2
GasTurCC-CON-NG-20_29                                        .    GasTurCC-CON-NG-20_29_TH2
GasTurCC-CON-NG-30_49                                        .    GasTurCC-CON-NG-30_49_TH2
GasTurCC-CON-NG-50                                           .    GasTurCC-CON-NG-50_TH2
GasTurCC-EXT-NG-10_19                                        .    GasTurCC-EXT-NG-10_19_TH2
GasTurCC-EXT-NG-20_29                                        .    GasTurCC-EXT-NG-20_29_TH2
GasTurCC-EXT-NG-30_49                                        .    GasTurCC-EXT-NG-30_49_TH2
GasTurCC-EXT-NG-50                                           .    GasTurCC-EXT-NG-50_TH2
GasTurCC-BP-NG-10_19                                         .    GasTurCC-BP-NG-10_19_TH2
GasTurCC-BP-NG-20                                            .    GasTurCC-BP-NG-20_TH2
Engine-NG-10_19                                              .    Engine-NG-10_19_TH2
Engine-NG-20_29                                              .    Engine-NG-20_29_TH2
Engine-NG-30_49                                              .    Engine-NG-30_49_TH2
Engine-NG-50                                                 .    Engine-NG-50_TH2
Boiler-NG                                                    .    Boiler-NG_TH2
HO-B1-NG                                                     .    HO-B1-NG_TH2
HO-IND1-NG                                                   .    HO-IND1-NG_TH2
HCVSMV_ST_B8_NG                                              .    HCVSMV_ST_B8_NG_TH2
CC-B9-NGn                                                    .    CC-B9-NGn_TH2
ST-B8-NG                                                     .    ST-B8-NG_TH2
HO-B8-NG                                                     .    HO-B8-NG_TH2
DE_HO-NG                                                     .    DE_HO-NG_TH2
DE_HO-NG-TempFix                                             .    DE_HO-NG-TempFix_TH2
DE-COND-GAS-0-00                                             .    DE-COND-GAS-0-00_TH2
DE-COND-GAS-101-00                                           .    DE-COND-GAS-101-00_TH2
DE-KWK-GAS-CC-91                                             .    DE-KWK-GAS-CC-91_TH2
DE-KWK-GAS-GT-00                                             .    DE-KWK-GAS-GT-00_TH2
DE-KWK-GAS-IC-00                                             .    DE-KWK-GAS-IC-00_TH2
DE-KWK-GAS-ST-00                                             .    DE-KWK-GAS-ST-00_TH2
DE-COND-GAS-CC-0-91                                          .    DE-COND-GAS-CC-0-91_TH2
DE-KWK-GAS-CC-00                                             .    DE-KWK-GAS-CC-00_TH2
DK_CA_Aab_Boiler_NG                                          .    DK_CA_Aab_Boiler_NG_TH2
DK_CA_Aab_Engine_NG                                          .    DK_CA_Aab_Engine_NG_TH2
DK_CA_Aab_DEC_Boiler_NG                                      .    DK_CA_Aab_DEC_Boiler_NG_TH2
DK_CA_Aab_DEC_Engine_NG                                      .    DK_CA_Aab_DEC_Engine_NG_TH2
DK_CA_Aab_DEC_GasTur-NG                                      .    DK_CA_Aab_DEC_GasTur-NG_TH2
DK_CA_Aal_Boiler_NG                                          .    DK_CA_Aal_Boiler_NG_TH2
DK_CA_Aal_Engine_NG                                          .    DK_CA_Aal_Engine_NG_TH2
DK_CA_Aal_DEC_Boiler_NG                                      .    DK_CA_Aal_DEC_Boiler_NG_TH2
DK_CA_Aal_DEC_Engine_NG                                      .    DK_CA_Aal_DEC_Engine_NG_TH2
DK_CA_Aal_DEC_GasTur-NG                                      .    DK_CA_Aal_DEC_GasTur-NG_TH2
DK_CA_Aarhus_Boiler_NG                                       .    DK_CA_Aarhus_Boiler_NG_TH2
DK_CA_Aarhus_Engine_NG                                       .    DK_CA_Aarhus_Engine_NG_TH2
DK_CA_Aarhus_DEC_Boiler_NG                                   .    DK_CA_Aarhus_DEC_Boiler_NG_TH2
DK_CA_Aarhus_DEC_Engine_NG                                   .    DK_CA_Aarhus_DEC_Engine_NG_TH2
DK_CA_Esb_Boiler_NG                                          .    DK_CA_Esb_Boiler_NG_TH2
DK_CA_Esb_Engine_NG                                          .    DK_CA_Esb_Engine_NG_TH2
DK_CA_Esb_DEC_Boiler_NG                                      .    DK_CA_Esb_DEC_Boiler_NG_TH2
DK_CA_Esb_DEC_Engine_NG                                      .    DK_CA_Esb_DEC_Engine_NG_TH2
DK_CA_Esb_DEC_GasTur-NG                                      .    DK_CA_Esb_DEC_GasTur-NG_TH2
DK_CA_Hern_Boiler_NG                                         .    DK_CA_Hern_Boiler_NG_TH2
DK_CA_Hern_Engine_NG                                         .    DK_CA_Hern_Engine_NG_TH2
DK_CA_Hern_DEC_Boiler_NG                                     .    DK_CA_Hern_DEC_Boiler_NG_TH2
DK_CA_Hern_DEC_Engine_NG                                     .    DK_CA_Hern_DEC_Engine_NG_TH2
DK_CA_Hern_DEC_GasTur-NG                                     .    DK_CA_Hern_DEC_GasTur-NG_TH2
DK_CA_Kal_Boiler_NG                                          .    DK_CA_Kal_Boiler_NG_TH2
DK_CA_Kal_Engine_NG                                          .    DK_CA_Kal_Engine_NG_TH2
DK_CA_Kal_GasTur_CND_NG                                      .    DK_CA_Kal_GasTur_CND_NG_TH2
DK_CA_Kal_DEC_Boiler_NG                                      .    DK_CA_Kal_DEC_Boiler_NG_TH2
DK_CA_Kal_DEC_Engine_NG                                      .    DK_CA_Kal_DEC_Engine_NG_TH2
DK_CA_KBH_Boiler_NG                                          .    DK_CA_KBH_Boiler_NG_TH2
DK_CA_KBH_Engine_NG                                          .    DK_CA_KBH_Engine_NG_TH2
DK_CA_KBH_GasTur-NG                                          .    DK_CA_KBH_GasTur-NG_TH2
DK_CA_KBH_DEC_Boiler_NG                                      .    DK_CA_KBH_DEC_Boiler_NG_TH2
DK_CA_KBH_DEC_Engine_NG                                      .    DK_CA_KBH_DEC_Engine_NG_TH2
DK_CA_KBH_DEC_GasTur-NG                                      .    DK_CA_KBH_DEC_GasTur-NG_TH2
DK_CA_Odense_Boiler_NG                                       .    DK_CA_Odense_Boiler_NG_TH2
DK_CA_Odense_Engine_NG                                       .    DK_CA_Odense_Engine_NG_TH2
DK_CA_Odense_DEC_Boiler_NG                                   .    DK_CA_Odense_DEC_Boiler_NG_TH2
DK_CA_Odense_DEC_Engine_NG                                   .    DK_CA_Odense_DEC_Engine_NG_TH2
DK_CA_Odense_DEC_GasTur-NG                                   .    DK_CA_Odense_DEC_GasTur-NG_TH2
DK_CA_Randers_Boiler_NG                                      .    DK_CA_Randers_Boiler_NG_TH2
DK_CA_Randers_Engine_NG                                      .    DK_CA_Randers_Engine_NG_TH2
DK_CA_Randers_DEC_Boiler_NG                                  .    DK_CA_Randers_DEC_Boiler_NG_TH2
DK_CA_Randers_DEC_Engine_NG                                  .    DK_CA_Randers_DEC_Engine_NG_TH2
DK_CA_Randers_DEC_GasTur-NG                                  .    DK_CA_Randers_DEC_GasTur-NG_TH2
DK_CA_Roenne_DEC_Boiler_NG                                   .    DK_CA_Roenne_DEC_Boiler_NG_TH2
DK_CA_TVIS_Boiler_NG                                         .    DK_CA_TVIS_Boiler_NG_TH2
DK_CA_TVIS_GasTurCC-NG                                       .    DK_CA_TVIS_GasTurCC-NG_TH2
DK_CA_TVIS_GasTur-NG                                         .    DK_CA_TVIS_GasTur-NG_TH2
DK_CA_TVIS_DEC_Boiler_NG                                     .    DK_CA_TVIS_DEC_Boiler_NG_TH2
DK_CA_TVIS_DEC_Engine_CND_NG                                 .    DK_CA_TVIS_DEC_Engine_CND_NG_TH2
DK_CA_TVIS_DEC_Engine_NG                                     .    DK_CA_TVIS_DEC_Engine_NG_TH2
DK_CA_Vestfrb_DEC_Boiler_NG                                  .    DK_CA_Vestfrb_DEC_Boiler_NG_TH2
DK_CA_Vestfrb_DEC_Engine_NG                                  .    DK_CA_Vestfrb_DEC_Engine_NG_TH2
DK_CA_Vestfrb_DEC_GasTur-NG                                  .    DK_CA_Vestfrb_DEC_GasTur-NG_TH2
DK2_DTU_Boiler_NG                                            .    DK2_DTU_Boiler_NG_TH2
DK2_DTU_GasTur-NG                                            .    DK2_DTU_GasTur-NG_TH2
DK_MA_Hil_Boiler_NG                                          .    DK_MA_Hil_Boiler_NG_TH2
DK_MA_Hil_Engine_NG                                          .    DK_MA_Hil_Engine_NG_TH2
DK_MA_Hil_GasTur-NG                                          .    DK_MA_Hil_GasTur-NG_TH2
DK_MA_Hil_DEC_Boiler_NG                                      .    DK_MA_Hil_DEC_Boiler_NG_TH2
DK_MA_Hil_DEC_Engine_NG                                      .    DK_MA_Hil_DEC_Engine_NG_TH2
DK_MA_Hjoerring_Boiler_NG                                    .    DK_MA_Hjoerring_Boiler_NG_TH2
DK_MA_Hjoerring_Engine_NG                                    .    DK_MA_Hjoerring_Engine_NG_TH2
DK_MA_Hjoerring_GasTur-NG                                    .    DK_MA_Hjoerring_GasTur-NG_TH2
DK_MA_Holst_Boiler_NG                                        .    DK_MA_Holst_Boiler_NG_TH2
DK_MA_Holst_DEC_Boiler_NG                                    .    DK_MA_Holst_DEC_Boiler_NG_TH2
DK_MA_Holst_DEC_Engine_NG                                    .    DK_MA_Holst_DEC_Engine_NG_TH2
DK_MA_Holst_DEC_GasTur-NG                                    .    DK_MA_Holst_DEC_GasTur-NG_TH2
DK_MA_Horsens_Boiler_NG                                      .    DK_MA_Horsens_Boiler_NG_TH2
DK_MA_Horsens_DEC_Boiler_NG                                  .    DK_MA_Horsens_DEC_Boiler_NG_TH2
DK_MA_Horsens_DEC_Engine_NG                                  .    DK_MA_Horsens_DEC_Engine_NG_TH2
DK_MA_NrdOstSj_Boiler_NG                                     .    DK_MA_NrdOstSj_Boiler_NG_TH2
DK_MA_NrdOstSj_Engine_NG                                     .    DK_MA_NrdOstSj_Engine_NG_TH2
DK_MA_NrdOstSj_GasTur-NG                                     .    DK_MA_NrdOstSj_GasTur-NG_TH2
DK_MA_NrdOstSj_DEC_Engine_NG                                 .    DK_MA_NrdOstSj_DEC_Engine_NG_TH2
DK_MA_Silk_Boiler_NG                                         .    DK_MA_Silk_Boiler_NG_TH2
DK_MA_Silk_GasTur-NG                                         .    DK_MA_Silk_GasTur-NG_TH2
DK_MA_Sndborg_Boiler_NG                                      .    DK_MA_Sndborg_Boiler_NG_TH2
DK_MA_Sndborg_DEC_Boiler_NG                                  .    DK_MA_Sndborg_DEC_Boiler_NG_TH2
DK_MA_Sndborg_DEC_Engine_NG                                  .    DK_MA_Sndborg_DEC_Engine_NG_TH2
DK_MA_Viborg_Boiler_NG                                       .    DK_MA_Viborg_Boiler_NG_TH2
DK_MA_Viborg_Engine_NG                                       .    DK_MA_Viborg_Engine_NG_TH2
DK_MA_Viborg_GasTur-NG                                       .    DK_MA_Viborg_GasTur-NG_TH2
DK_MA_Viborg_DEC_Boiler_NG                                   .    DK_MA_Viborg_DEC_Boiler_NG_TH2
DK_MA_Viborg_DEC_Engine_NG                                   .    DK_MA_Viborg_DEC_Engine_NG_TH2
DK_MAM_Aars_Boiler_NG                                        .    DK_MAM_Aars_Boiler_NG_TH2
DK_MAM_Aars_Engine_NG                                        .    DK_MAM_Aars_Engine_NG_TH2
DK_MAM_Aars_DEC_Boiler_NG                                    .    DK_MAM_Aars_DEC_Boiler_NG_TH2
DK_MAM_Aars_DEC_Engine_NG                                    .    DK_MAM_Aars_DEC_Engine_NG_TH2
DK_MAM_Aars_DEC_GasTur-NG                                    .    DK_MAM_Aars_DEC_GasTur-NG_TH2
DK_MAM_Frdhavn_Boiler_NG                                     .    DK_MAM_Frdhavn_Boiler_NG_TH2
DK_MAM_Frdhavn_GasTur-NG                                     .    DK_MAM_Frdhavn_GasTur-NG_TH2
DK_MAM_Frdhavn_DEC_Boiler_NG                                 .    DK_MAM_Frdhavn_DEC_Boiler_NG_TH2
DK_MAM_Frdhavn_DEC_Engine_NG                                 .    DK_MAM_Frdhavn_DEC_Engine_NG_TH2
DK_MAM_Had_Boiler_NG                                         .    DK_MAM_Had_Boiler_NG_TH2
DK_MAM_Had_Engine_NG                                         .    DK_MAM_Had_Engine_NG_TH2
DK_MAM_Had_DEC_Boiler_NG                                     .    DK_MAM_Had_DEC_Boiler_NG_TH2
DK_MAM_Had_DEC_Engine_NG                                     .    DK_MAM_Had_DEC_Engine_NG_TH2
DK_MAM_Hammel_DEC_Boiler_NG                                  .    DK_MAM_Hammel_DEC_Boiler_NG_TH2
DK_MAM_Hammel_DEC_Engine_NG                                  .    DK_MAM_Hammel_DEC_Engine_NG_TH2
DK_MAM_Hobro_Boiler_NG                                       .    DK_MAM_Hobro_Boiler_NG_TH2
DK_MAM_Hobro_Engine_NG                                       .    DK_MAM_Hobro_Engine_NG_TH2
DK_MAM_Hobro_DEC_Boiler_NG                                   .    DK_MAM_Hobro_DEC_Boiler_NG_TH2
DK_MAM_Hobro_DEC_Engine_NG                                   .    DK_MAM_Hobro_DEC_Engine_NG_TH2
DK_MAM_Naestved_Boiler_NG                                    .    DK_MAM_Naestved_Boiler_NG_TH2
DK_MAM_Naestved_Engine_NG                                    .    DK_MAM_Naestved_Engine_NG_TH2
DK_MAM_Naestved_DEC_Boiler_NG                                .    DK_MAM_Naestved_DEC_Boiler_NG_TH2
DK_MAM_Naestved_DEC_Engine_NG                                .    DK_MAM_Naestved_DEC_Engine_NG_TH2
DK_MAM_NrAlslev_Boiler_NG                                    .    DK_MAM_NrAlslev_Boiler_NG_TH2
DK_MAM_Nyborg_Boiler_NG                                      .    DK_MAM_Nyborg_Boiler_NG_TH2
DK_MAM_Nyborg_GasTur-NG                                      .    DK_MAM_Nyborg_GasTur-NG_TH2
DK_MAM_Nyk_Boiler_NG                                         .    DK_MAM_Nyk_Boiler_NG_TH2
DK_MAM_Nyk_DEC_Boiler_NG                                     .    DK_MAM_Nyk_DEC_Boiler_NG_TH2
DK_MAM_Skagen_Boiler_NG                                      .    DK_MAM_Skagen_Boiler_NG_TH2
DK_MAM_Skagen_Engine_NG                                      .    DK_MAM_Skagen_Engine_NG_TH2
DK_MAM_Skagen_GasTur-NG                                      .    DK_MAM_Skagen_GasTur-NG_TH2
DK_MAM_Slagelse_Boiler_NG                                    .    DK_MAM_Slagelse_Boiler_NG_TH2
DK_MAM_Slagelse_DEC_Boiler_NG                                .    DK_MAM_Slagelse_DEC_Boiler_NG_TH2
DK_MAM_Slagelse_DEC_Engine_NG                                .    DK_MAM_Slagelse_DEC_Engine_NG_TH2
DK_MAM_Svend_Boiler_NG                                       .    DK_MAM_Svend_Boiler_NG_TH2
DK_MAM_Svend_Engine_NG                                       .    DK_MAM_Svend_Engine_NG_TH2
DK_MAM_Svend_DEC_Boiler_NG                                   .    DK_MAM_Svend_DEC_Boiler_NG_TH2
DK_MAM_Svend_DEC_Engine_NG                                   .    DK_MAM_Svend_DEC_Engine_NG_TH2
DK_MAM_Thisted_Boiler_NG                                     .    DK_MAM_Thisted_Boiler_NG_TH2
DK_MAM_Thisted_Engine_NG                                     .    DK_MAM_Thisted_Engine_NG_TH2
DK_MAM_Thisted_DEC_Boiler_NG                                 .    DK_MAM_Thisted_DEC_Boiler_NG_TH2
DK_MAM_Thisted_DEC_Engine_NG                                 .    DK_MAM_Thisted_DEC_Engine_NG_TH2
GT_CND_NG_2020                                               .    GT_CND_NG_2020_TH2
GT_CND_NG_2025                                               .    GT_CND_NG_2025_TH2
GT_CND_NG_2030                                               .    GT_CND_NG_2030_TH2
GTCC_EXT_NG_2020                                             .    GTCC_EXT_NG_2020_TH2
GTCC_EXT_NG_2025                                             .    GTCC_EXT_NG_2025_TH2
GTCC_EXT_NG_2030                                             .    GTCC_EXT_NG_2030_TH2
GTCC_BP_NG_2020                                              .    GTCC_BP_NG_2020_TH2
GTCC_BP_NG_2025                                              .    GTCC_BP_NG_2025_TH2
GTCC_BP_NG_2030                                              .    GTCC_BP_NG_2030_TH2
ENG_EXT_NG_2020                                              .    ENG_EXT_NG_2020_TH2
ENG_EXT_NG_2025                                              .    ENG_EXT_NG_2025_TH2
ENG_EXT_NG_2030                                              .    ENG_EXT_NG_2030_TH2
BO_NG_2020                                                   .    BO_NG_2020_TH2
BO_NG_2025                                                   .    BO_NG_2025_TH2
BO_NG_2030                                                   .    BO_NG_2030_TH2
/;






















































































































































































































































































































































































































































































