* DATACENTERS G(GGG) ADDITIONS                         
                                                       
SET G(GGG)  'Generation technologies in the simulation'
/                                                      
G_DC_ABS_CHILLER                                       
G_DC_ELE_CHILLER                                       
G_DC_COOL_STORAGE                                      
G_DC_HEATPUMP                                          
/;                                                     
