* DATACENTERS XHKFX(YYY,IAAAE,IAAAI) ADDITIONS                                            
                                                                                          
PARAMETER XHKFX(YYY,IAAAE,IAAAI) 'Initial heat transmission capacicty between areas (MW)';
*Unlimited, one-way flow from DC-generation to DC-storage areas                           
XHKFX(Y,IAAAE,IAAAI)$DC_AMAP(IAAAE,IAAAI) = 1000000;                                      
                                                                                          
                                                                                          
                                                                                          
                                                                                          
