* DATACENTERS XHLOSS(IAAAE,IAAAI) ADDITIONS                                                                           
                                                                                                                      
PARAMETER XHLOSS(IAAAE,IAAAI)  'Heat transmission loss between areas (calculated from exported quantity) (share)';    
                                                                                                                      
XHLOSS('DK1_Large-DC_G','DK1_Large-DC_S') = 0;                                                                        
XHLOSS('DK2_Large-DC_G','DK2_Large-DC_S') = 0;                                                                        
XHLOSS('DK1_Medium-DC_G','DK1_Medium-DC_S') = 0;                                                                      
XHLOSS('DK2_Medium-DC_G','DK2_Medium-DC_S') = 0;                                                                      
XHLOSS('DK1_MedSmall-DC_G','DK1_MedSmall-DC_S') = 0;                                                                  
XHLOSS('DK2_MedSmall-DC_G','DK2_MedSmall-DC_S') = 0;                                                                  
                                                                                                                      
                                                                                                                      
XHLOSS('DK1_Large','DK1_Large-DC_G') = 0.1;                                                                           
XHLOSS('DK1_Large-DC_G','DK1_Large') = 0.1;                                                                           
XHLOSS('DK2_Large','DK2_Large-DC_G') = 0.1;                                                                           
XHLOSS('DK2_Large-DC_G','DK2_Large') = 0.1;                                                                           
XHLOSS('DK1_Medium','DK1_Medium-DC_G') = 0.1;                                                                         
XHLOSS('DK1_Medium-DC_G','DK1_Medium') = 0.1;                                                                         
XHLOSS('DK2_Medium','DK2_Medium-DC_G') = 0.1;                                                                         
XHLOSS('DK2_Medium-DC_G','DK2_Medium') = 0.1;                                                                         
XHLOSS('DK1_MedSmall','DK1_MedSmall-DC_G') = 0.1;                                                                     
XHLOSS('DK1_MedSmall-DC_G','DK1_MedSmall') = 0.1;                                                                     
XHLOSS('DK2_MedSmall','DK2_MedSmall-DC_G') = 0.1;                                                                     
XHLOSS('DK2_MedSmall-DC_G','DK2_MedSmall') = 0.1;                                                                     
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
