SET CCCRRRAAA 'All geographical entities (CCC + RRR + AAA)'
/                                                          
*Areas                                                     
DK1_Large-DC_G                                             
DK1_Large-DC_S                                             
DK2_Large-DC_G                                             
DK2_Large-DC_S                                             
DK1_Medium-DC_G                                            
DK1_Medium-DC_S                                            
DK2_Medium-DC_G                                            
DK2_Medium-DC_S                                            
DK1_MedSmall-DC_G                                          
DK1_MedSmall-DC_S                                          
DK2_MedSmall-DC_G                                          
DK2_MedSmall-DC_S                                          
/;                                                         
                                                           
