* DATACENTERS AREA SETS ADDITIONS                                                             
* Explanation in 'base/addons/datacenters/bb4/datacenters_setdeclare.inc'                     
                                                                                              
SET DC_AG(AAA)                                                                                
/                                                                                             
DK1_Large-DC_G                                                                                
DK2_Large-DC_G                                                                                
DK1_Medium-DC_G                                                                               
/;                                                                                            
                                                                                              
SET DC_AS(AAA)                                                                                
/                                                                                             
DK1_Large-DC_S                                                                                
DK2_Large-DC_S                                                                                
DK1_Medium-DC_S                                                                               
/;                                                                                            
                                                                                              
SET DC_AMAP(AAA,AAA)                                                                          
/                                                                                             
DK1_Large-DC_G                                                            .    DK1_Large-DC_S 
DK2_Large-DC_G                                                            .    DK2_Large-DC_S 
DK1_Medium-DC_G                                                           .    DK1_Medium-DC_S
/;                                                                                            
