* DATACENTERS AGKN(AAA,GGG) ADDITIONS               
                                                    
AGKN('DK1_Large-DC_G','G_DC_ABS_CHILLER')     = YES;
AGKN('DK1_Large-DC_G','G_DC_ELE_CHILLER')     = YES;
AGKN('DK1_Large-DC_S','G_DC_COOL_STORAGE')    = YES;
AGKN('DK1_Large-DC_G','G_DC_HEATPUMP')        = YES;
                                                    
AGKN('DK2_Large-DC_G','G_DC_ABS_CHILLER')     = YES;
AGKN('DK2_Large-DC_G','G_DC_ELE_CHILLER')     = YES;
AGKN('DK2_Large-DC_S','G_DC_COOL_STORAGE')    = YES;
AGKN('DK2_Large-DC_G','G_DC_HEATPUMP')        = YES;
                                                    
AGKN('DK1_Medium-DC_G','G_DC_ABS_CHILLER')    = YES;
AGKN('DK1_Medium-DC_G','G_DC_ELE_CHILLER')    = YES;
AGKN('DK1_Medium-DC_S','G_DC_COOL_STORAGE')   = YES;
AGKN('DK1_Medium-DC_G','G_DC_HEATPUMP')       = YES;
                                                    
AGKN('DK2_Medium-DC_G','G_DC_ABS_CHILLER')    = YES;
AGKN('DK2_Medium-DC_G','G_DC_ELE_CHILLER')    = YES;
AGKN('DK2_Medium-DC_S','G_DC_COOL_STORAGE')   = YES;
AGKN('DK2_Medium-DC_G','G_DC_HEATPUMP')       = YES;
                                                    
AGKN('DK1_MedSmall-DC_G','G_DC_ABS_CHILLER')  = YES;
AGKN('DK1_MedSmall-DC_G','G_DC_ELE_CHILLER')  = YES;
AGKN('DK1_MedSmall-DC_S','G_DC_COOL_STORAGE') = YES;
AGKN('DK1_MedSmall-DC_G','G_DC_HEATPUMP')     = YES;
                                                    
AGKN('DK2_MedSmall-DC_G','G_DC_ABS_CHILLER')  = YES;
AGKN('DK2_MedSmall-DC_G','G_DC_ELE_CHILLER')  = YES;
AGKN('DK2_MedSmall-DC_S','G_DC_COOL_STORAGE') = YES;
AGKN('DK2_MedSmall-DC_G','G_DC_HEATPUMP')     = YES;
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
