SET RRRAAA(RRR,AAA) 'Areas in regions'                                                    
/                                                                                         
DK1                                                                 .    DK1_Large-DC_G   
DK1                                                                 .    DK1_Large-DC_S   
DK2                                                                 .    DK2_Large-DC_G   
DK2                                                                 .    DK2_Large-DC_S   
DK1                                                                 .    DK1_Medium-DC_G  
DK1                                                                 .    DK1_Medium-DC_S  
DK2                                                                 .    DK2_Medium-DC_G  
DK2                                                                 .    DK2_Medium-DC_S  
DK1                                                                 .    DK1_MedSmall-DC_G
DK1                                                                 .    DK1_MedSmall-DC_S
DK2                                                                 .    DK2_MedSmall-DC_G
DK2                                                                 .    DK2_MedSmall-DC_S
                                                                                          
/;                                                                                        
                                                                                          
