* DATACENTERS G(GGG) ADDITIONS                         
                                                       
SET G(GGG)  'Generation technologies in the simulation'
/                                                      
G_DC_ABSCHILLER                                        
G_DC_ELCHILLER                                         
G_DC_HEATPUMP                                          
G_DC_FREECOOLING                                       
G_DC_COLDSTORAGE                                       
/;                                                     
