* DATACENTERS DUSER_DC()                    
                                            
SET DUSER_DC    'Datacenter DC user groups' 
                                            
/                                           
DATACENTER_LARGE                            
DATACENTER_MEDIUM                           
/;                                          
                                            
