* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$8:$A$14
* -----------------------------------------------------
SET DEF  'Steps in elastic electricity demand'                                   
/                                                                                
DEF_D1_9,DEF_D1_8,DEF_D1_7,DEF_D1_6,DEF_D1_5,DEF_D1_4,DEF_D1_3,DEF_D1_2,DEF_D1_1,
DEF_U1_1,DEF_U1_2,DEF_U1_3,DEF_U1_4,DEF_U1_5,DEF_U1_6,DEF_U1_7,DEF_U1_8,DEF_U1_9,
DEF_D2_9,DEF_D2_8,DEF_D2_7,DEF_D2_6,DEF_D2_5,DEF_D2_4,DEF_D2_3,DEF_D2_2,DEF_D2_1,
DEF_U2_1,DEF_U2_2,DEF_U2_3,DEF_U2_4,DEF_U2_5,DEF_U2_6,DEF_U2_7,DEF_U2_8,DEF_U2_9 
/;                                                                               
* -----------------------------------------------------
