* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$21:$A$24
* -----------------------------------------------------
SET DEF_U1(DEF) 'Upwards steps in elastic el. demand, relative data format'
/                                                                          
* Empty, i.e. no elasticity in demand from DEF_U1                          
/;                                                                         
* -----------------------------------------------------
