* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$36:$A$40
* -----------------------------------------------------
SET DEF_D3(DEF) 'Downwards steps in elastic el. demand, absolute Money and fraction of nominal demand data format'
/                                                                                                                 
*Commerce, Industry, Residential, Agriculture,  PublicServ,  ProcessingInd                                        
*  DEF_D3_3,DEF_D3_2,DEF_D3_1                                                                                     
/;                                                                                                                
* -----------------------------------------------------
