* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$42:$A$46
* -----------------------------------------------------
SET DEF_U3(DEF) 'Upwards steps in elastic el. demand, absolute Money and fraction of nominal demand data format'
/                                                                                                               
* Commerce_U3, Industry_U3, Residential_U3, Agriculture_U3,  PublicServ_U3,  ProcessingInd_U3                   
* DEF_D3_3,DEF_D3_2,DEF_D3_1                                                                                    
/;                                                                                                              
* -----------------------------------------------------
