* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       21(Sheet28)
* Range:       $A$46:$H$67
* -----------------------------------------------------
TABLE DEFP_CALIB(RRR,SSS,TTT)  'Calibrate the price side of electricity demand (EUR90/MWh) in order to get demand consistent for a base year.'                                       
                                                                                                                                               S01.T001 S01.T002 S02.T001 S02.T002   
DK1                                                                                                                                            0        0        0        0          
DK2                                                                                                                                            0        0        0        0          
FIN                                                                                                                                            0        0        0        0          
GER                                                                                                                                            0        0        0        0          
NE                                                                                                                                             0        0        0        0          
NO1                                                                                                                                            0        0        0        0          
NO2                                                                                                                                            0        0        0        0          
NO3                                                                                                                                            0        0        0        0          
NO4                                                                                                                                            0        0        0        0          
NO5                                                                                                                                            0        0        0        0          
SE1                                                                                                                                            0        0        0        0          
SE2                                                                                                                                            0        0        0        0          
SE3                                                                                                                                            0        0        0        0          
SE4                                                                                                                                            0        0        0        0          
UK                                                                                                                                             0        0        0        0          
EE                                                                                                                                             0        0        0        0          
LV                                                                                                                                             0        0        0        0          
LT                                                                                                                                             0        0        0        0          
PL                                                                                                                                             0        0        0        0          
;                                                                                                                                                                                    
* -----------------------------------------------------
