TABLE DEFP_CALIB(RRR,SSS,TTT)  'Calibrate the price side of electricity demand (EUR90/MWh) in order to get demand consistent for a base year.'                                       
                                                                                                                                               S01.T001 S01.T002 S02.T001 S02.T002   
DK1                                                                                                                                            0        0        0        0          
DK2                                                                                                                                            0        0        0        0          
FIN                                                                                                                                            0        0        0        0          
GER                                                                                                                                            0        0        0        0          
NE                                                                                                                                             0        0        0        0          
NO1                                                                                                                                            0        0        0        0          
NO2                                                                                                                                            0        0        0        0          
NO3                                                                                                                                            0        0        0        0          
NO4                                                                                                                                            0        0        0        0          
NO5                                                                                                                                            0        0        0        0          
SE1                                                                                                                                            0        0        0        0          
SE2                                                                                                                                            0        0        0        0          
SE3                                                                                                                                            0        0        0        0          
SE4                                                                                                                                            0        0        0        0          
UK                                                                                                                                             0        0        0        0          
EE                                                                                                                                             0        0        0        0          
LV                                                                                                                                             0        0        0        0          
LT                                                                                                                                             0        0        0        0          
PL                                                                                                                                             0        0        0        0          
;                                                                                                                                                                                    
