PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (including taxes) in the base year (Money/MWh)'         
/                                                                                                                                    
HSTAN_R1                                                                                                                          40      
WINDIA_R1                                                                                                                         40      
/;                                                                                                                                   
