PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (including taxes) in the base year (Money/MWh)'         
/                                                                                                                                    
DK1                                                                                                                          40      
DK2                                                                                                                          40      
NO1                                                                                                                          40      
NO2                                                                                                                          40      
NO3                                                                                                                          40      
NO4                                                                                                                          40      
NO5                                                                                                                          40      
/;                                                                                                                                   
