* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       32(Sheet45)
* Range:       $A$5:$F$26
* -----------------------------------------------------
PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (including taxes) in the base year (Money/MWh)'         
/                                                                                                                                    
DK1                                                                                                                          40      
DK2                                                                                                                          40      
FIN                                                                                                                          40      
GER                                                                                                                          50.2    
NE                                                                                                                           50.2    
NO1                                                                                                                          40      
NO2                                                                                                                          40      
NO3                                                                                                                          40      
NO4                                                                                                                          40      
NO5                                                                                                                          40      
SE1                                                                                                                          40      
SE2                                                                                                                          40      
SE3                                                                                                                          40      
SE4                                                                                                                          40      
UK                                                                                                                           40      
EE                                                                                                                           40      
LV                                                                                                                           40      
LT                                                                                                                           40      
PL                                                                                                                           40      
/;                                                                                                                                   
* -----------------------------------------------------
