* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$1:$A$5
* -----------------------------------------------------
SET DF_QP  'Quantity and price information for elastic demands'
/                                                              
DF_QUANT                                                       
DF_PRICE                                                       
/;                                                             
* -----------------------------------------------------
