* File dh.inc
* Not updated for Baltic countries
* This file is part of the Balmorel model, version XX

*------------------------------------------------------------------------------

* PARAMETER DH contains the BRUTTO nominal annual heat consumption.
* (If demand is elastic, there may be deviation from this nominal value).

TABLE DH(YYY,AAA,DHUSER)  'Annual brutto heat consumption'
                                RESH
2020    .       HSTAN_A2        5000
2030    .       HSTAN_A2        5000
2040    .       HSTAN_A2        5000
2050    .       HSTAN_A2        5000
2020    .       WINDIA_A2       30000
2030    .       WINDIA_A2       30000
2040    .       WINDIA_A2       30000
2050    .       WINDIA_A2       30000

;
































































































