* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$61:$A$64
* -----------------------------------------------------
SET DHF_U1(DHF)  'Downwards steps in elastic heat demand, relative data format'
/                                                                              
* Empty, i.e. no elasticity in demand from DHF_U1                              
/;                                                                             
* -----------------------------------------------------
