* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       11(Sheet13)
* Range:       $A$71:$A$74
* -----------------------------------------------------
SET DHF_U2(DHF)  'Upwards steps in elastic heat demand'
/                                                      
* Empty, i.e. no elasticity in demand from DHF_u2      
/;                                                     
* -----------------------------------------------------
