PARAMETER DHFP_BASE(AAA)  'Nominal annual average consumer heat price (including taxes) in the base year (Money/MWh)'                                                                                                                 
/                                                                                                                                                                                                                                     
HSTAN_A1    12 
WINDIA_A1	12      
/;                                                                                                                                                                                                                                    
