                                                                                                                                      
SET DHUSER  "Electricity demand user groups. Set must include element RESE for holding demand not included in any other user group"   
/                                                                                                                                     
RESH                                                                                                                                  
                                                                                                                                      
                                                                                                                                      
                                                                                                                                      
                                                                                                                                      
/;                                                                                                                                    
                                                                                                                                      
                                                                                                                                      
                                                                                                                                      
