SET DHUSER "Heat demand user groups. Set must include element RESH for holding demand not included in any other user group"
/                                                                                                                          
RESH        'district heat'                                                                                                
                                                                                                                           
SPACEHEAT   'individual space heat'                                                                                        
HOTWATER    'individual hot water'                                                                                         
                                                                                                                           
                                                                                                                           
/;                                                                                                                         
