SET DHUSER        "Heat demand user groups. Set must include element RESH for holding demand not included in any other user group"         
/                                                                                                                                          
RESH        /*   District heating connected residential and tertiary sector users                                                  */      
IND-PHL     /*   Industrial users, process heat low temperature  (<100C)                                                           */      
IND-SH      /*   Industrial users, spaceheating  (<100C)                                                                           */      
IND-PHM     /*   Industrial users, process heat medium temperature                                                                 */      
IND-PHH     /*   Industrial users, process heat high temperature (>100C)                                                           */      
RESIDENTIAL /*   Non connected to District heating  residential users                                                              */      
TERTIARY    /*   Non connected to District heating  tertiary sector users                                                          */      
/;                                                                                                                                         
                                                                                                                                           
                                                                                                                                           
                                                                                                                                           
