PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'     
* Areas merged, average values used                                   
/                                                                     
DK1_Large                                                         2   
DK1_Rural                                                         2   
DK1_Medium                                                        2   
DK2_Large                                                         2   
DK2_Rural                                                         2   
DK2_Medium                                                        2   
DK2_MedSmall                                                      2   
DK1_Small                                                         2   
DK1_MedSmall                                                      2   
DK2_Small                                                         2   
DK2_NoDH                                                          2   
DK1_NoDH                                                          2   
DK2_Offshore                                                      2   
DK1_Offshore                                                      2   
FinA                                                              2   
GerA                                                              2   
NeA                                                               2   
UKA                                                               2   
EE_A                                                              2   
EE_NARVA                                                          2   
EE_TALLINN                                                        2   
EE_TARTU                                                          2   
EE_Parnu                                                          2   
EE_Kohtla_Jarve                                                   2   
EE_Industry                                                       2   
EE_SMALL                                                          2   
LV_A1                                                             2   
LV_A2                                                             2   
LV_A3                                                             2   
LT_A                                                              2   
PL_A                                                              2   
GER_OFFSHORE                                                      2   
NE_OFFSHORE                                                       2   
SE1A                                                              2   
SE2A                                                              2   
SE3A                                                              2   
SE4A                                                              2   
                                                                      
                                                                      
                                                                      
                                                                      
                                                                      
/;                                                                    
