PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'     
* Areas merged, average values used                                   
/                                                                     
DK1_Large                                                         2   
DK1_Rural                                                         2   
DK1_Medium                                                        2   
DK2_Large                                                         2   
DK2_Rural                                                         2   
DK2_Medium                                                        2   
DK2_MedSmall                                                      2   
DK1_Small                                                         2   
DK1_MedSmall                                                      2   
DK2_Small                                                         2   
DK2_NoDH                                                          2   
DK1_NoDH                                                          2   
DK2_Offshore                                                      2   
DK1_Offshore                                                      2   
/;                                                                    
