* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       24(Sheet31)
* Range:       $A$1:$B$22
* -----------------------------------------------------
PARAMETER DISCOST_E(RRR)  'Cost of electricity distribution (Money/MWh)'     
/                                                                            
DK1                                                                      5   
DK2                                                                      5   
FIN                                                                      5   
GER                                                                      5   
NE                                                                       5   
NO1                                                                      5   
NO2                                                                      5   
NO3                                                                      5   
NO4                                                                      5   
NO5                                                                      5   
SE1                                                                      5   
SE2                                                                      5   
SE3                                                                      5   
SE4                                                                      5   
UK                                                                       5   
EE                                                                       5   
LV                                                                       5   
LT                                                                       5   
PL                                                                       5   
/;                                                                           
* -----------------------------------------------------
