PARAMETER DISCOST_E(RRR)  'Cost of electricity distribution (Money/MWh)'     
/                                                                            
DK1                                                                      5   
DK2                                                                      5   
NO1                                                                      5   
NO2                                                                      5   
NO3                                                                      5   
NO4                                                                      5   
NO5                                                                      5   
/;                                                                           
