* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       21(Sheet28)
* Range:       $A$3:$B$4
* -----------------------------------------------------
*Source;http://research.stlouisfed.org/fred2/series/INTDSRCNM193N                         
SCALAR    DISCOUNTRATE                 'Discount rate by country (fraction)' / 0.0325  /; 
* -----------------------------------------------------
