* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       24(Sheet31)
* Range:       $A$24:$B$46
* -----------------------------------------------------
PARAMETER DISLOSS_E(RRR)  'Loss in electricity distribution'                   
/                                                                              
DK1                                                          0.0410545023696682
DK2                                                          0.0410545023696682
FIN                                                          0.0212986414920562
GER                                                          0.0482863049464869
NE                                                           0.029597407028318 
NO1                                                          0.0496942268326864
NO2                                                          0.0496942268326864
NO3                                                          0.0496942268326864
NO4                                                          0.0496942268326864
NO5                                                          0.0496942268326864
SE1                                                          0.0563329847174327
SE2                                                          0.0563329847174327
SE3                                                          0.0563329847174327
SE4                                                          0.0563329847174327
UK                                                           0.0803            
EE                                                           0.05              
LV                                                           0.05              
LT                                                           0.05              
PL                                                           0.05              
/;                                                                             
                                                                               
* -----------------------------------------------------
