* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       25(Sheet32)
* Range:       $A$48:$E$50
* -----------------------------------------------------
PARAMETER DISLOSS_H(AAA)  'Loss in heat distribution (fraction)' ;    
                                                                      
DISLOSS_H(AAA) = 0;                                                   
* -----------------------------------------------------
