PARAMETER DISLOSS_E(RRR)  'Loss in electricity distribution'                   
/                                                                              
DK1                                                          0.0410545023696682
DK2                                                          0.0410545023696682
NO1                                                          0.0496942268326864
NO2                                                          0.0496942268326864
NO3                                                          0.0496942268326864
NO4                                                          0.0496942268326864
NO5                                                          0.0496942268326864
/;                                                                             
                                                                               
