TABLE EMI_POLNA(YYY,GROUP,EMIPOLSET) 'Emission policy data; default for the LIM_ entries: 0 implies irrelevant, EPS implies no emission permitted (aggregated countries)'

      ALL_SECTORS . LIM_CO2
                           
2025           1.745598e+09
2030           1.501960e+09
2035           8.766216e+08
2040           2.512833e+08
2045           8.400030e+07
2050          -8.328270e+07
;