* -----------------------------------------------------
* XLS2GMS Version 1.5,  August 2002
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\TortoiseGit\Balmorel_flex4RES\transport_scenario_data\EV_data.xlsx
* Sheet:       HIntervals
* Range:       $A$1:$J$27
* -----------------------------------------------------
TABLE EV_HINTERVALS(HHH,EV_IALLINTERVALS)                                                                                                          
      EV_TZERO EV_TINFLEX EV_TNOTDECREASABLE EV_TNOTINCREASABLE EV_TN EV_TD /*  Corresponding hour in TTT */   
H17                                                             yes         /*  T001                         */
H18                                                             yes         /*  T002                         */
H19                                                             yes         /*  T003                         */
H20                                                             yes         /*  T004                         */
H21                                                             yes         /*  T005                         */
H22                                                             yes         /*  T006                         */
H23                                                             yes         /*  T007                         */
H24            yes                                              yes         /*  T008                         */
H01            yes                                                    yes   /*  T009                         */
H02                                                                   yes   /*  T010                         */
H03                                                                   yes   /*  T011                         */
H04                                                                   yes   /*  T012                         */
H05                                                                   yes   /*  T013                         */
H06                                                                   yes   /*  T014                         */
H07                                                                   yes   /*  T015                         */
H08            yes                                                    yes   /*  T016                         */
H09            yes                                              yes         /*  T017                         */
H10                                                             yes         /*  T018                         */
H11                                                             yes         /*  T019                         */
H12                                                             yes         /*  T020                         */
H13                                                             yes         /*  T021                         */
H14                                                             yes         /*  T022                         */
H15                                                             yes         /*  T023                         */
H16                                                             yes         /*  T024                         */
;                                                                                                              
* -----------------------------------------------------
