
Parameter
FB_ACRAM(ACNETWORKS,LINES)                                                                                                                                                                              ;

TABLE                                                                                                                                               FB_ACRAM_ACSCAND(LINES,ACNETWORKS)

                                                                                                                                                                                       ACSCAND          ACEUR                              ACBALT
ACLine1                                                                                                                                                                                2377.34365643673
ACLine2                                                                                                                                                                                398.419089236628
ACLine3                                                                                                                                                                                2775.76274567336
ACLine4                                                                                                                                                                                1188.67182821836
ACLine5                                                                                                                                                                                10388.5307978641
ACLine6                                                                                                                                                                                740.86194279538
ACLine7                                                                                                                                                                                2377.34365643673
ACLine8                                                                                                                                                                                4306.87742745049
ACLine9                                                                                                                                                                                1481.72388559076
ACLine10                                                                                                                                                                               1929.53377101375
ACLine11                                                                                                                                                                               1188.67182821836
ACLine12                                                                                                                                                                               1188.67182821836
ACLine13                                                                                                                                                                               398.419089236628
ACLine14                                                                                                                                                                               4754.68731287348
ACLine15                                                                                                                                                                               10704.6318934568
ACLine16                                                                                                                                                                               5943.35914109184
ACLine17                                                                                                                                                                                                4761.27275236499
ACLine18                                                                                                                                                                                                4754.68731287348
ACLine19                                                                                                                                                                                                13872.2282888753
ACLine20                                                                                                                                                                                                5943.35914109184
ACLine21                                                                                                                                                                                                6740.1973195651
ACLine22                                                                                                                                                                                                4754.68731287348
ACLine23                                                                                                                                                                                                7928.86914778343
ACLine24                                                                                                                                                                                                9509.37462574694
ACLine25                                                                                                                                                                                                2377.34365643673
ACLine26                                                                                                                                                                                                4754.68731287348
ACLine27                                                                                                                                                                                                3174.18183490999
ACLine28                                                                                                                                                                                                                                   1481.72388559076
ACLine29                                                                                                                                                                                                                                   2963.44777118153
;

FB_ACRAM(ACNETWORKS,                                                                                                                                 LINES)                             =                FB_ACRAM_ACSCAND(LINES,ACNETWORKS)                                                    ;
