
Parameter
FB_ACRAM(ACNETWORKS,LINES)                                                                                                                                                                              ;

TABLE                                                                                                                                               FB_ACRAM_ACSCAND(LINES,ACNETWORKS)

                                                                                                                                                                                       ACSCAND          ACEUR                              ACBALT
ACLine1                                                                                                                                                                                2377.34365643673
ACLine2                                                                                                                                                                                398.419089236628
ACLine3                                                                                                                                                                                2775.76274567336
ACLine4                                                                                                                                                                                1188.67182821836
ACLine5                                                                                                                                                                                5340.79142761826
ACLine6                                                                                                                                                                                740.86194279538
ACLine7                                                                                                                                                                                5047.73937024587
ACLine8                                                                                                                                                                                2377.34365643673
ACLine9                                                                                                                                                                                740.86194279538
ACLine10                                                                                                                                                                               1481.72388559076
ACLine11                                                                                                                                                                               1188.67182821836
ACLine12                                                                                                                                                                               1188.67182821836
ACLine13                                                                                                                                                                               1188.67182821836
ACLine14                                                                                                                                                                               398.419089236628
ACLine15                                                                                                                                                                               4754.68731287348
ACLine16                                                                                                                                                                               10704.6318934568
ACLine17                                                                                                                                                                               5943.35914109184
ACLine18                                                                                                                                                                                                4761.27275236499
ACLine19                                                                                                                                                                                                4754.68731287348
ACLine20                                                                                                                                                                                                13872.2282888753
ACLine21                                                                                                                                                                                                5943.35914109184
ACLine22                                                                                                                                                                                                6740.1973195651
ACLine23                                                                                                                                                                                                4754.68731287348
ACLine24                                                                                                                                                                                                7928.86914778343
ACLine25                                                                                                                                                                                                9509.37462574694
ACLine26                                                                                                                                                                                                2377.34365643673
ACLine27                                                                                                                                                                                                4754.68731287348
ACLine28                                                                                                                                                                                                3174.18183490999
ACLine29                                                                                                                                                                                                                                   1481.72388559076
ACLine30                                                                                                                                                                                                                                   2963.44777118153
;

FB_ACRAM(ACNETWORKS,                                                                                                                                 LINES)                             =                FB_ACRAM_ACSCAND(LINES,ACNETWORKS)                                                    ;
