* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       09(Sheet12)
* Range:       $A$3:$A$11
* -----------------------------------------------------
SET FDATASET  'Characteristics of fuels '                
/                                                        
FDACRONYM 'Acronym (name) of the fuel'                   
FDNB      'Fuel number for internal use'                 
FDCO2     'Emission CO2 (kg/GJ)'                         
FDSO2     'Emission SO2 (kg/GJ)'                         
FDN2O     'Emission N2O (kg/GJ)'                         
FDRE         "Share of fuel considered renewable ([1;0])"
/;                                                       
* -----------------------------------------------------
