* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       08(Sheet11)
* Range:       $A$1:$A$114
* -----------------------------------------------------
* The set of all fuels:                                                            
                                                                                   
SET FFF  'Fuels'                                                                   
/                                                                                  
NUCLEAR                                                                            
NATGAS                                                                             
COAL                                                                               
LIGNITE                                                                            
FUELOIL                                                                            
LIGHTOIL                                                                           
HEAVYFUELOIL                                                                       
ORIMULSION                                                                         
SHALE                                                                              
PEAT                                                                               
MUNIWASTE                                                                          
STRAW                                                                              
WOOD                                                                               
WOODCHIPS                                                                          
DRYWOODCHIPS                                                                       
RECYCLEDWOOD                                                                       
WOODPELLETS                                                                        
WOODWASTE                                                                          
BIOOIL                                                                             
LPG                                                                                
LNG                                                                                
BIOGAS                                                                             
OTHERGAS                                                                           
WASTEHEAT                                                                          
WIND                                                                               
WATER                                                                              
SUN                                                                                
ELECTRIC                                                                           
WATERRES                                                                           
HEAT                                                                               
HYDROGEN                                                                           
DUMMY                                                                              
COAL_EXETS                                                                         
NATGAS_EXETS                                                                       
FUELOIL_EXETS                                                                      
LPG_EXETS                                                                          
HEAVYFUELOIL_EXETS                                                                 
                                                                                   
*TopWaste fuels                                                                    
BIOGAS_NET                                                                         
COAL_CCS                                                                           
NG_CCS                                                                             
WP_CCS                                                                             
BIOGAS_EC_net                                                                      
BIOGAS_EC                                                                          
GeoEl                                                                              
SURPLUS_H                                                                          
STRAW_PELLETS                                                                      
HAZARDOUSWASTE                                                                     
GH2FUEL                                                                            
COKE                                                                               
RETORTGAS                                                                          
/                                                                                  
;                                                                                  
                                                                                   
* File for holding fuel acronyms for the Balmorel model, version 3.01 (April 2009).
ACRONYMS                                                                           
NUCLEAR                                                                            
NATGAS                                                                             
COAL                                                                               
LIGNITE                                                                            
FUELOIL                                                                            
LIGHTOIL                                                                           
HEAVYFUELOIL                                                                       
ORIMULSION                                                                         
SHALE                                                                              
PEAT                                                                               
MUNIWASTE                                                                          
STRAW                                                                              
WOOD                                                                               
WOODCHIPS                                                                          
DRYWOODCHIPS                                                                       
RECYCLEDWOOD                                                                       
WOODPELLETS                                                                        
WOODWASTE                                                                          
BIOOIL                                                                             
LPG                                                                                
LNG                                                                                
BIOGAS                                                                             
OTHERGAS                                                                           
WASTEHEAT                                                                          
WIND                                                                               
WATER                                                                              
SUN                                                                                
ELECTRIC                                                                           
WATERRES                                                                           
HEAT                                                                               
HYDROGEN                                                                           
DUMMY                                                                              
COAL_EXETS                                                                         
NATGAS_EXETS                                                                       
FUELOIL_EXETS                                                                      
LPG_EXETS                                                                          
HEAVYFUELOIL_EXETS                                                                 
                                                                                   
*TopWaste fuels                                                                    
BIOGAS_NET                                                                         
COAL_CCS                                                                           
NG_CCS                                                                             
WP_CCS                                                                             
BIOGAS_EC_net                                                                      
BIOGAS_EC                                                                          
GeoEl                                                                              
SURPLUS_H                                                                          
STRAW_PELLETS                                                                      
HAZARDOUSWASTE                                                                     
GH2FUEL                                                                            
COKE                                                                               
RETORTGAS                                                                          
;                                                                                  
* -----------------------------------------------------
