* The set of all fuels:                                                            
                                                                                   
SET FFF  'Fuels'                                                                   
/                                                                                  
NUCLEAR                                                                            
NATGAS                                                                             
COAL                                                                               
LIGNITE                                                                            
FUELOIL                                                                            
LIGHTOIL                                                                           
MUNIWASTE                                                                          
WOODCHIPS                                                                          
WOODPELLETS                                                                        
WOODWASTE                                                                          
BIOOIL                                                                             
BIOGAS                                                                             
WIND                                                                               
WATER                                                                              
SUN                                                                                
ELECTRIC                                                                           
HEAT                                                                               
THERMGAS                                                                           
DUMMY                                                                              
/;                                                                                  
                                                                                   
* File for holding fuel acronyms for the Balmorel model, version 3.01 (April 2009).
ACRONYMS                                                                           
NUCLEAR                                                                            
NATGAS                                                                             
COAL                                                                               
LIGNITE                                                                            
FUELOIL                                                                            
LIGHTOIL                                                                           
MUNIWASTE                                                                          
WOODCHIPS                                                                          
WOODPELLETS                                                                        
WOODWASTE                                                                          
BIOOIL                                                                             
BIOGAS                                                                             
WIND                                                                               
WATER                                                                              
SUN                                                                                
ELECTRIC                                                                           
HEAT                                                                               
THERMGAS                                                                           
DUMMY                                                                         
;                                                                                  
