TABLE FGEMAX(YYY,CCCRRRAAA,FFF)   'Maximum electricity generation by fuel (MWh)'                                                             
*                                                                                NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2020.DK_W                                                                      0                                                           
;                                                                                                                                            
