* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       27_1(Sheet34)
* Range:       $A$11:$F$14
* -----------------------------------------------------
TABLE FGEMAX(CCCRRRAAA,FFF)   'Maximum electricity generation by fuel (MWh)'                                                             
*                                                                            NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* DK_W                                                                       0                                                           
;                                                                                                                                        
* -----------------------------------------------------
