TABLE FGEMAX(CCCRRRAAA,FFF)   'Maximum electricity generation by fuel (MWh)'                                                       
                                                                             NATGAS       COAL    STRAW       WOOD        WOODWASTE
DENMARK                                                                      0            4973500                                  
;                                                                                                                                  
