* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       27_2(Sheet35)
* Range:       $A$19:$F$22
* -----------------------------------------------------
TABLE FKMAX(YYY,CCCRRRAAA,FFF)     'Minimum capacity by fuel per year (MW)'                                                             
*                                                                           NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2012.DK_W                                                                                            0           0                    
;                                                                                                                                       
* -----------------------------------------------------
