TABLE FKMINNA(YYY,FFF)     'Minimum capacity by year and fuel (aggregated countries)(MW)'                                                             
*                                                                                         NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2012.DK_W                                                                                                          0           0                    
;                                                                                                                                                     
