TABLE FKMIN(YYY,CCCRRRAAA,FFF)     'Minimum fuel capacity restricted by geography (MW)'                                                             
*                                                                                       NATGAS       MUNIWASTE     STRAW       WOOD        WOODWASTE
* 2012.DK_W                                                                                                        0           0                    
;                                                                                                                                                   
