* Fuel potentials specified at geographical level.                                                                                          
* The fuel potential is specified as an upper limit on the countries'installed                                                              
* generation capacity relative to the individual fuel type.                                                                                 
* For now no limitations on fuel potential                                                                                                  
                                                                                                                                            
* Note: The value 0 or white space implies no restriction. The value 'eps' implies zero MW.                                                 
                                                                                                                                            
TABLE FKPOT(CCCRRRAAA,FFF)       'Fuel potential restriction by geography (MW)'                                                             
;                                                                                                                                           
                                                                                                                                            
                                                                                                                                            
