* Fuel potentials specified at geographical level.                                                                                          
* The fuel potential is specified as an upper limit on the countries'installed                                                              
* generation capacity relative to the individual fuel type.                                                                                 
* For now no limitations on fuel potential                                                                                                  
                                                                                                                                            
* Note: The value 0 or white space implies no restriction. The value 'eps' implies zero MW.                                                 
                                                                                                                                            
TABLE FKPOT(CCCRRRAAA,FFF)       'Fuel potential restriction by geography (MW)'                                                             
                                                                                            NUCLEAR LIGNITE ORIMULSION SHALE PEAT           
DENMARK                                                                                     0       0       0          0     0              
NORWAY                                                                                      0       0       0          0     0              
                                                                                                                                            
+                                                                                           STRAW   WOOD    WOODWASTE                       
DENMARK                                                                                                                                     
NORWAY                                                                                                                                      
                                                                                                                                            
+                                                                                           WIND            SUN                             
DK1_NoDH                                                                                                                                    
DK2_NoDH                                                                                                                                    
NO1_A1                                                                                                                                      
NO2_A1                                                                                                                                      
NO3_A1                                                                                                                                      
NO4_A1                                                                                                                                      
NO5_A1                                                                                                                                      
                                                                                                                                            
*                                                                                                                                           
DK1_Offshore                                                                                                                                
DK2_Offshore                                                                                                                                
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
;                                                                                                                                           
                                                                                                                                            
                                                                                                                                            
