* Fuel potentials specified at geographical level.                                                                                          
* The fuel potential is specified as an upper limit on the countries'installed                                                              
* generation capacity relative to the individual fuel type.                                                                                 
* For now no limitations on fuel potential                                                                                                  
                                                                                                                                            
* Note: The value 0 or white space implies no restriction. The value 'eps' implies zero MW.                                                 
                                                                                                                                            
TABLE FKPOT(CCCRRRAAA,FFF)       'Fuel potential restriction by geography (MW)'                                                             
                                                                                            NUCLEAR LIGNITE ORIMULSION SHALE PEAT           
DENMARK                                                                                     0       0       0          0     0              
FINLAND                                                                                     0       0       0          0     0              
GERMANY                                                                                     0       0       0          0     0              
NETHERLANDS                                                                                 0       0       0          0     0              
NORWAY                                                                                      0       0       0          0     0              
SWEDEN                                                                                      0       0       0          0     0              
ESTONIA                                                                                     0       0       0          0     0              
LATVIA                                                                                      0       0       0          0     0              
LITHUANIA                                                                                   0       0       0          0     0              
POLAND                                                                                      0       0       0          0     0              
                                                                                                                                            
+                                                                                           STRAW   WOOD    WOODWASTE                       
DENMARK                                                                                                                                     
FINLAND                                                                                                                                     
GERMANY                                                                                                                                     
NETHERLANDS                                                                                                                                 
NORWAY                                                                                                                                      
SWEDEN                                                                                                                                      
ESTONIA                                                                                                                                     
LATVIA                                                                                                                                      
LITHUANIA                                                                                                                                   
POLAND                                                                                                                                      
                                                                                                                                            
+                                                                                           WIND            SUN                             
DK1_NoDH                                                                                                                                    
DK2_NoDH                                                                                                                                    
SE1A                                                                                                                                        
SE2A                                                                                                                                        
SE3A                                                                                                                                        
SE4A                                                                                                                                        
NO1_A1                                                                                                                                      
NO2_A1                                                                                                                                      
NO3_A1                                                                                                                                      
NO4_A1                                                                                                                                      
NO5_A1                                                                                                                                      
DE4-W_A                                                                                                                                     
DE4-N_A                                                                                                                                     
DE4-E_A                                                                                                                                     
DE4-S_A                                                                                                                                     
FinA                                                                                                                                        
UK_A                                                                                                                                        
NL_A                                                                                                                                        
EE_A                                                                                                                                        
LV_A                                                                                                                                        
LT_A                                                                                                                                        
PL_A                                                                                                                                        
;                                                                                                                                           
