TABLE FMAXINVEST(CCC,FFF)     'Maximum investment by year and fuel type for each year simulated (MW)'                                                     
*some data added for baltics based on ENMAK study for 2-year modellign intervals                                                                          
*assumptions also added for germany and france. Assumed 15 GW possible to add annually                                                                    
                                                                                                      WIND MUNIWASTE     STRAW       WOOD        WOODWASTE
ESTONIA                                                                                                                                                   
LATVIA                                                                                                                                                    
LITHUANIA                                                                                                                                                 
FRANCE                                                                                                                                                    
GERMANY                                                                                                                                                   
;                                                                                                                                                         
