* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       31_1(Sheet43)
* Range:       $A$8:$F$14
* -----------------------------------------------------
TABLE GEFFRATE(AAA,GGG)  'Reduction in fuel efficiency (fraction)'                                                       
*                                                                                                      DK_E_Rural_WI     
* DK_E_Rural                                                                                           1                 
;                                                                                                                        
                                                                                                                         
* Unless other values are assigned in the TABLE above, a default value are used and assigned below:                      
GEFFRATE(AAA,G)$(GEFFRATE(AAA,G) EQ 0)=                                                                1             ;   
* -----------------------------------------------------
