SET GGG  'All generation technologies'                                                                     
/                                                                                                          
GNR_BO_BIOIL_E-90                                                                                                 
GNR_BO_COAL_E-90                                                                                                  
GNR_BO_ELEC_E-98                                                                                                  
GNR_BO_ELEC_E-99_LS-10-MW-FEED_Y-2020                                                                             
GNR_BO_FUELOIL_E-90                                                                                               
GNR_BO_LIGHTOIL_E-90                                                                                              
GNR_BO_MSW_E-90                                                                                                   
GNR_BO_NGAS_E-105_SS-500-KW_Y-2020                                                                                
GNR_BO_NGAS_E-90                                                                                                  
GNR_BO_WOODCHI_E-117_LS-6-MW-FEED_Y-2020                                                                          
GNR_BO_WOODCHI_E-90                                                                                               
GNR_BO_WOODPEL_E-90                                                                                               
GNR_CC_NGAS_BP_E-30                                                                                               
GNR_CC_NGAS_CND_E-51                                                                                              
GNR_CC_NGAS_CND_E-59_LS-100-MW_Y-2020                                                                             
GNR_ENG_NGAS_BP_E-45                                                                                              
GNR_ENG_NGAS_BP_E-47_Y-2020                                                                                       
GNR_ES_ELEC_BAT-LITHIO-PEAK_E-86_Y-20-29                                                                          
GNR_GT_LIGHTOIL_CND_E-27                                                                                          
GNR_GT_NGAS_BP_E-36                                                                                               
GNR_GT_NGAS_CND_E-31                                                                                              
GNR_GT_NGAS_CND_E-42_LS-40-MW_Y-2020                                                                              
GNR_HS_HEAT_WTR-TANK_LS_E-95_Y-2010                                                                               
GNR_PV_SUN                                                                                                        
GNR_PV_SUN_LS-4-MW_Y-2020                                                                                         
GNR_RES_WTR_NOPMP                                                                                                 
GNR_RES_WTR_NOPMP_MC-01                                                                                           
GNR_RES_WTR_NOPMP_MC-02                                                                                           
GNR_RES_WTR_NOPMP_MC-03                                                                                           
GNR_RES_WTR_NOPMP_MC-04                                                                                           
GNR_RES_WTR_NOPMP_MC-05                                                                                           
GNR_RES_WTR_NOPMP_MC-06                                                                                           
GNR_RES_WTR_NOPMP_MC-07                                                                                           
GNR_RES_WTR_NOPMP_MC-08                                                                                           
GNR_RES_WTR_NOPMP_MC-09                                                                                           
GNR_RES_WTR_NOPMP_MC-10                                                                                           
GNR_ROR_WTR                                                                                                       
GNR_SH_SUN                                                                                                        
GNR_ST_COAL_BP_E-38                                                                                               
GNR_ST_COAL_CND_E-33                                                                                              
GNR_ST_COAL_CND_E-40                                                                                              
GNR_ST_COAL_EXT_E-39                                                                                              
GNR_ST_FUELOIL_CND_E-30                                                                                           
GNR_ST_LIGN_CND_E-32                                                                                              
GNR_ST_MSW_BP_CB-10                                                                                               
GNR_ST_NGAS_EXT_E-47_LS-400-MW_Y-2020                                                                             
GNR_ST_NUCL_CND_E-33                                                                                              
GNR_ST_WOODCHI_BP_E-29_LS-600-MW-FEED_Y-2020                                                                      
GNR_ST_WOODCHI_BP_E-30                                                                                            
GNR_WT_WIND_OFF                                                                                                   
GNR_WT_WIND_OFF_L-FS_Y-2020                                                                                       
GNR_WT_WIND_ON_LS_Y-2020                                                                                          
GNR_WT_WIND_ONS                                                                                                   
/;                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
