* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       30(Sheet42)
* Range:       $A$4:$C$6
* -----------------------------------------------------
TABLE GINVCOST(AAA,GGG)  'Investment cost for new technology (Mmoney(MEUR90)/MW)'               
* Default values given by GDATA(GGG,'GDINVCOST0')                                               
*                                                                                 DK_E_Rural_WI 
* -----------------------------------------------------
