* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       23(Sheet30)
* Range:       $A$7:$D$11
* -----------------------------------------------------
* PARAMETER GKNMAX holds the maximum capacities of those production technologies           
* for which investments are allowed. If not any value is specified in this table           
* the default value is inf.                                                                
* Units: MW.                                                                               
GKNMAX(YYY,AAA,GGG)=                                                             INF  ;    
* -----------------------------------------------------
