* PARAMETER GKNMAX holds the maximum capacities of those production technologies           
* for which investments are allowed. If not any value is specified in this table           
* the default value is inf.                                                                
* Units: MW.                                                                               
GKNMAX(YYY,AAA,GGG)=                                                             INF  ;    
GKNMAX('2050','DK2_Large','GNR_HP_ELEC_COP-740_Y-2050')=                         200  ;    
GKNMAX('2050','DK1_Large','GNR_HP_ELEC_COP-740_Y-2050')=                         200  ;    
