TABLE GKRATE(AAA,GGG,SSS)  'Reduction in capacity'
* PARAMETER GKDERATE contains a possibility to represent planned outages.
* It works through the parameter GKDERATE.
* It permits to take out units in one or more season (whole seasons only).
* If unit 'G' in area 'A' is planned out in season 'S' then let GKDERATE('G','A','S')=0.
* If unit 'G' in area 'A' is not planned out in season 'S' then let GKDERATE('G','A','S')
* attain 1 minus the stochastic FOR value (typically this will be 0.9 or 0.95).
* Germany


;


































