TABLE GMINF(YYY,CCCRRRAAA,FFF) 'Minimum fuel use (GJ) per year' 
                                                                
;                                                                                                   
                                            
*Values from Eurostat 2023 expect UK 2019, use of biogas                                               
                                                    
                                                   
                                                     
                                                    
                                                 
                                                    
                                                 
                                            
                                     
                                                                                                          
                                                      
    