TABLE GMINF(YYY,CCCRRRAAA,FFF) 'Minimum fuel use (GJ) per year'
                                                                NATGAS           MUNIWASTE     STRAW       WOOD        WOODWASTE WOODPELLETS WOODCHIPS BIOGAS BIONG
2016.ESTONIA                                                    0
2017.ESTONIA                                                    1440000
2018.ESTONIA                                                    1418181.81818182
2019.ESTONIA                                                    1396363.63636364
2020.ESTONIA                                                    1374545.45454545
2021.ESTONIA                                                    1352727.27272727
2022.ESTONIA                                                    1330909.09090909
2023.ESTONIA                                                    1309090.90909091
2024.ESTONIA                                                    1287272.72727273
2025.ESTONIA                                                    1265454.54545455
2026.ESTONIA                                                    1243636.36363636
2027.ESTONIA                                                    1221818.18181818
2028.ESTONIA                                                    1200000
2029.ESTONIA                                                    1178181.81818182

2020.DENMARK                                                    EPS                    15254380                          41116790    34015823
2025.DENMARK                                                    EPS
2030.DENMARK                                                    EPS
2040.DENMARK                                                    EPS
2050.DENMARK                                                    EPS














;


