* -----------------------------------------------------
* XLS2GMS Version 1.5,  August 2002
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    \\nmbu.no\my\home\Documents\Prosjekter\Flex4RES\taxes\Grid_rent_data.xlsx
* Sheet:       3
* Range:       $A$3:$L$13
* -----------------------------------------------------
TABLE GR_PRICE(CCC,GRDATASET) 'Data on grid tariff rates'                                                                                                                                                                                                                      
                GRDFC           GRDECW               GRDECS               GRDTOU1             GRDTOU2             GRDTOU3             GRDTOU4             GRDDCW               GRDDCS               GRDDC2          GRDDCTOU         
*** description Fixed component Energy charge winter Energy charge summer TOU energy charge 1 TOU energy charge 2 TOU energy charge 3 TOU energy charge 4 Demand charge winter Demand charge summer Demand charge 2 Demand charge TOU
*** unit        €/MW            €/MWh                €/MWh                €/MWh               €/MWh               €/MWh               €/MWh               €/kW-peak/month      €/kW-peak/month      €/kW-peak/month €/kW-peak/month  
DENMARK                                                                                                                                                                                                                              
ESTONIA                                                                                                                                                                                                                              
FINLAND                                                                                                                                                                                                                              
LATVIA                                                                                                                                                                                                                               
LITHUANIA                                                                                                                                                                                                                            
NORWAY                                                                                                                                                                                                                               
SWEDEN                                                                                                                                                                                                                               
* -----------------------------------------------------
