SET GRDATASET 'Grid rent data'                                    
/                                                                 
GRDFC                                                             
GRDSUBS                                                           
GRDECW                                                            
GRDECS                                                            
GRDTOU1                                                           
GRDTOU2                                                           
GRDTOU3                                                           
GRDTOU4                                                           
GRDDCW                                                            
GRDDCS                                                            
GRDDC2                                                            
GRDDCTOU                                                          
GRDDCY                                                            
/;                                                                
                                                                  
SET GRTECHGROUP 'relevant groups of technologies for grid tariffs'
/                                                                 
P2H                                                               
BATTERIES_GRID                                                    
BATTERIES_HOME                                                    
ELECTROLYSERS                                                     
PRODUCTION                                                        
PHS                                                               
/;                                                                
