* -----------------------------------------------------
* XLS2GMS Version 1.5,  August 2002
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    \\nmbu.no\my\home\Documents\Prosjekter\Flex4RES\taxes\Grid_rent_data.xlsx
* Sheet:       set
* Range:       $A$1:$A$14
* -----------------------------------------------------
SET GRDATASET 'Grid rent data'
/    
GRDFC
GRDECW
GRDECS
GRDTOU1
GRDTOU2
GRDTOU3
GRDTOU4
GRDDCW
GRDDCS
GRDDC2
GRDDCTOU
/;   
* -----------------------------------------------------
