*GROUP                                                   
SET GROUP 'Groups included in the model (e.g. sectors)'/ 
ALL_SECTORS                                              
INDUSTRY                                                 
INDIVIDUAL_USERS                                         
OTHER_SECTORS                                            
/;                                                       
