* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       23(Sheet30)
* Range:       $A$4:$A$5
* -----------------------------------------------------
PARAMETER GROWTHCAP(C,GGG)  'Maximum model generated capacity increase (MW) from one year to the next';
GROWTHCAP(C,GGG) =0;                                                                                   
* -----------------------------------------------------
