TABLE GRTIME_M(CCC,GRDATASET,MMM)
                                  1    2    3    4    5    6    7    8    9    10   11   12
NORWAY.GRDECW                     1    1    1    1    1    1    1    1    1    1    1    1
NORWAY.GRDECS
NORWAY.GRDTOU1
NORWAY.GRDTOU2
NORWAY.GRDTOU3
NORWAY.GRDDCW
NORWAY.GRDDCS
NORWAY.GRDDC2
NORWAY.GRDDCTOU
NORWAY.GRDDCY                     1    1    1    1    1    1    1    1    1    1    1    1
SWEDEN.GRDECW                     1    1    1    1    1    1    1    1    1    1    1    1
SWEDEN.GRDECS
SWEDEN.GRDTOU1
SWEDEN.GRDTOU2
SWEDEN.GRDTOU3
SWEDEN.GRDDCW
SWEDEN.GRDDCS
SWEDEN.GRDDC2
SWEDEN.GRDDCTOU
DENMARK.GRDECW                    1    1    1    1    1    1    1    1    1    1    1    1
DENMARK.GRDECS
DENMARK.GRDTOU1
DENMARK.GRDTOU2
DENMARK.GRDTOU3
DENMARK.GRDDCW
DENMARK.GRDDCS
DENMARK.GRDDC2
DENMARK.GRDDCTOU
FINLAND.GRDECW                    1    1    1    1    1    1    1    1    1    1    1    1
FINLAND.GRDECS
FINLAND.GRDTOU1                   1    1    1                                       1    1
FINLAND.GRDTOU2                   1    1    1    1    1    1    1    1    1    1    1    1
FINLAND.GRDTOU3                                  1    1    1    1    1    1    1
FINLAND.GRDDCW                    1    1    1    1    1    1    1    1    1    1    1    1
FINLAND.GRDDCS
FINLAND.GRDDC2
FINLAND.GRDDCTOU
ESTONIA.GRDECW                    1    1    1    1    1    1    1    1    1    1    1    1
ESTONIA.GRDECS
ESTONIA.GRDTOU1
ESTONIA.GRDTOU2
ESTONIA.GRDTOU3
ESTONIA.GRDDCW
ESTONIA.GRDDCS
ESTONIA.GRDDC2
ESTONIA.GRDDCTOU
ESTONIA.GRDDCY                    1    1    1    1    1    1    1    1    1    1    1    1
LATVIA.GRDECW                     1    1    1    1    1    1    1    1    1    1    1    1
LATVIA.GRDECS
LATVIA.GRDTOU1
LATVIA.GRDTOU2
LATVIA.GRDTOU3
LATVIA.GRDDCW
LATVIA.GRDDCS
LATVIA.GRDDC2
LATVIA.GRDDCTOU
LATVIA.GRDDCY                     1    1    1    1    1    1    1    1    1    1    1    1
LITHUANIA.GRDECW                  1    1    1    1    1    1    1    1    1    1    1    1
LITHUANIA.GRDECS
LITHUANIA.GRDTOU1
LITHUANIA.GRDTOU2
LITHUANIA.GRDTOU3
LITHUANIA.GRDDCW
LITHUANIA.GRDDCS
LITHUANIA.GRDDC2
LITHUANIA.GRDDCTOU                0
LITHUANIA.GRDDCY                  1    1    1    1    1    1    1    1    1    1    1    1
GERMANY.GRDECW                    1    1    1    1    1    1    1    1    1    1    1    1
NETHERLANDS.GRDECW                1    1    1    1    1    1    1    1    1    1    1    1
UNITED_KINGDOM.GRDECW             1    1    1    1    1    1    1    1    1    1    1    1
POLAND.GRDECW                     1    1    1    1    1    1    1    1    1    1    1    1


;
