* -----------------------------------------------------
* XLS2GMS 2.8      24.4.5 r52258 Released May 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    https://eduumb-my.sharepoint.com/personal/jon_gustav_kirkerud_nmbu_no/Documents/Documents/DATA/Balmoreldokumenter/Vannkraft/Input to balmorel new.xlsx
* Sheet:       GDATA
* Range:       $A$1:$D$77
* -----------------------------------------------------
TABLE GDATA(GGG,GDATASET) 'Technology Characteristics'                   
                                                       GDTYPE GDFUEL GDFE
AGG-NO1_WTR1                                           GHYRS  WATER  1   
AGG-NO1_WTR4                                           GHYRS  WATER  1   
AGG-NO1_WTR5                                           GHYRS  WATER  1   
AGG-NO1_WTR6                                           GHYRS  WATER  1   
AGG-NO1_WTR7                                           GHYRS  WATER  1   
AGG-NO1_WTR8                                           GHYRS  WATER  1   
AGG-NO1_WTR9                                           GHYRS  WATER  1   
AGG-NO2_WTR1                                           GHYRS  WATER  1   
AGG-NO2_WTR2                                           GHYRS  WATER  1   
AGG-NO2_WTR3                                           GHYRS  WATER  1   
AGG-NO2_WTR4                                           GHYRS  WATER  1   
AGG-NO2_WTR5                                           GHYRS  WATER  1   
AGG-NO2_WTR6                                           GHYRS  WATER  1   
AGG-NO2_WTR7                                           GHYRS  WATER  1   
AGG-NO2_WTR8                                           GHYRS  WATER  1   
AGG-NO2_WTR9                                           GHYRS  WATER  1   
AGG-NO2_WTR10                                          GHYRS  WATER  1   
AGG-NO2_WTR11                                          GHYRS  WATER  1   
AGG-NO2_WTR12                                          GHYRS  WATER  1   
AGG-NO2_WTR13                                          GHYRS  WATER  1   
AGG-NO2_WTR14                                          GHYRS  WATER  1   
AGG-NO2_WTR15                                          GHYRS  WATER  1   
AGG-NO3_WTR1                                           GHYRS  WATER  1   
AGG-NO3_WTR2                                           GHYRS  WATER  1   
AGG-NO3_WTR3                                           GHYRS  WATER  1   
AGG-NO3_WTR5                                           GHYRS  WATER  1   
AGG-NO3_WTR6                                           GHYRS  WATER  1   
AGG-NO3_WTR7                                           GHYRS  WATER  1   
AGG-NO3_WTR8                                           GHYRS  WATER  1   
AGG-NO3_WTR9                                           GHYRS  WATER  1   
AGG-NO3_WTR13                                          GHYRS  WATER  1   
AGG-NO3_WTR14                                          GHYRS  WATER  1   
AGG-NO3_WTR15                                          GHYRS  WATER  1   
AGG-NO4_WTR1                                           GHYRS  WATER  1   
AGG-NO4_WTR2                                           GHYRS  WATER  1   
AGG-NO4_WTR3                                           GHYRS  WATER  1   
AGG-NO4_WTR4                                           GHYRS  WATER  1   
AGG-NO4_WTR5                                           GHYRS  WATER  1   
AGG-NO4_WTR6                                           GHYRS  WATER  1   
AGG-NO4_WTR7                                           GHYRS  WATER  1   
AGG-NO4_WTR8                                           GHYRS  WATER  1   
AGG-NO4_WTR9                                           GHYRS  WATER  1   
AGG-NO5_WTR1                                           GHYRS  WATER  1   
AGG-NO5_WTR2                                           GHYRS  WATER  1   
AGG-NO5_WTR3                                           GHYRS  WATER  1   
AGG-NO5_WTR4                                           GHYRS  WATER  1   
AGG-NO5_WTR5                                           GHYRS  WATER  1   
AGG-NO5_WTR6                                           GHYRS  WATER  1   
AGG-NO5_WTR7                                           GHYRS  WATER  1   
AGG-NO5_WTR8                                           GHYRS  WATER  1   
AGG-NO5_WTR9                                           GHYRS  WATER  1   
AGG-NO5_WTR10                                          GHYRS  WATER  1   
AGG-NO5_WTR11                                          GHYRS  WATER  1   
AGG-NO5_WTR12                                          GHYRS  WATER  1   
AGG-NO5_WTR13                                          GHYRS  WATER  1   
AGG-NO5_WTR14                                          GHYRS  WATER  1   
AGG-NO5_WTR15                                          GHYRS  WATER  1   
AGG-SE1_WTR1                                           GHYRS  WATER  1   
AGG-SE1_WTR2                                           GHYRS  WATER  1   
AGG-SE1_WTR3                                           GHYRS  WATER  1   
AGG-SE2_WTR1                                           GHYRS  WATER  1   
AGG-SE2_WTR2                                           GHYRS  WATER  1   
AGG-SE2_WTR3                                           GHYRS  WATER  1   
AGG-SE2_WTR4                                           GHYRS  WATER  1   
AGG-SE2_WTR5                                           GHYRS  WATER  1   
AGG-SE2_WTR6                                           GHYRS  WATER  1   
AGG-SE2_WTR7                                           GHYRS  WATER  1   
AGG-SE2_WTR8                                           GHYRS  WATER  1   
AGG-SE3_WTR1                                           GHYRS  WATER  1   
AGG-SE3_WTR2                                           GHYRS  WATER  1   
AGG-SE3_WTR3                                           GHYRS  WATER  1   
AGG-SE3_WTR4                                           GHYRS  WATER  1   
AGG-SE4_WTR1                                           GHYRS  WATER  1   
AGG-FIN_WTR1                                           GHYRS  WATER  1   
;                                                                        
* -----------------------------------------------------
