SET HEATSV_STEPS  'Steps used in heat savings'
/                                             
STEP1*STEP360                                 
/;                                            
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
