TABLE XHINVCOST(YYY,IAAAE,IAAAI)  "Investment cost in new heat transmission capacity (Money/MW)"                                     
                                                                                                                 DK1_Large DK1_Medium
2016                                                                                             .    DK1_Large  0         210       
2016                                                                                             .    DK1_Medium 210       0         
;                                                                                                                                    
                                                                                                                                     
XHINVCOST(YYY,IAAAE,IAAAI) = XHINVCOST('2016',IAAAE,IAAAI);                                                                          
