SET XHKN(IAAAE,IAAAI) "Pair of areas that may get new heat transmission capacity";
                                                                                  
                                                                                  
*XHKN('DK1_LARGE','DK1_medium') = yes;                                            
*XHKN('DK1_medium','DK1_LARGE') = yes;                                            
                                                                                  
XHKN(IAE,IAI) = NO;                                                               
