SET XHGETOH(GGG) "Heat pumps used for lifting temperature for heat transmitted between two Areas"
/                                                                                                
* Try out with/without and verify:                                                               
*GNR_HP_ELEC_COP-400_PHL_Y-2020                                                                  
*GNR_HP_ELEC_COP-400_PHH_Y-2020                                                                  
GNR_HP_ELEC_COP-200_PHL_Y-2030                                                                   
GNR_HP_ELEC_COP-100_PHH_Y-2030                                                                   
*GNR_HP_ELEC_COP-600_PHL_Y-2050                                                                  
*GNR_HP_ELEC_COP-600_PHH_Y-2050                                                                  
/;                                                                                               
