TABLE XHINVCOST(IAAAE,IAAAI)  "Investment cost in new heat transmission capacity (Money/MW)"                     
                                                                                             DK1_Large DK1_Medium
DK1_Large                                                                                    0         210       
DK1_Medium                                                                                   210       0         
;                                                                                                                
