PARAMETER METHANATION_DE(GGG) 'Electricity demand needed to produce biomethane through biogas methanation (MW/MWth biomethane)'; 
METHANATION_DE('GNR_BIOGASMETHANATION_E-168_Y-2020')=0.011;                                                                      
METHANATION_DE('GNR_BIOGASMETHANATION_E-168_Y-2030')=0.011;                                                                      
METHANATION_DE('GNR_BIOGASMETHANATION_E-168_Y-2040')=0.011;                                                                      
METHANATION_DE('GNR_BIOGASMETHANATION_E-168_Y-2050')=0.011;                                                                      
