SET FFF  'Hydrogen-Fuels'
/                        
BIOMETHANE               
THERMGAS_H2              
HYDROGEN                 
BIOGAS_H2                
/;                       
                         
ACRONYMS                 
BIOGAS_H2                
THERMGAS_H2              
BIOMETHANE               
HYDROGEN                 
;                        
                         
                         
                         
                         
                         
