TABLE HYDROGEN_GDATA(HYDROGEN_GGG,GDATASET)  'Hydrogen technologies characteristics'
                                                          GDTYPE                  GDFUEL   GDCV GDCB      GDFE  GDCH4 GDNOX  GDDESO2 GDINVCOST0 GDOMFCOST0 GDOMVCOST0 GDFROMYEAR GDLIFETIME GDKVARIABL GDLASTYEAR GDMOTHBALL GDSTOHLOAD GDSTOHUNLD GDCOMB GDCOMBSK GDCOMBSLO GDCOMBSUP GDCOMBKRES GDCOMBFCAP GDLOADLOSS GDSTOLOSS GDUC GDUCUNITSIZE
GNR_ELE_ELEC_AEC_Y-15-19                                  HYDROGEN_GETOH2         ELECTRIC      6.615     0.545                      1.4        56                    2015       25         1          2019
GNR_ELE_ELEC_AEC_Y-20-29                                  HYDROGEN_GETOH2         ELECTRIC      6.615     0.59                       1          40                    2020       28         1          2029
GNR_ELE_ELEC_AEC_Y-30                                     HYDROGEN_GETOH2         ELECTRIC      6.615     0.615                      1          40                    2030       30         1
GNR_ELE_ELEC_SOEC_Y-20                                    HYDROGEN_GETOH2         ELECTRIC      -1        0.98                       0.59       15                    2020       20         1
GNR_ELE_ELEC_PEMEC_Y-15-19                                HYDROGEN_GETOH2         ELECTRIC                0.535                      6                                2015       15         1          2019
GNR_ELE_ELEC_PEMEC_Y-20-29                                HYDROGEN_GETOH2         ELECTRIC                0.62                       1                                2020       25         1          2029
GNR_ELE_ELEC_PEMEC_Y-30                                   HYDROGEN_GETOH2         ELECTRIC                0.675                      1                                2030       25         1
GNR_H2S_H2                                                HYDROGEN_GH2STO         HYDROGEN                1
GNR_FC_H2_SOFC-C_Y-15-19                                  HYDROGEN_GH2TOE         HYDROGEN                50          0.0001 0       5                     25         2015       6          1          2019
GNR_FC_H2_SOFC-C_Y-20-29                                  HYDROGEN_GH2TOE         HYDROGEN                55          0.0001 0       1.5                   10         2020       15         1          2029
GNR_FC_H2_SOFC-C_Y-30-49                                  HYDROGEN_GH2TOE         HYDROGEN                60          0.0001 0       0.8                   4          2030       20         1          2049
GNR_FC_H2_SOFC-C_Y-50                                     HYDROGEN_GH2TOE         HYDROGEN                63          0.0001 0       0.5                   3          2050       20         1
DK_MAM_Thisted_DEC_Engine_BG_H2                           HYDROGEN_GH2UP          BIOGAS_H2 1   0.783     0.893                      3.472946   30.348774  5.058129   2015       20         1                                                      2
;
