Table AGKN1(GGG,AAA) 'For hydrogen technologies'
                            DK2_Large DK2_Medium DK2_MedSmall DK2_Rural DK2_Small NO1_A1 NO1_A2 DK1_Offshore10
GNR_ELYS_ELEC_AEC_Y-15      YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_AEC_Y-20      YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_AEC_Y-30      YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_SOEC_Y-20     YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_PEMEC_Y-15    YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_PEMEC_Y-20    YES       YES        YES          YES       YES       YES    YES
GNR_ELYS_ELEC_PEMEC_Y-30    YES       YES        YES          YES       YES       YES    YES
GNR_H2S_H2-Y-30             YES       YES        YES          YES       YES       YES    YES
;

AGKN1(GGG,                                                                                                                                                                           'DK1_Large'     )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'DK1_Medium'    )=AGKN1(GGG, 'DK2_Medium'    );
AGKN1(GGG,                                                                                                                                                                           'DK1_MedSmall'  )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'DK1_Rural'     )=AGKN1(GGG, 'DK2_Rural'     );
AGKN1(GGG,                                                                                                                                                                           'DK1_Small'     )=AGKN1(GGG, 'DK2_Small'     );
AGKN1(GGG,                                                                                                                                                                           'FinA'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'GerA'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'NeA'           )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'SE1A'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'SE2A'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'SE3A'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'SE4A'          )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'UKA'           )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'FIN_ESPOO'     )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_HELS'      )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_TAMP'      )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_EL'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_HP'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_OTHER'     )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'FIN_GAS'       )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'NO1_A1'        )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'NO1_A2'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'NO2_A1'        )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'NO3_A1'        )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'NO3_A2'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'NO4_A1'        )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'NO5_A1'        )=AGKN1(GGG, 'DK2_Large'     );
AGKN1(GGG,                                                                                                                                                                           'SE1_EL'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE1_OTHER'     )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE2_EL'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE2_OTHER'     )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE3_STO'       )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE3_GOT'       )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE3_EL'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE3_HP'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE3_OTHER'     )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE4_MAL'       )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE4_EL'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE4_HP'        )=AGKN1(GGG, 'DK2_MedSmall'  );
AGKN1(GGG,                                                                                                                                                                           'SE4_OTHER'     )=AGKN1(GGG, 'DK2_MedSmall'  );

AGKN(AAA,GGG) = AGKN1(GGG,AAA);
