PARAMETER BIOGASUPGRADING_DE(GGG) 'Electricity demand needed to produce biomethane through biogas upgrading (MW/MWth biomethane)'; 
BIOGASUPGRADING_DE('GNR_BIOGASUPGRADING_E-99_Y-2020')=0.0537;                                                                      
BIOGASUPGRADING_DE('GNR_BIOGASUPGRADING_E-99_Y-2030')=0.0316;                                                                      
BIOGASUPGRADING_DE('GNR_BIOGASUPGRADING_E-100_Y-2040')=0.0316;                                                                     
BIOGASUPGRADING_DE('GNR_BIOGASUPGRADING_E-100_Y-2050')=0.0316;                                                                     
