PARAMETER XH2KN_ES(IRRRE,IRRRI,XES) 'Installed capacity in H2 transmission lines at the beginning of each XES (MW)';                     
                                                                                                                                         
XH2KN_ES('NO2','DK1','XES1')=EPS;                                                                                                        
XH2KN_ES('DK1','NO2','XES2')=250;                                                                                                        
XH2KN_ES('NO2','DK1','XES2')=250;                                                                                                        
XH2KN_ES('DK1','NO2','XES3')=500;                                                                                                        
XH2KN_ES('NO2','DK1','XES3')=500;                                                                                                        
XH2KN_ES('DK1','NO2','XES4')=1000;                                                                                                       
XH2KN_ES('NO2','DK1','XES4')=1000;                                                                                                       
XH2KN_ES('DK1','NO2','XES5')=6000;                                                                                                       
XH2KN_ES('NO2','DK1','XES5')=6000;                                                                                                       
XH2KN_ES('DK1','NO2','XES6')=50000;                                                                                                      
XH2KN_ES('NO2','DK1','XES6')=50000;                                                                                                      
                                                                                                                                         
