SET HYDROGEN_GGG(GGG)  'All hydrogen technologies'                                                                                                                                        
/                                                                                                                                                                             
ElectrolyserAEC                                                                                                                                                               
H2_storage                                                                                                                                                                    
/;                                                                                                                                                                            
