SET FFF  'Hydrogen-Fuels'
/                        
BIOMETHANE               
THERMGAS_H2              
HYDROGEN                 
BIOGAS_H2
IMPORT_H2
NATGAS_CCS               
/;                       
                         
ACRONYMS                 
BIOMETHANE               
THERMGAS_H2              
HYDROGEN                 
BIOGAS_H2
IMPORT_H2
NATGAS_CCS                 
                         
;                        
