PARAMETER METHANATION_DH2(GGG) 'H2 demand needed to produce biomethane through biogas methanation (MWth/MWth biomethane)'; 
METHANATION_DH2('GNR_BIOGASMETHANATION_E-168_Y-2020')=0.5169;                                                              
METHANATION_DH2('GNR_BIOGASMETHANATION_E-168_Y-2030')=0.5169;                                                              
METHANATION_DH2('GNR_BIOGASMETHANATION_E-168_Y-2040')=0.5169;                                                              
METHANATION_DH2('GNR_BIOGASMETHANATION_E-168_Y-2050')=0.5169;                                                              
                                                                                                                           
