TABLE FDATA(FFF,FDATASET)   'Fuel specific values'                                                                                           
* PARAMETER FDATA contains information about emission characteristics of fuels.                                                              
* In addition it contains a name (FDACRONYM) for the fuel, note that this must be as an ACRONYM previously.                                  
* Note: So far values just copied from BIOGAS from FDATA                                                                                     
                                                                                                                                             
                                                                                                            FDACRONYM  FDNB FDCO2 FDSO2 FDN2O
*                                                                                                           Units           kg/GJ kg/GJ kg/GJ
HYDROGEN                                                                                                    HYDROGEN                         
BIOMETHANE                                                                                                  BIOMETHANE 38                    
IMPORT_H2                                                                                                   IMPORT_H2  39   5.61             
NATGAS_CCS                                                                                                                                   
;                                                                                                                                            
