* Defining hydrogen investment options
SET H2_INV_OPTIONS(GGG)
/
GNR_ELYS_ELEC_AEC_Y-2020
GNR_ELYS_ELEC_AEC_Y-2030
GNR_ELYS_ELEC_AEC_Y-2040
GNR_ELYS_ELEC_AEC_Y-2050
GNR_ELYS_ELEC_AEC_DH_Y-2020
GNR_ELYS_ELEC_AEC_DH_Y-2030
GNR_ELYS_ELEC_AEC_DH_Y-2040
GNR_ELYS_ELEC_AEC_DH_Y-2050
GNR_FC_H2_SOFCC_Y-2020
GNR_FC_H2_SOFCC_Y-2030
GNR_FC_H2_SOFCC_Y-2040
GNR_FC_H2_SOFCC_Y-2050
GNR_H2S_H2-TNKC_Y-2020
GNR_H2S_H2-TNKC_Y-2030
GNR_H2S_H2-TNKC_Y-2040
GNR_H2S_H2-TNKC_Y-2050
GNR_STEAM-REFORMING_E-70_Y-2020
GNR_STEAM-REFORMING-CCS_E-70_Y-2020
/;
AGKN('Aabenraa_A',GGG) = AGKN('Aabenraa_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Aalborg_A',GGG) = AGKN('Aalborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Aarhus_A',GGG) = AGKN('Aarhus_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Aeroe_A',GGG) = AGKN('Aeroe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Albertslund_A',GGG) = AGKN('Albertslund_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Alleroed_A',GGG) = AGKN('Alleroed_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Assens_A',GGG) = AGKN('Assens_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Ballerup_A',GGG) = AGKN('Ballerup_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Billund_A',GGG) = AGKN('Billund_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Bornholm_A',GGG) = AGKN('Bornholm_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Broendby_A',GGG) = AGKN('Broendby_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Broenderslev_A',GGG) = AGKN('Broenderslev_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Christiansoe_A',GGG) = AGKN('Christiansoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Dragoer_A',GGG) = AGKN('Dragoer_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Egedal_A',GGG) = AGKN('Egedal_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Esbjerg_A',GGG) = AGKN('Esbjerg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Faaborg-Midtfyn_A',GGG) = AGKN('Faaborg-Midtfyn_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Fanoe_A',GGG) = AGKN('Fanoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Favrskov_A',GGG) = AGKN('Favrskov_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Faxe_A',GGG) = AGKN('Faxe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Fredensborg_A',GGG) = AGKN('Fredensborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Fredericia_A',GGG) = AGKN('Fredericia_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Frederiksberg_A',GGG) = AGKN('Frederiksberg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Frederikshavn_A',GGG) = AGKN('Frederikshavn_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Frederikssund_A',GGG) = AGKN('Frederikssund_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Furesoe_A',GGG) = AGKN('Furesoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Gentofte_A',GGG) = AGKN('Gentofte_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Gladsaxe_A',GGG) = AGKN('Gladsaxe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Glostrup_A',GGG) = AGKN('Glostrup_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Greve_A',GGG) = AGKN('Greve_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Gribskov_A',GGG) = AGKN('Gribskov_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Guldborgsund_A',GGG) = AGKN('Guldborgsund_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Haderslev_A',GGG) = AGKN('Haderslev_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Halsnaes_A',GGG) = AGKN('Halsnaes_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hedensted_A',GGG) = AGKN('Hedensted_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Helsingoer_A',GGG) = AGKN('Helsingoer_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Herlev_A',GGG) = AGKN('Herlev_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Herning_A',GGG) = AGKN('Herning_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hilleroed_A',GGG) = AGKN('Hilleroed_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hjoerring_A',GGG) = AGKN('Hjoerring_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hoeje-Taastrup_A',GGG) = AGKN('Hoeje-Taastrup_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hoersholm_A',GGG) = AGKN('Hoersholm_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Holbaek_A',GGG) = AGKN('Holbaek_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Holstebro_A',GGG) = AGKN('Holstebro_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Horsens_A',GGG) = AGKN('Horsens_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Hvidovre_A',GGG) = AGKN('Hvidovre_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Ikast-Brande_A',GGG) = AGKN('Ikast-Brande_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Ishoej_A',GGG) = AGKN('Ishoej_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Jammerbugt_A',GGG) = AGKN('Jammerbugt_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Kalundborg_A',GGG) = AGKN('Kalundborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Kerteminde_A',GGG) = AGKN('Kerteminde_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Koebenhavn_A',GGG) = AGKN('Koebenhavn_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Koege_A',GGG) = AGKN('Koege_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Kolding_A',GGG) = AGKN('Kolding_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Laesoe_A',GGG) = AGKN('Laesoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Langeland_A',GGG) = AGKN('Langeland_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Lejre_A',GGG) = AGKN('Lejre_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Lemvig_A',GGG) = AGKN('Lemvig_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Lolland_A',GGG) = AGKN('Lolland_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Lyngby-Taarbaek_A',GGG) = AGKN('Lyngby-Taarbaek_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Mariagerfjord_A',GGG) = AGKN('Mariagerfjord_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Middelfart_A',GGG) = AGKN('Middelfart_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Morsoe_A',GGG) = AGKN('Morsoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Naestved_A',GGG) = AGKN('Naestved_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Norddjurs_A',GGG) = AGKN('Norddjurs_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Nordfyns_A',GGG) = AGKN('Nordfyns_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Nyborg_A',GGG) = AGKN('Nyborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Odder_A',GGG) = AGKN('Odder_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Odense_A',GGG) = AGKN('Odense_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Odsherred_A',GGG) = AGKN('Odsherred_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Randers_A',GGG) = AGKN('Randers_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Rebild_A',GGG) = AGKN('Rebild_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Ringkoebing-Skjern_A',GGG) = AGKN('Ringkoebing-Skjern_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Ringsted_A',GGG) = AGKN('Ringsted_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Roedovre_A',GGG) = AGKN('Roedovre_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Roskilde_A',GGG) = AGKN('Roskilde_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Rudersdal_A',GGG) = AGKN('Rudersdal_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Samsoe_A',GGG) = AGKN('Samsoe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Silkeborg_A',GGG) = AGKN('Silkeborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Skanderborg_A',GGG) = AGKN('Skanderborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Skive_A',GGG) = AGKN('Skive_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Slagelse_A',GGG) = AGKN('Slagelse_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Soenderborg_A',GGG) = AGKN('Soenderborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Solroed_A',GGG) = AGKN('Solroed_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Soroe_A',GGG) = AGKN('Soroe_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Stevns_A',GGG) = AGKN('Stevns_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Struer_A',GGG) = AGKN('Struer_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Svendborg_A',GGG) = AGKN('Svendborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Syddjurs_A',GGG) = AGKN('Syddjurs_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Taarnby_A',GGG) = AGKN('Taarnby_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Thisted_A',GGG) = AGKN('Thisted_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Toender_A',GGG) = AGKN('Toender_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Vallensbaek_A',GGG) = AGKN('Vallensbaek_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Varde_A',GGG) = AGKN('Varde_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Vejen_A',GGG) = AGKN('Vejen_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Vejle_A',GGG) = AGKN('Vejle_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Vesthimmerlands_A',GGG) = AGKN('Vesthimmerlands_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Viborg_A',GGG) = AGKN('Viborg_A',GGG) + H2_INV_OPTIONS(GGG);
AGKN('Vordingborg_A',GGG) = AGKN('Vordingborg_A',GGG) + H2_INV_OPTIONS(GGG);

* Add cavern investment option in Viborg
AGKN('Viborg_A','GNR_H2S_H2-CAVERN_Y-2030') = YES;
AGKN('Viborg_A','GNR_H2S_H2-CAVERN_Y-2040') = YES;
AGKN('Viborg_A','GNR_H2S_H2-CAVERN_Y-2050') = YES;