PARAMETER XH2KN_ES(IRRRE,IRRRI,XES) 'Installed capacity in H2 transmission lines at the beginning of each XES (MW)';                                         
                                                                                                                                                             
XH2KN_ES('BE','DE4-W','XES1')=EPS;

*OBS FF - Deleted all except first rows as placeholder            