TABLE HYRSMAXVOL_G(AAA,GGG)  'Reservoir capacity (MWh storage capacity/MW installed capacity)'                                                           
                                                                                               GNR_RES_WTR_NOPMP                                         
AL_A                                                                                           847.391890694675                                          
AT_A                                                                                           275.924281940305                                          
BA_A                                                                                           942.240293809024                                          
BG_A                                                                                           657.816280340279                                          
HR_A                                                                                           1050.21328583382                                          
CZ_A                                                                                           3.58426401824014                                          
FR_A                                                                                           1015.53772722657                                          
DE4-E_A                                                                                        289.64590964591                                           
DE4-N_A                                                                                        289.64590964591                                           
DE4-S_A                                                                                        289.64590964591                                           
DE4-W_A                                                                                        289.64590964591
FIN_A                                                                                          1708.578858                                           
GR_A                                                                                           1473.92207602872                                          
HU_A                                                                                           300                                                       
IT_A                                                                                           652.5803394                                          
LU_A                                                                                           300                                          
ME_A                                                                                           550.26455026455                                           
MK_A                                                                                           862.3895141367                                            
NO1_A                                                                                          2754.819561                                          
NO2_A                                                                                          2754.819561                                          
NO3_A                                                                                          2754.819561                                          
NO4_A                                                                                          2754.819561                                          
NO5_A                                                                                          2754.819561                                          
PL_A                                                                                           4.01951544                                          
PT_A                                                                                           300                                          
RO_A                                                                                           913.387335890336                                          
RS_A                                                                                           1487.55382596081                                          
SK_A                                                                                           810.222982260338                                          
ES_A                                                                                           1294.44752540478                                          
SE1_A                                                                                          2649.946179                                          
SE2_A                                                                                          1934.432086                                          
SE3_A                                                                                          1152.7021                                          
SE4_A                                                                                          300.9278785                                          
CH_A                                                                                           927.543962485346                                          
TR_A                                                                                           75.7575757575758
UK_A                                                                                           9.96573082632224                                          
;                                                                                                                                                        
                                                                                                                                                         
                                                                                                                                                         
* From TYNDP2024 hydro inflow data (https://2024.entsos-tyndp-scenarios.eu/download/)
* Used 2030 data
* Reservoir MWh storage / MW capacity
* AL = 847.3902224
* AT = 275.9242819
* BA = 942.2402938
* BE = 0.0
* BG = 657.8169511
* CH = 927.5443456
* CZ = 3.584264018
* DE = 289.6422879
* ES = 1294.386417
* FI = 1708.578858
* FR = 1015.537727
* GR = 1473.922076
* HR = 1050.213286
* HU = 0.0 (There is a small reservoi according to ENTSO-E, so used a value not too big here)
* IE = 0.0
* IT = 816.2171103 - 941.3451979 - 862.7362989 - 584.2419528 - 799.2709299 - 480.3863642 (Italy had several files with data, so calculating a weighted average based on size of the reservoirs)
* IT_weighted_average = 652.5803394
* LT = 0.0
* LU = 0.0 (There is a small reservoi according to ENTSO-E, so used a value not too big here)
* LV = 0.0
* ME = 550.2645503
* MK = 862.3895141
* NL = 0.0
* NO = 2389.851067 - 4418.035131 - 1892.252413 (Norwat had several files with data, so calculating a weighted average based on size of the reservoirs)
* NO_weighted_average = 2754.819561
* PL = 4.01951544
* PT = 0.0 (There is a small reservoi according to ENTSO-E, so used a value not too big here)
* RO = 913.3873359
* RS = 1487.553826
* SE1 = 2649.946179
* SE2 = 1934.432086
* SE3 = 1152.7021
* SE4 = 300.9278785
* SI = 0.0 (There is a small reservoi according to ENTSO-E, so used a value not too big here)
* SK = 810.2229823
* UK = 0.0 (old data is put in)