SET RRRAAA(RRR,AAA) "Areas in regions"                    
/                                                         
DK2                                    .    DK2_NoDH_ind  
DK1                                    .    DK1_NoDH_ind  
DK2                                    .    DK2_NoDH_apart
DK1                                    .    DK1_NoDH_apart
/                                                         
;                                                         
