SET INDHEAT_GROUP 'Group of technologies'
/                                        
GR_OIL                                   
GR_GB                                    
GR_WP                                    
GR_EL                                    
GR_HPA2W                                 
GR_GBHPA2W                               
GR_GBSH                                  
GR_WPSH                                  
GR_ELHPA2A                               
/                                        
;                                        
