SET INDHEAT_AAA(AAA) 'Areas with individual heating'
/                                                   
DK2_NoDH_ind                                        
DK1_NoDH_ind                                        
DK2_NoDH_apart                                      
DK1_NoDH_apart                                      
/                                                   
;                                                   
