PARAMETER INDHEAT_CARDGROUP(INDHEAT_GROUP) 'Cardinality of groups of technologies'     
/                                                                                      
GR_COAL_TANK    2
GR_EL_TANK      2
GR_ELHPA2A_TANK 3
GR_WPSTOV_TANK  3
GR_OIL_TANK     2
GR_GBHPA2W_TANK 3
GR_GB_TANK      2
GR_WP_TANK      2
GR_HPA2W_TANK   2
GR_GBSH_TANK    3
GR_WPSH_TANK    3

*                                                                                      
GR_AbGHPA2W_TANK 2
GR_AbGHPB2W_TANK 2
GR_GEHPA2W_TANK  2 
GR_GEHPB2W_TANK  2 
GR_AdGHPB2W_TANK 2   
/                                                                                      
;                                                                                      
