SET INDHEAT_RELGROUP(INDHEAT_SUMGROUP,INDHEAT_GROUP) 'Relation of summed groups and groups'
/                                                                                          
RADIATOR . (GR_GBHPA2W, GR_OIL, GR_GB, GR_WP, GR_HPA2W, GR_GBSH, GR_WPSH, GR_HPB2W, GR_ELW)
NO_RADIATOR . (GR_EL, GR_ELHPA2A)                                                          
SOLARHEATING . (GR_GBSH, GR_WPSH)                                                          
BIOMASS . (GR_WP, GR_WPSH)                                                                 
/                                                                                          
;                                                                                          
