PARAMETER INDHEAT_SOLHFLH(INDHEAT_AAA)  'Full load hours for solar heat (hours)'
* Average FLH from existing solar plants in Denmark.
/
DK2_NoDH_ind                                                                                                                                                               703
DK1_NoDH_ind                                                                                                                                                               703
DK2_NoDH_apart                                                                                                                                                             703
DK1_NoDH_apart                                                                                                                                                             703
/;