PARAMETER INDHEAT_DHPOT(YYY,AAA,INDHEAT_AAA)         'Potential of DH expansion (MWh)';

INDHEAT_DHPOT(YYY,'DK1_Large','DK1_NoDH_ind')   =        24061.55   ;
INDHEAT_DHPOT(YYY,'DK1_Medium','DK1_NoDH_ind')  =        148939.82  ;
INDHEAT_DHPOT(YYY,'DK1_MedSmall','DK1_NoDH_ind')=        41208.48   ;
INDHEAT_DHPOT(YYY,'DK1_Small','DK1_NoDH_ind')   =        107137.95  ;
INDHEAT_DHPOT(YYY,'DK1_Rural','DK1_NoDH_ind')   =        349616.50  ;

INDHEAT_DHPOT(YYY,'DK1_Large','DK1_NoDH_apart')   =        19486.18 ;
INDHEAT_DHPOT(YYY,'DK1_Medium','DK1_NoDH_apart')  =        55119.49 ;
INDHEAT_DHPOT(YYY,'DK1_MedSmall','DK1_NoDH_apart')=        22489.67 ;
INDHEAT_DHPOT(YYY,'DK1_Small','DK1_NoDH_apart')   =        20557.59 ;
INDHEAT_DHPOT(YYY,'DK1_Rural','DK1_NoDH_apart')   =        73338.71 ;

INDHEAT_DHPOT(YYY,'DK2_Large','DK2_NoDH_ind')   =        157104.56  ;
INDHEAT_DHPOT(YYY,'DK2_Medium','DK2_NoDH_ind')  =        123952.40  ;
INDHEAT_DHPOT(YYY,'DK2_MedSmall','DK2_NoDH_ind')=        70604.44   ;
INDHEAT_DHPOT(YYY,'DK2_Small','DK2_NoDH_ind')   =        14637.16   ;
INDHEAT_DHPOT(YYY,'DK2_Rural','DK2_NoDH_ind')   =        181876.79  ;

INDHEAT_DHPOT(YYY,'DK2_Large','DK2_NoDH_apart')   =        379581.71;
INDHEAT_DHPOT(YYY,'DK2_Medium','DK2_NoDH_apart')  =        94068.49 ;
INDHEAT_DHPOT(YYY,'DK2_MedSmall','DK2_NoDH_apart')=        41048.54 ;
INDHEAT_DHPOT(YYY,'DK2_Small','DK2_NoDH_apart')   =        5961.49  ;
INDHEAT_DHPOT(YYY,'DK2_Rural','DK2_NoDH_apart')   =        71975.58 ;
