SET CCCRRRAAA 'All geographical entities (CCC + RRR + AAA)'
/                                                          
DK2_NoDH_ind                                               
DK1_NoDH_ind                                               
DK2_NoDH_apart                                             
DK1_NoDH_apart                                             
/                                                          
;                                                          
