PARAMETER INDHEAT_AGKN(INDHEAT_AAA,INDHEAT_GGG,INDHEAT_GROUP)  'Allowed investment in area and group'
/
DK1_NoDH         . INDHEAT_GB_2010 . GR_GB              1
DK1_NoDH         . INDHEAT_GB_2020 . GR_GB              1
DK1_NoDH         . INDHEAT_GB_2030 . GR_GB              1
DK1_NoDH         . INDHEAT_GB_2050 . GR_GB              1
DK1_NoDH         . INDHEAT_GB_2010 . GR_GBHPA2W         1
DK1_NoDH         . INDHEAT_GB_2020 . GR_GBHPA2W         1
DK1_NoDH         . INDHEAT_GB_2030 . GR_GBHPA2W         1
DK1_NoDH         . INDHEAT_GB_2050 . GR_GBHPA2W         1
DK1_NoDH         . INDHEAT_GB_2010 . GR_GBSH            1
DK1_NoDH         . INDHEAT_GB_2020 . GR_GBSH            1
DK1_NoDH         . INDHEAT_GB_2030 . GR_GBSH            1
DK1_NoDH         . INDHEAT_GB_2050 . GR_GBSH            1
DK1_NoDH         . INDHEAT_WP_2010 . GR_WP              1
DK1_NoDH         . INDHEAT_WP_2020 . GR_WP              1
DK1_NoDH         . INDHEAT_WP_2030 . GR_WP              1
DK1_NoDH         . INDHEAT_WP_2050 . GR_WP              1
DK1_NoDH         . INDHEAT_WP_2010 . GR_WPSH            1
DK1_NoDH         . INDHEAT_WP_2020 . GR_WPSH            1
DK1_NoDH         . INDHEAT_WP_2030 . GR_WPSH            1
DK1_NoDH         . INDHEAT_WP_2050 . GR_WPSH            1
DK1_NoDH         . INDHEAT_HPA2W_2010 . GR_HPA2W        1
DK1_NoDH         . INDHEAT_HPA2W_2020 . GR_HPA2W        1
DK1_NoDH         . INDHEAT_HPA2W_2030 . GR_HPA2W        1
DK1_NoDH         . INDHEAT_HPA2W_2050 . GR_HPA2W        1
DK1_NoDH         . INDHEAT_HPA2W_2010 . GR_GBHPA2W      1
DK1_NoDH         . INDHEAT_HPA2W_2020 . GR_GBHPA2W      1
DK1_NoDH         . INDHEAT_HPA2W_2030 . GR_GBHPA2W      1
DK1_NoDH         . INDHEAT_HPA2W_2050 . GR_GBHPA2W      1
DK1_NoDH         . INDHEAT_HPA2A_2010 . GR_ELHPA2A      1
DK1_NoDH         . INDHEAT_HPA2A_2020 . GR_ELHPA2A      1
DK1_NoDH         . INDHEAT_HPA2A_2030 . GR_ELHPA2A      1
DK1_NoDH         . INDHEAT_HPA2A_2050 . GR_ELHPA2A      1
DK1_NoDH         . INDHEAT_SH_2010 . GR_GBSH            1
DK1_NoDH         . INDHEAT_SH_2020 . GR_GBSH            1
DK1_NoDH         . INDHEAT_SH_2030 . GR_GBSH            1
DK1_NoDH         . INDHEAT_SH_2050 . GR_GBSH            1
DK1_NoDH         . INDHEAT_SH_2010 . GR_WPSH            1
DK1_NoDH         . INDHEAT_SH_2020 . GR_WPSH            1
DK1_NoDH         . INDHEAT_SH_2030 . GR_WPSH            1
DK1_NoDH         . INDHEAT_SH_2050 . GR_WPSH            1
DK1_NoDH         . INDHEAT_EL_2010 . GR_EL              1
DK1_NoDH         . INDHEAT_EL_2020 . GR_EL              1
DK1_NoDH         . INDHEAT_EL_2030 . GR_EL              1
DK1_NoDH         . INDHEAT_EL_2050 . GR_EL              1
DK1_NoDH         . INDHEAT_EL_2010 . GR_ELHPA2A         1
DK1_NoDH         . INDHEAT_EL_2020 . GR_ELHPA2A         1
DK1_NoDH         . INDHEAT_EL_2030 . GR_ELHPA2A         1
DK1_NoDH         . INDHEAT_EL_2050 . GR_ELHPA2A         1
/;

INDHEAT_AGKN(INDHEAT_AAA,INDHEAT_G,INDHEAT_GROUP)=INDHEAT_AGKN('DK1_NoDH',INDHEAT_G,INDHEAT_GROUP);
