SET INDHEAT_GMOVE(INDHEAT_GGG,INDHEAT_GROUPFROM,INDHEAT_GROUPTO) 'Technologies that can be moved from group GROUPFROM to GROUPTO'
/
INDHEAT_GB_2010_IND                                                                                                               .    GR_GB .    GR_GBHPA2W
INDHEAT_GB_2010_IND                                                                                                               .    GR_GB .    GR_GBSH
INDHEAT_WP_2010_IND                                                                                                               .    GR_WP .    GR_WPSH
INDHEAT_EL_2010_IND                                                                                                               .    GR_EL .    GR_ELHPA2A
INDHEAT_GB_2010_APART                                                                                                             .    GR_GB .    GR_GBHPA2W
INDHEAT_GB_2010_APART                                                                                                             .    GR_GB .    GR_GBSH
INDHEAT_WP_2010_APART                                                                                                             .    GR_WP .    GR_WPSH
INDHEAT_GB_2020_IND                                                                                                               .    GR_GB .    GR_GBHPA2W
INDHEAT_GB_2020_IND                                                                                                               .    GR_GB .    GR_GBSH
INDHEAT_WP_2020_IND                                                                                                               .    GR_WP .    GR_WPSH
INDHEAT_EL_2020_IND                                                                                                               .    GR_EL .    GR_ELHPA2A
INDHEAT_GB_2020_APART                                                                                                             .    GR_GB .    GR_GBHPA2W
INDHEAT_GB_2020_APART                                                                                                             .    GR_GB .    GR_GBSH
INDHEAT_WP_2020_APART                                                                                                             .    GR_WP .    GR_WPSH
/
;
