$onmulti                                            
SET AAA(CCCRRRAAA)  'All areas'                     
/                                                   
DK2_NoDH_ind                                        
DK1_NoDH_ind                                        
DK2_NoDH_apart                                      
DK1_NoDH_apart                                      
/                                                   
;                                                   
$offmulti                                           
                                                    
SET INDHEAT_AAA(AAA) 'Areas with individual heating'
/                                                   
DK2_NoDH_ind                                        
DK1_NoDH_ind                                        
DK2_NoDH_apart                                      
DK1_NoDH_apart                                      
/                                                   
;                                                   
