TABLE INDHEAT_GDATA(INDHEAT_GGG,GDATASET)  'Technology characteristics'
                                                                                       GDTYPE GDFUEL      GDFE              GDCH4 GDNOX            GDDESO2 GDINVCOST0         GDOMFCOST0        GDOMVCOST0       GDFROMYEAR GDLIFETIME GDKVARIABL GDLASTYEAR
INDHEAT_OIL_2010_IND                                                                   GHOB   LIGHTOIL    0.919851668295407 0     30               0.5     0.40098887803062   16.6292212585509  0                2010       20         1          2019
INDHEAT_OIL_2020_IND                                                                   GHOB   LIGHTOIL    0.919851668295407 0     25               0.5     0.391063903315102  16.2472124333787  0                2020       20         1          2029
INDHEAT_OIL_2030_IND                                                                   GHOB   LIGHTOIL    0.929962917073852 0     20               0.5     0.371944840102481  15.7154380676157  0                2030       20         1          2039
INDHEAT_OIL_2040_IND                                                                   GHOB   LIGHTOIL    0.939962917073852 0     17.5             0.5     0.354205020271626  14.9989217348305  0                2040       20         1          2049
INDHEAT_OIL_2050_IND                                                                   GHOB   LIGHTOIL    0.949962917073852 0     15               0.5     0.336465200440771  14.2824054020454  0                2050       20         1          2050
INDHEAT_GB_2010_IND                                                                    GHOB   NATGAS      0.969315794621871 2     20               0       0.32               20.945            0                2010       20         1          2019
INDHEAT_GB_2020_IND                                                                    GHOB   NATGAS      0.969315794621871 1     10               0       0.312079600999     20.4709750624375  0                2020       20         1          2029
INDHEAT_GB_2030_IND                                                                    GHOB   NATGAS      0.979315794621871 0.5   5                0       0.296822070021865  19.8643793763666  0                2030       20         1          2039
INDHEAT_GB_2040_IND                                                                    GHOB   NATGAS      0.984315794621871 0.375 4                0       0.282665212670225  18.9665757918891  0                2040       20         1          2049
INDHEAT_GB_2050_IND                                                                    GHOB   NATGAS      0.989315794621871 0.25  3                0       0.268508355318586  18.0687722074116  0                2050       20         1          2050
INDHEAT_WP_2010_IND                                                                    GHOB   WOODPELLETS 0.79921693912407  3     90               25      0.583333333333333  42.975055597068   0                2010       20         1          2019
INDHEAT_WP_2020_IND                                                                    GHOB   WOODPELLETS 0.819373551299256 2     70               25      0.682674127185313  50.4130345360498  0                2020       20         1          2029
INDHEAT_WP_2030_IND                                                                    GHOB   WOODPELLETS 0.859060326948884 1     50               25      0.65184047856506   48.7828250747032  0                2030       20         1          2039
INDHEAT_WP_2040_IND                                                                    GHOB   WOODPELLETS 0.869295245211663 0.5   45               25      0.620751103471117  46.6207599793936  0                2040       20         1          2049
INDHEAT_WP_2050_IND                                                                    GHOB   WOODPELLETS 0.879530163474442 0     40               25      0.589661728377175  44.4586948840839  0                2050       20         1          2050
INDHEAT_HPA2W_2010_IND                                                                 GETOH  ELECTRIC    3.45308092042614                                 1.17417011367694   39.2367006159981  0                2010       18         1          2019
INDHEAT_HPA2W_2020_IND                                                                 GETOH  ELECTRIC    3.56469226133794                                 1.10488104094751   37.488195151811   0                2020       18         1          2029
INDHEAT_HPA2W_2030_IND                                                                 GETOH  ELECTRIC    3.74727524997024                                 0.995141761397453  34.3984016342412  0                2030       18         1          2039
INDHEAT_HPA2W_2040_IND                                                                 GETOH  ELECTRIC    3.83477524997024                                 0.943174956850375  33.2940059715664  0                2040       18         1          2049
INDHEAT_HPA2W_2050_IND                                                                 GETOH  ELECTRIC    3.92227524997024                                 0.891208152303297  32.1896103088916  0                2050       18         1          2050
INDHEAT_HPA2A_2010_IND                                                                 GETOH  ELECTRIC    4.95355463635281                                 0.345497931793834  48.4217838650161  0                2010       12         1          2019
INDHEAT_HPA2A_2020_IND                                                                 GETOH  ELECTRIC    5.05355463635281                                 0.326303602249732  46.0486346540386  0                2020       12         1          2029
INDHEAT_HPA2A_2030_IND                                                                 GETOH  ELECTRIC    3.93744122723485                                 0.243128174225291  28.4104467842707  0                2030       12         1          2039
INDHEAT_HPA2A_2040_IND                                                                 GETOH  ELECTRIC    3.99905256814665                                 0.236730064377257  27.0554173473031  0                2040       12         1          2049
INDHEAT_HPA2A_2050_IND                                                                 GETOH  ELECTRIC    4.06066390905845                                 0.230331954529223  25.7003879103356  0                2050       12         1          2050
INDHEAT_SH_2010_IND                                                                    GSOLH  SUN         1                                                0.92166397918889   16.5357142857143  0                2010       20         1          2019
INDHEAT_SH_2020_IND                                                                    GSOLH  SUN         1                                                0.84805197710221   16.2321250445982  0                2020       25         1          2029
INDHEAT_SH_2030_IND                                                                    GSOLH  SUN         1                                                0.761868517380006  16.3771757450237  0                2030       30         1          2039
INDHEAT_SH_2040_IND                                                                    GSOLH  SUN         1                                                0.693103423974889  15.7142208037303  0                2040       30         1          2049
INDHEAT_SH_2050_IND                                                                    GSOLH  SUN         1                                                0.624338330569772  15.0512658624369  0                2050       30         1          2050
INDHEAT_EL_2010_IND                                                                    GETOH  ELECTRIC    1                                                1                  8.33333333333333  0                2010       30         1          2019
INDHEAT_EL_2020_IND                                                                    GETOH  ELECTRIC    1                                                0.975248753121875  8.12707294268229  0                2020       30         1          2029
INDHEAT_EL_2030_IND                                                                    GETOH  ELECTRIC    1                                                0.927568968818328  7.7297414068194   0                2030       30         1          2039
INDHEAT_EL_2040_IND                                                                    GETOH  ELECTRIC    1                                                0.883328789594454  7.36107324662045  0                2040       30         1          2049
INDHEAT_EL_2050_IND                                                                    GETOH  ELECTRIC    1                                                0.83908861037058   6.9924050864215   0                2050       30         1          2050
*
INDHEAT_AbGHPA2W_2010_IND                                                              GHOB   NATGAS      1.35              2     15               0       0.722222222222222  13.0555555555556  0                2010       20         1          2019
INDHEAT_AbGHPA2W_2020_IND                                                              GHOB   NATGAS      1.45              1     10               0       0.407333333333333  7.83333333333333  0                2020       20         1          2029
INDHEAT_AbGHPA2W_2030_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.3666             7.83333333333333  0                2030       20         1          2039
INDHEAT_AbGHPA2W_2040_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.34827            7.83333333333333  0                2040       20         1          2049
INDHEAT_AbGHPA2W_2050_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.32994            7.83333333333333  0                2050       20         1          2050
INDHEAT_AbGHPB2W_2010_IND                                                              GHOB   NATGAS      1.35              2     15               0       0.866666666666667  13.0555555555556  0                2010       20         1          2019
INDHEAT_AbGHPB2W_2020_IND                                                              GHOB   NATGAS      1.45              1     10               0       0.49               7.83333333333333  0                2020       20         1          2029
INDHEAT_AbGHPB2W_2030_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.44               7.83333333333333  0                2030       20         1          2039
INDHEAT_AbGHPB2W_2040_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.418333333333333  7.83333333333333  0                2040       20         1          2049
INDHEAT_AbGHPB2W_2050_IND                                                              GHOB   NATGAS      1.7               0.5   5                0       0.396666666666667  7.83333333333333  0                2050       20         1          2050
INDHEAT_AdGHPB2W_2010_IND                                                              GHOB   NATGAS      1.35              2     20               0       1.4                23.5              0                2010       20         1          2019
INDHEAT_AdGHPB2W_2020_IND                                                              GHOB   NATGAS      1.35              1     10               0       1.316              23.5              0                2020       20         1          2029
INDHEAT_AdGHPB2W_2030_IND                                                              GHOB   NATGAS      1.35              0.5   5                0       1.1844             23.5              0                2030       20         1          2039
INDHEAT_AdGHPB2W_2040_IND                                                              GHOB   NATGAS      1.35              0.5   5                0       1.12518            23.5              0                2040       20         1          2049
INDHEAT_AdGHPB2W_2050_IND                                                              GHOB   NATGAS      1.35              0.5   5                0       1.06596            23.5              0                2050       20         1          2050
*
*
INDHEAT_OIL_2010_APART                                                                 GHOB   LIGHTOIL    0.919992706585953 0     30.0018233535118 0.5     0.0875159543432281 2.136502078623    25.2             2010       20         1          2019
INDHEAT_OIL_2020_APART                                                                 GHOB   LIGHTOIL    0.919992706585953 0     25               0.5     0.0853498253515041 2.09471719819919  24.5762685786713 2020       20         1          2029
INDHEAT_OIL_2030_APART                                                                 GHOB   LIGHTOIL    0.929998176646488 0     20               0.5     0.0811770835253    2.09083822330657  23.3747380142219 2030       20         1          2039
INDHEAT_OIL_2040_APART                                                                 GHOB   LIGHTOIL    0.939998176646488 0     17.5             0.5     0.0773053620202071 2.01814700125916  22.2598854977802 2040       20         1          2049
INDHEAT_OIL_2050_APART                                                                 GHOB   LIGHTOIL    0.949998176646488 0     15               0.5     0.0734336405151143 1.94545577921174  21.1450329813386 2050       20         1          2050
INDHEAT_GB_2010_APART                                                                  GHOB   NATGAS      1.01              2     20               0       0.0649125666033091 1.75022199155579  0                2010       25         1          2019
INDHEAT_GB_2020_APART                                                                  GHOB   NATGAS      1.01              1     10               0       0.0633058996418179 1.71440640482348  0                2020       25         1          2029
INDHEAT_GB_2030_APART                                                                  GHOB   NATGAS      1.02              0.5   5                0       0.0602108824675825 1.66611814102764  0                2030       25         1          2039
INDHEAT_GB_2040_APART                                                                  GHOB   NATGAS      1.02              0.375 4                0       0.0573391388871704 1.62620354516561  0                2040       25         1          2049
INDHEAT_GB_2050_APART                                                                  GHOB   NATGAS      1.02              0.25  3                0       0.0544673953067584 1.58628894930359  0                2050       25         1          2050
INDHEAT_WP_2010_APART                                                                  GHOB   WOODPELLETS 0.8               3     90               25      0.230343614718615  4.52778566919192  0                2010       20         1          2019
INDHEAT_WP_2020_APART                                                                  GHOB   WOODPELLETS 0.85              2     70               25      0.224642323043915  4.44560615978106  0                2020       20         1          2029
INDHEAT_WP_2030_APART                                                                  GHOB   WOODPELLETS 0.9               1     50               25      0.213659589178432  4.39462199414579  0                2030       20         1          2039
INDHEAT_WP_2040_APART                                                                  GHOB   WOODPELLETS 0.9               0.5   45               25      0.203469146380205  4.22811386057367  0                2040       20         1          2049
INDHEAT_WP_2050_APART                                                                  GHOB   WOODPELLETS 0.9               0     40               25      0.193278703581979  4.06160572700156  0                2050       20         1          2050
INDHEAT_HPA2W_2010_APART                                                               GETOH  ELECTRIC    3.82986953883495                                 0.431413076456311  7.80069781553398  0.5              2010       20         1          2019
INDHEAT_HPA2W_2020_APART                                                               GETOH  ELECTRIC    3.92986953883495                                 0.407408727750809  7.84826304611651  0.47             2020       20         1          2029
INDHEAT_HPA2W_2030_APART                                                               GETOH  ELECTRIC    4.02478256472492                                 0.363382635517799  8.87567202669903  0.42             2030       20         1          2039
INDHEAT_HPA2W_2040_APART                                                               GETOH  ELECTRIC    4.09967384708738                                 0.345628286812298  10.1718245600728  0.4              2040       20         1          2049
INDHEAT_HPA2W_2050_APART                                                               GETOH  ELECTRIC    4.17456512944984                                 0.327873938106796  11.4679770934466  0.38             2050       20         1          2050
INDHEAT_SH_2010_APART                                                                  GSOLH  SUN         1                                                0.623797009084036  8.25749826629681  0                2010       20         1          2019
INDHEAT_SH_2020_APART                                                                  GSOLH  SUN         1                                                0.575263662511985  8.13336598171154  0                2020       25         1          2029
INDHEAT_SH_2030_APART                                                                  GSOLH  SUN         1                                                0.52096100163312   8.40281837418117  0                2030       30         1          2039
INDHEAT_SH_2040_APART                                                                  GSOLH  SUN         1                                                0.493809671193688  8.06679576507786  0                2040       30         1          2049
INDHEAT_SH_2050_APART                                                                  GSOLH  SUN         1                                                0.466658340754255  7.73077315597455  0                2050       30         1          2050
INDHEAT_EL_2010_APART                                                                  GETOH  ELECTRIC    1                                                0.6625             0.3125            0                2010       30         1          2019
INDHEAT_EL_2020_APART                                                                  GETOH  ELECTRIC    1                                                0.646102298943242  0.304765235350586 0                2020       30         1          2029
INDHEAT_EL_2030_APART                                                                  GETOH  ELECTRIC    1                                                0.614514441842142  0.289865302755728 0                2030       30         1          2039
INDHEAT_EL_2040_APART                                                                  GETOH  ELECTRIC    1                                                0.585205323106326  0.276040246748267 0                2040       30         1          2049
INDHEAT_EL_2050_APART                                                                  GETOH  ELECTRIC    1                                                0.555896204370509  0.262215190740806 0                2050       30         1          2050
*
INDHEAT_AbGHPA2W_2010_APART                                                            GHOB   NATGAS      135               2     15               0       0.409090909090909  5.34090909090909  0                2010       20         1          2019
INDHEAT_AbGHPA2W_2020_APART                                                            GHOB   NATGAS      145               1     10               0       0.2125             2.9375            0                2020       20         1          2029
INDHEAT_AbGHPA2W_2030_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.1875             2.9375            0                2030       20         1          2039
INDHEAT_AbGHPA2W_2040_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.18125            2.9375            0                2040       20         1          2049
INDHEAT_AbGHPA2W_2050_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.175              2.9375            0                2050       20         1          2050
INDHEAT_AbGHPB2W_2010_APART                                                            GHOB   NATGAS      135               2     15               0       0.75               5.34090909090909  0                2010       20         1          2019
INDHEAT_AbGHPB2W_2020_APART                                                            GHOB   NATGAS      145               1     10               0       0.38775            2.9375            0                2020       20         1          2029
INDHEAT_AbGHPB2W_2030_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.348975           2.9375            0                2030       20         1          2039
INDHEAT_AbGHPB2W_2040_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.33152625         2.9375            0                2040       20         1          2049
INDHEAT_AbGHPB2W_2050_APART                                                            GHOB   NATGAS      170               0.5   5                0       0.3140775          2.9375            0                2050       20         1          2050
INDHEAT_GEHPA2W_2010_APART                                                             GHOB   NATGAS      150               5     120              0       0.08               4.7               0                2010       15         1          2019
INDHEAT_GEHPA2W_2020_APART                                                             GHOB   NATGAS      155               5     80               0       0.08               4.7               0                2020       20         1          2029
INDHEAT_GEHPA2W_2030_APART                                                             GHOB   NATGAS      155               5     50               0       0.06               4.7               0                2030       20         1          2039
INDHEAT_GEHPA2W_2040_APART                                                             GHOB   NATGAS      157.5             5     50               0       0.06               4.7               0                2040       20         1          2049
INDHEAT_GEHPA2W_2050_APART                                                             GHOB   NATGAS      160               5     50               0       0.06               4.7               0                2050       20         1          2050
INDHEAT_GEHPB2W_2010_APART                                                             GHOB   NATGAS      150               5     120              0       0.38               4.7               0                2010       15         1          2019
INDHEAT_GEHPB2W_2020_APART                                                             GHOB   NATGAS      155               5     80               0       0.3572             4.7               0                2020       20         1          2029
INDHEAT_GEHPB2W_2030_APART                                                             GHOB   NATGAS      155               5     50               0       0.32148            4.7               0                2030       20         1          2039
INDHEAT_GEHPB2W_2040_APART                                                             GHOB   NATGAS      157.5             5     50               0       0.305406           4.7               0                2040       20         1          2049
INDHEAT_GEHPB2W_2050_APART                                                             GHOB   NATGAS      160               5     50               0       0.289332           4.7               0                2050       20         1          2050
*
$ifi not %COMBTECH%==yes $goto endcombtech
INDHEAT_GB_2010_IND_BIONG                                                              GHOB   BIONG       0.969315794621871 2     20               0       0.32               20.945            0                2010       20         1          2019
INDHEAT_GB_2020_IND_BIONG                                                              GHOB   BIONG       0.969315794621871 1     10               0       0.312079600999     20.4709750624375  0                2020       20         1          2029
INDHEAT_GB_2030_IND_BIONG                                                              GHOB   BIONG       0.979315794621871 0.5   5                0       0.296822070021865  19.8643793763666  0                2030       20         1          2039
INDHEAT_GB_2040_IND_BIONG                                                              GHOB   BIONG       0.984315794621871 0.375 4                0       0.282665212670225  18.9665757918891  0                2040       20         1          2049
INDHEAT_GB_2050_IND_BIONG                                                              GHOB   BIONG       0.989315794621871 0.25  3                0       0.268508355318586  18.0687722074116  0                2050       20         1          2050
INDHEAT_GB_2010_APART_BIONG                                                            GHOB   BIONG       1.01              2     20               0       0.0649125666033091 1.75022199155579  0                2010       25         1          2019
INDHEAT_GB_2020_APART_BIONG                                                            GHOB   BIONG       1.01              1     10               0       0.0633058996418179 1.71440640482348  0                2020       25         1          2029
INDHEAT_GB_2030_APART_BIONG                                                            GHOB   BIONG       1.02              0.5   5                0       0.0602108824675825 1.66611814102764  0                2030       25         1          2039
INDHEAT_GB_2040_APART_BIONG                                                            GHOB   BIONG       1.02              0.375 4                0       0.0573391388871704 1.62620354516561  0                2040       25         1          2049
INDHEAT_GB_2050_APART_BIONG                                                            GHOB   BIONG       1.02              0.25  3                0       0.0544673953067584 1.58628894930359  0                2050       25         1          2050
$label endcombtech
;

$ifi not %COMBTECH%==yes $goto endcombtech2
INDHEAT_GDATA(INDHEAT_GGG,'GDCOMB')$(INDHEAT_GDATA(INDHEAT_GGG,'GDFUEL')=NATGAS)=1;
INDHEAT_GDATA(INDHEAT_GGG,'GDCOMBGUP')$(INDHEAT_GDATA(INDHEAT_GGG,'GDFUEL')=NATGAS)=1;
INDHEAT_GDATA(INDHEAT_GGG,'GDCOMB')$(INDHEAT_GDATA(INDHEAT_GGG,'GDFUEL')=BIONG)=2;
$label endcombtech2


*TA CEntral:increase/decrease inv.cost of the following techs.
$ifi NOT  %TECHALT%== _CEntral_up_40 $goto NOLOW_40
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2020_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2020_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2030_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2030_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2040_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2040_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2050_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2050_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2020_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2020_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2030_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2030_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2040_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2040_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2050_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2050_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AdGHPB2W_2020_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AdGHPB2W_2020_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AdGHPB2W_2030_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AdGHPB2W_2030_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AdGHPB2W_2040_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AdGHPB2W_2040_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AdGHPB2W_2050_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AdGHPB2W_2050_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPA2W_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPA2W_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_AbGHPB2W_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_AbGHPB2W_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2020_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2020_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2030_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2030_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2040_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2040_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2050_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2050_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GB_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GB_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPA2W_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPA2W_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPA2W_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPA2W_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPA2W_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPA2W_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPA2W_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPA2W_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPB2W_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPB2W_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPB2W_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPB2W_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPB2W_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPB2W_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_GEHPB2W_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_GEHPB2W_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2020_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2020_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2020_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2020_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2030_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2030_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2030_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2030_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2040_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2040_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2040_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2040_IND','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2050_APART','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2050_APART','GDINVCOST0')*1.4;
INDHEAT_GDATA('INDHEAT_WP_2050_IND','GDINVCOST0')=INDHEAT_GDATA('INDHEAT_WP_2050_IND','GDINVCOST0')*1.4;

$label NOLOW_40
