PARAMETER INDHEAT_CARDGROUP(INDHEAT_GROUP) 'Cardinality of groups of technologies'     
/                                                                                      
GR_GBHPA2W                                                                         2   
GR_OIL                                                                             1   
GR_GB                                                                              1   
GR_WP                                                                              1   
GR_HPA2W                                                                           1   
GR_EL                                                                              1   
GR_GBSH                                                                            2   
GR_WPSH                                                                            2   
GR_ELHPA2A                                                                         2   
*                                                                                      
GR_AbGHPA2W                                                                        1   
GR_AbGHPB2W                                                                        1   
GR_GEHPA2W                                                                         1   
GR_GEHPB2W                                                                         1   
GR_AdGHPB2W                                                                        1   
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
/                                                                                      
;                                                                                      
