SET INDHEAT_SUMGROUP 'Name of summed groups'
/                                           
$ifi %TECHALT%=="_decouplingCost" GAS       
RADIATOR                                    
NO_RADIATOR                                 
SOLARHEATING                                
BIOMASS                                     
OIL                                         
/                                           
;                                           
