SET INDHEAT_GGCOMB(INDHEAT_GGG,INDHEAT_IGGGALIAS) 'Pair of combination technologies'                                 
/                                                                                                                    
INDHEAT_GB_2010_IND                                                                  .    INDHEAT_GB_2010_IND_BIONG  
INDHEAT_GB_2020_IND                                                                  .    INDHEAT_GB_2020_IND_BIONG  
INDHEAT_GB_2030_IND                                                                  .    INDHEAT_GB_2030_IND_BIONG  
INDHEAT_GB_2040_IND                                                                  .    INDHEAT_GB_2040_IND_BIONG  
INDHEAT_GB_2050_IND                                                                  .    INDHEAT_GB_2050_IND_BIONG  
INDHEAT_GB_2010_APART                                                                .    INDHEAT_GB_2010_APART_BIONG
INDHEAT_GB_2020_APART                                                                .    INDHEAT_GB_2020_APART_BIONG
INDHEAT_GB_2030_APART                                                                .    INDHEAT_GB_2030_APART_BIONG
INDHEAT_GB_2040_APART                                                                .    INDHEAT_GB_2040_APART_BIONG
INDHEAT_GB_2050_APART                                                                .    INDHEAT_GB_2050_APART_BIONG
/;                                                                                                                   
