PARAMETER INDHEAT_DHCOST(YYY,AAA,INDHEAT_AAA,INDHEAT_DHEXPAREA)         'Cost of DH expansion (Money/MWh)';

INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_ind','INSIDEDH')   =        201.55        ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_ind','INSIDEDH')  =        22.01        ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_ind','INSIDEDH')=        27.55        ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_ind','INSIDEDH')   =        3.42        ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_ind','INSIDEDH')   =        1.07        ;
INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_apart','INSIDEDH')   =        103.33        ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_apart','INSIDEDH')  =        16.05        ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_apart','INSIDEDH')=        13.93        ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_apart','INSIDEDH')   =        8.87        ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_apart','INSIDEDH')   =        2.06        ;
INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_ind','INSIDEDH')   =        132.33        ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_ind','INSIDEDH')  =        20.41        ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_ind','INSIDEDH')=        18.97        ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_ind','INSIDEDH')   =        25.59        ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_ind','INSIDEDH')   =        3.10        ;
INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_apart','INSIDEDH')   =        31.81        ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_apart','INSIDEDH')  =        17.53        ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_apart','INSIDEDH')=        13.89        ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_apart','INSIDEDH')   =        46.04        ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_apart','INSIDEDH')   =        2.20        ;

INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_ind','NEARDH')   =        495.31        ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_ind','NEARDH')  =        198.89        ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_ind','NEARDH')=        146.53        ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_ind','NEARDH')   =        57.96        ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_ind','NEARDH')   =        7.39        ;
INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_apart','NEARDH')   =        495.31        ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_apart','NEARDH')  =        198.85        ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_apart','NEARDH')=        207.10        ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_apart','NEARDH')   =        92.73        ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_apart','NEARDH')   =        19.54        ;
INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_ind','NEARDH')   =        172.05        ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_ind','NEARDH')  =        66.84        ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_ind','NEARDH')=        66.97        ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_ind','NEARDH')   =        130.52        ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_ind','NEARDH')   =        10.26        ;
INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_apart','NEARDH')   =        208.47        ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_apart','NEARDH')  =        72.46        ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_apart','NEARDH')=        153.53        ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_apart','NEARDH')   =        97.29        ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_apart','NEARDH')   =        23.22        ;


