SET INDHEAT_RELGROUP(INDHEAT_SUMGROUP,INDHEAT_GROUP) 'Relation of summed groups and groups'                                                                                       
/                                                                                                                                                                                 
RADIATOR . (GR_GBHPA2W, GR_OIL, GR_GB, GR_WP, GR_HPA2W, GR_GBSH, GR_WPSH, GR_COAL, GR_OIL_TANK,GR_GBHPA2W_TANK, GR_GB_TANK, GR_WP_TANK, GR_HPA2W_TANK, GR_GBSH_TANK, GR_WPSH_TANK)
NO_RADIATOR . (GR_EL, GR_ELHPA2A, GR_WPSTOV,GR_EL_TANK, GR_ELHPA2A_TANK, GR_WPSTOV_TANK)                                                                                          
/                                                                                                                                                                                 
;                                                                                                                                                                                 
