SET INDHEAT_GROUP 'Group of technologies'
/
GR_COAL_TANK
GR_EL_TANK
GR_ELHPA2A_TANK
GR_WPSTOV_TANK
GR_OIL_TANK
GR_GBHPA2W_TANK
GR_GB_TANK
GR_WP_TANK
GR_HPA2W_TANK
GR_GBSH_TANK
GR_WPSH_TANK

*                                        
GR_AbGHPA2W_TANK                             
GR_AbGHPB2W_TANK                              
GR_GEHPA2W_TANK                               
GR_GEHPB2W_TANK                               
GR_AdGHPB2W_TANK 
/;
