PARAMETER INDHEAT_DHCOST(YYY,AAA,INDHEAT_AAA)         'Cost of DH expansion (Money/MWh)';

INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_ind')   =        1504.55        ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_ind')  =        164.29         ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_ind')=        205.64         ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_ind')   =        25.55          ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_ind')   =        7.99           ;


INDHEAT_DHCOST(YYY,'DK1_Large','DK1_NoDH_apart')   =        771.37       ;
INDHEAT_DHCOST(YYY,'DK1_Medium','DK1_NoDH_apart')  =        119.81       ;
INDHEAT_DHCOST(YYY,'DK1_MedSmall','DK1_NoDH_apart')=        104.00       ;
INDHEAT_DHCOST(YYY,'DK1_Small','DK1_NoDH_apart')   =        66.19        ;
INDHEAT_DHCOST(YYY,'DK1_Rural','DK1_NoDH_apart')   =        15.41        ;

INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_ind')   =        987.83         ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_ind')  =        152.34         ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_ind')=        141.65         ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_ind')   =        191.04         ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_ind')   =        23.16          ;

INDHEAT_DHCOST(YYY,'DK2_Large','DK2_NoDH_apart')   =        237.43       ;
INDHEAT_DHCOST(YYY,'DK2_Medium','DK2_NoDH_apart')  =        130.89       ;
INDHEAT_DHCOST(YYY,'DK2_MedSmall','DK2_NoDH_apart')=        103.69       ;
INDHEAT_DHCOST(YYY,'DK2_Small','DK2_NoDH_apart')   =        343.66       ;
INDHEAT_DHCOST(YYY,'DK2_Rural','DK2_NoDH_apart')   =        16.39        ;
