PARAMETER INDHEAT_AGKN(INDHEAT_AAA,INDHEAT_GGG,INDHEAT_GROUP) 'Allowed investment in area and group'
/
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2010_IND      .    GR_GB      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2020_IND      .    GR_GB      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2030_IND      .    GR_GB      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2040_IND      .    GR_GB      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2050_IND      .    GR_GB      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2010_IND      .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2020_IND      .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2030_IND      .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2040_IND      .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2050_IND      .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2010_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2020_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2030_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2040_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_GB_2050_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2010_IND      .    GR_WP      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2020_IND      .    GR_WP      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2030_IND      .    GR_WP      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2040_IND      .    GR_WP      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2050_IND      .    GR_WP      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2010_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2020_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2030_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2040_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_WP_2050_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2010_IND   .    GR_HPA2W   1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2020_IND   .    GR_HPA2W   1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2030_IND   .    GR_HPA2W   1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2040_IND   .    GR_HPA2W   1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2050_IND   .    GR_HPA2W   1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2010_IND   .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2020_IND   .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2030_IND   .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2040_IND   .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2W_2050_IND   .    GR_GBHPA2W 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2A_2010_IND   .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2A_2020_IND   .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2A_2030_IND   .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2A_2040_IND   .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_HPA2A_2050_IND   .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2010_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2020_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2030_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2040_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2050_IND      .    GR_GBSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2010_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2020_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2030_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2040_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_SH_2050_IND      .    GR_WPSH    1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2010_IND      .    GR_EL      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2020_IND      .    GR_EL      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2030_IND      .    GR_EL      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2040_IND      .    GR_EL      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2050_IND      .    GR_EL      1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2010_IND      .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2020_IND      .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2030_IND      .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2040_IND      .    GR_ELHPA2A 1
DK1_NoDH_ind                                                                                                   .    INDHEAT_EL_2050_IND      .    GR_ELHPA2A 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2010_APART    .    GR_GB      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2020_APART    .    GR_GB      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2030_APART    .    GR_GB      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2040_APART    .    GR_GB      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2050_APART    .    GR_GB      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2010_APART    .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2020_APART    .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2030_APART    .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2040_APART    .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2050_APART    .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2010_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2020_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2030_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2040_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_GB_2050_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2010_APART    .    GR_WP      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2020_APART    .    GR_WP      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2030_APART    .    GR_WP      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2040_APART    .    GR_WP      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2050_APART    .    GR_WP      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2010_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2020_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2030_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2040_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_WP_2050_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2010_APART .    GR_HPA2W   1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2020_APART .    GR_HPA2W   1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2030_APART .    GR_HPA2W   1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2040_APART .    GR_HPA2W   1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2050_APART .    GR_HPA2W   1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2010_APART .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2020_APART .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2030_APART .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2040_APART .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_HPA2W_2050_APART .    GR_GBHPA2W 1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2010_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2020_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2030_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2040_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2050_APART    .    GR_GBSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2010_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2020_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2030_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2040_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_SH_2050_APART    .    GR_WPSH    1
DK1_NoDH_apart                                                                                                 .    INDHEAT_EL_2010_APART    .    GR_EL      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_EL_2020_APART    .    GR_EL      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_EL_2030_APART    .    GR_EL      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_EL_2040_APART    .    GR_EL      1
DK1_NoDH_apart                                                                                                 .    INDHEAT_EL_2050_APART    .    GR_EL      1
/;

INDHEAT_AGKN('DK2_NoDH_ind',INDHEAT_G,INDHEAT_GROUP)=INDHEAT_AGKN('DK1_NoDH_ind',INDHEAT_G,INDHEAT_GROUP);
INDHEAT_AGKN('DK2_NoDH_apart',INDHEAT_G,INDHEAT_GROUP)=INDHEAT_AGKN('DK1_NoDH_apart',INDHEAT_G,INDHEAT_GROUP);
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2010_IND',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2020_IND',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2030_IND',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2040_IND',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2050_IND',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2010_APART',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2020_APART',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2030_APART',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2040_APART',INDHEAT_GROUP)=NO;
INDHEAT_AGKN(INDHEAT_AAA,'INDHEAT_WP_2050_APART',INDHEAT_GROUP)=NO;
