SET RRRAAA(RRR,AAA) "Areas in regions"                                                        
/                                                                                             
BE                                                                  .    BE_IDVU-HOTWTR       
DE4-E                                                               .    DE4-E_IDVU-HOTWTR    
DE4-N                                                               .    DE4-N_IDVU-HOTWTR    
DE4-S                                                               .    DE4-S_IDVU-HOTWTR    
DE4-W                                                               .    DE4-W_IDVU-HOTWTR    
DK1                                                                 .    DK1_IDVU-HOTWTR      
DK2                                                                 .    DK2_IDVU-HOTWTR      
EE                                                                  .    EE_IDVU-HOTWTR       
FIN                                                                 .    FIN_IDVU-HOTWTR      
FR                                                                  .    FR_IDVU-HOTWTR       
LT                                                                  .    LT_IDVU-HOTWTR       
LV                                                                  .    LV_IDVU-HOTWTR       
NL                                                                  .    NL_IDVU-HOTWTR       
NO1                                                                 .    NO1_IDVU-HOTWTR      
NO2                                                                 .    NO2_IDVU-HOTWTR      
NO3                                                                 .    NO3_IDVU-HOTWTR      
NO4                                                                 .    NO4_IDVU-HOTWTR      
NO5                                                                 .    NO5_IDVU-HOTWTR      
PL                                                                  .    PL_IDVU-HOTWTR       
SE1                                                                 .    SE1_IDVU-HOTWTR      
SE2                                                                 .    SE2_IDVU-HOTWTR      
SE3                                                                 .    SE3_IDVU-HOTWTR      
SE4                                                                 .    SE4_IDVU-HOTWTR      
UK                                                                  .    UK_IDVU-HOTWTR       
                                                                                              
BE                                                                  .    BE_IDVU-SPACEHEAT    
DE4-E                                                               .    DE4-E_IDVU-SPACEHEAT 
DE4-N                                                               .    DE4-N_IDVU-SPACEHEAT 
DE4-S                                                               .    DE4-S_IDVU-SPACEHEAT 
DE4-W                                                               .    DE4-W_IDVU-SPACEHEAT 
DK1                                                                 .    DK1_IDVU-SPACEHEAT   
DK2                                                                 .    DK2_IDVU-SPACEHEAT   
EE                                                                  .    EE_IDVU-SPACEHEAT    
FIN                                                                 .    FIN_IDVU-SPACEHEAT   
FR                                                                  .    FR_IDVU-SPACEHEAT    
LT                                                                  .    LT_IDVU-SPACEHEAT    
LV                                                                  .    LV_IDVU-SPACEHEAT    
NL                                                                  .    NL_IDVU-SPACEHEAT    
NO1                                                                 .    NO1_IDVU-SPACEHEAT   
NO2                                                                 .    NO2_IDVU-SPACEHEAT   
NO3                                                                 .    NO3_IDVU-SPACEHEAT   
NO4                                                                 .    NO4_IDVU-SPACEHEAT   
NO5                                                                 .    NO5_IDVU-SPACEHEAT   
PL                                                                  .    PL_IDVU-SPACEHEAT    
SE1                                                                 .    SE1_IDVU-SPACEHEAT   
SE2                                                                 .    SE2_IDVU-SPACEHEAT   
SE3                                                                 .    SE3_IDVU-SPACEHEAT   
SE4                                                                 .    SE4_IDVU-SPACEHEAT   
UK                                                                  .    UK_IDVU-SPACEHEAT    
                                                                                              
                                                                                              
/;                                                                                            
