SET INDIVUSERS_AAA(CCCRRRAAA)  'Individual user areas'                                                                                                                                       
/                                                                                                                                                                                            
                                                                                                                                                    
                                                                                                                                                                                             
/;                                                                                                                                                                                           
