SET CCCRRRAAA 'All geographical entities (CCC + RRR + AAA)'
/                                                          
                                                           
*Areas                                                     
BE_IDVU-HOTWTR                                             
DE4-E_IDVU-HOTWTR                                          
DE4-N_IDVU-HOTWTR                                          
DE4-S_IDVU-HOTWTR                                          
DE4-W_IDVU-HOTWTR                                          
DK1_IDVU-HOTWTR                                            
DK2_IDVU-HOTWTR                                            
EE_IDVU-HOTWTR                                             
FIN_IDVU-HOTWTR                                            
FR_IDVU-HOTWTR                                             
LT_IDVU-HOTWTR                                             
LV_IDVU-HOTWTR                                             
NL_IDVU-HOTWTR                                             
NO1_IDVU-HOTWTR                                            
NO2_IDVU-HOTWTR                                            
NO3_IDVU-HOTWTR                                            
NO4_IDVU-HOTWTR                                            
NO5_IDVU-HOTWTR                                            
PL_IDVU-HOTWTR                                             
SE1_IDVU-HOTWTR                                            
SE2_IDVU-HOTWTR                                            
SE3_IDVU-HOTWTR                                            
SE4_IDVU-HOTWTR                                            
UK_IDVU-HOTWTR                                             
                                                           
BE_IDVU-SPACEHEAT                                          
DE4-E_IDVU-SPACEHEAT                                       
DE4-N_IDVU-SPACEHEAT                                       
DE4-S_IDVU-SPACEHEAT                                       
DE4-W_IDVU-SPACEHEAT                                       
DK1_IDVU-SPACEHEAT                                         
DK2_IDVU-SPACEHEAT                                         
EE_IDVU-SPACEHEAT                                          
FIN_IDVU-SPACEHEAT                                         
FR_IDVU-SPACEHEAT                                          
LT_IDVU-SPACEHEAT                                          
LV_IDVU-SPACEHEAT                                          
NL_IDVU-SPACEHEAT                                          
NO1_IDVU-SPACEHEAT                                         
NO2_IDVU-SPACEHEAT                                         
NO3_IDVU-SPACEHEAT                                         
NO4_IDVU-SPACEHEAT                                         
NO5_IDVU-SPACEHEAT                                         
PL_IDVU-SPACEHEAT                                          
SE1_IDVU-SPACEHEAT                                         
SE2_IDVU-SPACEHEAT                                         
SE3_IDVU-SPACEHEAT                                         
SE4_IDVU-SPACEHEAT                                         
UK_IDVU-SPACEHEAT                                          
                                                           
                                                           
                                                           
/;                                                         
                                                           
