PARAMETER XHCOST(IAAAE,IAAAI)  "Heat transmission cost between areas (calculated from exported quantity) (Money/MWh)";     
                                                                                                                           
                                                                                                                           
XHCOST('BE_IDVU-HOTWTR','BE_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('DE4-E_IDVU-HOTWTR','DE4-E_IDVU-SPACEHEAT')=0;                                                                      
XHCOST('DE4-N_IDVU-HOTWTR','DE4-N_IDVU-SPACEHEAT')=0;                                                                      
XHCOST('DE4-S_IDVU-HOTWTR','DE4-S_IDVU-SPACEHEAT')=0;                                                                      
XHCOST('DE4-W_IDVU-HOTWTR','DE4-W_IDVU-SPACEHEAT')=0;                                                                      
XHCOST('DK1_IDVU-HOTWTR','DK1_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('DK2_IDVU-HOTWTR','DK2_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('EE_IDVU-HOTWTR','EE_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('FIN_IDVU-HOTWTR','FIN_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('FR_IDVU-HOTWTR','FR_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('LT_IDVU-HOTWTR','LT_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('LV_IDVU-HOTWTR','LV_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('NL_IDVU-HOTWTR','NL_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('NO1_IDVU-HOTWTR','NO1_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('NO2_IDVU-HOTWTR','NO2_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('NO3_IDVU-HOTWTR','NO3_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('NO4_IDVU-HOTWTR','NO4_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('NO5_IDVU-HOTWTR','NO5_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('PL_IDVU-HOTWTR','PL_IDVU-SPACEHEAT')=0;                                                                            
XHCOST('SE1_IDVU-HOTWTR','SE1_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('SE2_IDVU-HOTWTR','SE2_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('SE3_IDVU-HOTWTR','SE3_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('SE4_IDVU-HOTWTR','SE4_IDVU-SPACEHEAT')=0;                                                                          
XHCOST('UK_IDVU-HOTWTR','UK_IDVU-SPACEHEAT')=0;                                                                            
                                                                                                                           
XHCOST('BE_IDVU-SPACEHEAT','BE_IDVU-HOTWTR')=0;                                                                            
XHCOST('DE4-E_IDVU-SPACEHEAT','DE4-E_IDVU-HOTWTR')=0;                                                                      
XHCOST('DE4-N_IDVU-SPACEHEAT','DE4-N_IDVU-HOTWTR')=0;                                                                      
XHCOST('DE4-S_IDVU-SPACEHEAT','DE4-S_IDVU-HOTWTR')=0;                                                                      
XHCOST('DE4-W_IDVU-SPACEHEAT','DE4-W_IDVU-HOTWTR')=0;                                                                      
XHCOST('DK1_IDVU-SPACEHEAT','DK1_IDVU-HOTWTR')=0;                                                                          
XHCOST('DK2_IDVU-SPACEHEAT','DK2_IDVU-HOTWTR')=0;                                                                          
XHCOST('EE_IDVU-SPACEHEAT','EE_IDVU-HOTWTR')=0;                                                                            
XHCOST('FIN_IDVU-SPACEHEAT','FIN_IDVU-HOTWTR')=0;                                                                          
XHCOST('FR_IDVU-SPACEHEAT','FR_IDVU-HOTWTR')=0;                                                                            
XHCOST('LT_IDVU-SPACEHEAT','LT_IDVU-HOTWTR')=0;                                                                            
XHCOST('LV_IDVU-SPACEHEAT','LV_IDVU-HOTWTR')=0;                                                                            
XHCOST('NL_IDVU-SPACEHEAT','NL_IDVU-HOTWTR')=0;                                                                            
XHCOST('NO1_IDVU-SPACEHEAT','NO1_IDVU-HOTWTR')=0;                                                                          
XHCOST('NO2_IDVU-SPACEHEAT','NO2_IDVU-HOTWTR')=0;                                                                          
XHCOST('NO3_IDVU-SPACEHEAT','NO3_IDVU-HOTWTR')=0;                                                                          
XHCOST('NO4_IDVU-SPACEHEAT','NO4_IDVU-HOTWTR')=0;                                                                          
XHCOST('NO5_IDVU-SPACEHEAT','NO5_IDVU-HOTWTR')=0;                                                                          
XHCOST('PL_IDVU-SPACEHEAT','PL_IDVU-HOTWTR')=0;                                                                            
XHCOST('SE1_IDVU-SPACEHEAT','SE1_IDVU-HOTWTR')=0;                                                                          
XHCOST('SE2_IDVU-SPACEHEAT','SE2_IDVU-HOTWTR')=0;                                                                          
XHCOST('SE3_IDVU-SPACEHEAT','SE3_IDVU-HOTWTR')=0;                                                                          
XHCOST('SE4_IDVU-SPACEHEAT','SE4_IDVU-HOTWTR')=0;                                                                          
XHCOST('UK_IDVU-SPACEHEAT','UK_IDVU-HOTWTR')=0;                                                                            
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
                                                                                                                           
