*PARAMETER SOLHFLH(AAA)  'Full load hours for solar heat (hours)'  
* Data from https://zenodo.org/record/1146666#.Xl-shqhKguU         
                                                                   
                                                                   
                                                                   
SOLHFLH('BE_IDVU-HOTWTR')=561.986968554354;                        
SOLHFLH('DE4-E_IDVU-HOTWTR')=612.251263689368;                     
SOLHFLH('DE4-N_IDVU-HOTWTR')=612.251263689368;                     
SOLHFLH('DE4-S_IDVU-HOTWTR')=612.251263689368;                     
SOLHFLH('DE4-W_IDVU-HOTWTR')=612.251263689368;                     
SOLHFLH('DK1_IDVU-HOTWTR')=520.212001354722;                       
SOLHFLH('DK2_IDVU-HOTWTR')=520.212001354722;                       
SOLHFLH('EE_IDVU-HOTWTR')=444.791212631231;                        
SOLHFLH('FIN_IDVU-HOTWTR')=386.329175591457;                       
SOLHFLH('FR_IDVU-HOTWTR')=709.367418438484;                        
SOLHFLH('LT_IDVU-HOTWTR')=490.359980287282;                        
SOLHFLH('LV_IDVU-HOTWTR')=466.25452712218;                         
SOLHFLH('NL_IDVU-HOTWTR')=531.818287642972;                        
SOLHFLH('NO1_IDVU-HOTWTR')=423.202360176718;                       
SOLHFLH('NO2_IDVU-HOTWTR')=423.202360176718;                       
SOLHFLH('NO3_IDVU-HOTWTR')=423.202360176718;                       
SOLHFLH('NO4_IDVU-HOTWTR')=423.202360176718;                       
SOLHFLH('NO5_IDVU-HOTWTR')=423.202360176718;                       
SOLHFLH('PL_IDVU-HOTWTR')=584.952690003189;                        
SOLHFLH('SE1_IDVU-HOTWTR')=501.022626588929;                       
SOLHFLH('SE2_IDVU-HOTWTR')=501.022626588929;                       
SOLHFLH('SE3_IDVU-HOTWTR')=501.022626588929;                       
SOLHFLH('SE4_IDVU-HOTWTR')=501.022626588929;                       
SOLHFLH('UK_IDVU-HOTWTR')=455.498730490753;                        
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
