SET RRRAAA(RRR,AAA) "Areas in regions"                                                
/                                                                                     
DK1                                                                 .    DK1_Large_PHH
DK1                                                                 .    DK1_Large_PHL
DK1                                                                 .    DK1_NoDH_PHH 
DK1                                                                 .    DK1_NoDH_PHL 
DK2                                                                 .    DK2_Large_PHH
DK2                                                                 .    DK2_Large_PHL
DK2                                                                 .    DK2_NoDH_PHH 
DK2                                                                 .    DK2_NoDH_PHL 
/;                                                                                    
