SET AAA(CCCRRRAAA)  'All areas'    
/                                  
* Danish industry areas - lessAreas
DK1_Large_PHH                      
DK1_Large_PHL                      
DK1_NoDH_PHH                       
DK1_NoDH_PHL                       
DK2_Large_PHH                      
DK2_Large_PHL                      
DK2_NoDH_PHH                       
DK2_NoDH_PHL                       
/;                                 
