*SOLH_VAR_T                                                                 
SOLH_VAR_T('DK1_IND-LT',SSS,TTT)=SOLH_VAR_T('DK1_A',SSS,TTT);        
SOLH_VAR_T('DK2_IND-LT',SSS,TTT)=SOLH_VAR_T('DK1_A',SSS,TTT);      
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
