PARAMETER XHCOST(IAAAE,IAAAI)  "Heat transmission cost between areas (calculated from exported quantity) (Money/MWh)" 
*Cost of HT to LT areas has no cost since they are in the same location
/
BE_IND-HT-NODH                                                                                                          .    BE_IND-LT-NODH    0
BE_IND-HT-DH                                                                                                            .    BE_IND-LT-DH      0
DE4-E_IND-HT-NODH                                                                                                       .    DE4-E_IND-LT-NODH 0
DE4-E_IND-HT-DH                                                                                                         .    DE4-E_IND-LT-DH   0
DE4-N_IND-HT-NODH                                                                                                       .    DE4-N_IND-LT-NODH 0
DE4-N_IND-HT-DH                                                                                                         .    DE4-N_IND-LT-DH   0
DE4-S_IND-HT-NODH                                                                                                       .    DE4-S_IND-LT-NODH 0
DE4-S_IND-HT-DH                                                                                                         .    DE4-S_IND-LT-DH   0
DE4-W_IND-HT-NODH                                                                                                       .    DE4-W_IND-LT-NODH 0
DE4-W_IND-HT-DH                                                                                                         .    DE4-W_IND-LT-DH   0
DK1_IND-HT-NODH                                                                                                         .    DK1_IND-LT-NODH   0
DK1_IND-HT-DH                                                                                                           .    DK1_IND-LT-DH     0
DK2_IND-HT-NODH                                                                                                         .    DK2_IND-LT-NODH   0
DK2_IND-HT-DH                                                                                                           .    DK2_IND-LT-DH     0
EE_IND-HT-NODH                                                                                                          .    EE_IND-LT-NODH    0
EE_IND-HT-DH                                                                                                            .    EE_IND-LT-DH      0
FIN_IND-HT-NODH                                                                                                         .    FIN_IND-LT-NODH   0
FIN_IND-HT-DH                                                                                                           .    FIN_IND-LT-DH     0
FR_IND-HT-NODH                                                                                                          .    FR_IND-LT-NODH    0
FR_IND-HT-DH                                                                                                            .    FR_IND-LT-DH      0
LT_IND-HT-NODH                                                                                                          .    LT_IND-LT-NODH    0
LT_IND-HT-DH                                                                                                            .    LT_IND-LT-DH      0
LV_IND-HT-NODH                                                                                                          .    LV_IND-LT-NODH    0
LV_IND-HT-DH                                                                                                            .    LV_IND-LT-DH      0
NL_IND-HT-NODH                                                                                                          .    NL_IND-LT-NODH    0
NL_IND-HT-DH                                                                                                            .    NL_IND-LT-DH      0
NO1_IND-HT-NODH                                                                                                         .    NO1_IND-LT-NODH   0
NO1_IND-HT-DH                                                                                                           .    NO1_IND-LT-DH     0
NO2_IND-HT-NODH                                                                                                         .    NO2_IND-LT-NODH   0
NO2_IND-HT-DH                                                                                                           .    NO2_IND-LT-DH     0
NO3_IND-HT-NODH                                                                                                         .    NO3_IND-LT-NODH   0
NO3_IND-HT-DH                                                                                                           .    NO3_IND-LT-DH     0
NO4_IND-HT-NODH                                                                                                         .    NO4_IND-LT-NODH   0
NO4_IND-HT-DH                                                                                                           .    NO4_IND-LT-DH     0
NO5_IND-HT-NODH                                                                                                         .    NO5_IND-LT-NODH   0
NO5_IND-HT-DH                                                                                                           .    NO5_IND-LT-DH     0
PL_IND-HT-NODH                                                                                                          .    PL_IND-LT-NODH    0
PL_IND-HT-DH                                                                                                            .    PL_IND-LT-DH      0
SE1_IND-HT-NODH                                                                                                         .    SE1_IND-LT-NODH   0
SE1_IND-HT-DH                                                                                                           .    SE1_IND-LT-DH     0
SE2_IND-HT-NODH                                                                                                         .    SE2_IND-LT-NODH   0
SE2_IND-HT-DH                                                                                                           .    SE2_IND-LT-DH     0
SE3_IND-HT-NODH                                                                                                         .    SE3_IND-LT-NODH   0
SE3_IND-HT-DH                                                                                                           .    SE3_IND-LT-DH     0
SE4_IND-HT-NODH                                                                                                         .    SE4_IND-LT-NODH   0
SE4_IND-HT-DH                                                                                                           .    SE4_IND-LT-DH     0
UK_IND-HT-NODH                                                                                                          .    UK_IND-LT-NODH    0
UK_IND-HT-DH                                                                                                            .    UK_IND-LT-DH      0
/
;
