                                                
SET INDUSTRY_AAA(CCCRRRAAA)  'Industry areas'   
/                                               
AL_IND-HT                                       
AL_IND-LT                                       
AL_IND-MT                                       
AT_IND-HT                                       
AT_IND-LT                                       
AT_IND-MT                                       
BA_IND-HT                                       
BA_IND-LT                                       
BA_IND-MT                                       
BE_IND-HT                                       
BE_IND-LT                                       
BE_IND-MT                                       
BG_IND-HT                                       
BG_IND-LT                                       
BG_IND-MT                                       
CH_IND-HT                                       
CH_IND-LT                                       
CH_IND-MT                                       
CY_IND-HT                                       
CY_IND-LT                                       
CY_IND-MT                                       
CZ_IND-HT                                       
CZ_IND-LT                                       
CZ_IND-MT                                       
DE4-E_IND-HT                                    
DE4-E_IND-LT                                    
DE4-E_IND-MT                                    
DE4-N_IND-HT                                    
DE4-N_IND-LT                                    
DE4-N_IND-MT                                    
DE4-S_IND-HT                                    
DE4-S_IND-LT                                    
DE4-S_IND-MT                                    
DE4-W_IND-HT                                    
DE4-W_IND-LT                                    
DE4-W_IND-MT                                    
DK1_IND-HT                                      
DK1_IND-LT                                      
DK1_IND-MT                                      
DK2_IND-HT                                      
DK2_IND-LT                                      
DK2_IND-MT                                      
EE_IND-HT                                       
EE_IND-LT                                       
EE_IND-MT                                       
ES_IND-HT                                       
ES_IND-LT                                       
ES_IND-MT                                       
FIN_IND-HT                                      
FIN_IND-LT                                      
FIN_IND-MT                                      
FR_IND-HT                                       
FR_IND-LT                                       
FR_IND-MT                                       
GR_IND-HT                                       
GR_IND-LT                                       
GR_IND-MT                                       
HR_IND-HT                                       
HR_IND-LT                                       
HR_IND-MT                                       
HU_IND-HT                                       
HU_IND-LT                                       
HU_IND-MT                                       
IE_IND-HT                                       
IE_IND-LT                                       
IE_IND-MT                                       
IT_IND-HT                                       
IT_IND-LT                                       
IT_IND-MT                                       
LT_IND-HT                                       
LT_IND-LT                                       
LT_IND-MT                                       
LU_IND-HT                                       
LU_IND-LT                                       
LU_IND-MT                                       
LV_IND-HT                                       
LV_IND-LT                                       
LV_IND-MT                                       
ME_IND-HT                                       
ME_IND-LT                                       
ME_IND-MT                                       
MK_IND-HT                                       
MK_IND-LT                                       
MK_IND-MT                                       
MT_IND-HT                                       
MT_IND-LT                                       
MT_IND-MT                                       
NL_IND-HT                                       
NL_IND-LT                                       
NL_IND-MT                                       
NO1_IND-HT                                      
NO1_IND-LT                                      
NO1_IND-MT                                      
NO2_IND-HT                                      
NO2_IND-LT                                      
NO2_IND-MT                                      
NO3_IND-HT                                      
NO3_IND-LT                                      
NO3_IND-MT                                      
NO4_IND-HT                                      
NO4_IND-LT                                      
NO4_IND-MT                                      
NO5_IND-HT                                      
NO5_IND-LT                                      
NO5_IND-MT                                      
PL_IND-HT                                       
PL_IND-LT                                       
PL_IND-MT                                       
PT_IND-HT                                       
PT_IND-LT                                       
PT_IND-MT                                       
RO_IND-HT                                       
RO_IND-LT                                       
RO_IND-MT                                       
RS_IND-HT                                       
RS_IND-LT                                       
RS_IND-MT                                       
SE1_IND-HT                                      
SE1_IND-LT                                      
SE1_IND-MT                                      
SE2_IND-HT                                      
SE2_IND-LT                                      
SE2_IND-MT                                      
SE3_IND-HT                                      
SE3_IND-LT                                      
SE3_IND-MT                                      
SE4_IND-HT                                      
SE4_IND-LT                                      
SE4_IND-MT                                      
SI_IND-HT                                       
SI_IND-LT                                       
SI_IND-MT                                       
SK_IND-HT                                       
SK_IND-LT                                       
SK_IND-MT                                       
TR_IND-HT                                       
TR_IND-LT                                       
TR_IND-MT                                       
UK_IND-HT                                       
UK_IND-LT                                       
UK_IND-MT                                       
                                                
/;                                              
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
