SET LIMITSFORFUELS_VGFMAXSET(LIMITSFORFUELS_NUMCONMAX,CCCRRRAAA,FFF) 'Sets of which a combination of maxima are set'      
/                                                                                                                         
/                                                                                                                         
;                                                                                                                         
LIMITSFORFUELS_VGFMAXSET(LIMITSFORFUELS_NUMCONMAX,C,FFF)=LIMITSFORFUELS_VGFMAXSET(LIMITSFORFUELS_NUMCONMAX,'DENMARK',FFF);
