* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       40(Sheet53)
* Range:       $A$10:$I$15
* -----------------------------------------------------
TABLE M_POLNA(YYY,MPOLSET)  "Emission policy data; default for the 'LIM_' entries: 0 implies irrelevant, EPS implies no emission permitted (aggerated countries)"                                      
                                                                                                                                                                                                       
*                                                                                                                                                                 LIM_CO2    LIM_SO2    LIM_NOX        
* Units:                                                                                                                                                          t CO2/year t SO2/year t NOx/year     
*2012                                                                                                                                                                                                  
;                                                                                                                                                                                                      
* -----------------------------------------------------
