TABLE M_POL(YYY,MPOLSET,CCC)  'Emission policy data'                                                                                                                                  
                                                                                                                                                                                      
                                                     LIM_CO2.DENMARK        LIM_SO2.DENMARK        LIM_NOX.DENMARK                                                                    
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.DENMARK        TAX_SO2.DENMARK        TAX_NOX.DENMARK                                                                    
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox            /*   Without increase (IEA scenario) PRIMES-scenarios */    
2012                                                 8                      0                                             /*   8                8              8                */    
2013                                                 8                      0                                             /*   8                12             8                */    
2014                                                 8                      0                                             /*   8                16             8                */    
2015                                                 5                      0                                             /*   8                20             5                */    
2016                                                 5                      0                                             /*   8                22             5                */    
2017                                                 5                      0                                             /*   8                24             5                */    
2018                                                 5                      0                                             /*   8                26             5                */    
2019                                                 5                      0                                             /*   8                28             5                */    
2020                                                 10                     0                                             /*   8                30             10               */    
2021                                                 10                     0                                             /*   8                31             10               */    
2022                                                 10                     0                                             /*   8                32             10               */    
2023                                                 10                     0                                             /*   8                33             10               */    
2024                                                 10                     0                                             /*   8                34             10               */    
2025                                                 14                     0                                             /*   8                35             14               */    
2026                                                 14                     0                                             /*   8                36             14               */    
2027                                                 14                     0                                             /*   8                37             14               */    
2028                                                 14                     0                                             /*   8                38             14               */    
2029                                                 35                     0                                             /*   8                39             35               */    
2030                                                 35                     0                                             /*   8                40             35               */    
* 2031                                                                      0                                             /*   8                41                              */    
* 2032                                                                      0                                             /*   8                42                              */    
* 2033                                                                      0                                             /*   8                43                              */    
* 2034                                                                      0                                             /*   8                44                              */    
* 2035                                                                      0                                             /*   8                45                              */    
                                                                                                                                                                                      
+                                                    LIM_CO2.FINLAND        LIM_SO2.FINLAND        LIM_NOX.FINLAND                                                                    
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.FINLAND        TAX_SO2.FINLAND        TAX_NOX.FINLAND                                                                    
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
+                                                    LIM_CO2.GERMANY        LIM_SO2.GERMANY        LIM_NOX.GERMANY                                                                    
*                                                    t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.GERMANY        TAX_SO2.GERMANY        TAX_NOX.GERMANY                                                                    
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
+                                                    LIM_CO2.NETHERLANDS    LIM_SO2.NETHERLANDS    LIM_NOX.NETHERLANDS                                                                
*                                                    t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.NETHERLANDS    TAX_SO2.NETHERLANDS    TAX_NOX.NETHERLANDS                                                                
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
+                                                    LIM_CO2.NORWAY         LIM_SO2.NORWAY         LIM_NOX.NORWAY                                                                     
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.NORWAY         TAX_SO2.NORWAY         TAX_NOX.NORWAY                                                                     
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
+                                                    LIM_CO2.SWEDEN         LIM_SO2.SWEDEN         LIM_NOX.SWEDEN                                                                     
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.SWEDEN         TAX_SO2.SWEDEN         TAX_NOX.SWEDEN                                                                     
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
+                                                    LIM_CO2.UNITED_KINGDOM LIM_SO2.UNITED_KINGDOM LIM_NOX.UNITED_KINGDOM                                                             
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
2028                                                 INF                    INF                    INF                                                                                
2029                                                 INF                    INF                    INF                                                                                
2030                                                 INF                    INF                    INF                                                                                
* 2031                                               INF                    INF                    INF                                                                                
* 2032                                               INF                    INF                    INF                                                                                
* 2033                                               INF                    INF                    INF                                                                                
* 2034                                               INF                    INF                    INF                                                                                
* 2035                                               INF                    INF                    INF                                                                                
                                                                                                                                                                                      
+                                                    TAX_CO2.UNITED_KINGDOM TAX_SO2.UNITED_KINGDOM TAX_NOX.UNITED_KINGDOM                                                             
* Units:                                             EUR12/t CO2            EUR90/t SO2            EUR90/t Nox                                                                        
2012                                                 8                      0                                                                                                         
2013                                                 8                      0                                                                                                         
2014                                                 8                      0                                                                                                         
2015                                                 5                      0                                                                                                         
2016                                                 5                      0                                                                                                         
2017                                                 5                      0                                                                                                         
2018                                                 5                      0                                                                                                         
2019                                                 5                      0                                                                                                         
2020                                                 10                     0                                                                                                         
2021                                                 10                     0                                                                                                         
2022                                                 10                     0                                                                                                         
2023                                                 10                     0                                                                                                         
2024                                                 10                     0                                                                                                         
2025                                                 14                     0                                                                                                         
2026                                                 14                     0                                                                                                         
2027                                                 14                     0                                                                                                         
2028                                                 14                     0                                                                                                         
2029                                                 35                     0                                                                                                         
2030                                                 35                     0                                                                                                         
* 2031                                               0                      0                                                                                                         
* 2032                                               0                      0                                                                                                         
* 2033                                               0                      0                                                                                                         
* 2034                                               0                      0                                                                                                         
* 2035                                               0                      0                                                                                                         
                                                                                                                                                                                      
                                                                                                                                                                                      
+                                                    LIM_CO2.ESTONIA        LIM_SO2.ESTONIA        LIM_NOX.ESTONIA                                                                    
* Units:                                             t CO2/year             t SO2/year             t NOx/year                                                                         
2012                                                 INF                    INF                    INF                                                                                
2013                                                 INF                    INF                    INF                                                                                
2014                                                 INF                    INF                    INF                                                                                
2015                                                 INF                    INF                    INF                                                                                
2016                                                 INF                    INF                    INF                                                                                
2017                                                 INF                    INF                    INF                                                                                
2018                                                 INF                    INF                    INF                                                                                
2019                                                 INF                    INF                    INF                                                                                
2020                                                 INF                    INF                    INF                                                                                
2021                                                 INF                    INF                    INF                                                                                
2022                                                 INF                    INF                    INF                                                                                
2023                                                 INF                    INF                    INF                                                                                
2024                                                 INF                    INF                    INF                                                                                
2025                                                 INF                    INF                    INF                                                                                
2026                                                 INF                    INF                    INF                                                                                
2027                                                 INF                    INF                    INF                                                                                
