* -----------------------------------------------------
* XLS2GMS Version 1.5,  August 2002
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    \\nmbu.no\my\home\Documents\Prosjekter\Flex4RES\taxes\Grid_rent_data.xlsx
* Sheet:       MMM
* Range:       $A$1:$A$2
* -----------------------------------------------------
SET MMM 'Month'
/1*12/;
* -----------------------------------------------------
