* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       09(Sheet12)
* Range:       $A$22:$A$30
* -----------------------------------------------------
SET MPOLSET  'Emission and other policy data'
/                                            
TAX_CO2  'CO2 emission tax (Euro/t CO2)'     
TAX_SO2  'SO2 emission tax (Euro/t SO2)'     
TAX_NOx  'NOx emission tax (Euro/kg NOx)'    
LIM_CO2  'Annual CO2 limit (t CO2/year)'     
LIM_SO2  'Annual SO2 limit (t SO2/year)'     
LIM_NOx  'Annual NOx limit(kg NOx/year)'     
/;                                           
* -----------------------------------------------------
