TABLE SUBTECHGROUPKPOT(CCCRRRAAA,TECH_GROUP,SUBTECH_GROUP)       'SubTechnology group capacity restriction by geography (MW)'                                                            
                                                                                                                              WINDTURBINE_OFFSHORE.HUB_OFF                               
31_DE_OFF_2_Hub_BorWin                                                                                                        7010.8                                                     
93_UK_OFF_2_Hub_DoggerBank_e                                                                                                  4800                                                       
93_UK_OFF_2_Hub_DoggerBank_w                                                                                                  4800                                                       
31_DE_OFF_2_Hub_DolWin                                                                                                        2756.2                                                     
31_DE_OFF_2_Hub_HelWin                                                                                                        1077                                                       
93_UK_OFF_2_Hub_HornSea_e                                                                                                     2400                                                       
93_UK_OFF_2_Hub_HornSea_w                                                                                                     2800                                                       
NSY_OFF_2_Hub_NO_c                                                                                                            2000                                                       
NSY_OFF_2_Hub_NO_e                                                                                                            2000                                                       
NSY_OFF_2_Hub_NO_w                                                                                                            2000                                                       
31_DE_OFF_2_Hub_NorWin                                                                                                        11257                                                      
31_DE_OFF_2_Hub_SylWin                                                                                                        1264                                                       
NL3_OFF_2_Hub_UKandNL_e                                                                                                       8700                                                       
90_UK_OFF_2_Hub_UKandNL_w                                                                                                     4800                                                       
31_DE_OFF_2_Hub_WeiWin                                                                                                        8556                                                       
DK_w_OFF_2_Hub_DK_hub                                                                                                         2000                                                       
                                                                                                                                                                                         
;                                                                                                                                                                                        
                                                                                                                                                                                         
*Lines when simplified set is used                                                                                                                                                       
SUBTECHGROUPKPOT(CCCRRRAAA,'WINDTURBINE_OFFSHORE','HUB_OFF')=0;                                                                                                                          
                                                                                                                                                                                         
                                                                                                                                                                                         
                                                                                                                                                                                         
                                                                                                                                                                                         
                                                                                                                                                                                         
