SET CCCRRR(CCC,RRR) "Regions in countries"                                                
/                                                                                         
GERMANY                                                .    31_DE_OFF_2_Hub_BorWin        
UNITED_KINGDOM                                         .    93_UK_OFF_2_Hub_DoggerBank_e  
UNITED_KINGDOM                                         .    93_UK_OFF_2_Hub_DoggerBank_w  
GERMANY                                                .    31_DE_OFF_2_Hub_DolWin        
GERMANY                                                .    31_DE_OFF_2_Hub_HelWin        
UNITED_KINGDOM                                         .    93_UK_OFF_2_Hub_HornSea_e     
UNITED_KINGDOM                                         .    93_UK_OFF_2_Hub_HornSea_w     
NORWAY                                                 .    NSY_OFF_2_Hub_NO_c            
NORWAY                                                 .    NSY_OFF_2_Hub_NO_e            
NORWAY                                                 .    NSY_OFF_2_Hub_NO_w            
GERMANY                                                .    31_DE_OFF_2_Hub_NorWin        
GERMANY                                                .    31_DE_OFF_2_Hub_SylWin        
NETHERLANDS                                            .    NL3_OFF_2_Hub_UKandNL_e       
UNITED_KINGDOM                                         .    90_UK_OFF_2_Hub_UKandNL_w     
GERMANY                                                .    31_DE_OFF_2_Hub_WeiWin        
DENMARK                                                .    DK_w_OFF_2_Hub_DK_hub         
/;                                                                                        
