SET RRRAAA(RRR,AAA) 'Areas in regions'
/
Esbjerg . Esbjerg_OFF
Haderslev . Haderslev_OFF
Soenderborg . Soenderborg_OFF
Ringkoebing-Skjern . Ringkoebing-Skjern_OFF
Varde . Varde_OFF
Lemvig . Lemvig_OFF
Frederikshavn . Frederikshavn_OFF
Norddjurs . Norddjurs_OFF
Norddjurs . Norddjurs_OFF2
Norddjurs . Norddjurs_OFF3
Halsnaes . Halsnaes_OFF
Aarhus . Aarhus_OFF
Samsoe . Samsoe_OFF
Kalundborg . Kalundborg_OFF
Lolland . Lolland_OFF
Lolland . Lolland_OFF2
Lolland . Lolland_OFF3
Vordingborg . Vordingborg_OFF1
Vordingborg . Vordingborg_OFF2
Vordingborg . Vordingborg_OFF3
Vordingborg . Vordingborg_OFF4
Stevns . Stevns_OFF
Stevns . Stevns_OFF2
Bornholm . Bornholm_OFF1
Bornholm . Bornholm_OFF2
Bornholm . Bornholm_OFF3
Esbjerg . Esbjerg_OFF5
Holstebro . Holstebro_OFF5
/;