* Parameters that hold the yearly number of full load hours for different technologies                  
* Updated for areas, but very rough number used!                                                        
                                                                                                        
                                                                                                        
                                                                                                        
PARAMETER WNDFLH(AAA)  'Full load hours for wind power (hours)'                                         
/                                                                                                       
31_DE_OFF_2_Hub_BorWin_2020                                                            4600.97223286789 
93_UK_OFF_2_Hub_DoggerBank_e_2020                                                      4700.51120009909 
93_UK_OFF_2_Hub_DoggerBank_w_2020                                                      4700.51120009909 
31_DE_OFF_2_Hub_DolWin_2020                                                            4558.76612596787 
31_DE_OFF_2_Hub_HelWin_2020                                                            4597.6365335002  
93_UK_OFF_2_Hub_HornSea_e_2020                                                         4666.42971064688 
93_UK_OFF_2_Hub_HornSea_w_2020                                                         4666.42971064688 
NSY_OFF_2_Hub_NO_c_2020                                                                4826.35144358407 
NSY_OFF_2_Hub_NO_e_2020                                                                4850.60706907515 
NSY_OFF_2_Hub_NO_w_2020                                                                4802.09590053041 
31_DE_OFF_2_Hub_NorWin_2020                                                            4667.15154609822 
31_DE_OFF_2_Hub_SylWin_2020                                                            4680.96073023485 
NL3_OFF_2_Hub_UKandNL_e_2020                                                           4489.97037651106 
90_UK_OFF_2_Hub_UKandNL_w_2020                                                         4535.70340188464 
31_DE_OFF_2_Hub_WeiWin_2020                                                            4646.60895890563 
DK_w_OFF_2_Hub_DK_hub_2020                                                             4566.50547129419 
31_DE_OFF_2_Hub_BorWin_2030                                                            4703.07693473616 
93_UK_OFF_2_Hub_DoggerBank_e_2030                                                      4799.64342252841 
93_UK_OFF_2_Hub_DoggerBank_w_2030                                                      4799.64342252841 
31_DE_OFF_2_Hub_DolWin_2030                                                            4662.92959496764 
31_DE_OFF_2_Hub_HelWin_2030                                                            4701.61714009119 
93_UK_OFF_2_Hub_HornSea_e_2030                                                         4763.31347137872 
93_UK_OFF_2_Hub_HornSea_w_2030                                                         4763.31347137872 
NSY_OFF_2_Hub_NO_c_2030                                                                4926.51242884482 
NSY_OFF_2_Hub_NO_e_2030                                                                4951.72666052925 
NSY_OFF_2_Hub_NO_w_2030                                                                4901.29819716038 
31_DE_OFF_2_Hub_NorWin_2030                                                            4768.9533815627  
31_DE_OFF_2_Hub_SylWin_2030                                                            4784.05358674305 
NL3_OFF_2_Hub_UKandNL_e_2030                                                           4589.88970799075 
90_UK_OFF_2_Hub_UKandNL_w_2030                                                         4633.70549940863 
31_DE_OFF_2_Hub_WeiWin_2030                                                            4749.01447753676 
DK_w_OFF_2_Hub_DK_hub_2030                                                             4682.07411058969 
31_DE_OFF_2_Hub_BorWin_2040                                                            4807.44754250778 
93_UK_OFF_2_Hub_DoggerBank_e_2040                                                      4900.8663106546  
93_UK_OFF_2_Hub_DoggerBank_w_2040                                                      4900.8663106546  
31_DE_OFF_2_Hub_DolWin_2040                                                            4769.47310013823 
31_DE_OFF_2_Hub_HelWin_2040                                                            4807.94938245595 
93_UK_OFF_2_Hub_HornSea_e_2040                                                         4862.20871919503 
93_UK_OFF_2_Hub_HornSea_w_2040                                                         4862.20871919503 
NSY_OFF_2_Hub_NO_c_2040                                                                5028.75204909219 
NSY_OFF_2_Hub_NO_e_2040                                                                5054.95427096535 
NSY_OFF_2_Hub_NO_w_2040                                                                5002.54982721903 
31_DE_OFF_2_Hub_NorWin_2040                                                            4872.97576067175 
31_DE_OFF_2_Hub_SylWin_2040                                                            4889.41694661061 
NL3_OFF_2_Hub_UKandNL_e_2040                                                           4692.03263382989 
90_UK_OFF_2_Hub_UKandNL_w_2040                                                         4733.82510997704 
31_DE_OFF_2_Hub_WeiWin_2040                                                            4853.67688723378 
DK_w_OFF_2_Hub_DK_hub_2040                                                             4800.56754883102 
31_DE_OFF_2_Hub_BorWin_2050                                                            4911.8181502794  
93_UK_OFF_2_Hub_DoggerBank_e_2050                                                      5002.08919878079 
93_UK_OFF_2_Hub_DoggerBank_w_2050                                                      5002.08919878079 
31_DE_OFF_2_Hub_DolWin_2050                                                            4876.01660530882 
31_DE_OFF_2_Hub_HelWin_2050                                                            4914.28162482072 
93_UK_OFF_2_Hub_HornSea_e_2050                                                         4961.10396701133 
93_UK_OFF_2_Hub_HornSea_w_2050                                                         4961.10396701133 
NSY_OFF_2_Hub_NO_c_2050                                                                5130.99166933956 
NSY_OFF_2_Hub_NO_e_2050                                                                5158.18188140145 
NSY_OFF_2_Hub_NO_w_2050                                                                5103.80145727767 
31_DE_OFF_2_Hub_NorWin_2050                                                            4976.9981397808  
31_DE_OFF_2_Hub_SylWin_2050                                                            4994.78030647817 
NL3_OFF_2_Hub_UKandNL_e_2050                                                           4794.17555966904 
90_UK_OFF_2_Hub_UKandNL_w_2050                                                         4833.94472054544 
31_DE_OFF_2_Hub_WeiWin_2050                                                            4958.33929693081 
DK_w_OFF_2_Hub_DK_hub_2050                                                             4919.06098707236 
                                                                                                        
/;                                                                                                      
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
