* Parameters that hold the yearly number of full load hours for different technologies                  
* Updated for areas, but very rough number used!                                                        
                                                                                                        
                                                                                                        
                                                                                                        
PARAMETER WNDFLH(AAA)  'Full load hours for wind power (hours)'                                         
/                                                                                                       
31_DE_OFF_2_Hub_BorWin_RG1_2020                                                        4600.97223286789 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2020                                                  4700.51120009909 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020                                                  4700.51120009909 
31_DE_OFF_2_Hub_DolWin_RG1_2020                                                        4558.76612596787 
31_DE_OFF_2_Hub_HelWin_RG1_2020                                                        4597.6365335002  
93_UK_OFF_2_Hub_HornSea_e_RG1_2020                                                     4666.42971064688 
93_UK_OFF_2_Hub_HornSea_w_RG1_2020                                                     4666.42971064688 
NSY_OFF_2_Hub_NO_c_RG1_2020                                                            4826.35144358407 
NSY_OFF_2_Hub_NO_e_RG1_2020                                                            4850.60706907515 
NSY_OFF_2_Hub_NO_w_RG1_2020                                                            4802.09590053041 
31_DE_OFF_2_Hub_NorWin_RG1_2020                                                        4667.15154609822 
31_DE_OFF_2_Hub_SylWin_RG1_2020                                                        4680.96073023485 
NL3_OFF_2_Hub_UKandNL_e_RG1_2020                                                       4489.97037651106 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2020                                                     4535.70340188464 
31_DE_OFF_2_Hub_WeiWin_RG1_2020                                                        4646.60895890563 
DK_w_OFF_2_Hub_DK_hub_RG1_2020                                                         4566.50547129419 
31_DE_OFF_2_Hub_BorWin_RG1_2030                                                        4703.07693473616 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2030                                                  4799.64342252841 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030                                                  4799.64342252841 
31_DE_OFF_2_Hub_DolWin_RG1_2030                                                        4662.92959496764 
31_DE_OFF_2_Hub_HelWin_RG1_2030                                                        4701.61714009119 
93_UK_OFF_2_Hub_HornSea_e_RG1_2030                                                     4763.31347137872 
93_UK_OFF_2_Hub_HornSea_w_RG1_2030                                                     4763.31347137872 
NSY_OFF_2_Hub_NO_c_RG1_2030                                                            4926.51242884482 
NSY_OFF_2_Hub_NO_e_RG1_2030                                                            4951.72666052925 
NSY_OFF_2_Hub_NO_w_RG1_2030                                                            4901.29819716038 
31_DE_OFF_2_Hub_NorWin_RG1_2030                                                        4768.9533815627  
31_DE_OFF_2_Hub_SylWin_RG1_2030                                                        4784.05358674305 
NL3_OFF_2_Hub_UKandNL_e_RG1_2030                                                       4589.88970799075 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2030                                                     4633.70549940863 
31_DE_OFF_2_Hub_WeiWin_RG1_2030                                                        4749.01447753676 
DK_w_OFF_2_Hub_DK_hub_RG1_2030                                                         4682.07411058969 
31_DE_OFF_2_Hub_BorWin_RG1_2040                                                        4807.44754250778 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2040                                                  4900.8663106546  
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040                                                  4900.8663106546  
31_DE_OFF_2_Hub_DolWin_RG1_2040                                                        4769.47310013823 
31_DE_OFF_2_Hub_HelWin_RG1_2040                                                        4807.94938245595 
93_UK_OFF_2_Hub_HornSea_e_RG1_2040                                                     4862.20871919503 
93_UK_OFF_2_Hub_HornSea_w_RG1_2040                                                     4862.20871919503 
NSY_OFF_2_Hub_NO_c_RG1_2040                                                            5028.75204909219 
NSY_OFF_2_Hub_NO_e_RG1_2040                                                            5054.95427096535 
NSY_OFF_2_Hub_NO_w_RG1_2040                                                            5002.54982721903 
31_DE_OFF_2_Hub_NorWin_RG1_2040                                                        4872.97576067175 
31_DE_OFF_2_Hub_SylWin_RG1_2040                                                        4889.41694661061 
NL3_OFF_2_Hub_UKandNL_e_RG1_2040                                                       4692.03263382989 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2040                                                     4733.82510997704 
31_DE_OFF_2_Hub_WeiWin_RG1_2040                                                        4853.67688723378 
DK_w_OFF_2_Hub_DK_hub_RG1_2040                                                         4800.56754883102 
31_DE_OFF_2_Hub_BorWin_RG1_2050                                                        4911.8181502794  
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2050                                                  5002.08919878079 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050                                                  5002.08919878079 
31_DE_OFF_2_Hub_DolWin_RG1_2050                                                        4876.01660530882 
31_DE_OFF_2_Hub_HelWin_RG1_2050                                                        4914.28162482072 
93_UK_OFF_2_Hub_HornSea_e_RG1_2050                                                     4961.10396701133 
93_UK_OFF_2_Hub_HornSea_w_RG1_2050                                                     4961.10396701133 
NSY_OFF_2_Hub_NO_c_RG1_2050                                                            5130.99166933956 
NSY_OFF_2_Hub_NO_e_RG1_2050                                                            5158.18188140145 
NSY_OFF_2_Hub_NO_w_RG1_2050                                                            5103.80145727767 
31_DE_OFF_2_Hub_NorWin_RG1_2050                                                        4976.9981397808  
31_DE_OFF_2_Hub_SylWin_RG1_2050                                                        4994.78030647817 
NL3_OFF_2_Hub_UKandNL_e_RG1_2050                                                       4794.17555966904 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2050                                                     4833.94472054544 
31_DE_OFF_2_Hub_WeiWin_RG1_2050                                                        4958.33929693081 
DK_w_OFF_2_Hub_DK_hub_RG1_2050                                                         4919.06098707236 
                                                                                                        
31_DE_OFF_2_Hub_BorWin_RG2_2020                                                        3726.78750862299 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2020                                                  3807.41407208026 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2020                                                  3807.41407208026 
31_DE_OFF_2_Hub_DolWin_RG2_2020                                                        3692.60056203397 
31_DE_OFF_2_Hub_HelWin_RG2_2020                                                        3724.08559213516 
93_UK_OFF_2_Hub_HornSea_e_RG2_2020                                                     3779.80806562397 
93_UK_OFF_2_Hub_HornSea_w_RG2_2020                                                     3779.80806562397 
NSY_OFF_2_Hub_NO_c_RG2_2020                                                            3909.3446693031  
NSY_OFF_2_Hub_NO_e_RG2_2020                                                            3928.99172595087 
NSY_OFF_2_Hub_NO_w_RG2_2020                                                            3889.69767942964 
31_DE_OFF_2_Hub_NorWin_RG2_2020                                                        3780.39275233956 
31_DE_OFF_2_Hub_SylWin_RG2_2020                                                        3791.57819149023 
NL3_OFF_2_Hub_UKandNL_e_RG2_2020                                                       3636.87600497396 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2020                                                     3673.91975552656 
31_DE_OFF_2_Hub_WeiWin_RG2_2020                                                        3763.75325671356 
DK_w_OFF_2_Hub_DK_hub_RG2_2020                                                         3698.86943174829 
31_DE_OFF_2_Hub_BorWin_RG2_2030                                                        3809.49231713629 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2030                                                  3887.71117224801 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2030                                                  3887.71117224801 
31_DE_OFF_2_Hub_DolWin_RG2_2030                                                        3776.97297192379 
31_DE_OFF_2_Hub_HelWin_RG2_2030                                                        3808.30988347386 
93_UK_OFF_2_Hub_HornSea_e_RG2_2030                                                     3858.28391181676 
93_UK_OFF_2_Hub_HornSea_w_RG2_2030                                                     3858.28391181676 
NSY_OFF_2_Hub_NO_c_RG2_2030                                                            3990.4750673643  
NSY_OFF_2_Hub_NO_e_RG2_2030                                                            4010.89859502869 
NSY_OFF_2_Hub_NO_w_RG2_2030                                                            3970.05153969991 
31_DE_OFF_2_Hub_NorWin_RG2_2030                                                        3862.85223906578 
31_DE_OFF_2_Hub_SylWin_RG2_2030                                                        3875.08340526187 
NL3_OFF_2_Hub_UKandNL_e_RG2_2030                                                       3717.8106634725  
90_UK_OFF_2_Hub_UKandNL_w_RG2_2030                                                     3753.30145452099 
31_DE_OFF_2_Hub_WeiWin_RG2_2030                                                        3846.70172680477 
DK_w_OFF_2_Hub_DK_hub_RG2_2030                                                         3792.48002957765 
31_DE_OFF_2_Hub_BorWin_RG2_2040                                                        3894.0325094313  
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2040                                                  3969.70171163023 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2040                                                  3969.70171163023 
31_DE_OFF_2_Hub_DolWin_RG2_2040                                                        3863.27321111197 
31_DE_OFF_2_Hub_HelWin_RG2_2040                                                        3894.43899978932 
93_UK_OFF_2_Hub_HornSea_e_RG2_2040                                                     3938.38906254797 
93_UK_OFF_2_Hub_HornSea_w_RG2_2040                                                     3938.38906254797 
NSY_OFF_2_Hub_NO_c_RG2_2040                                                            4073.28915976467 
NSY_OFF_2_Hub_NO_e_RG2_2040                                                            4094.51295948193 
NSY_OFF_2_Hub_NO_w_RG2_2040                                                            4052.06536004741 
31_DE_OFF_2_Hub_NorWin_RG2_2040                                                        3947.11036614412 
31_DE_OFF_2_Hub_SylWin_RG2_2040                                                        3960.42772675459 
NL3_OFF_2_Hub_UKandNL_e_RG2_2040                                                       3800.54643340221 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2040                                                     3834.3983390814  
31_DE_OFF_2_Hub_WeiWin_RG2_2040                                                        3931.47827865936 
DK_w_OFF_2_Hub_DK_hub_RG2_2040                                                         3888.45971455313 
31_DE_OFF_2_Hub_BorWin_RG2_2050                                                        3978.57270172632 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2050                                                  4051.69225101244 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2050                                                  4051.69225101244 
31_DE_OFF_2_Hub_DolWin_RG2_2050                                                        3949.57345030014 
31_DE_OFF_2_Hub_HelWin_RG2_2050                                                        3980.56811610478 
93_UK_OFF_2_Hub_HornSea_e_RG2_2050                                                     4018.49421327918 
93_UK_OFF_2_Hub_HornSea_w_RG2_2050                                                     4018.49421327918 
NSY_OFF_2_Hub_NO_c_RG2_2050                                                            4156.10325216505 
NSY_OFF_2_Hub_NO_e_RG2_2050                                                            4178.12732393518 
NSY_OFF_2_Hub_NO_w_RG2_2050                                                            4134.07918039492 
31_DE_OFF_2_Hub_NorWin_RG2_2050                                                        4031.36849322245 
31_DE_OFF_2_Hub_SylWin_RG2_2050                                                        4045.77204824732 
NL3_OFF_2_Hub_UKandNL_e_RG2_2050                                                       3883.28220333192 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2050                                                     3915.49522364181 
31_DE_OFF_2_Hub_WeiWin_RG2_2050                                                        4016.25483051396 
DK_w_OFF_2_Hub_DK_hub_RG2_2050                                                         3984.43939952861 
                                                                                                        
                                                                                                        
/;                                                                                                      
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
