SET AGKN(AAA,GGG) "Areas for possible location of new technologies";                                                                                                                    
$ontext                                                                                                                                                                                 
*Original                                                                                                                                                                               
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                              
AGKN('31_DE_OFF_2_Hub_DolWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_HelWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_c_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('31_DE_OFF_2_Hub_SylWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                 
AGKN('31_DE_OFF_2_Hub_WeiWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                             
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                  
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                             
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                  
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                             
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                  
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                             
AGKN('31_DE_OFF_2_Hub_DolWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_HelWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_HornSea_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_c_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('31_DE_OFF_2_Hub_SylWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                  
AGKN('90_UK_OFF_2_Hub_UKandNL_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                
AGKN('31_DE_OFF_2_Hub_WeiWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                    
$offtext                                                                                                                                                                                
                                                                                                                                                                                        
                                                                                                                                                                                        
*$ontext                                                                                                                                                                                
*Reducing number of options                                                                                                                                                             
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2020')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2020','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2020')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2030')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2030','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2030')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2040')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2040','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2040')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                    
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                              
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                 
AGKN('NSY_OFF_2_Hub_NO_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('NSY_OFF_2_Hub_NO_w_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                        
AGKN('31_DE_OFF_2_Hub_NorWin_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-30M_Y-2050')=YES;                                                                                                    
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                   
AGKN('DK_w_OFF_2_Hub_DK_hub_RG3_2050','GNR_WT_WIND_OFF_HUB_RG3_SD-20M_Y-2050')=YES;                                                                                                     
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                  
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                  
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                  
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                                                                                                    
                                                                                                                                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                             
AGKN('93_UK_OFF_2_Hub_HornSea_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                
AGKN('NSY_OFF_2_Hub_NO_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                       
AGKN('NSY_OFF_2_Hub_NO_w_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                       
AGKN('31_DE_OFF_2_Hub_NorWin_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                   
AGKN('NL3_OFF_2_Hub_UKandNL_e_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                  
AGKN('DK_w_OFF_2_Hub_DK_hub_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                                                                                                    
*$offtext                                                                                                                                                                               
                                                                                                                                                                                        
AGKN('DE_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' DE_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('DK_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' DK_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('DK_hub_2_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' DK_hub_2_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('DK_hub_3_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' DK_hub_3_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('EE_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' EE_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('EE_hub_2_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' EE_hub_2_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('FI_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' FI_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('FI_hub_2_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' FI_hub_2_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('FI_hub_3_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' FI_hub_3_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('FI_hub_4_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' FI_hub_4_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('LT_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' LT_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('LV_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' LV_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('LV_hub_2_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' LV_hub_2_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('PL_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' PL_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('SE_hub_1_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' SE_hub_1_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('SE_hub_2_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' SE_hub_2_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('SE_hub_3_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' SE_hub_3_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
AGKN('SE_hub_4_RG1_2020','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020')=YES;                      /*   AGKN(' SE_hub_4_RG1_2020 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2020        ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' DE_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('DK_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' DK_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('DK_hub_2_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' DK_hub_2_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('DK_hub_3_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' DK_hub_3_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('EE_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' EE_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('EE_hub_2_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' EE_hub_2_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('FI_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' FI_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('FI_hub_2_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' FI_hub_2_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('FI_hub_3_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' FI_hub_3_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('FI_hub_4_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' FI_hub_4_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('LT_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' LT_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('LV_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' LV_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('LV_hub_2_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' LV_hub_2_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('PL_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' PL_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('SE_hub_1_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' SE_hub_1_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('SE_hub_2_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' SE_hub_2_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('SE_hub_3_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' SE_hub_3_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
AGKN('SE_hub_4_RG1_2030','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030')=YES;                      /*   AGKN(' SE_hub_4_RG1_2030 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2030        ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' DE_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('DK_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' DK_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('DK_hub_2_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' DK_hub_2_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('DK_hub_3_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' DK_hub_3_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('EE_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' EE_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('EE_hub_2_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' EE_hub_2_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('FI_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' FI_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('FI_hub_2_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' FI_hub_2_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('FI_hub_3_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' FI_hub_3_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('FI_hub_4_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' FI_hub_4_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('LT_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' LT_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('LV_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' LV_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('LV_hub_2_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' LV_hub_2_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('PL_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' PL_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('SE_hub_1_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' SE_hub_1_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('SE_hub_2_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' SE_hub_2_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('SE_hub_3_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' SE_hub_3_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
AGKN('SE_hub_4_RG1_2040','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040')=YES;                      /*   AGKN(' SE_hub_4_RG1_2040 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2040        ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' DE_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('DK_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' DK_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('DK_hub_2_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' DK_hub_2_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('DK_hub_3_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' DK_hub_3_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('EE_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' EE_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('EE_hub_2_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' EE_hub_2_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('FI_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' FI_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('FI_hub_2_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' FI_hub_2_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('FI_hub_3_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' FI_hub_3_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('FI_hub_4_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' FI_hub_4_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('LT_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' LT_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('LV_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' LV_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('LV_hub_2_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' LV_hub_2_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('PL_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' PL_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('SE_hub_1_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' SE_hub_1_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('SE_hub_2_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' SE_hub_2_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('SE_hub_3_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' SE_hub_3_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
AGKN('SE_hub_4_RG1_2050','GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050')=YES;                      /*   AGKN(' SE_hub_4_RG1_2050 ','  GNR_WT_WIND_OFF_HUB_RG1_SD-20M_Y-2050        ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' DE_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('DK_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' DK_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('DK_hub_2_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' DK_hub_2_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('DK_hub_3_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' DK_hub_3_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('EE_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' EE_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('EE_hub_2_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' EE_hub_2_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('FI_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' FI_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('FI_hub_2_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' FI_hub_2_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('FI_hub_3_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' FI_hub_3_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('FI_hub_4_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' FI_hub_4_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('LT_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' LT_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('LV_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' LV_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('LV_hub_2_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' LV_hub_2_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('PL_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' PL_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('SE_hub_1_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' SE_hub_1_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('SE_hub_2_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' SE_hub_2_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('SE_hub_3_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' SE_hub_3_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
AGKN('SE_hub_4_RG2_2020','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020')=YES;                 /*   AGKN(' SE_hub_4_RG2_2020 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2020   ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' DE_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('DK_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' DK_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('DK_hub_2_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' DK_hub_2_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('DK_hub_3_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' DK_hub_3_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('EE_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' EE_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('EE_hub_2_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' EE_hub_2_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('FI_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' FI_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('FI_hub_2_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' FI_hub_2_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('FI_hub_3_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' FI_hub_3_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('FI_hub_4_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' FI_hub_4_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('LT_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' LT_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('LV_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' LV_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('LV_hub_2_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' LV_hub_2_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('PL_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' PL_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('SE_hub_1_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' SE_hub_1_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('SE_hub_2_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' SE_hub_2_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('SE_hub_3_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' SE_hub_3_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
AGKN('SE_hub_4_RG2_2030','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030')=YES;                 /*   AGKN(' SE_hub_4_RG2_2030 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2030   ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' DE_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('DK_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' DK_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('DK_hub_2_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' DK_hub_2_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('DK_hub_3_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' DK_hub_3_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('EE_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' EE_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('EE_hub_2_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' EE_hub_2_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('FI_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' FI_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('FI_hub_2_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' FI_hub_2_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('FI_hub_3_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' FI_hub_3_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('FI_hub_4_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' FI_hub_4_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('LT_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' LT_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('LV_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' LV_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('LV_hub_2_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' LV_hub_2_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('PL_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' PL_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('SE_hub_1_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' SE_hub_1_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('SE_hub_2_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' SE_hub_2_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('SE_hub_3_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' SE_hub_3_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
AGKN('SE_hub_4_RG2_2040','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040')=YES;                 /*   AGKN(' SE_hub_4_RG2_2040 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2040   ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' DE_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('DK_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' DK_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('DK_hub_2_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' DK_hub_2_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('DK_hub_3_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' DK_hub_3_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('EE_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' EE_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('EE_hub_2_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' EE_hub_2_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('FI_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' FI_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('FI_hub_2_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' FI_hub_2_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('FI_hub_3_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' FI_hub_3_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('FI_hub_4_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' FI_hub_4_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('LT_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' LT_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('LV_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' LV_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('LV_hub_2_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' LV_hub_2_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('PL_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' PL_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('SE_hub_1_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' SE_hub_1_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('SE_hub_2_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' SE_hub_2_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('SE_hub_3_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' SE_hub_3_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
AGKN('SE_hub_4_RG2_2050','GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050')=YES;                 /*   AGKN(' SE_hub_4_RG2_2050 ','  GNR_WT_WIND_OFF_HUB_RG2_6-GW_SD-20M_Y-2050   ')=YES; */  
                                                                                            /*                                                                                      */  
                                                                                                                                                                                        
                                                                                                                                                                                        
AGKN('DE_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' DE_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('DK_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' DK_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('DK_hub_2_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' DK_hub_2_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('DK_hub_3_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' DK_hub_3_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('EE_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' EE_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('EE_hub_2_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' EE_hub_2_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('FI_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' FI_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('FI_hub_2_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' FI_hub_2_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('FI_hub_3_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' FI_hub_3_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('FI_hub_4_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' FI_hub_4_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('LT_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' LT_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('LV_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' LV_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('LV_hub_2_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' LV_hub_2_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('PL_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' PL_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('SE_hub_1_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' SE_hub_1_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('SE_hub_2_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' SE_hub_2_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('SE_hub_3_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' SE_hub_3_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
AGKN('SE_hub_4_RG1_2020','GNR_OFF_HUB_2GW_Y-2020')=YES;                                     /*   AGKN(' SE_hub_4_RG1_2020 ','  GNR_OFF_HUB_2GW_Y-2020                       ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' DE_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('DK_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' DK_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('DK_hub_2_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' DK_hub_2_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('DK_hub_3_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' DK_hub_3_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('EE_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' EE_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('EE_hub_2_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' EE_hub_2_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('FI_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' FI_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('FI_hub_2_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' FI_hub_2_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('FI_hub_3_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' FI_hub_3_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('FI_hub_4_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' FI_hub_4_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('LT_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' LT_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('LV_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' LV_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('LV_hub_2_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' LV_hub_2_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('PL_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' PL_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('SE_hub_1_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' SE_hub_1_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('SE_hub_2_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' SE_hub_2_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('SE_hub_3_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' SE_hub_3_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
AGKN('SE_hub_4_RG1_2030','GNR_OFF_HUB_2GW_Y-2030')=YES;                                     /*   AGKN(' SE_hub_4_RG1_2030 ','  GNR_OFF_HUB_2GW_Y-2030                       ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' DE_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('DK_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' DK_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('DK_hub_2_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' DK_hub_2_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('DK_hub_3_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' DK_hub_3_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('EE_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' EE_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('EE_hub_2_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' EE_hub_2_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('FI_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' FI_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('FI_hub_2_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' FI_hub_2_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('FI_hub_3_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' FI_hub_3_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('FI_hub_4_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' FI_hub_4_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('LT_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' LT_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('LV_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' LV_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('LV_hub_2_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' LV_hub_2_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('PL_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' PL_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('SE_hub_1_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' SE_hub_1_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('SE_hub_2_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' SE_hub_2_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('SE_hub_3_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' SE_hub_3_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
AGKN('SE_hub_4_RG1_2040','GNR_OFF_HUB_2GW_Y-2040')=YES;                                     /*   AGKN(' SE_hub_4_RG1_2040 ','  GNR_OFF_HUB_2GW_Y-2040                       ')=YES; */  
                                                                                            /*                                                                                      */  
AGKN('DE_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' DE_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('DK_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' DK_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('DK_hub_2_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' DK_hub_2_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('DK_hub_3_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' DK_hub_3_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('EE_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' EE_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('EE_hub_2_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' EE_hub_2_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('FI_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' FI_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('FI_hub_2_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' FI_hub_2_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('FI_hub_3_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' FI_hub_3_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('FI_hub_4_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' FI_hub_4_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('LT_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' LT_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('LV_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' LV_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('LV_hub_2_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' LV_hub_2_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('PL_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' PL_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('SE_hub_1_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' SE_hub_1_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('SE_hub_2_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' SE_hub_2_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('SE_hub_3_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' SE_hub_3_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
AGKN('SE_hub_4_RG1_2050','GNR_OFF_HUB_2GW_Y-2050')=YES;                                     /*   AGKN(' SE_hub_4_RG1_2050 ','  GNR_OFF_HUB_2GW_Y-2050                       ')=YES; */  
                                                                                            /*                                                                                      */  
