TABLE SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, SUBTECH_GROUP)  'Subtechnology group capacity restriction by geography (MW)'
                                                   RG1_OFF1
                                                           
Aarhus_OFF . WINDTURBINE_OFFSHORE                309.936993
Bornholm_OFF1 . WINDTURBINE_OFFSHORE            2654.403396
Bornholm_OFF2 . WINDTURBINE_OFFSHORE            3584.789036
Bornholm_OFF3 . WINDTURBINE_OFFSHORE             566.457788
Esbjerg_OFF . WINDTURBINE_OFFSHORE              1011.959257
Esbjerg_OFF5 . WINDTURBINE_OFFSHORE            17278.529948
Frederikshavn_OFF . WINDTURBINE_OFFSHORE        4170.411169
Haderslev_OFF . WINDTURBINE_OFFSHORE             151.022043
Halsnaes_OFF . WINDTURBINE_OFFSHORE             1932.548665
Kalundborg_OFF . WINDTURBINE_OFFSHORE            283.819873
Lemvig_OFF . WINDTURBINE_OFFSHORE                136.481441
Lolland_OFF . WINDTURBINE_OFFSHORE                94.477532
Lolland_OFF2 . WINDTURBINE_OFFSHORE              558.689785
Lolland_OFF3 . WINDTURBINE_OFFSHORE              225.709853
Norddjurs_OFF . WINDTURBINE_OFFSHORE             609.917383
Norddjurs_OFF2 . WINDTURBINE_OFFSHORE           1251.113594
Norddjurs_OFF3 . WINDTURBINE_OFFSHORE           1105.469025
Ringkoebing-Skjern_OFF . WINDTURBINE_OFFSHORE    120.401947
Samsoe_OFF . WINDTURBINE_OFFSHORE                160.426845
Soenderborg_OFF . WINDTURBINE_OFFSHORE           216.650561
Stevns_OFF . WINDTURBINE_OFFSHORE                299.531285
Stevns_OFF2 . WINDTURBINE_OFFSHORE               454.066863
Varde_OFF . WINDTURBINE_OFFSHORE                 222.256504
Vordingborg_OFF1 . WINDTURBINE_OFFSHORE          775.139121
Vordingborg_OFF2 . WINDTURBINE_OFFSHORE          346.425130
Vordingborg_OFF3 . WINDTURBINE_OFFSHORE          700.655255
Vordingborg_OFF4 . WINDTURBINE_OFFSHORE          778.709703
;