                                                                                 
SET AGKN(AAA,GGG) "Areas for possible location of new technologies";             
$ontext                                                                          
*Original                                                                        
AGKN('31_DE_OFF_2_Hub_BorWin_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;        
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;  
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;  
AGKN('31_DE_OFF_2_Hub_DolWin_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;        
AGKN('31_DE_OFF_2_Hub_HelWin_2020','GNR_WT_WIND_OFF_HUB_1GW_Y-2020')=YES;        
AGKN('93_UK_OFF_2_Hub_HornSea_e_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;     
AGKN('93_UK_OFF_2_Hub_HornSea_w_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;     
AGKN('NSY_OFF_2_Hub_NO_c_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;            
AGKN('NSY_OFF_2_Hub_NO_e_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;            
AGKN('NSY_OFF_2_Hub_NO_w_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;            
AGKN('31_DE_OFF_2_Hub_NorWin_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;        
AGKN('31_DE_OFF_2_Hub_SylWin_2020','GNR_WT_WIND_OFF_HUB_1GW_Y-2020')=YES;        
AGKN('NL3_OFF_2_Hub_UKandNL_e_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;       
AGKN('90_UK_OFF_2_Hub_UKandNL_w_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;     
AGKN('31_DE_OFF_2_Hub_WeiWin_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;         
                                                                                 
AGKN('31_DE_OFF_2_Hub_BorWin_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;        
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;  
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;  
AGKN('31_DE_OFF_2_Hub_DolWin_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;        
AGKN('31_DE_OFF_2_Hub_HelWin_2030','GNR_WT_WIND_OFF_HUB_1GW_Y-2030')=YES;        
AGKN('93_UK_OFF_2_Hub_HornSea_e_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;     
AGKN('93_UK_OFF_2_Hub_HornSea_w_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;     
AGKN('NSY_OFF_2_Hub_NO_c_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;            
AGKN('NSY_OFF_2_Hub_NO_e_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;            
AGKN('NSY_OFF_2_Hub_NO_w_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;            
AGKN('31_DE_OFF_2_Hub_NorWin_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;        
AGKN('31_DE_OFF_2_Hub_SylWin_2030','GNR_WT_WIND_OFF_HUB_1GW_Y-2030')=YES;        
AGKN('NL3_OFF_2_Hub_UKandNL_e_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;       
AGKN('90_UK_OFF_2_Hub_UKandNL_w_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;     
AGKN('31_DE_OFF_2_Hub_WeiWin_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;         
                                                                                 
AGKN('31_DE_OFF_2_Hub_BorWin_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;        
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;  
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;  
AGKN('31_DE_OFF_2_Hub_DolWin_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;        
AGKN('31_DE_OFF_2_Hub_HelWin_2040','GNR_WT_WIND_OFF_HUB_1GW_Y-2040')=YES;        
AGKN('93_UK_OFF_2_Hub_HornSea_e_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;     
AGKN('93_UK_OFF_2_Hub_HornSea_w_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;     
AGKN('NSY_OFF_2_Hub_NO_c_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;            
AGKN('NSY_OFF_2_Hub_NO_e_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;            
AGKN('NSY_OFF_2_Hub_NO_w_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;            
AGKN('31_DE_OFF_2_Hub_NorWin_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;        
AGKN('31_DE_OFF_2_Hub_SylWin_2040','GNR_WT_WIND_OFF_HUB_1GW_Y-2040')=YES;        
AGKN('NL3_OFF_2_Hub_UKandNL_e_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;       
AGKN('90_UK_OFF_2_Hub_UKandNL_w_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;     
AGKN('31_DE_OFF_2_Hub_WeiWin_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;         
                                                                                 
AGKN('31_DE_OFF_2_Hub_BorWin_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;        
AGKN('93_UK_OFF_2_Hub_DoggerBank_e_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;  
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;  
AGKN('31_DE_OFF_2_Hub_DolWin_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;        
AGKN('31_DE_OFF_2_Hub_HelWin_2050','GNR_WT_WIND_OFF_HUB_1GW_Y-2050')=YES;        
AGKN('93_UK_OFF_2_Hub_HornSea_e_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;     
AGKN('93_UK_OFF_2_Hub_HornSea_w_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;     
AGKN('NSY_OFF_2_Hub_NO_c_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;            
AGKN('NSY_OFF_2_Hub_NO_e_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;            
AGKN('NSY_OFF_2_Hub_NO_w_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;            
AGKN('31_DE_OFF_2_Hub_NorWin_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;        
AGKN('31_DE_OFF_2_Hub_SylWin_2050','GNR_WT_WIND_OFF_HUB_1GW_Y-2050')=YES;        
AGKN('NL3_OFF_2_Hub_UKandNL_e_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;       
AGKN('90_UK_OFF_2_Hub_UKandNL_w_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;     
AGKN('31_DE_OFF_2_Hub_WeiWin_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;         
$offtext                                                                         
                                                                                 
*Reducing number of options to a few                                             
                                                                                 
                                                                                 
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;  
AGKN('NSY_OFF_2_Hub_NO_c_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;            
AGKN('NL3_OFF_2_Hub_UKandNL_e_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;       
AGKN('31_DE_OFF_2_Hub_WeiWin_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2020','GNR_WT_WIND_OFF_HUB_2GW_Y-2020')=YES;         
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;  
AGKN('NSY_OFF_2_Hub_NO_c_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;            
AGKN('NL3_OFF_2_Hub_UKandNL_e_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;       
AGKN('31_DE_OFF_2_Hub_WeiWin_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2030','GNR_WT_WIND_OFF_HUB_2GW_Y-2030')=YES;         
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;  
AGKN('NSY_OFF_2_Hub_NO_c_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;            
AGKN('NL3_OFF_2_Hub_UKandNL_e_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;       
AGKN('31_DE_OFF_2_Hub_WeiWin_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2040','GNR_WT_WIND_OFF_HUB_2GW_Y-2040')=YES;         
AGKN('93_UK_OFF_2_Hub_DoggerBank_w_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;  
AGKN('NSY_OFF_2_Hub_NO_c_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;            
AGKN('NL3_OFF_2_Hub_UKandNL_e_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;       
AGKN('31_DE_OFF_2_Hub_WeiWin_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;        
AGKN('DK_w_OFF_2_Hub_DK_hub_2050','GNR_WT_WIND_OFF_HUB_2GW_Y-2050')=YES;         
