* Parameters that hold the yearly number of full load hours for different technologies                  
* Updated for areas, but very rough number used!                                                        
                                                                                                        
                                                                                                        
                                                                                                        
PARAMETER WNDFLH(AAA)  'Full load hours for wind power (hours)'                                         
/                                                                                                       
31_DE_OFF_2_Hub_BorWin_RG1_2020                                                        4600.97223286789 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2020                                                  4700.51120009909 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2020                                                  4700.51120009909 
31_DE_OFF_2_Hub_DolWin_RG1_2020                                                        4558.76612596787 
31_DE_OFF_2_Hub_HelWin_RG1_2020                                                        4597.6365335002  
93_UK_OFF_2_Hub_HornSea_e_RG1_2020                                                     4666.42971064688 
93_UK_OFF_2_Hub_HornSea_w_RG1_2020                                                     4666.42971064688 
NSY_OFF_2_Hub_NO_c_RG1_2020                                                            4826.35144358407 
NSY_OFF_2_Hub_NO_e_RG1_2020                                                            4850.60706907515 
NSY_OFF_2_Hub_NO_w_RG1_2020                                                            4802.09590053041 
31_DE_OFF_2_Hub_NorWin_RG1_2020                                                        4667.15154609822 
31_DE_OFF_2_Hub_SylWin_RG1_2020                                                        4680.96073023485 
NL3_OFF_2_Hub_UKandNL_e_RG1_2020                                                       4489.97037651106 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2020                                                     4535.70340188464 
31_DE_OFF_2_Hub_WeiWin_RG1_2020                                                        4646.60895890563 
DK_w_OFF_2_Hub_DK_hub_RG1_2020                                                         4566.50547129419 
31_DE_OFF_2_Hub_BorWin_RG1_2030                                                        4703.07693473616 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2030                                                  4799.64342252841 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2030                                                  4799.64342252841 
31_DE_OFF_2_Hub_DolWin_RG1_2030                                                        4662.92959496764 
31_DE_OFF_2_Hub_HelWin_RG1_2030                                                        4701.61714009119 
93_UK_OFF_2_Hub_HornSea_e_RG1_2030                                                     4763.31347137872 
93_UK_OFF_2_Hub_HornSea_w_RG1_2030                                                     4763.31347137872 
NSY_OFF_2_Hub_NO_c_RG1_2030                                                            4926.51242884482 
NSY_OFF_2_Hub_NO_e_RG1_2030                                                            4951.72666052925 
NSY_OFF_2_Hub_NO_w_RG1_2030                                                            4901.29819716038 
31_DE_OFF_2_Hub_NorWin_RG1_2030                                                        4768.9533815627  
31_DE_OFF_2_Hub_SylWin_RG1_2030                                                        4784.05358674305 
NL3_OFF_2_Hub_UKandNL_e_RG1_2030                                                       4589.88970799075 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2030                                                     4633.70549940863 
31_DE_OFF_2_Hub_WeiWin_RG1_2030                                                        4749.01447753676 
DK_w_OFF_2_Hub_DK_hub_RG1_2030                                                         4682.07411058969 
31_DE_OFF_2_Hub_BorWin_RG1_2040                                                        4807.44754250778 
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2040                                                  4900.8663106546  
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2040                                                  4900.8663106546  
31_DE_OFF_2_Hub_DolWin_RG1_2040                                                        4769.47310013823 
31_DE_OFF_2_Hub_HelWin_RG1_2040                                                        4807.94938245595 
93_UK_OFF_2_Hub_HornSea_e_RG1_2040                                                     4862.20871919503 
93_UK_OFF_2_Hub_HornSea_w_RG1_2040                                                     4862.20871919503 
NSY_OFF_2_Hub_NO_c_RG1_2040                                                            5028.75204909219 
NSY_OFF_2_Hub_NO_e_RG1_2040                                                            5054.95427096535 
NSY_OFF_2_Hub_NO_w_RG1_2040                                                            5002.54982721903 
31_DE_OFF_2_Hub_NorWin_RG1_2040                                                        4872.97576067175 
31_DE_OFF_2_Hub_SylWin_RG1_2040                                                        4889.41694661061 
NL3_OFF_2_Hub_UKandNL_e_RG1_2040                                                       4692.03263382989 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2040                                                     4733.82510997704 
31_DE_OFF_2_Hub_WeiWin_RG1_2040                                                        4853.67688723378 
DK_w_OFF_2_Hub_DK_hub_RG1_2040                                                         4800.56754883102 
31_DE_OFF_2_Hub_BorWin_RG1_2050                                                        4911.8181502794  
93_UK_OFF_2_Hub_DoggerBank_e_RG1_2050                                                  5002.08919878079 
93_UK_OFF_2_Hub_DoggerBank_w_RG1_2050                                                  5002.08919878079 
31_DE_OFF_2_Hub_DolWin_RG1_2050                                                        4876.01660530882 
31_DE_OFF_2_Hub_HelWin_RG1_2050                                                        4914.28162482072 
93_UK_OFF_2_Hub_HornSea_e_RG1_2050                                                     4961.10396701133 
93_UK_OFF_2_Hub_HornSea_w_RG1_2050                                                     4961.10396701133 
NSY_OFF_2_Hub_NO_c_RG1_2050                                                            5130.99166933956 
NSY_OFF_2_Hub_NO_e_RG1_2050                                                            5158.18188140145 
NSY_OFF_2_Hub_NO_w_RG1_2050                                                            5103.80145727767 
31_DE_OFF_2_Hub_NorWin_RG1_2050                                                        4976.9981397808  
31_DE_OFF_2_Hub_SylWin_RG1_2050                                                        4994.78030647817 
NL3_OFF_2_Hub_UKandNL_e_RG1_2050                                                       4794.17555966904 
90_UK_OFF_2_Hub_UKandNL_w_RG1_2050                                                     4833.94472054544 
31_DE_OFF_2_Hub_WeiWin_RG1_2050                                                        4958.33929693081 
DK_w_OFF_2_Hub_DK_hub_RG1_2050                                                         4919.06098707236 
                                                                                                        
31_DE_OFF_2_Hub_BorWin_RG2_2020                                                        3956.83612026639 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2020                                                  4042.43963208522 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2020                                                  4042.43963208522 
31_DE_OFF_2_Hub_DolWin_RG2_2020                                                        3920.53886833237 
31_DE_OFF_2_Hub_HelWin_RG2_2020                                                        3953.96741881017 
93_UK_OFF_2_Hub_HornSea_e_RG2_2020                                                     4013.12955115632 
93_UK_OFF_2_Hub_HornSea_w_RG2_2020                                                     4013.12955115632 
NSY_OFF_2_Hub_NO_c_RG2_2020                                                            4150.6622414823  
NSY_OFF_2_Hub_NO_e_RG2_2020                                                            4171.52207940463 
NSY_OFF_2_Hub_NO_w_RG2_2020                                                            4129.80247445616 
31_DE_OFF_2_Hub_NorWin_RG2_2020                                                        4013.75032964447 
31_DE_OFF_2_Hub_SylWin_RG2_2020                                                        4025.62622800197 
NL3_OFF_2_Hub_UKandNL_e_RG2_2020                                                       3861.37452379951 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2020                                                     3900.70492562079 
31_DE_OFF_2_Hub_WeiWin_RG2_2020                                                        3996.08370465885 
DK_w_OFF_2_Hub_DK_hub_RG2_2020                                                         3927.194705313   
31_DE_OFF_2_Hub_BorWin_RG2_2030                                                        4044.6461638731  
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2030                                                  4127.69334337443 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2030                                                  4127.69334337443 
31_DE_OFF_2_Hub_DolWin_RG2_2030                                                        4010.11945167217 
31_DE_OFF_2_Hub_HelWin_RG2_2030                                                        4043.39074047842 
93_UK_OFF_2_Hub_HornSea_e_RG2_2030                                                     4096.4495853857  
93_UK_OFF_2_Hub_HornSea_w_RG2_2030                                                     4096.4495853857  
NSY_OFF_2_Hub_NO_c_RG2_2030                                                            4236.80068880654 
NSY_OFF_2_Hub_NO_e_RG2_2030                                                            4258.48492805515 
NSY_OFF_2_Hub_NO_w_RG2_2030                                                            4215.11644955793 
31_DE_OFF_2_Hub_NorWin_RG2_2030                                                        4101.29990814392 
31_DE_OFF_2_Hub_SylWin_RG2_2030                                                        4114.28608459902 
NL3_OFF_2_Hub_UKandNL_e_RG2_2030                                                       3947.30514887204 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2030                                                     3984.98672949142 
31_DE_OFF_2_Hub_WeiWin_RG2_2030                                                        4084.15245068161 
DK_w_OFF_2_Hub_DK_hub_RG2_2030                                                         4026.58373510713 
31_DE_OFF_2_Hub_BorWin_RG2_2040                                                        4134.40488655669 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2040                                                  4214.74502716296 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2040                                                  4214.74502716296 
31_DE_OFF_2_Hub_DolWin_RG2_2040                                                        4101.74686611888 
31_DE_OFF_2_Hub_HelWin_RG2_2040                                                        4134.83646891212 
93_UK_OFF_2_Hub_HornSea_e_RG2_2040                                                     4181.49949850772 
93_UK_OFF_2_Hub_HornSea_w_RG2_2040                                                     4181.49949850772 
NSY_OFF_2_Hub_NO_c_RG2_2040                                                            4324.72676221928 
NSY_OFF_2_Hub_NO_e_RG2_2040                                                            4347.2606730302  
NSY_OFF_2_Hub_NO_w_RG2_2040                                                            4302.19285140836 
31_DE_OFF_2_Hub_NorWin_RG2_2040                                                        4190.7591541777  
31_DE_OFF_2_Hub_SylWin_RG2_2040                                                        4204.89857408512 
NL3_OFF_2_Hub_UKandNL_e_RG2_2040                                                       4035.14806509371 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2040                                                     4071.08959458025 
31_DE_OFF_2_Hub_WeiWin_RG2_2040                                                        4174.16212302105 
DK_w_OFF_2_Hub_DK_hub_RG2_2040                                                         4128.48809199468 
31_DE_OFF_2_Hub_BorWin_RG2_2050                                                        4224.16360924029 
93_UK_OFF_2_Hub_DoggerBank_e_RG2_2050                                                  4301.79671095148 
93_UK_OFF_2_Hub_DoggerBank_w_RG2_2050                                                  4301.79671095148 
31_DE_OFF_2_Hub_DolWin_RG2_2050                                                        4193.37428056558 
31_DE_OFF_2_Hub_HelWin_RG2_2050                                                        4226.28219734582 
93_UK_OFF_2_Hub_HornSea_e_RG2_2050                                                     4266.54941162975 
93_UK_OFF_2_Hub_HornSea_w_RG2_2050                                                     4266.54941162975 
NSY_OFF_2_Hub_NO_c_RG2_2050                                                            4412.65283563202 
NSY_OFF_2_Hub_NO_e_RG2_2050                                                            4436.03641800525 
NSY_OFF_2_Hub_NO_w_RG2_2050                                                            4389.2692532588  
31_DE_OFF_2_Hub_NorWin_RG2_2050                                                        4280.21840021148 
31_DE_OFF_2_Hub_SylWin_RG2_2050                                                        4295.51106357123 
NL3_OFF_2_Hub_UKandNL_e_RG2_2050                                                       4122.99098131538 
90_UK_OFF_2_Hub_UKandNL_w_RG2_2050                                                     4157.19245966908 
31_DE_OFF_2_Hub_WeiWin_RG2_2050                                                        4264.1717953605  
DK_w_OFF_2_Hub_DK_hub_RG2_2050                                                         4230.39244888223 
                                                                                                        
                                                                                                        
/;                                                                                                      
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
                                                                                                        
