SET NEGPOLFLOW(IPROCFROM,IPROCTO,FLOW) ""                                      
/                                                                              
CO2_Grid_Out                              .    CO2_Seq .    CO2_FLOW_DAC_SEQ   
CO2_Grid_Out                              .    CO2_Seq .    CO2_FLOW_BIOGEN_SEQ
CO2_Grid_Out                              .    CO2_Seq .    CO2_FLOW_BIOGAS_SEQ
                                                                               
/;                                                                             
