TABLE SOSIBUBOUND_AS(AAA,PROC,FLOW,SSS,iLOUPFXSET) "Bounds on Source, Sink and Buffer Process Flows - Seasonal values"
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
;                                                                                                                     
