PARAMETER MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                                                            
/                                                                                                                                                      
                                                                                                                                                       
*2020                                                                                       .    DENMARK .    Demand     .    SumDemand 10000          
                                                                                                                                                       
*2020                                                                                       .    DENMARK .    GasBuffer  .    GASFLOW   10000000       
2020                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   11000000       
2020                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  75000000       
2020                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   60000000       
                                                                                                                                                       
2030                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   11550000       
2030                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  78750000       
2030                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   63000000       
                                                                                                                                                       
2035                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   12127500       
2035                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  82687500       
2035                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   66150000       
                                                                                                                                                       
2040                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   12733875       
2040                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  86821875       
2040                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   69457500       
                                                                                                                                                       
2045                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   13370568.75    
2045                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  91162968.75    
2045                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   72930375       
                                                                                                                                                       
2050                                                                                        .    DENMARK .    SeaBuffer  .    SEAFLOW   14039097.1875  
2050                                                                                        .    DENMARK .    RoadBuffer .    ROADFLOW  95721117.1875  
2050                                                                                        .    DENMARK .    AirBuffer  .    AIRFLOW   76576893.75    
                                                                                                                                                       
                                                                                                                                                       
/;                                                                                                                                                     
                                                                                                                                                       
*MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) = MINFLOW('2020',CCCRRRAAA,PROC,FLOW);                                                                               
