TABLE PROCDATA(PROC,PROCDATASET)    "Process data"                                                                                           
                                                                                                                                             
*                                                          MEuro/unit/h                                                  Euro/unit/h         
                                                           PROCINVCOST         PROCKAPVARIABLE PROCFROMYEAR PROCLIFETIME PROCFIXCOST         
                                                                                                                                             
* OBS FF                                                                                                                                     
ProcExim_Pipeline_CO2                                      0.143               1               2020         50           20                  
                                                                                                                                             
***CO2 DAC                                                                                                                                   
CO2_DAC_20                                                 5.8                 1               2020         30           210000              
CO2_DAC_25                                                 4.3                 1               2025         30           160000              
CO2_DAC_30                                                 2.7                 1               2030         30           100000              
CO2_DAC_35                                                 2.3                 1               2035         30           85000               
CO2_DAC_40                                                 1.9                 1               2040         30           70000               
CO2_DAC_45                                                 1.75                1               2045         30           65000               
CO2_DAC_50                                                 1.6                 1               2050         30           60000               
                                                                                                                                             
                                                                                                                                             
***CO2 Sequestration                                                                                                                         
CO2_Seq_On_20                                              0.77672             1               2020         25           1224850.3202038     
CO2_Seq_On_25                                              0.738652991558328   1               2025         25           1287973.85454516    
CO2_Seq_On_30                                              0.702451645300839   1               2030         25           1354350.5052241     
CO2_Seq_On_35                                              0.668024525216982   1               2035         25           1424147.92390995    
CO2_Seq_On_40                                              0.635284676570521   1               2040         25           1497542.4023203     
CO2_Seq_On_45                                              0.604149406272505   1               2045         25           1574719.31749209    
CO2_Seq_On_50                                              0.574540074018145   1               2050         25           1655873.6           
                                                                                                                                             
CO2_Seq_Off_20                                             0.77672             1               2020         25           1224850.3202038     
CO2_Seq_Off_25                                             0.738652991558328   1               2025         25           1287973.85454516    
CO2_Seq_Off_30                                             0.702451645300839   1               2030         25           1354350.5052241     
CO2_Seq_Off_35                                             0.668024525216982   1               2035         25           1424147.92390995    
CO2_Seq_Off_40                                             0.635284676570521   1               2040         25           1497542.4023203     
CO2_Seq_Off_45                                             0.604149406272505   1               2045         25           1574719.31749209    
CO2_Seq_Off_50                                             0.574540074018145   1               2050         25           1655873.6           
                                                                                                                                             
***CO2 Storage                                                                                                                               
CO2_Accumulator                                            1.52                1               2020         30           30435               
                                                                                                                                             
***Biogas supply                                                                                                                             
Manure_Tank_20                                             1.569198587517E-005 1               2020         20           0.001               
Manure_Tank_25                                             1.490738658141E-005 1               2025         20           0.001               
Manure_Tank_30                                             1.412278728765E-005 1               2030         20           0.001               
Manure_Tank_35                                             1.376971760546E-005 1               2035         20           0.001               
Manure_Tank_40                                             1.341664792327E-005 1               2040         20           0.001               
Manure_Tank_45                                             1.306357824108E-005 1               2045         20           0.001               
Manure_Tank_50                                             1.271050855888E-005 1               2050         20           0.001               
Straw_Tank_20                                              5.19042609717E-005  1               2020         20           0.001               
Straw_Tank_25                                              4.930904792312E-005 1               2025         20           0.001               
Straw_Tank_30                                              4.671383487453E-005 1               2030         20           0.001               
Straw_Tank_35                                              4.554598900267E-005 1               2035         20           0.001               
Straw_Tank_40                                              4.437814313081E-005 1               2040         20           0.001               
Straw_Tank_45                                              4.321029725894E-005 1               2045         20           0.001               
Straw_Tank_50                                              4.204245138708E-005 1               2050         20           0.001               
                                                                                                                                             
***Biogas storage                                                                                                                            
Biogas_Grid_Sto                                            0.0059085           1               2020         20           59.085              
                                                                                                                                             
***Biogas technologies                                                                                                                       
Methanation_20                                             0.423               1               2020         20           16920               
Methanation_25                                             0.388               1               2025         20           15520               
Methanation_30                                             0.353               1               2030         20           14120               
Methanation_35                                             0.317               1               2035         20           12680               
Methanation_40                                             0.282               1               2040         20           11280               
Methanation_45                                             0.247               1               2045         20           9880                
Methanation_50                                             0.212               1               2050         20           8480                
                                                                                                                                             
Biogas_Upgrading_20                                        0.0908249056941763  1               2020         20           2556.94862404588    
Biogas_Upgrading_25                                        0.0906122047151871  1               2025         20           2719.05916681038    
Biogas_Upgrading_30                                        0.0775574488698658  1               2030         20           2255.32906402921    
Biogas_Upgrading_35                                        0.0713369329822316  1               2035         20           2072.53759248121    
Biogas_Upgrading_40                                        0.0651164170945975  1               2040         20           1889.74612093322    
Biogas_Upgrading_45                                        0.064804653207653   1               2045         20           1774.18610634378    
Biogas_Upgrading_50                                        0.0644928893207086  1               2050         20           1658.62609175433    
                                                                                                                                             
***Pyrolysis Straw                                                                                                                           
Pyrolysis_Straw_25                                         0.343693361111111   1               2025         25           16026.525           
Pyrolysis_Straw_30                                         0.319176083333333   1               2030         25           15045.8338888889    
Pyrolysis_Straw_35                                         0.306917444444444   1               2035         25           14555.4883333333    
Pyrolysis_Straw_40                                         0.294658805555556   1               2040         25           14065.1427777778    
Pyrolysis_Straw_45                                         0.282400166666667   1               2045         25           13697.3836111111    
Pyrolysis_Straw_50                                         0.270141527777778   1               2050         25           13329.6244444444    
                                                                                                                                             
***Hydrogen                                                                                                                                  
Hydrogen_STO_Large_20                                      0.125               1               2020         20           5771                
Hydrogen_STO_Large_25                                      0.111               1               2025         20           5108                
Hydrogen_STO_Large_30                                      0.096               1               2030         20           4446                
Hydrogen_STO_Large_35                                      0.092               1               2035         20           4224                
Hydrogen_STO_Large_40                                      0.087               1               2040         20           4013                
Hydrogen_STO_Large_45                                      0.083               1               2045         20           3812                
Hydrogen_STO_Large_50                                      0.079               1               2050         20           3621                
                                                                                                                                             
Hydrogen_STO_Small_20                                      0.224               1               2020         20           10311               
Hydrogen_STO_Small_25                                      0.198               1               2025         20           9129                
Hydrogen_STO_Small_30                                      0.172               1               2030         20           7946                
Hydrogen_STO_Small_35                                      0.164               1               2035         20           7549                
Hydrogen_STO_Small_40                                      0.155               1               2040         20           7172                
Hydrogen_STO_Small_45                                      0.148               1               2045         20           6813                
Hydrogen_STO_Small_50                                      0.14                1               2050         20           6472                
                                                                                                                                             
*****TG                                                                                                                                      
TG_20                                                      0.234516737109375   1               2020         30           9394.07044078125    
TG_25                                                      0.2233492734375     1               2025         30           8946.733753125      
TG_30                                                      0.21271359375       1               2030         30           8520.6988125        
TG_35                                                      0.202584375         1               2035         30           8114.95125          
TG_40                                                      0.1929375           1               2040         30           7728.525            
TG_45                                                      0.18375             1               2045         30           7360.5              
TG_50                                                      0.175               1               2050         30           7010                
                                                                                                                                             
                                                                                                                                             
***Methanol                                                                                                                                  
Methanol_synthesis_TG_20                                   0.0657789024849398  1               2020         30           1973.36707454819    
Methanol_synthesis_TG_25                                   0.0626465737951807  1               2025         30           1879.39721385542    
Methanol_synthesis_TG_30                                   0.0596634036144578  1               2030         30           1789.90210843374    
Methanol_synthesis_TG_35                                   0.0568222891566265  1               2035         30           1704.6686746988     
Methanol_synthesis_TG_40                                   0.0541164658634538  1               2040         30           1623.49397590361    
Methanol_synthesis_TG_45                                   0.0515394912985274  1               2045         30           1546.18473895582    
Methanol_synthesis_TG_50                                   0.0490852298081214  1               2050         30           1472.55689424364    
                                                                                                                                             
EMethanol_synthesis_20                                     0.235               1               2020         30           9402                
EMethanol_synthesis_25                                     0.188               1               2025         30           7521                
EMethanol_synthesis_30                                     0.141               1               2030         30           5641                
EMethanol_synthesis_35                                     0.141               1               2035         30           5641                
EMethanol_synthesis_40                                     0.141               1               2040         30           5641                
EMethanol_synthesis_45                                     0.141               1               2045         30           5641                
EMethanol_synthesis_50                                     0.141               1               2050         30           5641                
                                                                                                                                             
EMethanol_Upgrade_20                                       0.0915570046861632  1               2020         30           3252                
EMethanol_Upgrade_25                                       0.08976176930016    1               2025         30           3252                
EMethanol_Upgrade_30                                       0.088001734608      1               2030         30           3252                
EMethanol_Upgrade_35                                       0.0862762104        1               2035         30           3252                
EMethanol_Upgrade_40                                       0.08458452          1               2040         30           3252                
EMethanol_Upgrade_45                                       0.082926            1               2045         30           3252                
EMethanol_Upgrade_50                                       0.0813              1               2050         30           3252                
                                                                                                                                             
Methanol_Storage                                           1.539E-005          1               2020         30           0.4617              
                                                                                                                                             
***Ammonia                                                                                                                                   
Ammonia_Synthesis_20                                       0.2605145925375     1               2020         30           5716.80963339062    
Ammonia_Synthesis_25                                       0.24810913575       1               2025         30           6017.6943509375     
Ammonia_Synthesis_30                                       0.236294415         1               2030         30           6334.41510625       
Ammonia_Synthesis_35                                       0.2250423           1               2035         30           6667.805375         
Ammonia_Synthesis_40                                       0.214326            1               2040         30           7018.7425           
Ammonia_Synthesis_45                                       0.20412             1               2045         30           7388.15             
Ammonia_Synthesis_50                                       0.1944              1               2050         30           7777                
Ammonia_Storage                                            3.632458064516E-005 1               2020         30           1.81622903225806    
                                                                                                                                             
***Jet and oil products                                                                                                                      
BioJet_20                                                  0.351               1               2020         30           10483               
BioJet_25                                                  0.334               1               2025         30           9959                
BioJet_30                                                  0.317               1               2030         30           9461                
BioJet_35                                                  0.301               1               2035         30           8988                
BioJet_40                                                  0.286               1               2040         30           8539                
BioJet_45                                                  0.272               1               2045         30           8112                
BioJet_50                                                  0.258               1               2050         30           7706                
                                                                                                                                             
BioJet_H2_20                                               0.3861              1               2020         30           11531.3             
BioJet_H2_25                                               0.3674              1               2025         30           10954.9             
BioJet_H2_30                                               0.3487              1               2030         30           10407.1             
BioJet_H2_35                                               0.3311              1               2035         30           9886.8              
BioJet_H2_40                                               0.3146              1               2040         30           9392.9              
BioJet_H2_45                                               0.2992              1               2045         30           8923.2              
BioJet_H2_50                                               0.2838              1               2050         30           8476.6              
                                                                                                                                             
E_FT_20                                                    0.214               1               2020         30           8547                
E_FT_25                                                    0.175               1               2025         30           7007                
E_FT_30                                                    0.137               1               2030         30           5467                
E_FT_35                                                    0.137               1               2035         30           5467                
E_FT_40                                                    0.137               1               2040         30           5467                
E_FT_45                                                    0.137               1               2045         30           5467                
E_FT_50                                                    0.137               1               2050         30           5467                
;                                                                                                                                            
                                                                                                                                             
PROCDATA(PROC,'PROCINVCOST')=PROCDATA(PROC,'PROCINVCOST');                                                                                   
