PARAMETER TRANSFLOWMAX(IAAAE,IAAAI,PROC,FLOW)  "Transport quantity maximum value (ton/h)"
                                                                                         
/                                                                                        
                                                                                         
                                                                                         
/;                                                                                       
                                                                                         
*TRANSFLOWMAX(IAE,IAI,'ProcExim_Truck_Fuel',IFLOWEXIM)$(ITRANSFROMTO(IAE,IAI))=1e9;      
