SCALAR_MOUNTAIN_REL_INCR  'Increase in PROCINVCOST for the mountaineous share of a transport pipeline (relative increase from base)';
                                                                                                                                     
MOUNTAIN_REL_INCR=1.5;                                                                                                               
