PARAMETER PROCKAP_RETRO_SURVIVAL(YYY,PROC) "fraction of  capacity with vessels still technically operational in a given year (eligible for retrofit use only)"                                    
/                                                                                                                                                                                                 
2030                                                                                                                                                           .    Cap_Oil_Old_Existing    1     
2040                                                                                                                                                           .    Cap_Oil_Old_Existing    0.3624
2050                                                                                                                                                           .    Cap_Oil_Old_Existing    0.0661
                                                                                                                                                                                                  
2030                                                                                                                                                           .    Cap_Oil_Tanker_Existing 1     
2040                                                                                                                                                           .    Cap_Oil_Tanker_Existing 0.506 
2050                                                                                                                                                           .    Cap_Oil_Tanker_Existing 0.136 
                                                                                                                                                                                                  
2030                                                                                                                                                           .    Cap_LNG_Tanker_Existing 1     
2040                                                                                                                                                           .    Cap_LNG_Tanker_Existing 0.427 
2050                                                                                                                                                           .    Cap_LNG_Tanker_Existing 0.099 
                                                                                                                                                                                                  
/;                                                                                                                                                                                                
                                                                                                                                                                                                  
                                                                                                                                                                                                  
                                                                                                                                                                                                  
                                                                                                                                                                                                  
                                                                                                                                                                                                  
                                                                                                                                                                                                  
                                                                                                                                                                                                  
