PARAMETER EQFLOW_VAR_S(CCCRRRAAA,PROC,FLOW,SSS)"Constraint about fuel use requirements at S level"
/                                                                                                 
                                                                                                  
/;                                                                                                
