SET ALLOWEDTRANS(PROC, FLOW)                      
/                                                 
ProcExim_Pipeline_CO2        .    CO2_FLOW_BIOGAS 
ProcExim_Pipeline_CO2        .    CO2_FLOW_BIOGEN 
ProcExim_Pipeline_CO2        .    CO2_FLOW_DAC    
ProcExim_Pipeline_CO2        .    CO2_FLOW_FOSSIL 
ProcExim_Pipeline_CO2        .    CO2_OCC_OFF_PIPE
ProcExim_Ship_CO2            .    CO2_FLOW_BIOGAS 
ProcExim_Ship_CO2            .    CO2_FLOW_BIOGEN 
ProcExim_Ship_CO2            .    CO2_FLOW_DAC    
ProcExim_Ship_CO2            .    CO2_FLOW_FOSSIL 
ProcExim_Ship_CO2            .    CO2_OCC_OFF_SHIP
ProcExim_Truck_CO2           .    CO2_FLOW_BIOGAS 
ProcExim_Truck_CO2           .    CO2_FLOW_BIOGEN 
ProcExim_Truck_CO2           .    CO2_FLOW_DAC    
ProcExim_Truck_CO2           .    CO2_FLOW_FOSSIL 
                                                  
ProcExim_Truck_Oil           .    E_FT_DIESEL_FLOW
ProcExim_Truck_Methanol      .    METHANOLFLOW    
ProcExim_Truck_Methanol      .    EMETHANOLFLOW   
ProcExim_Truck_Ammonia       .    AMMONIA_FLOW    
ProcExim_Truck_Hydrogen      .    HYDROGEN_FLOW   
                                                  
ProcExim_Ship_Oil            .    E_FT_DIESEL_FLOW
ProcExim_Ship_Methanol       .    METHANOLFLOW    
ProcExim_Ship_Methanol       .    EMETHANOLFLOW   
ProcExim_Ship_Ammonia        .    AMMONIA_FLOW    
ProcExim_Ship_Hydrogen       .    HYDROGEN_FLOW   
/;                                                
