SET APKNDISCDATASET     "Processes investment data types for discrete capacity size investments (addon apkndisc)"
/                                                                                                                
   APKNDISCSIZE      "Size (U/h)"                                                                                
   APKNDISCINVCOST   "Investment cost (MMoney/[U/h])"                                                            
   APKNDISCOMFCOST   "Fixed annual operating and maintenance costs (kMoney/[U/h]) (default value)"               
   APKNDISCOMVCOST   "Variable annual operating and maintenance costs (Money/U) (default value)"                 
/;                                                                                                               
