SET PROCSTORAGE(PROC) "Storage processes"
                                         
/                                        
                                         
StoA                                     
StoD                                     
                                         
Hydrogen_STO_Large_20                    
Hydrogen_STO_Large_25                    
Hydrogen_STO_Large_30                    
Hydrogen_STO_Large_35                    
Hydrogen_STO_Large_40                    
Hydrogen_STO_Large_45                    
Hydrogen_STO_Large_50                    
                                         
Hydrogen_STO_Small_20                    
Hydrogen_STO_Small_25                    
Hydrogen_STO_Small_30                    
Hydrogen_STO_Small_35                    
Hydrogen_STO_Small_40                    
Hydrogen_STO_Small_45                    
Hydrogen_STO_Small_50                    
                                         
                                         
                                         
                                         
                                         
                                         
                                         
                                         
Biogas_Grid_STO                          
CO2_Sto                                  
/;                                       
