SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
*Liquid hydrocarbons (LHC)                                          
ProcExim_Truck_LHC                                                  
ProcExim_Ship_LHC                                                   
                                                                    
*Ammonia                                                            
ProcExim_Truck_Ammonia                                              
ProcExim_Ship_Ammonia                                               
                                                                    
*Methanol                                                           
ProcExim_Truck_Methanol                                             
ProcExim_Ship_Methanol                                              
                                                                    
*CO2                                                                
CO2_Pipeline                                                        
ProcExim_Truck_CO2                                                  
ProcExim_Ship_CO2                                                   
                                                                    
*Biomass                                                            
ProcExim_Truck_Wood                                                 
ProcExim_Truck_Straw                                                
/;                                                                  
