SET APROCKAPNEW(YYY,AAA,PROC)     'Areas for possible location of new Proc or capacity expansion of existing Proc'                                                 
*This is stablished according to economy of scale, where large plants can only be located when heat demand is high                                                 
                                                                                                                                                                   
/                                                                                                                                                                  
2020                                                                                                               .    DK1_Large    .    ProA                     
2020                                                                                                               .    DK1_Medium   .    ProA                     
2020                                                                                                               .    DK1_MedSmall .    ProA                     
2020                                                                                                               .    DK1_Small    .    ProA                     
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    StoA                     
2020                                                                                                               .    DK1_Medium   .    StoA                     
2020                                                                                                               .    DK1_MedSmall .    StoA                     
2020                                                                                                               .    DK1_Small    .    StoA                     
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    ProD                     
2020                                                                                                               .    DK1_Medium   .    ProD                     
2020                                                                                                               .    DK1_MedSmall .    ProD                     
2020                                                                                                               .    DK1_Small    .    ProD                     
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    StoD                     
2020                                                                                                               .    DK1_Medium   .    StoD                     
2020                                                                                                               .    DK1_MedSmall .    StoD                     
2020                                                                                                               .    DK1_Small    .    StoD                     
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    ProB                     
2020                                                                                                               .    DK1_Medium   .    ProB                     
2020                                                                                                               .    DK1_MedSmall .    ProB                     
2020                                                                                                               .    DK1_Small    .    ProB                     
                                                                                                                                                                   
                                                                                                                                                                   
                                                                                                                                                                   
                                                                                                                                                                   
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    CSMR_50                  
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    GtBioJet_50              
2020                                                                                                               .    DK1_Medium   .    GtBioJet_50              
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    GtMeOH_50                
2020                                                                                                               .    DK1_Medium   .    GtMeOH_50                
                                                                                                                                                                   
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    EMethanol_synthesis      
2020                                                                                                               .    DK1_Large    .    EMethanol_Upgrade        
2020                                                                                                               .    DK1_Large    .    E_FT                     
2020                                                                                                               .    DK1_Large    .    Ammonia_Synthesis        
2020                                                                                                               .    DK1_Large    .    CO2_PH                   
2020                                                                                                               .    DK1_Large    .    CO2_IND                  
2020                                                                                                               .    DK1_Large    .    CO2_DAC                  
2020                                                                                                               .    DK1_Large    .    CO2_Bio                  
2020                                                                                                               .    DK1_Large    .    CO2_STO                  
2020                                                                                                               .    DK1_Large    .    CO2_Bio_Pot              
2020                                                                                                               .    DK1_Large    .    HTL_ST                   
2020                                                                                                               .    DK1_Large    .    HTL_WO                   
2020                                                                                                               .    DK1_Large    .    HTL_WP                   
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    CO2_PH                   
2020                                                                                                               .    DK1_Medium   .    CO2_IND                  
2020                                                                                                               .    DK1_Medium   .    CO2_DAC                  
2020                                                                                                               .    DK1_Medium   .    CO2_STO                  
2020                                                                                                               .    DK1_Medium   .    CO2_Bio                  
2020                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot              
                                                                                                                                                                   
2020                                                                                                               .    DK1_Small    .    CO2_Bio                  
2020                                                                                                               .    DK1_Small    .    CO2_Bio_Pot              
                                                                                                                                                                   
2020                                                                                                               .    DK1_MedSmall .    CO2_Bio                  
2020                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot              
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_50_WO    
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_50_WP    
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_50_ST    
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_50_WO   
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_50_WP   
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_50_ST   
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    TG_50_WO                 
2020                                                                                                               .    DK1_Large    .    TG_50_WP                 
2020                                                                                                               .    DK1_Large    .    TG_50_ST                 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_50  
2020                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_50 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    Ethanol_50               
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    BioJet_50_ST             
2020                                                                                                               .    DK1_Large    .    BioJet_50_WO             
2020                                                                                                               .    DK1_Large    .    BioJet_50_WP             
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    BioJet_50_ST_H2          
2020                                                                                                               .    DK1_Large    .    BioJet_50_WO_H2          
2020                                                                                                               .    DK1_Large    .    BioJet_50_WP_H2          
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    Electrolysis_H2Prod      
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large       
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_50_WO   
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_50_WP   
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_50_ST   
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    TG_50_WO                 
2020                                                                                                               .    DK1_Medium   .    TG_50_WP                 
2020                                                                                                               .    DK1_Medium   .    TG_50_ST                 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_50_WO
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_50_WP
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_50_ST
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Straw_pre_BG             
2020                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG       
2020                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG        
2020                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG       
2020                                                                                                               .    DK1_Medium   .    Manure_tank              
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO          
                                                                                                                                                                   
2020                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_50      
2020                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_50      
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Electrolysis_H2Prod      
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large       
2020                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Small       
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_50  
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Ethanol_50               
                                                                                                                                                                   
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_50_WO
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_50_WP
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_50_ST
                                                                                                                                                                   
2020                                                                                                               .    DK1_MedSmall .    Straw_pre_BG             
2020                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG       
2020                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG        
2020                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG       
2020                                                                                                               .    DK1_MedSmall .    Manure_tank              
2020                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO          
2020                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_50      
2020                                                                                                               .    DK1_MedSmall .    Electrolysis_H2Prod      
2020                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small       
2020                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_50_WO
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_50_WP
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_50_ST
                                                                                                                                                                   
2020                                                                                                               .    DK1_Small    .    Straw_pre_BG             
2020                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG       
2020                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG        
2020                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG       
2020                                                                                                               .    DK1_Small    .    Manure_tank              
                                                                                                                                                                   
2020                                                                                                               .    DK1_Small    .    Biogas_Grid_STO          
2020                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_50      
2020                                                                                                               .    DK1_Small    .    Electrolysis_H2Prod      
2020                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small       
2020                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas 
                                                                                                                                                                   
2020                                                                                                               .    DK1_Medium   .    Engine_Syngas_50         
2020                                                                                                               .    DK1_Medium   .    Engine_Biogas_50         
                                                                                                                                                                   
2020                                                                                                               .    DK1_MedSmall .    Engine_Syngas_50         
2020                                                                                                               .    DK1_MedSmall .    Engine_Biogas_50         
                                                                                                                                                                   
2020                                                                                                               .    DK1_Small    .    Engine_Syngas_50         
2020                                                                                                               .    DK1_Small    .    Engine_Biogas_50         
                                                                                                                                                                   
/                                                                                                                                                                  
;                                                                                                                                                                  
                                                                                                                                                                   
APROCKAPNEW(Y,'DK2_Large',PROC)=APROCKAPNEW(Y,'DK1_Large',PROC);                                                                                                   
APROCKAPNEW(Y,'DK2_Medium',PROC)=APROCKAPNEW(Y,'DK1_Medium',PROC);                                                                                                 
APROCKAPNEW(Y,'DK2_MedSmall',PROC)=APROCKAPNEW(Y,'DK1_MedSmall',PROC);                                                                                             
APROCKAPNEW(Y,'DK2_Small',PROC)=APROCKAPNEW(Y,'DK1_Small',PROC);                                                                                                   
                                                                                                                                                                   
APROCKAPNEW(Y,'DK1_Rural',PROC)=APROCKAPNEW(Y,'DK1_Small',PROC);                                                                                                   
APROCKAPNEW(Y,'DK2_Rural',PROC)=APROCKAPNEW(Y,'DK2_Small',PROC);                                                                                                   
                                                                                                                                                                   
APROCKAPNEW(Y,AAA,PROC)=APROCKAPNEW('2020',AAA,PROC);                                                                                                              
