PARAMETER APKNDISCPDATA(PROC,APKNDISCPSIZESET,APKNDISCPDATASET) "Investment data for discrete Process capacity size investments (addon apkndisc)"
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
;                                                                                                                                                
