                                              
                                              
SET TECH_GROUP           'Technology Groups'  
/                                             
                                              
ResA                                          
ResB                                          
ResC                                          
ResD                                          
                                              
ProA                                          
ProB                                          
ProD                                          
                                              
StoA                                          
StoD                                          
                                              
Sum                                           
Demand                                        
                                              
Wood                                          
Straw                                         
Muni_Waste                                    
Wood_Pellets                                  
Manure                                        
Deep_Litter                                   
Food_Waste                                    
Nature_Area                                   
Excess_Heat_OptiFlow                          
EMethanolBuffer                               
EMethanol_Upgrade                             
E_FT                                          
AmmoniaBuffer                                 
CO2_PH                                        
CO2_IND                                       
CO2_DAC                                       
CO2_Bio                                       
EME_GasolineBuffer                            
EME_JetBuffer                                 
EME_LPGBuffer                                 
HTLBuffer                                     
E_FT_JetBuffer                                
E_FT_DieselBuffer                             
MethanolBuffer                                
BioGasolineBuffer                             
BiodieselBuffer                               
BioJetBuffer                                  
EthanolBuffer                                 
BioJet                                        
Ethanol                                       
Methane_synthesis                             
Methanol_synthesis                            
Gasifier                                      
Biodiesel                                     
SNG                                           
SYNGAS                                        
Pre-process-BG                                
Biogas                                        
BiogasUpgr                                    
Methanation_Biogas                            
Biogasoline                                   
Hydrogen                                      
BioOil                                        
OtherGas








                            
/;                                            
                                              
