PARAMETER PROCEXIM_ENDO_FUEL(PROC, FLOW) 'Subset of (PROCEXIM,FLOWEXIM) where onboard fuel use is endogenised as relative efficiency loss'                                          
/                                                                                                                                                                                   
ProcExim_Ship_Oil                                                                                                                          .    E_FT_DIESEL_FLOW 6.896059951582E-006
ProcExim_Ship_Methanol                                                                                                                     .    METHANOLFLOW     9.227507119579E-006
ProcExim_Ship_Methanol                                                                                                                     .    EMETHANOLFLOW    9.227507119579E-006
ProcExim_Ship_Ammonia                                                                                                                      .    AMMONIA_FLOW     2.264809371484E-005
ProcExim_Ship_Hydrogen                                                                                                                     .    HYDROGEN_FLOW    3.383891649158E-005
/;                                                                                                                                                                                  
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
