PARAMETER MAXFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                                                                          
/                                                                                                                                                                    
2030                                                                                                     .    AL_A    .    Manure_Gen .    MANURE_GEN_FLOW 1822000   
2030                                                                                                     .    AT_A    .    Manure_Gen .    MANURE_GEN_FLOW 7721000   
2030                                                                                                     .    BE_A    .    Manure_Gen .    MANURE_GEN_FLOW 47612000  
2030                                                                                                     .    BA_A    .    Manure_Gen .    MANURE_GEN_FLOW 1641000   
2030                                                                                                     .    BG_A    .    Manure_Gen .    MANURE_GEN_FLOW 5500000   
2030                                                                                                     .    HR_A    .    Manure_Gen .    MANURE_GEN_FLOW 3276900   
2030                                                                                                     .    CY_A    .    Manure_Gen .    MANURE_GEN_FLOW 4001000   
2030                                                                                                     .    CZ_A    .    Manure_Gen .    MANURE_GEN_FLOW 49609000  
2030                                                                                                     .    DK011_A .    Manure_Gen .    MANURE_GEN_FLOW 5242700   
2030                                                                                                     .    DK012_A .    Manure_Gen .    MANURE_GEN_FLOW 7695400   
2030                                                                                                     .    DK013_A .    Manure_Gen .    MANURE_GEN_FLOW 4294700   
2030                                                                                                     .    DK014_A .    Manure_Gen .    MANURE_GEN_FLOW 8645800   
2030                                                                                                     .    DK021_A .    Manure_Gen .    MANURE_GEN_FLOW 8018400   
2030                                                                                                     .    DK022_A .    Manure_Gen .    MANURE_GEN_FLOW 734900    
2030                                                                                                     .    DK031_A .    Manure_Gen .    MANURE_GEN_FLOW 531700    
2030                                                                                                     .    DK032_A .    Manure_Gen .    MANURE_GEN_FLOW 449700    
2030                                                                                                     .    DK041_A .    Manure_Gen .    MANURE_GEN_FLOW 39600     
2030                                                                                                     .    DK042_A .    Manure_Gen .    MANURE_GEN_FLOW 2336500   
2030                                                                                                     .    DK050_A .    Manure_Gen .    MANURE_GEN_FLOW 5589500   
2030                                                                                                     .    EE_A    .    Manure_Gen .    MANURE_GEN_FLOW 8100000   
2030                                                                                                     .    FI193_A .    Manure_Gen .    MANURE_GEN_FLOW 566100    
2030                                                                                                     .    FI194_A .    Manure_Gen .    MANURE_GEN_FLOW 397600    
2030                                                                                                     .    FI195_A .    Manure_Gen .    MANURE_GEN_FLOW 397600    
2030                                                                                                     .    FI196_A .    Manure_Gen .    MANURE_GEN_FLOW 460500    
2030                                                                                                     .    FI197_A .    Manure_Gen .    MANURE_GEN_FLOW 1034900   
2030                                                                                                     .    FI1B1_A .    Manure_Gen .    MANURE_GEN_FLOW 949500    
2030                                                                                                     .    FI1C1_A .    Manure_Gen .    MANURE_GEN_FLOW 424400    
2030                                                                                                     .    FI1C2_A .    Manure_Gen .    MANURE_GEN_FLOW 157400    
2030                                                                                                     .    FI1C3_A .    Manure_Gen .    MANURE_GEN_FLOW 181400    
2030                                                                                                     .    FI1C4_A .    Manure_Gen .    MANURE_GEN_FLOW 161500    
2030                                                                                                     .    FI1C5_A .    Manure_Gen .    MANURE_GEN_FLOW 118300    
2030                                                                                                     .    FI1D1_A .    Manure_Gen .    MANURE_GEN_FLOW 210700    
2030                                                                                                     .    FI1D2_A .    Manure_Gen .    MANURE_GEN_FLOW 345300    
2030                                                                                                     .    FI1D3_A .    Manure_Gen .    MANURE_GEN_FLOW 229700    
2030                                                                                                     .    FI1D4_A .    Manure_Gen .    MANURE_GEN_FLOW 105800    
2030                                                                                                     .    FI1D5_A .    Manure_Gen .    MANURE_GEN_FLOW 95700     
2030                                                                                                     .    FI1D6_A .    Manure_Gen .    MANURE_GEN_FLOW 567900    
2030                                                                                                     .    FI1D7_A .    Manure_Gen .    MANURE_GEN_FLOW 252700    
2030                                                                                                     .    FI200_A .    Manure_Gen .    MANURE_GEN_FLOW 13500     
2030                                                                                                     .    FR_A    .    Manure_Gen .    MANURE_GEN_FLOW 258705000 
2030                                                                                                     .    DE4-E_A .    Manure_Gen .    MANURE_GEN_FLOW 29100000  
2030                                                                                                     .    DE4-N_A .    Manure_Gen .    MANURE_GEN_FLOW 9700000   
2030                                                                                                     .    DE4-S_A .    Manure_Gen .    MANURE_GEN_FLOW 20400000  
2030                                                                                                     .    DE4-W_A .    Manure_Gen .    MANURE_GEN_FLOW 43100000  
2030                                                                                                     .    GR_A    .    Manure_Gen .    MANURE_GEN_FLOW 7393000   
2030                                                                                                     .    HU_A    .    Manure_Gen .    MANURE_GEN_FLOW 62792000  
2030                                                                                                     .    IE_A    .    Manure_Gen .    MANURE_GEN_FLOW 18101000  
2030                                                                                                     .    ITC_A   .    Manure_Gen .    MANURE_GEN_FLOW 62200000  
2030                                                                                                     .    ITF_A   .    Manure_Gen .    MANURE_GEN_FLOW 6400000   
2030                                                                                                     .    ITG_A   .    Manure_Gen .    MANURE_GEN_FLOW 3300000   
2030                                                                                                     .    ITH_A   .    Manure_Gen .    MANURE_GEN_FLOW 39500000  
2030                                                                                                     .    ITI_A   .    Manure_Gen .    MANURE_GEN_FLOW 8200000   
2030                                                                                                     .    LV_A    .    Manure_Gen .    MANURE_GEN_FLOW 7401000   
2030                                                                                                     .    LT_A    .    Manure_Gen .    MANURE_GEN_FLOW 12700000  
2030                                                                                                     .    LU_A    .    Manure_Gen .    MANURE_GEN_FLOW 1521900   
2030                                                                                                     .    MT_A    .    Manure_Gen .    MANURE_GEN_FLOW 407000    
2030                                                                                                     .    ME_A    .    Manure_Gen .    MANURE_GEN_FLOW 300000    
2030                                                                                                     .    NL_A    .    Manure_Gen .    MANURE_GEN_FLOW 48769000  
2030                                                                                                     .    MK_A    .    Manure_Gen .    MANURE_GEN_FLOW 703000    
2030                                                                                                     .    NO020_A .    Manure_Gen .    MANURE_GEN_FLOW 22300     
2030                                                                                                     .    NO060_A .    Manure_Gen .    MANURE_GEN_FLOW 27600     
2030                                                                                                     .    NO071_A .    Manure_Gen .    MANURE_GEN_FLOW 14600     
2030                                                                                                     .    NO072_A .    Manure_Gen .    MANURE_GEN_FLOW 10000     
2030                                                                                                     .    NO073_A .    Manure_Gen .    MANURE_GEN_FLOW 4600      
2030                                                                                                     .    NO081_A .    Manure_Gen .    MANURE_GEN_FLOW 40500     
2030                                                                                                     .    NO083_A .    Manure_Gen .    MANURE_GEN_FLOW 18800     
2030                                                                                                     .    NO084_A .    Manure_Gen .    MANURE_GEN_FLOW 43800     
2030                                                                                                     .    NO085_A .    Manure_Gen .    MANURE_GEN_FLOW 16200     
2030                                                                                                     .    NO092_A .    Manure_Gen .    MANURE_GEN_FLOW 18200     
2030                                                                                                     .    NO093_A .    Manure_Gen .    MANURE_GEN_FLOW 15400     
2030                                                                                                     .    NO094_A .    Manure_Gen .    MANURE_GEN_FLOW 10500     
2030                                                                                                     .    NO0A1_A .    Manure_Gen .    MANURE_GEN_FLOW 28400     
2030                                                                                                     .    NO0A2_A .    Manure_Gen .    MANURE_GEN_FLOW 37900     
2030                                                                                                     .    NO0A3_A .    Manure_Gen .    MANURE_GEN_FLOW 37900     
2030                                                                                                     .    PL_A    .    Manure_Gen .    MANURE_GEN_FLOW 71160000  
2030                                                                                                     .    PT_A    .    Manure_Gen .    MANURE_GEN_FLOW 22088000  
2030                                                                                                     .    RO_A    .    Manure_Gen .    MANURE_GEN_FLOW 22816000  
2030                                                                                                     .    RS_A    .    Manure_Gen .    MANURE_GEN_FLOW 10502000  
2030                                                                                                     .    SK_A    .    Manure_Gen .    MANURE_GEN_FLOW 13701000  
2030                                                                                                     .    SI_A    .    Manure_Gen .    MANURE_GEN_FLOW 1448000   
2030                                                                                                     .    ES_A    .    Manure_Gen .    MANURE_GEN_FLOW 100580000 
2030                                                                                                     .    SE110_A .    Manure_Gen .    MANURE_GEN_FLOW 360500    
2030                                                                                                     .    SE121_A .    Manure_Gen .    MANURE_GEN_FLOW 773000    
2030                                                                                                     .    SE122_A .    Manure_Gen .    MANURE_GEN_FLOW 621700    
2030                                                                                                     .    SE123_A .    Manure_Gen .    MANURE_GEN_FLOW 979400    
2030                                                                                                     .    SE124_A .    Manure_Gen .    MANURE_GEN_FLOW 638300    
2030                                                                                                     .    SE125_A .    Manure_Gen .    MANURE_GEN_FLOW 579700    
2030                                                                                                     .    SE211_A .    Manure_Gen .    MANURE_GEN_FLOW 1749100   
2030                                                                                                     .    SE212_A .    Manure_Gen .    MANURE_GEN_FLOW 960900    
2030                                                                                                     .    SE213_A .    Manure_Gen .    MANURE_GEN_FLOW 1197000   
2030                                                                                                     .    SE214_A .    Manure_Gen .    MANURE_GEN_FLOW 290900    
2030                                                                                                     .    SE221_A .    Manure_Gen .    MANURE_GEN_FLOW 381500    
2030                                                                                                     .    SE224_A .    Manure_Gen .    MANURE_GEN_FLOW 3189500   
2030                                                                                                     .    SE231_A .    Manure_Gen .    MANURE_GEN_FLOW 708500    
2030                                                                                                     .    SE232_A .    Manure_Gen .    MANURE_GEN_FLOW 3721700   
2030                                                                                                     .    SE311_A .    Manure_Gen .    MANURE_GEN_FLOW 362100    
2030                                                                                                     .    SE312_A .    Manure_Gen .    MANURE_GEN_FLOW 367600    
2030                                                                                                     .    SE313_A .    Manure_Gen .    MANURE_GEN_FLOW 369100    
2030                                                                                                     .    SE321_A .    Manure_Gen .    MANURE_GEN_FLOW 357400    
2030                                                                                                     .    SE322_A .    Manure_Gen .    MANURE_GEN_FLOW 186400    
2030                                                                                                     .    SE331_A .    Manure_Gen .    MANURE_GEN_FLOW 338300    
2030                                                                                                     .    SE332_A .    Manure_Gen .    MANURE_GEN_FLOW 322400    
2030                                                                                                     .    CH_A    .    Manure_Gen .    MANURE_GEN_FLOW 31728800  
2030                                                                                                     .    TR_A    .    Manure_Gen .    MANURE_GEN_FLOW 0         
2030                                                                                                     .    UK_GB_A .    Manure_Gen .    MANURE_GEN_FLOW 139189000 
2030                                                                                                     .    UK_NI_A .    Manure_Gen .    MANURE_GEN_FLOW 18000000  
/;                                                                                                                                                                   
                                                                                                                                                                     
*Limit on fossil CO2 in fuel production                                                                                                                              
MAXFLOW('2040',AAAOPTIFLOW,'CO2_Grid_Out','CO2_FLOW_FOSSIL_CU')=EPS;                                                                                                 
MAXFLOW('2050',AAAOPTIFLOW,'CO2_Grid_Out','CO2_FLOW_FOSSIL_CU')=EPS;                                                                                                 
                                                                                                                                                                     
*Manure limit                                                                                                                                                        
MAXFLOW('2035',AAA,'Manure_Gen','MANURE_GEN_FLOW') = MAXFLOW('2030',AAA,'Manure_Gen','MANURE_GEN_FLOW');                                                             
MAXFLOW('2040',AAA,'Manure_Gen','MANURE_GEN_FLOW') = MAXFLOW('2030',AAA,'Manure_Gen','MANURE_GEN_FLOW');                                                             
MAXFLOW('2045',AAA,'Manure_Gen','MANURE_GEN_FLOW') = MAXFLOW('2030',AAA,'Manure_Gen','MANURE_GEN_FLOW');                                                             
MAXFLOW('2050',AAA,'Manure_Gen','MANURE_GEN_FLOW') = MAXFLOW('2030',AAA,'Manure_Gen','MANURE_GEN_FLOW');                                                             
