SET TECH_GROUP "Technology Groups"
                                  
/                                 
CO2_DAC                           
CO2_Accumulator                   
CO2_Pipeline                      
OCC                               
CO2_Seq_On                        
CO2_Seq_Off                       
Manure_Tank                       
Straw_Tank                        
Biogas_Grid_Sto                   
Methanation                       
Biogas_Upgrading                  
Pyrolysis_Straw                   
Hydrogen_STO_Large                
Hydrogen_STO_Small                
TG                                
Methanol_synthesis_TG             
EMethanol_synthesis               
EMethanol_Upgrade                 
Ammonia_Synthesis                 
BioJet                            
BioJet_H2                         
E_FT                              
/;                                
