SET PROCDATASET  'Process data types'                                            
/                                                                                
  PROCINVCOST         'Investment cost (MMoney/(U/h))'                           
  PROCKAPVARIABLE     'Capacity is a variable to be found for each year (1/0) ()'
  PROCFROMYEAR        'Process available from this year ()'                      
  PROCLIFETIME        'Economic lifetime (years)'                                
  PROCFIXCOST         'Fix Operational Cost (Money/(U/h)/year)'                  
                                                                                 
                                                                                 
                                                                                 
/;                                                                               
