SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
CO2_Source_Biogen                                    
CO2_Source_DAC                                       
CO2_Source_Fossil                                    
DieselSource                                         
HydrogenSource_MWh                                   
KeroseneSource                                       
MDOSource                                            
Straw_Gen                                            
Wood_Gen                                             
Manure_Gen                                           
/;                                                   
