TABLE SOSIBU2INDIC_A(AAA,PROC,FLOW,FLOWINDIC) "Coefficients for transformation of VSOURCE, VSINK and VBUFFER flows to FLOWINDIC values"
                                                                                                                                       
                                                                                                                                       
                                                                                                                                       
                                                                                                                                       
;                                                                                                                                      
