SET PROCBUFFER(PROC) "Buffer processes (trace entering and/or leaving)"
/                                                                      
ElecBuffer                                                             
HeatBuffer                                                             
GHG_Buffer                                                             
GHGbio_Buffer                                                          
Gas_Buffer                                                             
/;                                                                     
