SET  PROCKAPDATA(YYY,PROC,FLOW,IFLOWINOUT)    "Process data: capacity relative to FLOW and in/out direction ()"                                                                               
/                                                                                                                                                                                             
2020                                                                                                            .    ProA                      .    ResProA                .    IFLOWINOUT_IN 
2020                                                                                                            .    StoA                      .    ProStoA                .    IFLOWINOUT_IN 
2020                                                                                                            .    ProB                      .    ResProB                .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    ProD                      .    ResProD                .    IFLOWINOUT_IN 
2020                                                                                                            .    StoD                      .    ProStoD                .    IFLOWINOUT_IN 
                                                                                                                                                                                              
                                                                                                                                                                                              
2020                                                                                                            .    CSMR_50                   .    NATGAS_FLOW            .    IFLOWINOUT_IN 
2020                                                                                                            .    GtBioJet_50               .    GASFLOW_GtBJ           .    IFLOWINOUT_IN 
2020                                                                                                            .    GtMeOH_50                 .    GASFLOW_GtMeOH         .    IFLOWINOUT_IN 
                                                                                                                                                                                              
                                                                                                                                                                                              
2020                                                                                                            .    CO2_PH                    .    ELECFLOW_GJ            .    IFLOWINOUT_IN 
2020                                                                                                            .    CO2_Bio                   .    ELECFLOW_GJ            .    IFLOWINOUT_IN 
2020                                                                                                            .    CO2_IND                   .    ELECFLOW_GJ            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    CO2_DAC                   .    CO2_FLOW_DAC           .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Sto                   .    CO2_FLOW_STO           .    IFLOWINOUT_IN 
2020                                                                                                            .    EMethanol_synthesis       .    EMETHANOLFLOW          .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade         .    EME_DROPIN_FLOW        .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT                      .    E_FT_SUM_FLOW          .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis         .    AMMONIA_FLOW           .    IFLOWINOUT_OUT
2020                                                                                                            .    HTL_ST                    .    HTLFLOW_ST             .    IFLOWINOUT_OUT
2020                                                                                                            .    HTL_WO                    .    HTLFLOW_WO             .    IFLOWINOUT_OUT
2020                                                                                                            .    HTL_WP                    .    HTLFLOW_WP             .    IFLOWINOUT_OUT
                                                                                                                                                                                              
2020                                                                                                            .    BioJet_50_ST              .    STRAW_GJ_BJ            .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_50_WO              .    WOOD_GJ_BJ             .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_50_WP              .    WOOD_PELLETS_GJ_BJ     .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    BioJet_50_ST_H2           .    STRAW_GJ_BJ_H2         .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_50_WO_H2           .    WOOD_GJ_BJ_H2          .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_50_WP_H2           .    WOOD_PELLETS_GJ_BJ_H2  .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    TG_FT_Biodiesel_50_WO     .    WOOD_GJ_FT             .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_FT_Biodiesel_50_WP     .    WOOD_PELLETS_GJ_FT     .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_FT_Biodiesel_50_ST     .    STRAW_GJ_FT            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    ThermGasific_SNG_50_WO    .    WOOD_GJ_SNG            .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_SNG_50_WP    .    WOOD_PELLETS_GJ_SNG    .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_SNG_50_ST    .    STRAW_GJ_SNG           .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_SNG_50_MW    .    MUNI_WASTE_GJ_SNG      .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    ThermGasific_Syngas_50_WO .    WOOD_GJ_SYNGAS         .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_Syngas_50_WP .    WOOD_PELLETS_GJ_SYNGAS .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_Syngas_50_ST .    STRAW_GJ_SYNGAS        .    IFLOWINOUT_IN 
2020                                                                                                            .    ThermGasific_Syngas_50_MW .    MUNI_WASTE_GJ_SYNGAS   .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    TG_50_WO                  .    WOOD_GJ_TG             .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_50_WP                  .    WOOD_PELLETS_GJ_TG     .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_50_ST                  .    STRAW_GJ_TG            .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_50_MW                  .    MUNI_WASTE_GJ_TG       .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Ethanol_50                .    STRAW_GJ_ET            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Straw_pre_BG              .    STRAW_GJ_BIOGAS        .    IFLOWINOUT_IN 
2020                                                                                                            .    Deep_Litter_pre_BG        .    DEEP_LITTER_GEN_FLOW   .    IFLOWINOUT_IN 
2020                                                                                                            .    Food_Waste_pre_BG         .    FOOD_WASTE_GEN_FLOW    .    IFLOWINOUT_IN 
2020                                                                                                            .    Nature_Area_pre_BG        .    NATURE_AREA_GEN_FLOW   .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank               .    MANURE_GEN_FLOW        .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Biogas_Grid_STO           .    BIOGAS_FLOW_STO        .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    BiogasUpgr_BMETH_50       .    BIOGAS_FLOW            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Electrolysis_H2Prod       .    ELECFLOW_GJ            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Hydrogen_STO_Large        .    HYDROGEN_FLOW_ST_Large .    IFLOWINOUT_IN 
2020                                                                                                            .    Hydrogen_STO_Small        .    HYDROGEN_FLOW_ST_Small .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Methanisation_Bio_BioGas  .    BIOGAS_FLOW            .    IFLOWINOUT_IN 
2020                                                                                                            .    Methane_synthesis_TG_50   .    BIO_TG_FLOW            .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_50  .    BIO_ME_FLOW            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
2020                                                                                                            .    Engine_Syngas_50          .    BIO_SYNGAS_FLOW        .    IFLOWINOUT_IN 
2020                                                                                                            .    Engine_Biogas_50          .    BIOGAS_FLOW            .    IFLOWINOUT_IN 
                                                                                                                                                                                              
                                                                                                                                                                                              
/                                                                                                                                                                                             
;                                                                                                                                                                                             
                                                                                                                                                                                              
PROCKAPDATA(YYY,PROC,FLOW,IFLOWINOUT)=PROCKAPDATA('2020',PROC,FLOW,IFLOWINOUT);                                                                                                               
