SET PROCSTORAGE(PROC) "Storage processes"
                                         
/                                        
                                         
StoA                                     
StoD                                     
                                         
Hydrogen_STO_Large                       
Hydrogen_STO_Small                       
Biogas_Grid_STO                          
CO2_Sto                                  
/;                                       
