SET APROCKAPNEW(YYY,AAA,PROC)     'Areas for possible location of new Proc or capacity expansion of existing Proc'                                                                      
*This is stablished according to economy of scale, where large plants can only be located when heat demand is high                                                                      
                                                                                                                                                                                        
/                                                                                                                                                                                       
2020                                                                                                               .    DK1_Large    .    ProA                                          
2020                                                                                                               .    DK1_Medium   .    ProA                                          
2020                                                                                                               .    DK1_MedSmall .    ProA                                          
2020                                                                                                               .    DK1_Small    .    ProA                                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    StoA                                          
2020                                                                                                               .    DK1_Medium   .    StoA                                          
2020                                                                                                               .    DK1_MedSmall .    StoA                                          
2020                                                                                                               .    DK1_Small    .    StoA                                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ProD                                          
2020                                                                                                               .    DK1_Medium   .    ProD                                          
2020                                                                                                               .    DK1_MedSmall .    ProD                                          
2020                                                                                                               .    DK1_Small    .    ProD                                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    StoD                                          
2020                                                                                                               .    DK1_Medium   .    StoD                                          
2020                                                                                                               .    DK1_MedSmall .    StoD                                          
2020                                                                                                               .    DK1_Small    .    StoD                                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ProB                                          
2020                                                                                                               .    DK1_Medium   .    ProB                                          
2020                                                                                                               .    DK1_MedSmall .    ProB                                          
2020                                                                                                               .    DK1_Small    .    ProB                                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Straw_pre_BG_20                               
2025                                                                                                               .    DK1_Medium   .    Straw_pre_BG_25                               
2030                                                                                                               .    DK1_Medium   .    Straw_pre_BG_30                               
2035                                                                                                               .    DK1_Medium   .    Straw_pre_BG_35                               
2040                                                                                                               .    DK1_Medium   .    Straw_pre_BG_40                               
2045                                                                                                               .    DK1_Medium   .    Straw_pre_BG_45                               
2050                                                                                                               .    DK1_Medium   .    Straw_pre_BG_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_20                         
2025                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_25                         
2030                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_30                         
2035                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_35                         
2040                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_40                         
2045                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_45                         
2050                                                                                                               .    DK1_Medium   .    Deep_Litter_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_20                          
2025                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_25                          
2030                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_30                          
2035                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_35                          
2040                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_40                          
2045                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_45                          
2050                                                                                                               .    DK1_Medium   .    Food_Waste_pre_BG_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_20                         
2025                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_25                         
2030                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_30                         
2035                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_35                         
2040                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_40                         
2045                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_45                         
2050                                                                                                               .    DK1_Medium   .    Nature_Area_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Manure_tank_20                                
2025                                                                                                               .    DK1_Medium   .    Manure_tank_25                                
2030                                                                                                               .    DK1_Medium   .    Manure_tank_30                                
2035                                                                                                               .    DK1_Medium   .    Manure_tank_35                                
2040                                                                                                               .    DK1_Medium   .    Manure_tank_40                                
2045                                                                                                               .    DK1_Medium   .    Manure_tank_45                                
2050                                                                                                               .    DK1_Medium   .    Manure_tank_50                                
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_20                               
2025                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_25                               
2030                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_30                               
2035                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_35                               
2040                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_40                               
2045                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_45                               
2050                                                                                                               .    DK1_MedSmall .    Straw_pre_BG_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_20                         
2025                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_25                         
2030                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_30                         
2035                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_35                         
2040                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_40                         
2045                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_45                         
2050                                                                                                               .    DK1_MedSmall .    Deep_Litter_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_20                          
2025                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_25                          
2030                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_30                          
2035                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_35                          
2040                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_40                          
2045                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_45                          
2050                                                                                                               .    DK1_MedSmall .    Food_Waste_pre_BG_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_20                         
2025                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_25                         
2030                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_30                         
2035                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_35                         
2040                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_40                         
2045                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_45                         
2050                                                                                                               .    DK1_MedSmall .    Nature_Area_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Manure_tank_20                                
2025                                                                                                               .    DK1_MedSmall .    Manure_tank_25                                
2030                                                                                                               .    DK1_MedSmall .    Manure_tank_30                                
2035                                                                                                               .    DK1_MedSmall .    Manure_tank_35                                
2040                                                                                                               .    DK1_MedSmall .    Manure_tank_40                                
2045                                                                                                               .    DK1_MedSmall .    Manure_tank_45                                
2050                                                                                                               .    DK1_MedSmall .    Manure_tank_50                                
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Straw_pre_BG_20                               
2025                                                                                                               .    DK1_Small    .    Straw_pre_BG_25                               
2030                                                                                                               .    DK1_Small    .    Straw_pre_BG_30                               
2035                                                                                                               .    DK1_Small    .    Straw_pre_BG_35                               
2040                                                                                                               .    DK1_Small    .    Straw_pre_BG_40                               
2045                                                                                                               .    DK1_Small    .    Straw_pre_BG_45                               
2050                                                                                                               .    DK1_Small    .    Straw_pre_BG_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_20                         
2025                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_25                         
2030                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_30                         
2035                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_35                         
2040                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_40                         
2045                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_45                         
2050                                                                                                               .    DK1_Small    .    Deep_Litter_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_20                          
2025                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_25                          
2030                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_30                          
2035                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_35                          
2040                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_40                          
2045                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_45                          
2050                                                                                                               .    DK1_Small    .    Food_Waste_pre_BG_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_20                         
2025                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_25                         
2030                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_30                         
2035                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_35                         
2040                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_40                         
2045                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_45                         
2050                                                                                                               .    DK1_Small    .    Nature_Area_pre_BG_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Manure_tank_20                                
2025                                                                                                               .    DK1_Small    .    Manure_tank_25                                
2030                                                                                                               .    DK1_Small    .    Manure_tank_30                                
2035                                                                                                               .    DK1_Small    .    Manure_tank_35                                
2040                                                                                                               .    DK1_Small    .    Manure_tank_40                                
2045                                                                                                               .    DK1_Small    .    Manure_tank_45                                
2050                                                                                                               .    DK1_Small    .    Manure_tank_50                                
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_DAC_20                                    
2025                                                                                                               .    DK1_Large    .    CO2_DAC_25                                    
2030                                                                                                               .    DK1_Large    .    CO2_DAC_30                                    
2035                                                                                                               .    DK1_Large    .    CO2_DAC_35                                    
2040                                                                                                               .    DK1_Large    .    CO2_DAC_40                                    
2045                                                                                                               .    DK1_Large    .    CO2_DAC_45                                    
2050                                                                                                               .    DK1_Large    .    CO2_DAC_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_IND_20                                    
2025                                                                                                               .    DK1_Large    .    CO2_IND_25                                    
2030                                                                                                               .    DK1_Large    .    CO2_IND_30                                    
2035                                                                                                               .    DK1_Large    .    CO2_IND_35                                    
2040                                                                                                               .    DK1_Large    .    CO2_IND_40                                    
2045                                                                                                               .    DK1_Large    .    CO2_IND_45                                    
2050                                                                                                               .    DK1_Large    .    CO2_IND_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_PH_20                                     
2025                                                                                                               .    DK1_Large    .    CO2_PH_25                                     
2030                                                                                                               .    DK1_Large    .    CO2_PH_30                                     
2035                                                                                                               .    DK1_Large    .    CO2_PH_35                                     
2040                                                                                                               .    DK1_Large    .    CO2_PH_40                                     
2045                                                                                                               .    DK1_Large    .    CO2_PH_45                                     
2050                                                                                                               .    DK1_Large    .    CO2_PH_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_Bio_20                                    
2025                                                                                                               .    DK1_Large    .    CO2_Bio_25                                    
2030                                                                                                               .    DK1_Large    .    CO2_Bio_30                                    
2035                                                                                                               .    DK1_Large    .    CO2_Bio_35                                    
2040                                                                                                               .    DK1_Large    .    CO2_Bio_40                                    
2045                                                                                                               .    DK1_Large    .    CO2_Bio_45                                    
2050                                                                                                               .    DK1_Large    .    CO2_Bio_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_DAC_20                                    
2025                                                                                                               .    DK1_Medium   .    CO2_DAC_25                                    
2030                                                                                                               .    DK1_Medium   .    CO2_DAC_30                                    
2035                                                                                                               .    DK1_Medium   .    CO2_DAC_35                                    
2040                                                                                                               .    DK1_Medium   .    CO2_DAC_40                                    
2045                                                                                                               .    DK1_Medium   .    CO2_DAC_45                                    
2050                                                                                                               .    DK1_Medium   .    CO2_DAC_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_IND_20                                    
2025                                                                                                               .    DK1_Medium   .    CO2_IND_25                                    
2030                                                                                                               .    DK1_Medium   .    CO2_IND_30                                    
2035                                                                                                               .    DK1_Medium   .    CO2_IND_35                                    
2040                                                                                                               .    DK1_Medium   .    CO2_IND_40                                    
2045                                                                                                               .    DK1_Medium   .    CO2_IND_45                                    
2050                                                                                                               .    DK1_Medium   .    CO2_IND_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_PH_20                                     
2025                                                                                                               .    DK1_Medium   .    CO2_PH_25                                     
2030                                                                                                               .    DK1_Medium   .    CO2_PH_30                                     
2035                                                                                                               .    DK1_Medium   .    CO2_PH_35                                     
2040                                                                                                               .    DK1_Medium   .    CO2_PH_40                                     
2045                                                                                                               .    DK1_Medium   .    CO2_PH_45                                     
2050                                                                                                               .    DK1_Medium   .    CO2_PH_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_Bio_20                                    
2025                                                                                                               .    DK1_Medium   .    CO2_Bio_25                                    
2030                                                                                                               .    DK1_Medium   .    CO2_Bio_30                                    
2035                                                                                                               .    DK1_Medium   .    CO2_Bio_35                                    
2040                                                                                                               .    DK1_Medium   .    CO2_Bio_40                                    
2045                                                                                                               .    DK1_Medium   .    CO2_Bio_45                                    
2050                                                                                                               .    DK1_Medium   .    CO2_Bio_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    CO2_Bio_20                                    
2025                                                                                                               .    DK1_MedSmall .    CO2_Bio_25                                    
2030                                                                                                               .    DK1_MedSmall .    CO2_Bio_30                                    
2035                                                                                                               .    DK1_MedSmall .    CO2_Bio_35                                    
2040                                                                                                               .    DK1_MedSmall .    CO2_Bio_40                                    
2045                                                                                                               .    DK1_MedSmall .    CO2_Bio_45                                    
2050                                                                                                               .    DK1_MedSmall .    CO2_Bio_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    CO2_Bio_20                                    
2025                                                                                                               .    DK1_Small    .    CO2_Bio_25                                    
2030                                                                                                               .    DK1_Small    .    CO2_Bio_30                                    
2035                                                                                                               .    DK1_Small    .    CO2_Bio_35                                    
2040                                                                                                               .    DK1_Small    .    CO2_Bio_40                                    
2045                                                                                                               .    DK1_Small    .    CO2_Bio_45                                    
2050                                                                                                               .    DK1_Small    .    CO2_Bio_50                                    
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2025                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2030                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2035                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2040                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2045                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
2050                                                                                                               .    DK1_Large    .    CO2_Bio_Pot                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2025                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2030                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2035                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2040                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2045                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
2050                                                                                                               .    DK1_Medium   .    CO2_Bio_Pot                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2025                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2030                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2035                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2040                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2045                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
2050                                                                                                               .    DK1_MedSmall .    CO2_Bio_Pot                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2025                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2030                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2035                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2040                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2045                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
2050                                                                                                               .    DK1_Small    .    CO2_Bio_Pot                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CO2_STO                                       
2025                                                                                                               .    DK1_Large    .    CO2_STO                                       
2030                                                                                                               .    DK1_Large    .    CO2_STO                                       
2035                                                                                                               .    DK1_Large    .    CO2_STO                                       
2040                                                                                                               .    DK1_Large    .    CO2_STO                                       
2045                                                                                                               .    DK1_Large    .    CO2_STO                                       
2050                                                                                                               .    DK1_Large    .    CO2_STO                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2025                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2030                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2035                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2040                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2045                                                                                                               .    DK1_Medium   .    CO2_STO                                       
2050                                                                                                               .    DK1_Medium   .    CO2_STO                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_MW_20                                      
2025                                                                                                               .    DK1_Medium   .    TG_MW_25                                      
2030                                                                                                               .    DK1_Medium   .    TG_MW_30                                      
2035                                                                                                               .    DK1_Medium   .    TG_MW_35                                      
2040                                                                                                               .    DK1_Medium   .    TG_MW_40                                      
2045                                                                                                               .    DK1_Medium   .    TG_MW_45                                      
2050                                                                                                               .    DK1_Medium   .    TG_MW_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_ST_20                                      
2025                                                                                                               .    DK1_Medium   .    TG_ST_25                                      
2030                                                                                                               .    DK1_Medium   .    TG_ST_30                                      
2035                                                                                                               .    DK1_Medium   .    TG_ST_35                                      
2040                                                                                                               .    DK1_Medium   .    TG_ST_40                                      
2045                                                                                                               .    DK1_Medium   .    TG_ST_45                                      
2050                                                                                                               .    DK1_Medium   .    TG_ST_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_WO_20                                      
2025                                                                                                               .    DK1_Medium   .    TG_WO_25                                      
2030                                                                                                               .    DK1_Medium   .    TG_WO_30                                      
2035                                                                                                               .    DK1_Medium   .    TG_WO_35                                      
2040                                                                                                               .    DK1_Medium   .    TG_WO_40                                      
2045                                                                                                               .    DK1_Medium   .    TG_WO_45                                      
2050                                                                                                               .    DK1_Medium   .    TG_WO_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_WP_20                                      
2025                                                                                                               .    DK1_Medium   .    TG_WP_25                                      
2030                                                                                                               .    DK1_Medium   .    TG_WP_30                                      
2035                                                                                                               .    DK1_Medium   .    TG_WP_35                                      
2040                                                                                                               .    DK1_Medium   .    TG_WP_40                                      
2045                                                                                                               .    DK1_Medium   .    TG_WP_45                                      
2050                                                                                                               .    DK1_Medium   .    TG_WP_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_MW_20                                      
2025                                                                                                               .    DK1_Large    .    TG_MW_25                                      
2030                                                                                                               .    DK1_Large    .    TG_MW_30                                      
2035                                                                                                               .    DK1_Large    .    TG_MW_35                                      
2040                                                                                                               .    DK1_Large    .    TG_MW_40                                      
2045                                                                                                               .    DK1_Large    .    TG_MW_45                                      
2050                                                                                                               .    DK1_Large    .    TG_MW_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_ST_20                                      
2025                                                                                                               .    DK1_Large    .    TG_ST_25                                      
2030                                                                                                               .    DK1_Large    .    TG_ST_30                                      
2035                                                                                                               .    DK1_Large    .    TG_ST_35                                      
2040                                                                                                               .    DK1_Large    .    TG_ST_40                                      
2045                                                                                                               .    DK1_Large    .    TG_ST_45                                      
2050                                                                                                               .    DK1_Large    .    TG_ST_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_WO_20                                      
2025                                                                                                               .    DK1_Large    .    TG_WO_25                                      
2030                                                                                                               .    DK1_Large    .    TG_WO_30                                      
2035                                                                                                               .    DK1_Large    .    TG_WO_35                                      
2040                                                                                                               .    DK1_Large    .    TG_WO_40                                      
2045                                                                                                               .    DK1_Large    .    TG_WO_45                                      
2050                                                                                                               .    DK1_Large    .    TG_WO_50                                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_WP_20                                      
2025                                                                                                               .    DK1_Large    .    TG_WP_25                                      
2030                                                                                                               .    DK1_Large    .    TG_WP_30                                      
2035                                                                                                               .    DK1_Large    .    TG_WP_35                                      
2040                                                                                                               .    DK1_Large    .    TG_WP_40                                      
2045                                                                                                               .    DK1_Large    .    TG_WP_45                                      
2050                                                                                                               .    DK1_Large    .    TG_WP_50                                      
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_20                        
2025                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_25                        
2030                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_30                        
2035                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_35                        
2040                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_40                        
2045                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_45                        
2050                                                                                                               .    DK1_Large    .    ThermGasific_SNG_MW_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_20                        
2025                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_25                        
2030                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_30                        
2035                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_35                        
2040                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_40                        
2045                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_45                        
2050                                                                                                               .    DK1_Large    .    ThermGasific_SNG_ST_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_20                        
2025                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_25                        
2030                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_30                        
2035                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_35                        
2040                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_40                        
2045                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_45                        
2050                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WO_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_20                        
2025                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_25                        
2030                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_30                        
2035                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_35                        
2040                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_40                        
2045                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_45                        
2050                                                                                                               .    DK1_Large    .    ThermGasific_SNG_WP_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_20                        
2025                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_25                        
2030                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_30                        
2035                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_35                        
2040                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_40                        
2045                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_45                        
2050                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_MW_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_20                        
2025                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_25                        
2030                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_30                        
2035                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_35                        
2040                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_40                        
2045                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_45                        
2050                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_ST_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_20                        
2025                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_25                        
2030                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_30                        
2035                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_35                        
2040                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_40                        
2045                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_45                        
2050                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WO_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_20                        
2025                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_25                        
2030                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_30                        
2035                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_35                        
2040                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_40                        
2045                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_45                        
2050                                                                                                               .    DK1_Medium   .    ThermGasific_SNG_WP_50                        
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_20                     
2025                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_25                     
2030                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_30                     
2035                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_35                     
2040                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_40                     
2045                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_45                     
2050                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_MW_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_20                     
2025                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_25                     
2030                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_30                     
2035                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_35                     
2040                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_40                     
2045                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_45                     
2050                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_ST_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_20                     
2025                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_25                     
2030                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_30                     
2035                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_35                     
2040                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_40                     
2045                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_45                     
2050                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WO_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_20                     
2025                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_25                     
2030                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_30                     
2035                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_35                     
2040                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_40                     
2045                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_45                     
2050                                                                                                               .    DK1_Medium   .    ThermGasific_Syngas_WP_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_20                     
2025                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_25                     
2030                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_30                     
2035                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_35                     
2040                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_40                     
2045                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_45                     
2050                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_MW_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_20                     
2025                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_25                     
2030                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_30                     
2035                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_35                     
2040                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_40                     
2045                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_45                     
2050                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_ST_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_20                     
2025                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_25                     
2030                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_30                     
2035                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_35                     
2040                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_40                     
2045                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_45                     
2050                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WO_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_20                     
2025                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_25                     
2030                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_30                     
2035                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_35                     
2040                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_40                     
2045                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_45                     
2050                                                                                                               .    DK1_MedSmall .    ThermGasific_Syngas_WP_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_20                     
2025                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_25                     
2030                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_30                     
2035                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_35                     
2040                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_40                     
2045                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_45                     
2050                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_MW_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_20                     
2025                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_25                     
2030                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_30                     
2035                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_35                     
2040                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_40                     
2045                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_45                     
2050                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_ST_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_20                     
2025                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_25                     
2030                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_30                     
2035                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_35                     
2040                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_40                     
2045                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_45                     
2050                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WO_50                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_20                     
2025                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_25                     
2030                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_30                     
2035                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_35                     
2040                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_40                     
2045                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_45                     
2050                                                                                                               .    DK1_Small    .    ThermGasific_Syngas_WP_50                     
                                                                                                                                                                                        
                                                                                                                                                                                        
************meth                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_20                   
2025                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_25                   
2030                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_30                   
2035                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_35                   
2040                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_40                   
2045                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_45                   
2050                                                                                                               .    DK1_Medium   .    Methanisation_Bio_BioGas_50                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_20                   
2025                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_25                   
2030                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_30                   
2035                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_35                   
2040                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_40                   
2045                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_45                   
2050                                                                                                               .    DK1_MedSmall .    Methanisation_Bio_BioGas_50                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_20                   
2025                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_25                   
2030                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_30                   
2035                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_35                   
2040                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_40                   
2045                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_45                   
2050                                                                                                               .    DK1_Small    .    Methanisation_Bio_BioGas_50                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_20                       
2025                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_25                       
2030                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_30                       
2035                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_35                       
2040                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_40                       
2045                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_45                       
2050                                                                                                               .    DK1_Large    .    Methane_synthesis_TG_50                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_20                       
2025                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_25                       
2030                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_30                       
2035                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_35                       
2040                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_40                       
2045                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_45                       
2050                                                                                                               .    DK1_Medium   .    Methane_synthesis_TG_50                       
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_20                      
2025                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_25                      
2030                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_30                      
2035                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_35                      
2040                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_40                      
2045                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_45                      
2050                                                                                                               .    DK1_Large    .    Methanol_synthesis_TG_50                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_20                      
2025                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_25                      
2030                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_30                      
2035                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_35                      
2040                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_40                      
2045                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_45                      
2050                                                                                                               .    DK1_Medium   .    Methanol_synthesis_TG_50                      
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2025                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2030                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2035                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2040                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2045                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
2050                                                                                                               .    DK1_Medium   .    Biogas_Grid_STO                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2025                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2030                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2035                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2040                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2045                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
2050                                                                                                               .    DK1_MedSmall .    Biogas_Grid_STO                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2025                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2030                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2035                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2040                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2045                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
2050                                                                                                               .    DK1_Small    .    Biogas_Grid_STO                               
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_20                           
2025                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_25                           
2030                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_30                           
2035                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_35                           
2040                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_40                           
2045                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_45                           
2050                                                                                                               .    DK1_Large    .    BiogasUpgr_BMETH_50                           
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_20                           
2025                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_25                           
2030                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_30                           
2035                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_35                           
2040                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_40                           
2045                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_45                           
2050                                                                                                               .    DK1_Medium   .    BiogasUpgr_BMETH_50                           
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_20                           
2025                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_25                           
2030                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_30                           
2035                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_35                           
2040                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_40                           
2045                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_45                           
2050                                                                                                               .    DK1_MedSmall .    BiogasUpgr_BMETH_50                           
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_20                           
2025                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_25                           
2030                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_30                           
2035                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_35                           
2040                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_40                           
2045                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_45                           
2050                                                                                                               .    DK1_Small    .    BiogasUpgr_BMETH_50                           
                                                                                                                                                                                        
*****SOEC                                                                                                                                                                               
2020                                                                                                               .    DK1_Large    .    AEC_20                                        
2025                                                                                                               .    DK1_Large    .    AEC_25                                        
2030                                                                                                               .    DK1_Large    .    AEC_30                                        
2035                                                                                                               .    DK1_Large    .    AEC_35                                        
2040                                                                                                               .    DK1_Large    .    AEC_40                                        
2045                                                                                                               .    DK1_Large    .    AEC_45                                        
2050                                                                                                               .    DK1_Large    .    AEC_50                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    AEC_20                                        
2025                                                                                                               .    DK1_Medium   .    AEC_25                                        
2030                                                                                                               .    DK1_Medium   .    AEC_30                                        
2035                                                                                                               .    DK1_Medium   .    AEC_35                                        
2040                                                                                                               .    DK1_Medium   .    AEC_40                                        
2045                                                                                                               .    DK1_Medium   .    AEC_45                                        
2050                                                                                                               .    DK1_Medium   .    AEC_50                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    PEM_20                                        
2025                                                                                                               .    DK1_Large    .    PEM_25                                        
2030                                                                                                               .    DK1_Large    .    PEM_30                                        
2035                                                                                                               .    DK1_Large    .    PEM_35                                        
2040                                                                                                               .    DK1_Large    .    PEM_40                                        
2045                                                                                                               .    DK1_Large    .    PEM_45                                        
2050                                                                                                               .    DK1_Large    .    PEM_50                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    PEM_20                                        
2025                                                                                                               .    DK1_Medium   .    PEM_25                                        
2030                                                                                                               .    DK1_Medium   .    PEM_30                                        
2035                                                                                                               .    DK1_Medium   .    PEM_35                                        
2040                                                                                                               .    DK1_Medium   .    PEM_40                                        
2045                                                                                                               .    DK1_Medium   .    PEM_45                                        
2050                                                                                                               .    DK1_Medium   .    PEM_50                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    SOEC_20                                       
2025                                                                                                               .    DK1_Large    .    SOEC_25                                       
2030                                                                                                               .    DK1_Large    .    SOEC_30                                       
2035                                                                                                               .    DK1_Large    .    SOEC_35                                       
2040                                                                                                               .    DK1_Large    .    SOEC_40                                       
2045                                                                                                               .    DK1_Large    .    SOEC_45                                       
2050                                                                                                               .    DK1_Large    .    SOEC_50                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    SOEC_20                                       
2025                                                                                                               .    DK1_Medium   .    SOEC_25                                       
2030                                                                                                               .    DK1_Medium   .    SOEC_30                                       
2035                                                                                                               .    DK1_Medium   .    SOEC_35                                       
2040                                                                                                               .    DK1_Medium   .    SOEC_40                                       
2045                                                                                                               .    DK1_Medium   .    SOEC_45                                       
2050                                                                                                               .    DK1_Medium   .    SOEC_50                                       
                                                                                                                                                                                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_20                         
2025                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_25                         
2030                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_30                         
2035                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_35                         
2040                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_40                         
2045                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_45                         
2050                                                                                                               .    DK1_Large    .    Hydrogen_STO_Large_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_20                         
2025                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_25                         
2030                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_30                         
2035                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_35                         
2040                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_40                         
2045                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_45                         
2050                                                                                                               .    DK1_Medium   .    Hydrogen_STO_Large_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_20                         
2025                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_25                         
2030                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_30                         
2035                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_35                         
2040                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_40                         
2045                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_45                         
2050                                                                                                               .    DK1_MedSmall .    Hydrogen_STO_Small_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_20                         
2025                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_25                         
2030                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_30                         
2035                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_35                         
2040                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_40                         
2045                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_45                         
2050                                                                                                               .    DK1_Small    .    Hydrogen_STO_Small_50                         
                                                                                                                                                                                        
                                                                                                                                                                                        
                                                                                                                                                                                        
                                                                                                                                                                                        
**************FUELS                                                                                                                                                                     
2020                                                                                                               .    DK1_Large    .    HTL_ST_20                                     
2025                                                                                                               .    DK1_Large    .    HTL_ST_25                                     
2030                                                                                                               .    DK1_Large    .    HTL_ST_30                                     
2035                                                                                                               .    DK1_Large    .    HTL_ST_35                                     
2040                                                                                                               .    DK1_Large    .    HTL_ST_40                                     
2045                                                                                                               .    DK1_Large    .    HTL_ST_45                                     
2050                                                                                                               .    DK1_Large    .    HTL_ST_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    HTL_ST_20                                     
2025                                                                                                               .    DK1_Medium   .    HTL_ST_25                                     
2030                                                                                                               .    DK1_Medium   .    HTL_ST_30                                     
2035                                                                                                               .    DK1_Medium   .    HTL_ST_35                                     
2040                                                                                                               .    DK1_Medium   .    HTL_ST_40                                     
2045                                                                                                               .    DK1_Medium   .    HTL_ST_45                                     
2050                                                                                                               .    DK1_Medium   .    HTL_ST_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    HTL_WO_20                                     
2025                                                                                                               .    DK1_Large    .    HTL_WO_25                                     
2030                                                                                                               .    DK1_Large    .    HTL_WO_30                                     
2035                                                                                                               .    DK1_Large    .    HTL_WO_35                                     
2040                                                                                                               .    DK1_Large    .    HTL_WO_40                                     
2045                                                                                                               .    DK1_Large    .    HTL_WO_45                                     
2050                                                                                                               .    DK1_Large    .    HTL_WO_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    HTL_WO_20                                     
2025                                                                                                               .    DK1_Medium   .    HTL_WO_25                                     
2030                                                                                                               .    DK1_Medium   .    HTL_WO_30                                     
2035                                                                                                               .    DK1_Medium   .    HTL_WO_35                                     
2040                                                                                                               .    DK1_Medium   .    HTL_WO_40                                     
2045                                                                                                               .    DK1_Medium   .    HTL_WO_45                                     
2050                                                                                                               .    DK1_Medium   .    HTL_WO_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    HTL_WP_20                                     
2025                                                                                                               .    DK1_Large    .    HTL_WP_25                                     
2030                                                                                                               .    DK1_Large    .    HTL_WP_30                                     
2035                                                                                                               .    DK1_Large    .    HTL_WP_35                                     
2040                                                                                                               .    DK1_Large    .    HTL_WP_40                                     
2045                                                                                                               .    DK1_Large    .    HTL_WP_45                                     
2050                                                                                                               .    DK1_Large    .    HTL_WP_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    HTL_WP_20                                     
2025                                                                                                               .    DK1_Medium   .    HTL_WP_25                                     
2030                                                                                                               .    DK1_Medium   .    HTL_WP_30                                     
2035                                                                                                               .    DK1_Medium   .    HTL_WP_35                                     
2040                                                                                                               .    DK1_Medium   .    HTL_WP_40                                     
2045                                                                                                               .    DK1_Medium   .    HTL_WP_45                                     
2050                                                                                                               .    DK1_Medium   .    HTL_WP_50                                     
                                                                                                                                                                                        
                                                                                                                                                                                        
*************************BioJet******************************                                                                                                                           
2020                                                                                                               .    DK1_Large    .    BioJet_ST_20                                  
2025                                                                                                               .    DK1_Large    .    BioJet_ST_25                                  
2030                                                                                                               .    DK1_Large    .    BioJet_ST_30                                  
2035                                                                                                               .    DK1_Large    .    BioJet_ST_35                                  
2040                                                                                                               .    DK1_Large    .    BioJet_ST_40                                  
2045                                                                                                               .    DK1_Large    .    BioJet_ST_45                                  
2050                                                                                                               .    DK1_Large    .    BioJet_ST_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BioJet_WO_20                                  
2025                                                                                                               .    DK1_Large    .    BioJet_WO_25                                  
2030                                                                                                               .    DK1_Large    .    BioJet_WO_30                                  
2035                                                                                                               .    DK1_Large    .    BioJet_WO_35                                  
2040                                                                                                               .    DK1_Large    .    BioJet_WO_40                                  
2045                                                                                                               .    DK1_Large    .    BioJet_WO_45                                  
2050                                                                                                               .    DK1_Large    .    BioJet_WO_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BioJet_WP_20                                  
2025                                                                                                               .    DK1_Large    .    BioJet_WP_25                                  
2030                                                                                                               .    DK1_Large    .    BioJet_WP_30                                  
2035                                                                                                               .    DK1_Large    .    BioJet_WP_35                                  
2040                                                                                                               .    DK1_Large    .    BioJet_WP_40                                  
2045                                                                                                               .    DK1_Large    .    BioJet_WP_45                                  
2050                                                                                                               .    DK1_Large    .    BioJet_WP_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_ST_20                                  
2025                                                                                                               .    DK1_Medium   .    BioJet_ST_25                                  
2030                                                                                                               .    DK1_Medium   .    BioJet_ST_30                                  
2035                                                                                                               .    DK1_Medium   .    BioJet_ST_35                                  
2040                                                                                                               .    DK1_Medium   .    BioJet_ST_40                                  
2045                                                                                                               .    DK1_Medium   .    BioJet_ST_45                                  
2050                                                                                                               .    DK1_Medium   .    BioJet_ST_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_WO_20                                  
2025                                                                                                               .    DK1_Medium   .    BioJet_WO_25                                  
2030                                                                                                               .    DK1_Medium   .    BioJet_WO_30                                  
2035                                                                                                               .    DK1_Medium   .    BioJet_WO_35                                  
2040                                                                                                               .    DK1_Medium   .    BioJet_WO_40                                  
2045                                                                                                               .    DK1_Medium   .    BioJet_WO_45                                  
2050                                                                                                               .    DK1_Medium   .    BioJet_WO_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_WP_20                                  
2025                                                                                                               .    DK1_Medium   .    BioJet_WP_25                                  
2030                                                                                                               .    DK1_Medium   .    BioJet_WP_30                                  
2035                                                                                                               .    DK1_Medium   .    BioJet_WP_35                                  
2040                                                                                                               .    DK1_Medium   .    BioJet_WP_40                                  
2045                                                                                                               .    DK1_Medium   .    BioJet_WP_45                                  
2050                                                                                                               .    DK1_Medium   .    BioJet_WP_50                                  
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BioJet_ST_H2_20                               
2025                                                                                                               .    DK1_Large    .    BioJet_ST_H2_25                               
2030                                                                                                               .    DK1_Large    .    BioJet_ST_H2_30                               
2035                                                                                                               .    DK1_Large    .    BioJet_ST_H2_35                               
2040                                                                                                               .    DK1_Large    .    BioJet_ST_H2_40                               
2045                                                                                                               .    DK1_Large    .    BioJet_ST_H2_45                               
2050                                                                                                               .    DK1_Large    .    BioJet_ST_H2_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BioJet_WO_H2_20                               
2025                                                                                                               .    DK1_Large    .    BioJet_WO_H2_25                               
2030                                                                                                               .    DK1_Large    .    BioJet_WO_H2_30                               
2035                                                                                                               .    DK1_Large    .    BioJet_WO_H2_35                               
2040                                                                                                               .    DK1_Large    .    BioJet_WO_H2_40                               
2045                                                                                                               .    DK1_Large    .    BioJet_WO_H2_45                               
2050                                                                                                               .    DK1_Large    .    BioJet_WO_H2_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    BioJet_WP_H2_20                               
2025                                                                                                               .    DK1_Large    .    BioJet_WP_H2_25                               
2030                                                                                                               .    DK1_Large    .    BioJet_WP_H2_30                               
2035                                                                                                               .    DK1_Large    .    BioJet_WP_H2_35                               
2040                                                                                                               .    DK1_Large    .    BioJet_WP_H2_40                               
2045                                                                                                               .    DK1_Large    .    BioJet_WP_H2_45                               
2050                                                                                                               .    DK1_Large    .    BioJet_WP_H2_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_20                               
2025                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_25                               
2030                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_30                               
2035                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_35                               
2040                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_40                               
2045                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_45                               
2050                                                                                                               .    DK1_Medium   .    BioJet_ST_H2_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_20                               
2025                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_25                               
2030                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_30                               
2035                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_35                               
2040                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_40                               
2045                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_45                               
2050                                                                                                               .    DK1_Medium   .    BioJet_WO_H2_50                               
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_20                               
2025                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_25                               
2030                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_30                               
2035                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_35                               
2040                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_40                               
2045                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_45                               
2050                                                                                                               .    DK1_Medium   .    BioJet_WP_H2_50                               
                                                                                                                                                                                        
********************************************************************************                                                                                                        
2020                                                                                                               .    DK1_Large    .    Emethanol_synthesis_20                        
2025                                                                                                               .    DK1_Large    .    EMethanol_synthesis_25                        
2030                                                                                                               .    DK1_Large    .    EMethanol_synthesis_30                        
2035                                                                                                               .    DK1_Large    .    EMethanol_synthesis_35                        
2040                                                                                                               .    DK1_Large    .    EMethanol_synthesis_40                        
2045                                                                                                               .    DK1_Large    .    EMethanol_synthesis_45                        
2050                                                                                                               .    DK1_Large    .    EMethanol_synthesis_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_20                          
2025                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_25                          
2030                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_30                          
2035                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_35                          
2040                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_40                          
2045                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_45                          
2050                                                                                                               .    DK1_Large    .    EMethanol_Upgrade_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Emethanol_synthesis_20                        
2025                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_25                        
2030                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_30                        
2035                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_35                        
2040                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_40                        
2045                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_45                        
2050                                                                                                               .    DK1_Medium   .    EMethanol_synthesis_50                        
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_20                          
2025                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_25                          
2030                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_30                          
2035                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_35                          
2040                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_40                          
2045                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_45                          
2050                                                                                                               .    DK1_Medium   .    EMethanol_Upgrade_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    E_FT_20                                       
2025                                                                                                               .    DK1_Large    .    E_FT_25                                       
2030                                                                                                               .    DK1_Large    .    E_FT_30                                       
2035                                                                                                               .    DK1_Large    .    E_FT_35                                       
2040                                                                                                               .    DK1_Large    .    E_FT_40                                       
2045                                                                                                               .    DK1_Large    .    E_FT_45                                       
2050                                                                                                               .    DK1_Large    .    E_FT_50                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    E_FT_20                                       
2025                                                                                                               .    DK1_Medium   .    E_FT_25                                       
2030                                                                                                               .    DK1_Medium   .    E_FT_30                                       
2035                                                                                                               .    DK1_Medium   .    E_FT_35                                       
2040                                                                                                               .    DK1_Medium   .    E_FT_40                                       
2045                                                                                                               .    DK1_Medium   .    E_FT_45                                       
2050                                                                                                               .    DK1_Medium   .    E_FT_50                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_20                          
2025                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_25                          
2030                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_30                          
2035                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_35                          
2040                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_40                          
2045                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_45                          
2050                                                                                                               .    DK1_Large    .    Ammonia_Synthesis_50                          
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_20                          
2025                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_25                          
2030                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_30                          
2035                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_35                          
2040                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_40                          
2045                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_45                          
2050                                                                                                               .    DK1_Medium   .    Ammonia_Synthesis_50                          
                                                                                                                                                                                        
*2020                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_20                         
*2025                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_25                         
*2030                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_30                         
*2035                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_35                         
*2040                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_40                         
*2045                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_45                         
*2050                                                                                                              .    DK1_Large    .    TG_FT_Biodiesel_MW_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_20                         
2025                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_25                         
2030                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_30                         
2035                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_35                         
2040                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_40                         
2045                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_45                         
2050                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_ST_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_20                         
2025                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_25                         
2030                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_30                         
2035                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_35                         
2040                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_40                         
2045                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_45                         
2050                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WO_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_20                         
2025                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_25                         
2030                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_30                         
2035                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_35                         
2040                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_40                         
2045                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_45                         
2050                                                                                                               .    DK1_Large    .    TG_FT_Biodiesel_WP_50                         
                                                                                                                                                                                        
*2020                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_20                         
*2025                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_25                         
*2030                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_30                         
*2035                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_35                         
*2040                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_40                         
*2045                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_45                         
*2050                                                                                                              .    DK1_Medium   .    TG_FT_Biodiesel_MW_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_20                         
2025                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_25                         
2030                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_30                         
2035                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_35                         
2040                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_40                         
2045                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_45                         
2050                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_ST_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_20                         
2025                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_25                         
2030                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_30                         
2035                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_35                         
2040                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_40                         
2045                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_45                         
2050                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WO_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_20                         
2025                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_25                         
2030                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_30                         
2035                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_35                         
2040                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_40                         
2045                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_45                         
2050                                                                                                               .    DK1_Medium   .    TG_FT_Biodiesel_WP_50                         
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    Ethanol_20                                    
2025                                                                                                               .    DK1_Large    .    Ethanol_25                                    
2030                                                                                                               .    DK1_Large    .    Ethanol_30                                    
2035                                                                                                               .    DK1_Large    .    Ethanol_35                                    
2040                                                                                                               .    DK1_Large    .    Ethanol_40                                    
2045                                                                                                               .    DK1_Large    .    Ethanol_45                                    
2050                                                                                                               .    DK1_Large    .    Ethanol_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Ethanol_20                                    
2025                                                                                                               .    DK1_Medium   .    Ethanol_25                                    
2030                                                                                                               .    DK1_Medium   .    Ethanol_30                                    
2035                                                                                                               .    DK1_Medium   .    Ethanol_35                                    
2040                                                                                                               .    DK1_Medium   .    Ethanol_40                                    
2045                                                                                                               .    DK1_Medium   .    Ethanol_45                                    
2050                                                                                                               .    DK1_Medium   .    Ethanol_50                                    
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    GtBioJet_20                                   
2025                                                                                                               .    DK1_Large    .    GtBioJet_25                                   
2030                                                                                                               .    DK1_Large    .    GtBioJet_30                                   
2035                                                                                                               .    DK1_Large    .    GtBioJet_35                                   
2040                                                                                                               .    DK1_Large    .    GtBioJet_40                                   
2045                                                                                                               .    DK1_Large    .    GtBioJet_45                                   
2050                                                                                                               .    DK1_Large    .    GtBioJet_50                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    GtBioJet_20                                   
2025                                                                                                               .    DK1_Medium   .    GtBioJet_25                                   
2030                                                                                                               .    DK1_Medium   .    GtBioJet_30                                   
2035                                                                                                               .    DK1_Medium   .    GtBioJet_35                                   
2040                                                                                                               .    DK1_Medium   .    GtBioJet_40                                   
2045                                                                                                               .    DK1_Medium   .    GtBioJet_45                                   
2050                                                                                                               .    DK1_Medium   .    GtBioJet_50                                   
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    GtMeOH_20                                     
2025                                                                                                               .    DK1_Large    .    GtMeOH_25                                     
2030                                                                                                               .    DK1_Large    .    GtMeOH_30                                     
2035                                                                                                               .    DK1_Large    .    GtMeOH_35                                     
2040                                                                                                               .    DK1_Large    .    GtMeOH_40                                     
2045                                                                                                               .    DK1_Large    .    GtMeOH_45                                     
2050                                                                                                               .    DK1_Large    .    GtMeOH_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    GtMeOH_20                                     
2025                                                                                                               .    DK1_Medium   .    GtMeOH_25                                     
2030                                                                                                               .    DK1_Medium   .    GtMeOH_30                                     
2035                                                                                                               .    DK1_Medium   .    GtMeOH_35                                     
2040                                                                                                               .    DK1_Medium   .    GtMeOH_40                                     
2045                                                                                                               .    DK1_Medium   .    GtMeOH_45                                     
2050                                                                                                               .    DK1_Medium   .    GtMeOH_50                                     
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Large    .    CSMR_20                                       
2025                                                                                                               .    DK1_Large    .    CSMR_25                                       
2030                                                                                                               .    DK1_Large    .    CSMR_30                                       
2035                                                                                                               .    DK1_Large    .    CSMR_35                                       
2040                                                                                                               .    DK1_Large    .    CSMR_40                                       
2045                                                                                                               .    DK1_Large    .    CSMR_45                                       
2050                                                                                                               .    DK1_Large    .    CSMR_50                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    CSMR_20                                       
2025                                                                                                               .    DK1_Medium   .    CSMR_25                                       
2030                                                                                                               .    DK1_Medium   .    CSMR_30                                       
2035                                                                                                               .    DK1_Medium   .    CSMR_35                                       
2040                                                                                                               .    DK1_Medium   .    CSMR_40                                       
2045                                                                                                               .    DK1_Medium   .    CSMR_45                                       
2050                                                                                                               .    DK1_Medium   .    CSMR_50                                       
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Medium   .    Engine_Syngas_50                              
2020                                                                                                               .    DK1_Medium   .    Engine_Biogas_50                              
                                                                                                                                                                                        
2020                                                                                                               .    DK1_MedSmall .    Engine_Syngas_50                              
2020                                                                                                               .    DK1_MedSmall .    Engine_Biogas_50                              
                                                                                                                                                                                        
2020                                                                                                               .    DK1_Small    .    Engine_Syngas_50                              
2020                                                                                                               .    DK1_Small    .    Engine_Biogas_50                              
                                                                                                                                                                                        
                                                                                                                                                                                        
/                                                                                                                                                                                       
;                                                                                                                                                                                       
                                                                                                                                                                                        
APROCKAPNEW(Y,'DK2_Large',PROC)=APROCKAPNEW(Y,'DK1_Large',PROC);                                                                                                                        
APROCKAPNEW(Y,'DK2_Medium',PROC)=APROCKAPNEW(Y,'DK1_Medium',PROC);                                                                                                                      
APROCKAPNEW(Y,'DK2_MedSmall',PROC)=APROCKAPNEW(Y,'DK1_MedSmall',PROC);                                                                                                                  
APROCKAPNEW(Y,'DK2_Small',PROC)=APROCKAPNEW(Y,'DK1_Small',PROC);                                                                                                                        
                                                                                                                                                                                        
APROCKAPNEW(Y,'DK1_Rural',PROC)=APROCKAPNEW(Y,'DK1_Small',PROC);                                                                                                                        
APROCKAPNEW(Y,'DK2_Rural',PROC)=APROCKAPNEW(Y,'DK2_Small',PROC);                                                                                                                        
                                                                                                                                                                                        
*APROCKAPNEW(Y,AAA,PROC)=APROCKAPNEW('2020',AAA,PROC);                                                                                                                                  
