PARAMETER MAXFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"
/                                                                                          
                                                                                           
*OBS FF - Example: No fossil CO2 from 2040                                                 
                                                                                           
/;                                                                                         
                                                                                           
*Limit on fossil CO2 in fuel production                                                    
                                                                                           
                                                                                           
