SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
CO2_Source_Biogen                                    
CO2_Source_DAC                                       
CO2_Source_Fossil                                    
Diesel_Source                                        
HydrogenSource_MWh                                   
Kerosene_Source                                      
LNG_Source                                           
MDO_Source                                           
Straw_Gen                                            
Wood_Gen                                             
Manure_Gen                                           
Methanol_Chile_Shipped                               
/;                                                   
