PARAMETER INDICLIMGOAL(FLOWINDIC,iINDICLIMGOALSET) "Limits, desirable quantities and weight of Indics"                      
/                                                                                                                           
OPERATIONCOST                                                                                          .    INDICWEIGHT 1   
GHGEMISSION_nonbio                                                                                     .    INDICWEIGHT 0   
GHGEMISSION_bio                                                                                        .    INDICWEIGHT 0   
                                                                                                                            
                                                                                                                            
/;                                                                                                                          
