SET PROCBUFFER(PROC) "Buffer processes (trace entering and/or leaving)"
/                                                                      
                                                                       
*AmmoniaBuffer                                                         
*BioGasolineBuffer                                                     
*BioJetBuffer                                                          
*E_FT_DieselBuffer                                                     
*E_FT_JetBuffer                                                        
*EME_GasolineBuffer                                                    
*EME_JetBuffer                                                         
*EME_LPGBuffer                                                         
*EMethanolBuffer                                                       
*MethanolBuffer                                                        
*Biooil_Buffer                                                         
                                                                       
ElecBuffer                                                             
HeatBuffer                                                             
GHG_Buffer                                                             
GHGbio_Buffer                                                          
Gas_Buffer                                                             
ElectroBuffer                                                          
                                                                       
/;                                                                     
