PARAMETER SOSIBU2INDIC_RST(RRR,PROC,FLOW,FLOWINDIC,SSS,TTT) "Coefficients for transformation of VSOURCE, VSINK and VBUFFER flows to FLOWINDIC values"
* Note: there is also parallel tables  that contain less indexes. For PROC for which this is relevant, enter 0 here (or omit the corresponding row). 
                                                                                                                                                     
/                                                                                                                                                    
                                                                                                                                                     
/;                                                                                                                                                   
