PARAMETER PROCKAPFXINV(YYY,AAA,PROC) "Investments in plants endogenously calculated from previous years"
/                                                                                                       
                                                                                                        
/;                                                                                                      
