SET APKNDISC_AP(AAA,PROC) "Areas for possible location of discrete capacity investments in Processes (addon apkndisc)"
/                                                                                                                     
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
                                                                                                                      
/;                                                                                                                    
