SET PROCFLOWWASTETR(IPROC,PROC,FLOW,WASTETREATMENT) 'Type of technology aggrupated'
/                                                                                  
                                                                                   
                                                                                   
/                                                                                  
;                                                                                  
