SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
                                                                    
*Liquid hydrocarbons                                                
ProcExim_Truck_Oil                                                  
ProcExim_Ship_Oil                                                   
                                                                    
*Methanol                                                           
ProcExim_Truck_Methanol                                             
ProcExim_Ship_Methanol                                              
                                                                    
*Ammonia                                                            
ProcExim_Truck_Ammonia                                              
ProcExim_Ship_Ammonia                                               
                                                                    
*Hydrogen                                                           
ProcExim_Truck_Hydrogen                                             
ProcExim_Ship_Hydrogen                                              
                                                                    
*CO2                                                                
ProcExim_Truck_CO2                                                  
ProcExim_Ship_CO2                                                   
ProcExim_Pipeline_CO2                                               
                                                                    
*Biomass                                                            
ProcExim_Truck_Wood                                                 
ProcExim_Truck_Straw                                                
/;                                                                  
