SET APKNDISCSIZESET     "Set of possible sizes for discrete capacity investments in Processes (addon apkndisc) ()"
                                                                                                                  
/                                                                                                                 
                                                                                                                  
/;                                                                                                                
