SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
ResA                                                 
ResB                                                 
ResC                                                 
ResD                                                 
                                                     
CO2_Source_PH                                        
CO2_Source_IND                                       
CO2_Source_DAC                                       
                                                     
                                                     
Wood_Gen                                             
Straw_Gen                                            
Muni_Waste_Gen                                       
Wood_Pellets_Gen                                     
Manure_Gen                                           
Deep_Litter_Gen                                      
Food_Waste_Gen                                       
Nature_Area_Gen                                      
                                                     
                                                     
Other_Gas_Gen                                        
                                                     
BioLiquid_Import                                     
NorthSeaGas                                          
/;                                                   
