SET PROCBUFFER(PROC) "Buffer processes (trace entering and/or leaving)"                                                                              
/                                                                                                                                                    
Demand                                                                                                                                               
GasDemand                                                                                                                                            
                                                                                                                                                     
AmmoniaBuffer_Exp                                                                                                                                    
HTLBuffer_Exp                                                                                                                                        
                                                                                                                                                     
BioJetBuffer_Exp                                                                                                                                     
E_FT_JetBuffer_Exp                                                                                                                                   
EME_JetBuffer_Exp                                                                                                                                    
                                                                                                                                                     
BioGasolineBuffer_Exp                                                                                                                                
MethanolBuffer_Exp                                                                                                                                   
EthanolBuffer_Exp                                                                                                                                    
BiodieselBuffer_Exp                                                                                                                                  
                                                                                                                                                     
E_FT_DieselBuffer_Exp                                                                                                                                
EME_GasolineBuffer_Exp                                                                                                                               
EME_LPGBuffer_Exp                                                                                                                                    
EMethanolBuffer_Exp                                                                                                                                  
                                                                                                                                                     
                                                                                                                                                     
ElectroBuffer                                                                                                                                        
                                                                                                                                                     
SeaBuffer                                                                                                                                            
RoadBuffer                                                                                                                                           
AirBuffer                                                                                                                                            
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
Money_buffer                                                                                                                                         
Money_buffer_T                                                                                                                                       
GHG_Buffer                                                                                                                                           
GHGbio_Buffer                                                                                                                                        
DieselBuffer                                                                                                                                         
GasBuffer                                                                                                                                            
ElecBuffer                                                                                                                                           
HeatBuffer                                                                                                                                           
*BioSyngasBuffer                                                                                                                                     
*BiogasBuffer                                                                                                                                        
                                                                                                                                                     
*E_FT_NaphthaBuffer                                                                                                                                  
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
*BioGasolineBuffer                                                                                                                                   
*BiodieselBuffer                                                                                                                                     
*MethanolBuffer                                                                                                                                      
*EthanolBuffer                                                                                                                                       
*E_FT_DieselBuffer                                                                                                                                   
*EME_GasolineBuffer                                                                                                                                  
*EME_LPGBuffer                                                                                                                                       
*EMethanolBuffer                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
*BioJetBuffer                                                                                                                                        
*E_FT_JetBuffer                                                                                                                                      
*EME_JetBuffer                                                                                                                                       
                                                                                                                                                     
*AmmoniaBuffer                                                                                                                                       
*HTLBuffer                                                                                                                                           
                                                                                                                                                     
                                                                                                                                                     
*Passenger_RE_fuels_Buffer                                                                                                                           
*Freight_RE_fuels_Buffer                                                                                                                             
                                                                                                                                                     
                                                                                                                                                     
*----------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                     
/;                                                                                                                                                   
