SET PROCINDIC(PROC) "The indicator NODEs (source/sink/buff(/exim?)) with net balances that we are interested in evaluating"
/                                                                                                                          
Money_buffer                                                                                                               
GHG_Buffer                                                                                                                 
GHGbio_Buffer                                                                                                              
Money_buffer_T                                                                                                             
                                                                                                                           
/;                                                                                                                         
