SET PROC "All 'transformations' that we use"                                                                             
/                                                                                                                        
* NB: for debugging, print and ailing memory nice to have FLOW elements in UPPERCASE og Proc elements in CamelCase.      
                                                                                                                         
ResA                                                                                                                     
ProA                                                                                                                     
                                                                                                                         
StoA                                                                                                                     
                                                                                                                         
SumA                                                                                                                     
                                                                                                                         
ResB                                                                                                                     
ProB                                                                                                                     
                                                                                                                         
ResC                                                                                                                     
                                                                                                                         
ResD                                                                                                                     
ProD                                                                                                                     
ProDD                                                                                                                    
StoD                                                                                                                     
                                                                                                                         
Sum                                                                                                                      
Demand                                                                                                                   
                                                                                                                         
                                                                                                                         
                                                                                                                         
EL_Bal_to_Opti_Conv                                                                                                      
EL_grid_tariff                                                                                                           
ElecBuffer_GJ                                                                                                            
EL_Opti_to_Bal_Conv                                                                                                      
                                                                                                                         
Heat_Bal_to_Opti_Conv                                                                                                    
Heat_grid_tariff                                                                                                         
HeatBuffer_GJ                                                                                                            
Heat_Opti_to_Bal_Conv                                                                                                    
                                                                                                                         
                                                                                                                         
Electro                                                                                                                  
ElectroBuffer                                                                                                            
                                                                                                                         
                                                                                                                         
Money_buffer                                                                                                             
Money_buffer_T                                                                                                           
GHG_Buffer                                                                                                               
GHGbio_Buffer                                                                                                            
                                                                                                                         
                                                                                                                         
CO2_Source_PH                                                                                                            
CO2_Source_IND                                                                                                           
CO2_Source_DAC                                                                                                           
                                                                                                                         
CO2_DAC_20                                                                                                               
CO2_DAC_25                                                                                                               
CO2_DAC_30                                                                                                               
CO2_DAC_35                                                                                                               
CO2_DAC_40                                                                                                               
CO2_DAC_45                                                                                                               
CO2_DAC_50                                                                                                               
                                                                                                                         
CO2_IND_20                                                                                                               
CO2_IND_25                                                                                                               
CO2_IND_30                                                                                                               
CO2_IND_35                                                                                                               
CO2_IND_40                                                                                                               
CO2_IND_45                                                                                                               
CO2_IND_50                                                                                                               
                                                                                                                         
CO2_PH_20                                                                                                                
CO2_PH_25                                                                                                                
CO2_PH_30                                                                                                                
CO2_PH_35                                                                                                                
CO2_PH_40                                                                                                                
CO2_PH_45                                                                                                                
CO2_PH_50                                                                                                                
                                                                                                                         
CO2_Bio_20                                                                                                               
CO2_Bio_25                                                                                                               
CO2_Bio_30                                                                                                               
CO2_Bio_35                                                                                                               
CO2_Bio_40                                                                                                               
CO2_Bio_45                                                                                                               
CO2_Bio_50                                                                                                               
                                                                                                                         
CO2                                                                                                                      
CO2_Grid_In                                                                                                              
CO2_Grid_Out                                                                                                             
CO2_Sto                                                                                                                  
CO2_Before_Use                                                                                                           
CO2_After_Sto                                                                                                            
CO2_Use                                                                                                                  
CO2_Sink                                                                                                                 
CO2_Bio_Pot                                                                                                              
                                                                                                                         
                                                                                                                         
Linkstorage_Res                                                                                                          
                                                                                                                         
                                                                                                                         
Wood_Source                                                                                                              
Straw_Source                                                                                                             
Muni_Waste_Source                                                                                                        
Wood_Pellets_Source                                                                                                      
Manure_Source                                                                                                            
Deep_Litter_Source                                                                                                       
Food_Waste_Source                                                                                                        
Nature_Area_Source                                                                                                       
                                                                                                                         
                                                                                                                         
Wood_Gen                                                                                                                 
Straw_Gen                                                                                                                
Muni_Waste_Gen                                                                                                           
Wood_Pellets_Gen                                                                                                         
Manure_Gen                                                                                                               
Deep_Litter_Gen                                                                                                          
Food_Waste_Gen                                                                                                           
Nature_Area_Gen                                                                                                          
                                                                                                                         
                                                                                                                         
Straw_Mass                                                                                                               
Wood_Mass                                                                                                                
Wood_Pellets_Mass                                                                                                        
Muni_Waste_Mass                                                                                                          
Manure_Mass                                                                                                              
Deep_Litter_Mass                                                                                                         
Food_Waste_Mass                                                                                                          
Nature_Area_Mass                                                                                                         
                                                                                                                         
                                                                                                                         
Wood                                                                                                                     
Wood_Pellets                                                                                                             
Straw                                                                                                                    
Muni_Waste                                                                                                               
Manure                                                                                                                   
                                                                                                                         
Straw_Biogas                                                                                                             
                                                                                                                         
Mix_Fuel                                                                                                                 
                                                                                                                         
ProcEximTruck                                                                                                            
ProcEximShip                                                                                                             
ProcEximTrain                                                                                                            
                                                                                                                         
                                                                                                                         
Tar                                                                                                                      
Digestate                                                                                                                
                                                                                                                         
                                                                                                                         
*SumSTWB                                                                                                                 
*BiogasProd_single                                                                                                       
                                                                                                                         
Straw_pre_BG_20                                                                                                          
Straw_pre_BG_25                                                                                                          
Straw_pre_BG_30                                                                                                          
Straw_pre_BG_35                                                                                                          
Straw_pre_BG_40                                                                                                          
Straw_pre_BG_45                                                                                                          
Straw_pre_BG_50                                                                                                          
                                                                                                                         
Deep_Litter_pre_BG_20                                                                                                    
Deep_Litter_pre_BG_25                                                                                                    
Deep_Litter_pre_BG_30                                                                                                    
Deep_Litter_pre_BG_35                                                                                                    
Deep_Litter_pre_BG_40                                                                                                    
Deep_Litter_pre_BG_45                                                                                                    
Deep_Litter_pre_BG_50                                                                                                    
                                                                                                                         
Food_Waste_pre_BG_20                                                                                                     
Food_Waste_pre_BG_25                                                                                                     
Food_Waste_pre_BG_30                                                                                                     
Food_Waste_pre_BG_35                                                                                                     
Food_Waste_pre_BG_40                                                                                                     
Food_Waste_pre_BG_45                                                                                                     
Food_Waste_pre_BG_50                                                                                                     
                                                                                                                         
Nature_Area_pre_BG_20                                                                                                    
Nature_Area_pre_BG_25                                                                                                    
Nature_Area_pre_BG_30                                                                                                    
Nature_Area_pre_BG_35                                                                                                    
Nature_Area_pre_BG_40                                                                                                    
Nature_Area_pre_BG_45                                                                                                    
Nature_Area_pre_BG_50                                                                                                    
                                                                                                                         
Manure_tank_20                                                                                                           
Manure_tank_25                                                                                                           
Manure_tank_30                                                                                                           
Manure_tank_35                                                                                                           
Manure_tank_40                                                                                                           
Manure_tank_45                                                                                                           
Manure_tank_50                                                                                                           
                                                                                                                         
BiogasProd_mix                                                                                                           
                                                                                                                         
                                                                                                                         
Biogas_Grid_SUM                                                                                                          
Biogas_Grid_IN                                                                                                           
Biogas_Grid_NoSTO                                                                                                        
Biogas_Grid_STO                                                                                                          
Biogas_Grid_After_STO                                                                                                    
Biogas_Grid_OUT                                                                                                          
                                                                                                                         
BiogasUpgr_BMETH_20                                                                                                      
BiogasUpgr_BMETH_25                                                                                                      
BiogasUpgr_BMETH_30                                                                                                      
BiogasUpgr_BMETH_35                                                                                                      
BiogasUpgr_BMETH_40                                                                                                      
BiogasUpgr_BMETH_45                                                                                                      
BiogasUpgr_BMETH_50                                                                                                      
                                                                                                                         
                                                                                                                         
                                                                                                                         
TG_MW_20                                                                                                                 
TG_MW_25                                                                                                                 
TG_MW_30                                                                                                                 
TG_MW_35                                                                                                                 
TG_MW_40                                                                                                                 
TG_MW_45                                                                                                                 
TG_MW_50                                                                                                                 
                                                                                                                         
TG_ST_20                                                                                                                 
TG_ST_25                                                                                                                 
TG_ST_30                                                                                                                 
TG_ST_35                                                                                                                 
TG_ST_40                                                                                                                 
TG_ST_45                                                                                                                 
TG_ST_50                                                                                                                 
                                                                                                                         
TG_WO_20                                                                                                                 
TG_WO_25                                                                                                                 
TG_WO_30                                                                                                                 
TG_WO_35                                                                                                                 
TG_WO_40                                                                                                                 
TG_WO_45                                                                                                                 
TG_WO_50                                                                                                                 
                                                                                                                         
TG_WP_20                                                                                                                 
TG_WP_25                                                                                                                 
TG_WP_30                                                                                                                 
TG_WP_35                                                                                                                 
TG_WP_40                                                                                                                 
TG_WP_45                                                                                                                 
TG_WP_50                                                                                                                 
                                                                                                                         
ThermGasific_SNG_MW_20                                                                                                   
ThermGasific_SNG_MW_25                                                                                                   
ThermGasific_SNG_MW_30                                                                                                   
ThermGasific_SNG_MW_35                                                                                                   
ThermGasific_SNG_MW_40                                                                                                   
ThermGasific_SNG_MW_45                                                                                                   
ThermGasific_SNG_MW_50                                                                                                   
                                                                                                                         
ThermGasific_SNG_ST_20                                                                                                   
ThermGasific_SNG_ST_25                                                                                                   
ThermGasific_SNG_ST_30                                                                                                   
ThermGasific_SNG_ST_35                                                                                                   
ThermGasific_SNG_ST_40                                                                                                   
ThermGasific_SNG_ST_45                                                                                                   
ThermGasific_SNG_ST_50                                                                                                   
                                                                                                                         
ThermGasific_SNG_WO_20                                                                                                   
ThermGasific_SNG_WO_25                                                                                                   
ThermGasific_SNG_WO_30                                                                                                   
ThermGasific_SNG_WO_35                                                                                                   
ThermGasific_SNG_WO_40                                                                                                   
ThermGasific_SNG_WO_45                                                                                                   
ThermGasific_SNG_WO_50                                                                                                   
                                                                                                                         
ThermGasific_SNG_WP_20                                                                                                   
ThermGasific_SNG_WP_25                                                                                                   
ThermGasific_SNG_WP_30                                                                                                   
ThermGasific_SNG_WP_35                                                                                                   
ThermGasific_SNG_WP_40                                                                                                   
ThermGasific_SNG_WP_45                                                                                                   
ThermGasific_SNG_WP_50                                                                                                   
                                                                                                                         
                                                                                                                         
ThermGasific_Syngas_MW_20                                                                                                
ThermGasific_Syngas_MW_25                                                                                                
ThermGasific_Syngas_MW_30                                                                                                
ThermGasific_Syngas_MW_35                                                                                                
ThermGasific_Syngas_MW_40                                                                                                
ThermGasific_Syngas_MW_45                                                                                                
ThermGasific_Syngas_MW_50                                                                                                
                                                                                                                         
ThermGasific_Syngas_ST_20                                                                                                
ThermGasific_Syngas_ST_25                                                                                                
ThermGasific_Syngas_ST_30                                                                                                
ThermGasific_Syngas_ST_35                                                                                                
ThermGasific_Syngas_ST_40                                                                                                
ThermGasific_Syngas_ST_45                                                                                                
ThermGasific_Syngas_ST_50                                                                                                
                                                                                                                         
ThermGasific_Syngas_WO_20                                                                                                
ThermGasific_Syngas_WO_25                                                                                                
ThermGasific_Syngas_WO_30                                                                                                
ThermGasific_Syngas_WO_35                                                                                                
ThermGasific_Syngas_WO_40                                                                                                
ThermGasific_Syngas_WO_45                                                                                                
ThermGasific_Syngas_WO_50                                                                                                
                                                                                                                         
ThermGasific_Syngas_WP_20                                                                                                
ThermGasific_Syngas_WP_25                                                                                                
ThermGasific_Syngas_WP_30                                                                                                
ThermGasific_Syngas_WP_35                                                                                                
ThermGasific_Syngas_WP_40                                                                                                
ThermGasific_Syngas_WP_45                                                                                                
ThermGasific_Syngas_WP_50                                                                                                
                                                                                                                         
                                                                                                                         
Bio_SNG_SUM                                                                                                              
Bio_SNG_OUT                                                                                                              
                                                                                                                         
                                                                                                                         
Bio_Syngas_Grid_IN                                                                                                       
Bio_Syngas_GRID_OUT                                                                                                      
                                                                                                                         
                                                                                                                         
Bio_TG_Grid_IN                                                                                                           
Bio_TG_Grid_OUT                                                                                                          
                                                                                                                         
                                                                                                                         
                                                                                                                         
                                                                                                                         
                                                                                                                         
*****hydrogen production and storage                                                                                     
AEC_20                                                                                                                   
AEC_25                                                                                                                   
AEC_30                                                                                                                   
AEC_35                                                                                                                   
AEC_40                                                                                                                   
AEC_45                                                                                                                   
AEC_50                                                                                                                   
                                                                                                                         
PEM_20                                                                                                                   
PEM_25                                                                                                                   
PEM_30                                                                                                                   
PEM_35                                                                                                                   
PEM_40                                                                                                                   
PEM_45                                                                                                                   
PEM_50                                                                                                                   
                                                                                                                         
SOEC_20                                                                                                                  
SOEC_25                                                                                                                  
SOEC_30                                                                                                                  
SOEC_35                                                                                                                  
SOEC_40                                                                                                                  
SOEC_45                                                                                                                  
SOEC_50                                                                                                                  
                                                                                                                         
Hydrogen_GRID_IN                                                                                                         
Hydrogen_GRID_OUT                                                                                                        
                                                                                                                         
Hydrogen_STO_Large_20                                                                                                    
Hydrogen_STO_Large_25                                                                                                    
Hydrogen_STO_Large_30                                                                                                    
Hydrogen_STO_Large_35                                                                                                    
Hydrogen_STO_Large_40                                                                                                    
Hydrogen_STO_Large_45                                                                                                    
Hydrogen_STO_Large_50                                                                                                    
                                                                                                                         
Hydrogen_STO_Small_20                                                                                                    
Hydrogen_STO_Small_25                                                                                                    
Hydrogen_STO_Small_30                                                                                                    
Hydrogen_STO_Small_35                                                                                                    
Hydrogen_STO_Small_40                                                                                                    
Hydrogen_STO_Small_45                                                                                                    
Hydrogen_STO_Small_50                                                                                                    
                                                                                                                         
Hydrogen_After_STO_Large                                                                                                 
Hydrogen_After_STO_Small                                                                                                 
                                                                                                                         
Hydrogen_Before_USE                                                                                                      
Hydrogen_Use                                                                                                             
                                                                                                                         
***********************meth                                                                                              
                                                                                                                         
Methanisation_Bio_BioGas_20                                                                                              
Methanisation_Bio_BioGas_25                                                                                              
Methanisation_Bio_BioGas_30                                                                                              
Methanisation_Bio_BioGas_35                                                                                              
Methanisation_Bio_BioGas_40                                                                                              
Methanisation_Bio_BioGas_45                                                                                              
Methanisation_Bio_BioGas_50                                                                                              
                                                                                                                         
                                                                                                                         
Methane_synthesis_TG_20                                                                                                  
Methane_synthesis_TG_25                                                                                                  
Methane_synthesis_TG_30                                                                                                  
Methane_synthesis_TG_35                                                                                                  
Methane_synthesis_TG_40                                                                                                  
Methane_synthesis_TG_45                                                                                                  
Methane_synthesis_TG_50                                                                                                  
                                                                                                                         
Methanol_synthesis_TG_20                                                                                                 
Methanol_synthesis_TG_25                                                                                                 
Methanol_synthesis_TG_30                                                                                                 
Methanol_synthesis_TG_35                                                                                                 
Methanol_synthesis_TG_40                                                                                                 
Methanol_synthesis_TG_45                                                                                                 
Methanol_synthesis_TG_50                                                                                                 
                                                                                                                         
                                                                                                                         
Ethanol_20                                                                                                               
Ethanol_25                                                                                                               
Ethanol_30                                                                                                               
Ethanol_35                                                                                                               
Ethanol_40                                                                                                               
Ethanol_45                                                                                                               
Ethanol_50                                                                                                               
                                                                                                                         
                                                                                                                         
*TG_FT_Biodiesel_MW_20                                                                                                   
*TG_FT_Biodiesel_MW_25                                                                                                   
*TG_FT_Biodiesel_MW_30                                                                                                   
*TG_FT_Biodiesel_MW_35                                                                                                   
*TG_FT_Biodiesel_MW_40                                                                                                   
*TG_FT_Biodiesel_MW_45                                                                                                   
*TG_FT_Biodiesel_MW_50                                                                                                   
                                                                                                                         
TG_FT_Biodiesel_ST_20                                                                                                    
TG_FT_Biodiesel_ST_25                                                                                                    
TG_FT_Biodiesel_ST_30                                                                                                    
TG_FT_Biodiesel_ST_35                                                                                                    
TG_FT_Biodiesel_ST_40                                                                                                    
TG_FT_Biodiesel_ST_45                                                                                                    
TG_FT_Biodiesel_ST_50                                                                                                    
                                                                                                                         
TG_FT_Biodiesel_WO_20                                                                                                    
TG_FT_Biodiesel_WO_25                                                                                                    
TG_FT_Biodiesel_WO_30                                                                                                    
TG_FT_Biodiesel_WO_35                                                                                                    
TG_FT_Biodiesel_WO_40                                                                                                    
TG_FT_Biodiesel_WO_45                                                                                                    
TG_FT_Biodiesel_WO_50                                                                                                    
                                                                                                                         
TG_FT_Biodiesel_WP_20                                                                                                    
TG_FT_Biodiesel_WP_25                                                                                                    
TG_FT_Biodiesel_WP_30                                                                                                    
TG_FT_Biodiesel_WP_35                                                                                                    
TG_FT_Biodiesel_WP_40                                                                                                    
TG_FT_Biodiesel_WP_45                                                                                                    
TG_FT_Biodiesel_WP_50                                                                                                    
                                                                                                                         
GtBioJet_20                                                                                                              
GtBioJet_25                                                                                                              
GtBioJet_30                                                                                                              
GtBioJet_35                                                                                                              
GtBioJet_40                                                                                                              
GtBioJet_45                                                                                                              
GtBioJet_50                                                                                                              
                                                                                                                         
                                                                                                                         
GtMeOH_20                                                                                                                
GtMeOH_25                                                                                                                
GtMeOH_30                                                                                                                
GtMeOH_35                                                                                                                
GtMeOH_40                                                                                                                
GtMeOH_45                                                                                                                
GtMeOH_50                                                                                                                
                                                                                                                         
CSMR_20                                                                                                                  
CSMR_25                                                                                                                  
CSMR_30                                                                                                                  
CSMR_35                                                                                                                  
CSMR_40                                                                                                                  
CSMR_45                                                                                                                  
CSMR_50                                                                                                                  
                                                                                                                         
                                                                                                                         
EMethanol_synthesis_20                                                                                                   
EMethanol_synthesis_25                                                                                                   
EMethanol_synthesis_30                                                                                                   
EMethanol_synthesis_35                                                                                                   
EMethanol_synthesis_40                                                                                                   
EMethanol_synthesis_45                                                                                                   
EMethanol_synthesis_50                                                                                                   
                                                                                                                         
EMethanol_Upgrade_20                                                                                                     
EMethanol_Upgrade_25                                                                                                     
EMethanol_Upgrade_30                                                                                                     
EMethanol_Upgrade_35                                                                                                     
EMethanol_Upgrade_40                                                                                                     
EMethanol_Upgrade_45                                                                                                     
EMethanol_Upgrade_50                                                                                                     
                                                                                                                         
E_FT_20                                                                                                                  
E_FT_25                                                                                                                  
E_FT_30                                                                                                                  
E_FT_35                                                                                                                  
E_FT_40                                                                                                                  
E_FT_45                                                                                                                  
E_FT_50                                                                                                                  
                                                                                                                         
Ammonia_Synthesis_20                                                                                                     
Ammonia_Synthesis_25                                                                                                     
Ammonia_Synthesis_30                                                                                                     
Ammonia_Synthesis_35                                                                                                     
Ammonia_Synthesis_40                                                                                                     
Ammonia_Synthesis_45                                                                                                     
Ammonia_Synthesis_50                                                                                                     
                                                                                                                         
**HTL                                                                                                                    
HTL_ST_20                                                                                                                
HTL_ST_25                                                                                                                
HTL_ST_30                                                                                                                
HTL_ST_35                                                                                                                
HTL_ST_40                                                                                                                
HTL_ST_45                                                                                                                
HTL_ST_50                                                                                                                
                                                                                                                         
HTL_WO_20                                                                                                                
HTL_WO_25                                                                                                                
HTL_WO_30                                                                                                                
HTL_WO_35                                                                                                                
HTL_WO_40                                                                                                                
HTL_WO_45                                                                                                                
HTL_WO_50                                                                                                                
                                                                                                                         
HTL_WP_20                                                                                                                
HTL_WP_25                                                                                                                
HTL_WP_30                                                                                                                
HTL_WP_35                                                                                                                
HTL_WP_40                                                                                                                
HTL_WP_45                                                                                                                
HTL_WP_50                                                                                                                
                                                                                                                         
HTL_Sum                                                                                                                  
                                                                                                                         
*******Biojet                                                                                                            
BioJet_ST_20                                                                                                             
BioJet_ST_25                                                                                                             
BioJet_ST_30                                                                                                             
BioJet_ST_35                                                                                                             
BioJet_ST_40                                                                                                             
BioJet_ST_45                                                                                                             
BioJet_ST_50                                                                                                             
                                                                                                                         
BioJet_WO_20                                                                                                             
BioJet_WO_25                                                                                                             
BioJet_WO_30                                                                                                             
BioJet_WO_35                                                                                                             
BioJet_WO_40                                                                                                             
BioJet_WO_45                                                                                                             
BioJet_WO_50                                                                                                             
                                                                                                                         
BioJet_WP_20                                                                                                             
BioJet_WP_25                                                                                                             
BioJet_WP_30                                                                                                             
BioJet_WP_35                                                                                                             
BioJet_WP_40                                                                                                             
BioJet_WP_45                                                                                                             
BioJet_WP_50                                                                                                             
                                                                                                                         
BioJet_ST_H2_20                                                                                                          
BioJet_ST_H2_25                                                                                                          
BioJet_ST_H2_30                                                                                                          
BioJet_ST_H2_35                                                                                                          
BioJet_ST_H2_40                                                                                                          
BioJet_ST_H2_45                                                                                                          
BioJet_ST_H2_50                                                                                                          
                                                                                                                         
BioJet_WO_H2_20                                                                                                          
BioJet_WO_H2_25                                                                                                          
BioJet_WO_H2_30                                                                                                          
BioJet_WO_H2_35                                                                                                          
BioJet_WO_H2_40                                                                                                          
BioJet_WO_H2_45                                                                                                          
BioJet_WO_H2_50                                                                                                          
                                                                                                                         
BioJet_WP_H2_20                                                                                                          
BioJet_WP_H2_25                                                                                                          
BioJet_WP_H2_30                                                                                                          
BioJet_WP_H2_35                                                                                                          
BioJet_WP_H2_40                                                                                                          
BioJet_WP_H2_45                                                                                                          
BioJet_WP_H2_50                                                                                                          
                                                                                                                         
Biodiesel_FT_SUM                                                                                                         
                                                                                                                         
MethanolTotal_sum                                                                                                        
MethanolTotal                                                                                                            
Methanol_Sum                                                                                                             
                                                                                                                         
E_FT_Sum                                                                                                                 
EME_Upgrade_Sum                                                                                                          
EMethanolTotal                                                                                                           
                                                                                                                         
Nitrogen_Production                                                                                                      
AmmoniaBuffer                                                                                                            
Ammonia_freight_eff                                                                                                      
EMethanolBuffer                                                                                                          
HTLBuffer                                                                                                                
E_FT_JetBuffer                                                                                                           
E_FT_DieselBuffer                                                                                                        
E_FT_NaphthaBuffer                                                                                                       
EME_JetBuffer                                                                                                            
EME_GasolineBuffer                                                                                                       
EME_LPGBuffer                                                                                                            
                                                                                                                         
BioLiquid_Import                                                                                                         
                                                                                                                         
                                                                                                                         
                                                                                                                         
BioJet_SUM                                                                                                               
                                                                                                                         
                                                                                                                         
Engine_Syngas_50                                                                                                         
Engine_Biogas_50                                                                                                         
                                                                                                                         
                                                                                                                         
Methanol_car_eff                                                                                                         
Ethanol_car_eff                                                                                                          
Biodiesel_car_eff                                                                                                        
BioGasoline_car_eff                                                                                                      
                                                                                                                         
                                                                                                                         
Methanol_freight_eff                                                                                                     
Ethanol_freight_eff                                                                                                      
Biodiesel_freight_eff                                                                                                    
BioGasoline_freight_eff                                                                                                  
                                                                                                                         
EMethanol_car_eff                                                                                                        
E_FT_Jet_car_eff                                                                                                         
E_FT_Diesel_car_eff                                                                                                      
EME_Jet_car_eff                                                                                                          
EME_Gasoline_car_eff                                                                                                     
EME_LPG_car_eff                                                                                                          
HTL_freight_eff                                                                                                          
EMethanol_freight_eff                                                                                                    
Sea_fuels_sum                                                                                                            
Road_fuels_sum                                                                                                           
Air_fuels_sum                                                                                                            
SeaBuffer                                                                                                                
RoadBuffer                                                                                                               
AirBuffer                                                                                                                
                                                                                                                         
AmmoniaBuffer_Exp                                                                                                        
Ammonia_Eff                                                                                                              
HTLBuffer_Exp                                                                                                            
HTL_Eff                                                                                                                  
                                                                                                                         
BioJetBuffer_Exp                                                                                                         
BioJet_Eff                                                                                                               
E_FT_JetBuffer_Exp                                                                                                       
E_FT_Jet_Eff                                                                                                             
EME_JetBuffer_Exp                                                                                                        
EME_Jet_Eff                                                                                                              
                                                                                                                         
BioGasolineBuffer_Exp                                                                                                    
BioGasoline_Eff                                                                                                          
MethanolBuffer_Exp                                                                                                       
Methanol_Eff                                                                                                             
EthanolBuffer_Exp                                                                                                        
Ethanol_Eff                                                                                                              
BiodieselBuffer_Exp                                                                                                      
Biodiesel_Eff                                                                                                            
                                                                                                                         
                                                                                                                         
E_FT_DieselBuffer_Exp                                                                                                    
E_FT_Diesel_Eff                                                                                                          
EME_GasolineBuffer_Exp                                                                                                   
EME_Gasoline_Eff                                                                                                         
EME_LPGBuffer_Exp                                                                                                        
EME_LPG_Eff                                                                                                              
EMethanolBuffer_Exp                                                                                                      
EMethanol_Eff                                                                                                            
                                                                                                                         
DieselBuffer                                                                                                             
GasBuffer                                                                                                                
ElecBuffer                                                                                                               
HeatBuffer                                                                                                               
BioSyngasBuffer                                                                                                          
BiogasBuffer                                                                                                             
BiodieselBuffer                                                                                                          
MethanolBuffer                                                                                                           
EthanolBuffer                                                                                                            
BioJetBuffer                                                                                                             
BioGasolineBuffer                                                                                                        
BioGasoline_SUM                                                                                                          
                                                                                                                         
Passenger_RE_fuels_sum                                                                                                   
Passenger_RE_fuels_Buffer                                                                                                
                                                                                                                         
                                                                                                                         
Freight_RE_fuels_sum                                                                                                     
Freight_RE_fuels_Buffer                                                                                                  
                                                                                                                         
                                                                                                                         
                                                                                                                         
Other_Gas_Source                                                                                                         
Other_Gas_Gen                                                                                                            
Other_Gas_Proc                                                                                                           
                                                                                                                         
*ProcEximGasPipe                                                                                                         
GasNode                                                                                                                  
LinePack                                                                                                                 
GasDemandNode                                                                                                            
GasDemand                                                                                                                
                                                                                                                         
NorthSeaGas                                                                                                              
                                                                                                                         
                                                                                                                         
                                                                                                                         
                                                                                                                         
                                                                                                                         
/;                                                                                                                       
