SET FLOWINDIC(FLOW) "The Indicators that we are interested in evaluating"
                                                                         
/                                                                        
OPERATIONCOST                                                            
GHGEMISSION_nonbio                                                       
GHGEMISSION_bio                                                          
/;                                                                       
