SET PROCSINK(PROC) "End PROC (no trace leaving it)"
/                                                  
Tar                                                
AirBuffer                                          
CO2_Seq_Buffer                                     
CO2_Biochar_Buffer                                 
Money_buffer_T                                     
RoadBuffer                                         
SeaBuffer                                          
/;                                                 
