PARAMETER MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                 
/                                                                                                           
                                                                                                            
/;                                                                                                          
