SET AAASOURCE(AAA)     'Areas that are used in the OptiFLow calculations'
                                                                         
                                                                         
/                                                                        
DK1_Large                                                                
DK1_Rural                                                                
DK1_Medium                                                               
DK2_Large                                                                
DK2_Rural                                                                
DK2_Medium                                                               
DK2_MedSmall                                                             
DK1_Small                                                                
DK1_MedSmall                                                             
DK2_Small                                                                
DK2_NoDH                                                                 
DK1_NoDH                                                                 
                                                                         
UK_A                                                                     
                                                                         
                                                                         
                                                                         
                                                                         
/;                                                                       
