$ONTEXT
PARAMETER TECH_GROUP_VALUE(TECH_GROUP)              'Technology Groups value'
/
ResA                                            .       ResA
ResB                                            .       ResB
ResC                                            .       ResC
ResD                                            .       ResD

ProA                                            .       ProA
ProB                                            .       ProB
ProD                                            .       ProD

StoA                                            .       StoA
StoD                                            .       StoD

Sum                                             .       Sum
Demand                                          .       Demand

Wood                                            .       Wood
Straw                                           .       Straw
Muni_Waste                                      .       Muni_Waste
Wood_Pellets                                    .       Wood_Pellets
Manure                                          .       Manure
Deep_Litter                                     .       Deep_Litter
Food_Waste                                      .       Food_Waste
Nature_Area                                     .       Nature_Area
Excess_Heat_OptiFlow                            .       Excess_Heat_OptiFlow
EMethanolBuffer                                 .       EMethanolBuffer
EMethanol_Upgrade                               .       EMethanol_Upgrade
E_FT                                            .       E_FT
AmmoniaBuffer                                   .       AmmoniaBuffer
CO2_PH                                          .       CO2_PH
CO2_IND                                         .       CO2_IND
CO2_DAC                                         .       CO2_DAC
CO2_Bio                                         .       CO2_Bio
EME_GasolineBuffer                              .       EME_GasolineBuffer
EME_JetBuffer                                   .       EME_JetBuffer
EME_LPGBuffer                                   .       EME_LPGBuffer
HTLBuffer                                       .       HTLBuffer
E_FT_JetBuffer                                  .       E_FT_JetBuffer
E_FT_DieselBuffer                               .       E_FT_DieselBuffer
MethanolBuffer                                  .       MethanolBuffer
BioGasolineBuffer                               .       BioGasolineBuffer
BiodieselBuffer                                 .       BiodieselBuffer
BioJetBuffer                                    .       BioJetBuffer
EthanolBuffer                                   .       EthanolBuffer
BioJet                                          .       BioJet
Ethanol                                         .       Ethanol
Methane_synthesis                               .       Methane_synthesis
Methanol_synthesis                              .       Methanol_synthesis
Gasifier                                        .       Gasifier
Biodiesel                                       .       Biodiesel
SNG                                             .       SNG
SYNGAS                                          .       SYNGAS
Pre-process-BG                                  .       Pre-process-BG
Biogas                                          .       Biogas
BiogasUpgr                                      .       BiogasUpgr
Methanation_Biogas                              .       Methanation_Biogas
Biogasoline                                     .       Biogasoline
Hydrogen                                        .       Hydrogen
BioOil                                          .       BioOil
OtherGas        .       OtherGas

/;
$OFFTEXT