SET AAAOPTIFLOW_OFF(AAA)     'Offshore areas used in the OptiFlow calculations'
                                                                               
/                                                                              
*HR_OFF_A                                                                      
*GR_OFF_A                                                                      
*IE_OFF_A                                                                      
*ITF_OFF_A                                                                     
*ITH_OFF_A                                                                     
*LT_OFF_A                                                                      
NO0A2_OFF_A                                                                    
NO092_OFF_A                                                                    
NO0A1_OFF_A                                                                    
*PT_OFF_A                                                                      
*UK_GB_OFF_A                                                                   
/;                                                                             
