PARAMETER PROCKAPNEWSCALE(PROC)  "Relationship at PROC between coming (index 3) and leaving (index 4) FLOW; interior PROC only"     
                                                                                                                                    
/                                                                                                                                   
*Methanol_synthesis_TG_50                                                                                                       500 
                                                                                                                                    
$ontext                                                                                                                             
TG_FT_Biodiesel_50_WO                                                                                                           500 
TG_FT_Biodiesel_50_WP                                                                                                           500 
TG_FT_Biodiesel_50_ST                                                                                                           500 
TG_FT_Biodiesel_50_MW                                                                                                           500 
                                                                                                                                    
ThermGasific_SNG_50_WO                                                                                                          500 
ThermGasific_SNG_50_WP                                                                                                          500 
ThermGasific_SNG_50_ST                                                                                                          500 
ThermGasific_SNG_50_MW                                                                                                          500 
                                                                                                                                    
TG_50_WO                                                                                                                        500 
TG_50_WP                                                                                                                        500 
TG_50_ST                                                                                                                        500 
TG_50_MW                                                                                                                        500 
                                                                                                                                    
*Methane_synthesis_TG_50                                                                                                            
                                                                                                                                    
                                                                                                                                    
Ethanol_50                                                                                                                      500 
                                                                                                                                    
                                                                                                                                    
BioJet_50_ST                                                                                                                    500 
BioJet_50_WO                                                                                                                    500 
BioJet_50_WP                                                                                                                    500 
                                                                                                                                    
ThermGasific_SNG_50_WO                                                                                                          200 
ThermGasific_SNG_50_WP                                                                                                          200 
ThermGasific_SNG_50_ST                                                                                                          200 
ThermGasific_SNG_50_MW                                                                                                          200 
                                                                                                                                    
$offtext                                                                                                                            
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
$ontext                                                                                                                             
                                                                                                                                    
MSW_chp_large                                                                                                                   70  
MSW_chp_medium                                                                                                                  25  
MSW_chp_small                                                                                                                   10  
MSW_chp_verysmall                                                                                                               5   
                                                                                                                                    
MSW_ho_large                                                                                                                    70  
MSW_ho_medium                                                                                                                   25  
MSW_ho_small                                                                                                                    10  
MSW_ho_verysmall                                                                                                                5   
                                                                                                                                    
$offtext                                                                                                                            
                                                                                                                                    
                                                                                                                                    
/;                                                                                                                                  
