TABLE APKNDISCDATA(PROC,APKNDISCSIZESET,APKNDISCDATASET) "Investment data for discrete Process capacity size investments (addon apkndisc)"
                                                                                                                                          
/                                                                                                                                         
                                                                                                                                          
                                                                                                                                          
/;                                                                                                                                        
