PARAMETER NEGPOL_Y_C(YYY,CCC) ""                         
/                                                        
2050                             .    BELGIUM        0   
2050                             .    DENMARK        0   
2050                             .    ESTONIA        0   
2050                             .    FINLAND        0   
2050                             .    GERMANY        0   
2050                             .    LATVIA         0   
2050                             .    NETHERLANDS    0   
2050                             .    NORWAY         0   
2050                             .    POLAND         0   
2050                             .    SWEDEN         0   
2050                             .    UNITED_KINGDOM 0   
/;                                                       
