PARAMETER SOSIBU2INDIC_AST(AAA,PROC,FLOW,FLOWINDIC,SSS,TTT) "Coefficients for transformation of VSOURCE, VSINK and VBUFFER flows to FLOWINDIC values"
/                                                                                                                                                    
                                                                                                                                                     
                                                                                                                                                     
/;                                                                                                                                                   
