SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
ProcExim_Truck_Fuel                                                 
ProcExim_Ship_Fuel                                                  
ProcExim_Truck_CO2                                                  
ProcExim_Ship_CO2                                                   
ProcExim_Pipeline_CO2                                               
/;                                                                  
