SET PROCTIMELINK(PROC) "TIME LINK STORAGE processes"
                                                    
/                                                   
                                                    
Linkstorage_Res                                     
                                                    
                                                    
/;                                                  
