PARAMETER PROCSTORAGEBOUND(YYY,AAA,PROC) "Upper bound (capacity) of Storage for Flow (U)"
/                                                                                        
                                                                                         
                                                                                         
                                                                                         
                                                                                         
/;                                                                                       
