PARAMETER PROCEXIM_ENDO_FUEL(PROC, FLOW) 'Subset of (PROCEXIM,FLOWEXIM) where onboard fuel use is endogenised as relative efficiency loss'                                          
/                                                                                                                                                                                   
ProcExim_Ship_Oil                                                                                                                          .    E_FT_DIESEL_FLOW 5.454545454545E-006
ProcExim_Ship_Methanol                                                                                                                     .    METHANOLFLOW     1.206030150754E-005
ProcExim_Ship_Methanol                                                                                                                     .    EMETHANOLFLOW    1.206030150754E-005
ProcExim_Ship_Ammonia                                                                                                                      .    AMMONIA_FLOW     1.290322580645E-005
ProcExim_Ship_Hydrogen                                                                                                                     .    HYDROGEN_FLOW    2E-006             
/;                                                                                                                                                                                  
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
