SET PROCSTORAGE_YT(PROC) "PROC that handles interseasonal storage - annual balance that can also be used intraseasonally"
/                                                                                                                        
                                                                                                                         
/                                                                                                                        
;                                                                                                                        
