SET WASTETREATMENT 'Categories of waste treatment for building up output results'
                                                                                 
/                                                                                
                                                                                 
                                                                                 
                                                                                 
/;                                                                               
