SET PROC "All 'transformations' that we use"                                                                       
/                                                                                                                  
* NB: for debugging, print and ailing memory nice to have FLOW elements in UPPERCASE og Proc elements in CamelCase.
                                                                                                                   
ResA                                                                                                               
ProA                                                                                                               
                                                                                                                   
StoA                                                                                                               
                                                                                                                   
SumA                                                                                                               
                                                                                                                   
ResB                                                                                                               
ProB                                                                                                               
                                                                                                                   
ResC                                                                                                               
                                                                                                                   
ResD                                                                                                               
ProD                                                                                                               
ProDD                                                                                                              
StoD                                                                                                               
                                                                                                                   
Sum                                                                                                                
                                                                                                                   
Demand                                                                                                             
                                                                                                                   
MethanolTotal_sum                                                                                                  
MethanolTotal                                                                                                      
Methanol_Sum                                                                                                       
                                                                                                                   
Nitrogen_Production                                                                                                
Ammonia_Synthesis                                                                                                  
AmmoniaBuffer                                                                                                      
Ammonia_freight_eff                                                                                                
EMethanolBuffer                                                                                                    
HTLBuffer                                                                                                          
E_FT_JetBuffer                                                                                                     
E_FT_DieselBuffer                                                                                                  
E_FT_NaphthaBuffer                                                                                                 
EME_JetBuffer                                                                                                      
EME_GasolineBuffer                                                                                                 
EME_LPGBuffer                                                                                                      
CO2_Source_PH                                                                                                      
CO2_Source_IND                                                                                                     
CO2_Source_DAC                                                                                                     
CO2_PH                                                                                                             
CO2_IND                                                                                                            
CO2_DAC                                                                                                            
CO2_Bio                                                                                                            
CO2                                                                                                                
CO2_Grid_In                                                                                                        
CO2_Grid_Out                                                                                                       
CO2_Sto                                                                                                            
CO2_Before_Use                                                                                                     
CO2_After_Sto                                                                                                      
CO2_Use                                                                                                            
CO2_Sink                                                                                                           
CO2_Bio_Pot                                                                                                        
EMethanol_synthesis                                                                                                
EMethanol_Upgrade                                                                                                  
E_FT                                                                                                               
E_FT_Sum                                                                                                           
EME_Upgrade_Sum                                                                                                    
EMethanolTotal                                                                                                     
HTL_ST                                                                                                             
HTL_WO                                                                                                             
HTL_WP                                                                                                             
HTL_Sum                                                                                                            
EMethanol_car_eff                                                                                                  
E_FT_Jet_car_eff                                                                                                   
E_FT_Diesel_car_eff                                                                                                
EME_Jet_car_eff                                                                                                    
EME_Gasoline_car_eff                                                                                               
EME_LPG_car_eff                                                                                                    
HTL_freight_eff                                                                                                    
EMethanol_freight_eff                                                                                              
Sea_fuels_sum                                                                                                      
Road_fuels_sum                                                                                                     
Air_fuels_sum                                                                                                      
SeaBuffer                                                                                                          
RoadBuffer                                                                                                         
AirBuffer                                                                                                          
                                                                                                                   
AmmoniaBuffer_Exp                                                                                                  
Ammonia_Eff                                                                                                        
HTLBuffer_Exp                                                                                                      
HTL_Eff                                                                                                            
                                                                                                                   
BioJetBuffer_Exp                                                                                                   
BioJet_Eff                                                                                                         
E_FT_JetBuffer_Exp                                                                                                 
E_FT_Jet_Eff                                                                                                       
EME_JetBuffer_Exp                                                                                                  
EME_Jet_Eff                                                                                                        
                                                                                                                   
BioGasolineBuffer_Exp                                                                                              
BioGasoline_Eff                                                                                                    
MethanolBuffer_Exp                                                                                                 
Methanol_Eff                                                                                                       
EthanolBuffer_Exp                                                                                                  
Ethanol_Eff                                                                                                        
BiodieselBuffer_Exp                                                                                                
Biodiesel_Eff                                                                                                      
                                                                                                                   
                                                                                                                   
E_FT_DieselBuffer_Exp                                                                                              
E_FT_Diesel_Eff                                                                                                    
EME_GasolineBuffer_Exp                                                                                             
EME_Gasoline_Eff                                                                                                   
EME_LPGBuffer_Exp                                                                                                  
EME_LPG_Eff                                                                                                        
EMethanolBuffer_Exp                                                                                                
EMethanol_Eff                                                                                                      
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
BioLiquid_Import                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
EL_Bal_to_Opti_Conv                                                                                                
EL_grid_tariff                                                                                                     
ElecBuffer_GJ                                                                                                      
EL_Opti_to_Bal_Conv                                                                                                
                                                                                                                   
Heat_Bal_to_Opti_Conv                                                                                              
Heat_grid_tariff                                                                                                   
HeatBuffer_GJ                                                                                                      
Heat_Opti_to_Bal_Conv                                                                                              
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
Electro                                                                                                            
ElectroBuffer                                                                                                      
                                                                                                                   
                                                                                                                   
Money_buffer                                                                                                       
Money_buffer_T                                                                                                     
GHG_Buffer                                                                                                         
GHGbio_Buffer                                                                                                      
DieselBuffer                                                                                                       
GasBuffer                                                                                                          
ElecBuffer                                                                                                         
HeatBuffer                                                                                                         
BioSyngasBuffer                                                                                                    
BiogasBuffer                                                                                                       
BiodieselBuffer                                                                                                    
MethanolBuffer                                                                                                     
                                                                                                                   
EthanolBuffer                                                                                                      
                                                                                                                   
BioJetBuffer                                                                                                       
BioGasolineBuffer                                                                                                  
                                                                                                                   
                                                                                                                   
BioGasoline_SUM                                                                                                    
                                                                                                                   
                                                                                                                   
                                                                                                                   
Linkstorage_Res                                                                                                    
                                                                                                                   
                                                                                                                   
Wood_Source                                                                                                        
Straw_Source                                                                                                       
Muni_Waste_Source                                                                                                  
Wood_Pellets_Source                                                                                                
Manure_Source                                                                                                      
Deep_Litter_Source                                                                                                 
Food_Waste_Source                                                                                                  
Nature_Area_Source                                                                                                 
                                                                                                                   
                                                                                                                   
Wood_Gen                                                                                                           
Straw_Gen                                                                                                          
Muni_Waste_Gen                                                                                                     
Wood_Pellets_Gen                                                                                                   
Manure_Gen                                                                                                         
Deep_Litter_Gen                                                                                                    
Food_Waste_Gen                                                                                                     
Nature_Area_Gen                                                                                                    
                                                                                                                   
                                                                                                                   
Straw_Mass                                                                                                         
Wood_Mass                                                                                                          
Wood_Pellets_Mass                                                                                                  
Muni_Waste_Mass                                                                                                    
Manure_Mass                                                                                                        
Deep_Litter_Mass                                                                                                   
Food_Waste_Mass                                                                                                    
Nature_Area_Mass                                                                                                   
                                                                                                                   
                                                                                                                   
Wood                                                                                                               
Wood_Pellets                                                                                                       
Straw                                                                                                              
Muni_Waste                                                                                                         
Manure                                                                                                             
                                                                                                                   
Straw_Biogas                                                                                                       
                                                                                                                   
Mix_Fuel                                                                                                           
                                                                                                                   
ProcEximTruck                                                                                                      
ProcEximShip                                                                                                       
ProcEximTrain                                                                                                      
                                                                                                                   
ThermGasific_SNG_50_WO                                                                                             
ThermGasific_SNG_50_WP                                                                                             
ThermGasific_SNG_50_ST                                                                                             
ThermGasific_SNG_50_MW                                                                                             
                                                                                                                   
ThermGasific_Syngas_50_WO                                                                                          
ThermGasific_Syngas_50_WP                                                                                          
ThermGasific_Syngas_50_ST                                                                                          
ThermGasific_Syngas_50_MW                                                                                          
                                                                                                                   
                                                                                                                   
TG_50_WO                                                                                                           
TG_50_WP                                                                                                           
TG_50_ST                                                                                                           
TG_50_MW                                                                                                           
                                                                                                                   
                                                                                                                   
TG_FT_Biodiesel_50_WO                                                                                              
TG_FT_Biodiesel_50_WP                                                                                              
TG_FT_Biodiesel_50_ST                                                                                              
*TG_FT_Biodiesel_50_MW                                                                                             
                                                                                                                   
                                                                                                                   
                                                                                                                   
Biodiesel_FT_SUM                                                                                                   
                                                                                                                   
                                                                                                                   
Bio_SNG_SUM                                                                                                        
Bio_SNG_OUT                                                                                                        
                                                                                                                   
                                                                                                                   
Bio_Syngas_Grid_IN                                                                                                 
Bio_Syngas_GRID_OUT                                                                                                
                                                                                                                   
                                                                                                                   
Bio_TG_Grid_IN                                                                                                     
Bio_TG_Grid_OUT                                                                                                    
                                                                                                                   
                                                                                                                   
Tar                                                                                                                
Digestate                                                                                                          
                                                                                                                   
                                                                                                                   
*SumSTWB                                                                                                           
*BiogasProd_single                                                                                                 
                                                                                                                   
                                                                                                                   
                                                                                                                   
Manure_tank                                                                                                        
Straw_pre_BG                                                                                                       
Deep_Litter_pre_BG                                                                                                 
Food_Waste_pre_BG                                                                                                  
Nature_Area_pre_BG                                                                                                 
                                                                                                                   
                                                                                                                   
                                                                                                                   
BiogasProd_mix                                                                                                     
                                                                                                                   
                                                                                                                   
Biogas_Grid_SUM                                                                                                    
Biogas_Grid_IN                                                                                                     
Biogas_Grid_NoSTO                                                                                                  
Biogas_Grid_STO                                                                                                    
Biogas_Grid_After_STO                                                                                              
Biogas_Grid_OUT                                                                                                    
                                                                                                                   
                                                                                                                   
                                                                                                                   
BiogasUpgr_BMETH_50                                                                                                
                                                                                                                   
                                                                                                                   
Electrolysis_H2Prod                                                                                                
                                                                                                                   
Hydrogen_GRID_IN                                                                                                   
Hydrogen_GRID_OUT                                                                                                  
                                                                                                                   
Hydrogen_STO_Large                                                                                                 
Hydrogen_After_STO_Large                                                                                           
Hydrogen_STO_Small                                                                                                 
Hydrogen_After_STO_Small                                                                                           
                                                                                                                   
Hydrogen_Before_USE                                                                                                
Hydrogen_Use                                                                                                       
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
Methanisation_Bio_BioGas                                                                                           
Methane_synthesis_TG_50                                                                                            
Methanol_synthesis_TG_50                                                                                           
                                                                                                                   
Engine_Syngas_50                                                                                                   
Engine_Biogas_50                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
Ethanol_50                                                                                                         
                                                                                                                   
BioJet_50_ST                                                                                                       
BioJet_50_WO                                                                                                       
BioJet_50_WP                                                                                                       
                                                                                                                   
BioJet_50_ST_H2                                                                                                    
BioJet_50_WO_H2                                                                                                    
BioJet_50_WP_H2                                                                                                    
                                                                                                                   
BioJet_SUM                                                                                                         
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
Methanol_car_eff                                                                                                   
Ethanol_car_eff                                                                                                    
Biodiesel_car_eff                                                                                                  
BioGasoline_car_eff                                                                                                
                                                                                                                   
                                                                                                                   
Methanol_freight_eff                                                                                               
Ethanol_freight_eff                                                                                                
Biodiesel_freight_eff                                                                                              
BioGasoline_freight_eff                                                                                            
                                                                                                                   
                                                                                                                   
                                                                                                                   
Passenger_RE_fuels_sum                                                                                             
Passenger_RE_fuels_Buffer                                                                                          
                                                                                                                   
                                                                                                                   
Freight_RE_fuels_sum                                                                                               
Freight_RE_fuels_Buffer                                                                                            
                                                                                                                   
                                                                                                                   
                                                                                                                   
Other_Gas_Source                                                                                                   
Other_Gas_Gen                                                                                                      
Other_Gas_Proc                                                                                                     
                                                                                                                   
*ProcEximGasPipe                                                                                                   
GasNode                                                                                                            
LinePack                                                                                                           
GasDemandNode                                                                                                      
GasDemand                                                                                                          
                                                                                                                   
GtBioJet_50                                                                                                        
                                                                                                                   
GtMeOH_50                                                                                                          
                                                                                                                   
NorthSeaGas                                                                                                        
CSMR_50                                                                                                            
                                                                                                                   
                                                                                                                   
                                                                                                                   
                                                                                                                   
/;                                                                                                                 
