SET INCIN_TYPEFLOW/MASSFLOW, ENERGYFLOW, ELECTRICITY, HEAT/;                                     
                                                                                                 
SET  INCINFLOW(PROC,FLOW,INCIN_TYPEFLOW)    "Process data: capacity relative to FLOW and in flow"
/                                                                                                
                                                                                                 
                                                                                                 
                                                                                                 
                                                                                                 
/;                                                                                               
