* Transport distances from onshore centroids to offshore sequestration centroids

TRANSDIST1('ProcExim_Pipeline_CO2', 'GR_A', 'GR_OFF_A') = 231.03;
TRANSDIST1('ProcExim_Pipeline_CO2', 'HR_A', 'HR_OFF_A') = 183.09;
TRANSDIST1('ProcExim_Pipeline_CO2', 'IE_A', 'IE_OFF_A') = 176.56;
TRANSDIST1('ProcExim_Pipeline_CO2', 'ITF_A', 'ITF_OFF_A') = 211.47;
TRANSDIST1('ProcExim_Pipeline_CO2', 'ITH_A', 'ITH_OFF_A') = 181.08;
TRANSDIST1('ProcExim_Pipeline_CO2', 'LT_A', 'LT_OFF_A') = 253.99;
TRANSDIST1('ProcExim_Pipeline_CO2', 'NO092_A', 'NO092_OFF_A') = 140.42;
TRANSDIST1('ProcExim_Pipeline_CO2', 'NO0A1_A', 'NO0A1_OFF_A') = 154.42;
TRANSDIST1('ProcExim_Pipeline_CO2', 'NO0A2_A', 'NO0A2_OFF_A') = 209.06;
TRANSDIST1('ProcExim_Pipeline_CO2', 'PT_A', 'PT_OFF_A') = 91.14;
TRANSDIST1('ProcExim_Pipeline_CO2', 'UK_GB_A', 'UK_GB_OFF_A') = 439.14;
TRANSDIST1('ProcExim_Ship_CO2', 'GR_A', 'GR_OFF_A') = 231.03;
TRANSDIST1('ProcExim_Ship_CO2', 'HR_A', 'HR_OFF_A') = 183.09;
TRANSDIST1('ProcExim_Ship_CO2', 'IE_A', 'IE_OFF_A') = 176.56;
TRANSDIST1('ProcExim_Ship_CO2', 'ITF_A', 'ITF_OFF_A') = 211.47;
TRANSDIST1('ProcExim_Ship_CO2', 'ITH_A', 'ITH_OFF_A') = 181.08;
TRANSDIST1('ProcExim_Ship_CO2', 'LT_A', 'LT_OFF_A') = 253.99;
TRANSDIST1('ProcExim_Ship_CO2', 'NO092_A', 'NO092_OFF_A') = 140.42;
TRANSDIST1('ProcExim_Ship_CO2', 'NO0A1_A', 'NO0A1_OFF_A') = 154.42;
TRANSDIST1('ProcExim_Ship_CO2', 'NO0A2_A', 'NO0A2_OFF_A') = 209.06;
TRANSDIST1('ProcExim_Ship_CO2', 'PT_A', 'PT_OFF_A') = 91.14;
TRANSDIST1('ProcExim_Ship_CO2', 'UK_GB_A', 'UK_GB_OFF_A') = 439.14;
