* PARAMETER WEIGHT_T reflects how much of the day year each time period                                       
* represents expressed relatively between the time periods.                                                   
* Units: (none).                                                                                              
                                                                                                              
* A specific shouce is to set all values equal, this implies that the duration of all T-segments are the same.
                                                                                                              
                                                                                                              
 WEIGHT_T(TTT)=1;                                                                                             
