PARAMETER SOSIBU2INDIC_AS(AAA,PROC,FLOW,FLOWINDIC,SSS) "Coefficients for transformation of VSOURCE, VSINK and VBUFFER flows to FLOWINDIC values"
/                                                                                                                                               
/                                                                                                                                               
;                                                                                                                                               
