SET PROCSINK(PROC) "End PROC (no trace leaving it)"
/                                                  
                                                   
Tar                                                
Digestate                                          
                                                   
CO2_Sink                                           
                                                   
*Bottom_ash                                        
                                                   
/;                                                 
