SET PB_THRESHOLDS_SET 'Threshold values for the planetary boundaries'
/
SOS_CO2_sector   'Safe operating space for the carrying capacity climate change for the sector in balmorel'    
SOS_Ozone_depletion_sector 'Safe operating space for the carrying capacity ozone depletion for the sector in balmorel'
SOS_LU_sector 'Safe operating space for the carrying capacity land use for the sector in balmorel'
SOS_WU_sector 'Safe operating space for the carrying capacity water use for the sector in balmorel'
SOS_EUTROPHICATION_FRESHWATER_sector 'Safe operating space for the carrying capacity eutrophication freshwater for the sector in balmorel'
SOS_ECOTOXICITY_FRESHWATER_sector 'Safe operating space for the carrying capacity ecotoxicity freshwater for the sector in balmorel'
SOS_PM_sector 'Safe operating space for the carrying capacity particulate matter for the sector in balmorel'
*SOS_RADIATION_sector 'Safe operating space for the carrying capacity ionising radiation for the sector in balmorel'
SOS_ACIDIFICATION_sector 'Safe operating space for the carrying capacity acidification for the sector in balmorel'
SOS_RESOURCE_sector 'Safe operating space for the carrying capacity resource use, minerals and metals for the sector in balmorel'
/;