PARAMETER RAMPING_TECH_GROUP_VALUE(RAMPING_TECH_GROUP)  'Names of ramping technology groups'
/                                                                                           
STEAM_TURBINE_SUBCRITICAL      STEAM_TURBINE_SUBCRITICAL                                    
GAS_TURBINE        GAS_TURBINE                                                              
COMBINED_CYCLE     COMBINED_CYCLE                                                           
/;                                                                                          
