PARAMETER RAMPING_COSTS_DOWN(RAMPING_TECH_TYPE,RAMPING_TECH_GROUP,RAMPING_FUELS,RAMPING_RATE)                                                                                
/                                                                                                                                                                            
/;                                                                                                                                                                           
RAMPING_COSTS_DOWN(RAMPING_TECH_TYPE,RAMPING_TECH_GROUP,RAMPING_FUELS,RAMPING_RATE)=RAMPING_COSTS_UP(RAMPING_TECH_TYPE,RAMPING_TECH_GROUP,RAMPING_FUELS,RAMPING_RATE);       
