PARAMETER RAMPING_TECH_TYPE_VALUE(RAMPING_TECH_TYPE) 'Names of ramping technology types'
/                                                                                       
GCND GCND                                                                               
GEXT GEXT                                                                               
GBPR GBPR                                                                               
/;                                                                                      
