PARAMETER RAMPING_FUELS_VALUE(RAMPING_FUELS)
/                                           
NATGAS   NATGAS                             
LIGNITE   LIGNITE                           
HEAVYFUELOIL   HEAVYFUELOIL                 
PEAT   PEAT                                 
WOODWASTE   WOODWASTE                       
FUELOIL   FUELOIL                           
MUNIWASTE   MUNIWASTE                       
SHALE   SHALE                               
STRAW   STRAW                               
COAL   COAL                                 
RETORTGAS   RETORTGAS                       
OTHERGAS   OTHERGAS                         
BIOGAS   BIOGAS                             
BIOOIL   BIOOIL                             
LIGHTOIL   LIGHTOIL                         
LNG   LNG                                   
WOOD   WOOD                                 
WOODCHIPS   WOODCHIPS                       
WOODPELLETS   WOODPELLETS                   
NUCLEAR   NUCLEAR                           
/;                                          
