SET RAMPING_TECH_GROUP 'Technology group with ramping constraints'
 /                                                                
STEAM_TURBINE_SUBCRITICAL                                         
GAS_TURBINE                                                       
COMBINED_CYCLE                                                    
/;                                                                
