* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       01_3
* Range:       $A$1:$D$34
* -----------------------------------------------------
SET RRR(CCCRRRAAA)  'All regions'       
/                                       
DK1                            "DK_W"   
DK2                            "DK_E"   
                                        
FIN                                     
GER                                     
NE                                      
NO1                                     
NO2                                     
NO3                                     
NO4                                     
NO5                                     
SE1                                     
SE2                                     
SE3                                     
SE4                                     
UK                                      
EE                                      
LV                                      
LT                                      
PL                                      
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
/;                                      
                                        
* -----------------------------------------------------
