                                     
SET RRR(CCCRRRAAA)  'All regions'    
/                                    
DK1                            "DK_W"
DK2                            "DK_E"
                                     
FIN                                  
GER                                  
NE                                   
NO1                                  
NO2                                  
NO3                                  
NO4                                  
NO5                                  
SE1                                  
SE2                                  
SE3                                  
SE4                                  
UK                                   
EE                                   
LV                                   
LT                                   
PL                                   
/;                                   
                                     
