SET RRRAAA(RRR,AAA) "Areas in regions"                                                     
/                                                                                          
DK1                                                                 .    DK1_Large         
DK1                                                                 .    DK1_Rural         
DK1                                                                 .    DK1_Medium        
DK2                                                                 .    DK2_Large         
DK2                                                                 .    DK2_Rural         
DK2                                                                 .    DK2_Medium        
DK2                                                                 .    DK2_MedSmall      
DK1                                                                 .    DK1_Small         
DK1                                                                 .    DK1_MedSmall      
DK2                                                                 .    DK2_Small         
DK2                                                                 .    DK2_NoDH          
DK1                                                                 .    DK1_NoDH          
DK1                                                                 .    DK2_Rural         
DK2                                                                 .    DK2_Offshore      
DK1                                                                 .    DK1_Offshore      
                                                                                           
                                                                                           
FIN                                                                 .    FinA              
DE4-E                                                               .    DE4-E_A           
DE4-E                                                               .    DE4-E_Offshore_A  
DE4-N                                                               .    DE4-N_A           
DE4-N                                                               .    DE4-N_Offshore_A  
DE4-S                                                               .    DE4-S_A           
DE4-W                                                               .    DE4-W_A           
DE4-W                                                               .    DE4-W_Offshore_A  
Ne                                                                  .    NeA               
EE                                                                  .    EE_A              
EE                                                                  .    EE_Narva          
EE                                                                  .    EE_Tartu          
EE                                                                  .    EE_Parnu          
EE                                                                  .    EE_Tallinn        
EE                                                                  .    EE_Kohtla_Jarve   
EE                                                                  .    EE_Industry       
EE                                                                  .    EE_Small          
                                                                                           
LV                                                                  .    LV_A              
LV                                                                  .    LV_A1             
LV                                                                  .    LV_A2             
LV                                                                  .    LV_A3             
                                                                                           
LT                                                                  .    LT_A              
LT                                                                  .    LT_A1             
PL                                                                  .    PL_A              
PL                                                                  .    PL_A1             
                                                                                           
NO1                                                                 .    NO1_A1            
NO1                                                                 .    NO1_A2            
NO2                                                                 .    NO2_A1            
NO3                                                                 .    NO3_A1            
NO3                                                                 .    NO3_A2            
NO4                                                                 .    NO4_A1            
NO5                                                                 .    NO5_A1            
SE1                                                                 .    SE1A              
SE2                                                                 .    SE2A              
SE3                                                                 .    SE3A              
SE4                                                                 .    SE4A              
UK                                                                  .    UKA               
NE                                                                  .    NE_OFFSHORE       
UK                                                                  .    UK_OFFSHORE       
FIN                                                                 .    FIN_ESPOO         
FIN                                                                 .    FIN_HELS          
FIN                                                                 .    FIN_TAMP          
FIN                                                                 .    FIN_EL            
FIN                                                                 .    FIN_HP            
FIN                                                                 .    FIN_OTHER         
FIN                                                                 .    FIN_GAS           
SE1                                                                 .    SE1_EL            
SE1                                                                 .    SE1_OTHER         
SE2                                                                 .    SE2_EL            
SE2                                                                 .    SE2_OTHER         
SE3                                                                 .    SE3_STO           
SE3                                                                 .    SE3_GOT           
SE3                                                                 .    SE3_EL            
SE3                                                                 .    SE3_HP            
SE3                                                                 .    SE3_OTHER         
SE4                                                                 .    SE4_MAL           
SE4                                                                 .    SE4_EL            
SE4                                                                 .    SE4_HP            
SE4                                                                 .    SE4_OTHER         
/;                                                                                         
