SET RRRAAA(RRR,AAA) "Areas in regions"                                                      
/                                                                                           
FIN                                                                 .    FinA               
DE4-E                                                               .    DE4-E_A            
DE4-N                                                               .    DE4-N_A            
DE4-S                                                               .    DE4-S_A            
DE4-W                                                               .    DE4-W_A            
DE4-E                                                               .    DE4-E_nonDH        
DE4-N                                                               .    DE4-N_nonDH        
DE4-S                                                               .    DE4-S_nonDH        
DE4-W                                                               .    DE4-W_nonDH        
SE1                                                                 .    SE1A               
SE2                                                                 .    SE2A               
SE3                                                                 .    SE3A               
SE4                                                                 .    SE4A               
                                                                                            
EE                                                                  .    EE_A               
EE                                                                  .    EE_Enefit          
EE                                                                  .    EE_Industry        
EE                                                                  .    EE_Kohtla_Jarve    
EE                                                                  .    EE_Narva           
EE                                                                  .    EE_Parnu           
EE                                                                  .    EE_Rural           
EE                                                                  .    EE_Sillamae        
EE                                                                  .    EE_Tallinn         
EE                                                                  .    EE_Tartu           
EE                                                                  .    EE_Urban           
LT                                                                  .    LT_A               
LT                                                                  .    LT_KauU            
LT                                                                  .    LT_KlaU            
LT                                                                  .    LT_Other_DH        
LT                                                                  .    LT_Panevezys       
LT                                                                  .    LT_Rural           
LT                                                                  .    LT_SiaU            
LT                                                                  .    LT_VilU            
LV                                                                  .    LV_A               
LV                                                                  .    LV_Other_DH        
LV                                                                  .    LV_RigaR           
LV                                                                  .    LV_Rural           
NL                                                                  .    NL_A               
NL                                                                  .    NL_nonDH           
PL                                                                  .    PL_A               
PL                                                                  .    PL_Rural           
PL                                                                  .    PL_nonDH           
UK                                                                  .    UK_A               
UK                                                                  .    UK_nonDH           
                                                                                            
FIN                                                                 .    FI_large           
FIN                                                                 .    FI_large_gas       
FIN                                                                 .    FI_medium          
FIN                                                                 .    FI_medium_gas      
FIN                                                                 .    FI_small           
FIN                                                                 .    FI_small_gas       
FIN                                                                 .    FI_IND             
NO1                                                                 .    NO1_A1             
NO1                                                                 .    NO1_A2             
NO1                                                                 .    NO1_A3             
NO2                                                                 .    NO2_A1             
NO2                                                                 .    NO2_A2             
NO3                                                                 .    NO3_A1             
NO3                                                                 .    NO3_A2             
NO3                                                                 .    NO3_A3             
NO4                                                                 .    NO4_A1             
NO4                                                                 .    NO4_A2             
NO5                                                                 .    NO5_A1             
NO5                                                                 .    NO5_A2             
SE1                                                                 .    SE1_medium         
SE1                                                                 .    SE1_small          
SE2                                                                 .    SE2_medium         
SE2                                                                 .    SE2_small          
SE3                                                                 .    SE3_large          
SE3                                                                 .    SE3_medium         
SE3                                                                 .    SE3_small          
SE4                                                                 .    SE4_large          
SE4                                                                 .    SE4_medium         
SE4                                                                 .    SE4_small          
SE1                                                                 .    SE1_IND            
SE2                                                                 .    SE2_IND            
SE3                                                                 .    SE3_IND            
SE4                                                                 .    SE4_IND            
DK1                                                                 .    DK1_Large          
DK1                                                                 .    DK1_Rural          
DK1                                                                 .    DK1_Medium         
DK2                                                                 .    DK2_Large          
DK2                                                                 .    DK2_Rural          
DK2                                                                 .    DK2_Medium         
DK2                                                                 .    DK2_MedSmall       
DK1                                                                 .    DK1_Small          
DK1                                                                 .    DK1_MedSmall       
DK2                                                                 .    DK2_Small          
DK2                                                                 .    DK2_NoDH           
DK1                                                                 .    DK1_NoDH           
BE                                                                  .    BE_A               
BE                                                                  .    BE_nonDH           
FR                                                                  .    FR_A               
FR                                                                  .    FR_nonDH           
                                                                                            
DE4-E                                                               .    DE4-E_Offshore     
DE4-N                                                               .    DE4-N_Offshore     
DE4-W                                                               .    DE4-W_Offshore     
DK1                                                                 .    DK1_Offshore       
DK2                                                                 .    DK2_Offshore       
EE                                                                  .    EE_Offshore        
FIN                                                                 .    FI_Offshore        
UK                                                                  .    UK_Offshore        
LT                                                                  .    LT_Offshore        
LV                                                                  .    LV_Offshore        
NL                                                                  .    NL_Offshore        
NO5                                                                 .    NO_Offshore        
PL                                                                  .    PL_Offshore        
SE4                                                                 .    SE_Offshore        
DE4-E                                                               .    DE4-E_A_20-30      
DE4-N                                                               .    DE4-N_A_20-30      
DE4-S                                                               .    DE4-S_A_20-30      
DE4-W                                                               .    DE4-W_A_20-30      
DK1                                                                 .    DK1_20-30          
DK2                                                                 .    DK2_20-30          
EE                                                                  .    EE_20-30           
FIN                                                                 .    FInA_20-30         
UK                                                                  .    UK_20-30           
LT                                                                  .    LT_20-30           
LV                                                                  .    LV_20-30           
NL                                                                  .    NL_20-30           
NO3                                                                 .    NO3_20-30          
NO4                                                                 .    NO4_20-30          
NO2                                                                 .    NO2_20-30          
NO5                                                                 .    NO5_20-30          
NO1                                                                 .    NO1_20-30          
PL                                                                  .    PL_20-30           
SE1                                                                 .    SE1_20-30          
SE2                                                                 .    SE2_20-30          
SE3                                                                 .    SE3_20-30          
SE4                                                                 .    SE4_20-30          
DE4-N                                                               .    DE_Offshore_20-30  
DK1                                                                 .    DK1_Offshore_20-30 
DK2                                                                 .    DK2_Offshore_20-30 
EE                                                                  .    EE_Offshore_20-30  
FIN                                                                 .    FI_Offshore_20-30  
UK                                                                  .    UK_Offshore_20-30  
LT                                                                  .    LT_Offshore_20-30  
LV                                                                  .    LV_Offshore_20-30  
NL                                                                  .    NL_Offshore_20-30  
NO5                                                                 .    NO_Offshore_20-30  
PL                                                                  .    PL_Offshore_20-30  
SE4                                                                 .    SE_Offshore_20-30  
DE4-E                                                               .    DE4-E_A_30-40      
DE4-N                                                               .    DE4-N_A_30-40      
DE4-S                                                               .    DE4-S_A_30-40      
DE4-W                                                               .    DE4-W_A_30-40      
DK1                                                                 .    DK1_30-40          
DK2                                                                 .    DK2_30-40          
EE                                                                  .    EE_30-40           
FIN                                                                 .    FInA_30-40         
UK                                                                  .    UK_30-40           
LT                                                                  .    LT_30-40           
LV                                                                  .    LV_30-40           
NL                                                                  .    NL_30-40           
NO3                                                                 .    NO3_30-40          
NO4                                                                 .    NO4_30-40          
NO2                                                                 .    NO2_30-40          
NO5                                                                 .    NO5_30-40          
NO1                                                                 .    NO1_30-40          
PL                                                                  .    PL_30-40           
SE1                                                                 .    SE1_30-40          
SE2                                                                 .    SE2_30-40          
SE3                                                                 .    SE3_30-40          
SE4                                                                 .    SE4_30-40          
DE4-N                                                               .    DE_Offshore_30-40  
DK1                                                                 .    DK1_Offshore_30-40 
DK2                                                                 .    DK2_Offshore_30-40 
EE                                                                  .    EE_Offshore_30-40  
FIN                                                                 .    FI_Offshore_30-40  
UK                                                                  .    UK_Offshore_30-40  
LT                                                                  .    LT_Offshore_30-40  
LV                                                                  .    LV_Offshore_30-40  
NL                                                                  .    NL_Offshore_30-40  
NO5                                                                 .    NO_Offshore_30-40  
PL                                                                  .    PL_Offshore_30-40  
SE4                                                                 .    SE_Offshore_30-40  
DE4-E                                                               .    DE4-E_A_40-50      
DE4-N                                                               .    DE4-N_A_40-50      
DE4-S                                                               .    DE4-S_A_40-50      
DE4-W                                                               .    DE4-W_A_40-50      
DK1                                                                 .    DK1_40-50          
DK2                                                                 .    DK2_40-50          
EE                                                                  .    EE_40-50           
FIN                                                                 .    FInA_40-50         
UK                                                                  .    UK_40-50           
LT                                                                  .    LT_40-50           
LV                                                                  .    LV_40-50           
NL                                                                  .    NL_40-50           
NO3                                                                 .    NO3_40-50          
NO4                                                                 .    NO4_40-50          
NO2                                                                 .    NO2_40-50          
NO5                                                                 .    NO5_40-50          
NO1                                                                 .    NO1_40-50          
PL                                                                  .    PL_40-50           
SE1                                                                 .    SE1_40-50          
SE2                                                                 .    SE2_40-50          
SE3                                                                 .    SE3_40-50          
SE4                                                                 .    SE4_40-50          
DE4-N                                                               .    DE_Offshore_40-50  
DK1                                                                 .    DK1_Offshore_40-50 
DK2                                                                 .    DK2_Offshore_40-50 
EE                                                                  .    EE_Offshore_40-50  
FIN                                                                 .    FI_Offshore_40-50  
UK                                                                  .    UK_Offshore_40-50  
LT                                                                  .    LT_Offshore_40-50  
LV                                                                  .    LV_Offshore_40-50  
NL                                                                  .    NL_Offshore_40-50  
NO5                                                                 .    NO_Offshore_40-50  
PL                                                                  .    PL_Offshore_40-50  
SE4                                                                 .    SE_Offshore_40-50  
DE4-E                                                               .    DE4-E_A_50         
DE4-N                                                               .    DE4-N_A_50         
DE4-S                                                               .    DE4-S_A_50         
DE4-W                                                               .    DE4-W_A_50         
DK1                                                                 .    DK1_50             
DK2                                                                 .    DK2_50             
EE                                                                  .    EE_50              
FIN                                                                 .    FInA_50            
UK                                                                  .    UK_50              
LT                                                                  .    LT_50              
LV                                                                  .    LV_50              
NL                                                                  .    NL_50              
NO3                                                                 .    NO3_50             
NO4                                                                 .    NO4_50             
NO2                                                                 .    NO2_50             
NO5                                                                 .    NO5_50             
NO1                                                                 .    NO1_50             
PL                                                                  .    PL_50              
SE1                                                                 .    SE1_50             
SE2                                                                 .    SE2_50             
SE3                                                                 .    SE3_50             
SE4                                                                 .    SE4_50             
DE4-N                                                               .    DE_Offshore_50     
DK1                                                                 .    DK1_Offshore_50    
DK2                                                                 .    DK2_Offshore_50    
EE                                                                  .    EE_Offshore_50     
FIN                                                                 .    FI_Offshore_50     
UK                                                                  .    UK_Offshore_50     
LT                                                                  .    LT_Offshore_50     
LV                                                                  .    LV_Offshore_50     
NL                                                                  .    NL_Offshore_50     
NO5                                                                 .    NO_Offshore_50     
PL                                                                  .    PL_Offshore_50     
SE4                                                                 .    SE_Offshore_50     
BE                                                                  .    BE_20-30           
BE                                                                  .    BE_30-40           
BE                                                                  .    BE_40-50           
BE                                                                  .    BE_50              
BE                                                                  .    BE_Offshore_20-30  
BE                                                                  .    BE_Offshore_30-40  
BE                                                                  .    BE_Offshore_40-50  
BE                                                                  .    BE_Offshore_50     
FR                                                                  .    FR_20-30           
FR                                                                  .    FR_30-40           
FR                                                                  .    FR_40-50           
FR                                                                  .    FR_50              
FR                                                                  .    FR_Offshore_20-30  
FR                                                                  .    FR_Offshore_30-40  
FR                                                                  .    FR_Offshore_40-50  
FR                                                                  .    FR_Offshore_50     
                                                                                            
                                                                                            
                                                                                            
                                                                                            
/;                                                                                          
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
                                                                                            
