SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S02,S16,S28,S40                                                                               
S12                                                                                            
/;                                                                                             
