SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S01                                                                                           
S02,S15,S25                                                                                    
/;                                                                                             
