SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S02,S08,S15,S21,S28,S34,S41,S47
*S02, S15, S34, S47      
S02, S15, S34, S47                                                             
/;                                                                                             
