SCALAR SELF_CONSUMPTION_RATE "How much of solar generation that can be used on site (and hence get indirect subsidy)"
* (Gustav 29.08.19) we have to assess how good such assumption is and perhaps find some source to back it up)        
/                                                                                                                    
0.5                                                                                                                  
/;                                                                                                                   
