SET  Y(YYY) "Years in the simulation"                               
/                                                                   
2030                                                                
                                                                    
/;                                                                  
                                                                    
SET C(CCC)  'Countries in the simulation'                           
/                                                                   
BELGIUM                                                             
DENMARK                                                             
ESTONIA                                                             
FINLAND                                                             
FRANCE                                                              
GERMANY                                                             
GREAT_BRITAIN                                                       
HOLLAND                                                             
LATVIA                                                              
LITHUANIA                                                           
NORWAY                                                              
POLAND                                                              
SWEDEN                                                              
                                                                    
/;                                                                  
                                                                    
SET SCENARIO     'All scenarios (one only:  /sc1*sc1/)'   /sc1*sc1/;
* To be used with:                                                  
* SET SCENARSIM(SCENARIO) 'Scenarios in simulation' /sc1/ ;         
* ALIAS(SCENARSIM,SC);                                              
                                                                    
*SET SCENARIO     'All scenarios'   /sc1*sc100/;                    
SET SCENARSIM(SCENARIO) 'Scenarios in simulation' /sc1/ ;           
ALIAS(SCENARSIM,SC);                                                
                                                                    
                                                                    
SET T(TTT)  'Time periods within a season in the simulation'        
/                                                                   
T001*t168                                                           
/;                                                                  
                                                                    
                                                                    
SET S(SSS)  'Seasons in the simulation'                             
/                                                                   
*S01,S05,S09,S13,S17,S21,S25,S29,S33,S37,S41,S45,S49                
*S01*S52                                                            
S02,S16,S25,S40                                                     
/;                                                                  
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
