* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       03(Sheet6)
* Range:       $A$8:$A$11
* -----------------------------------------------------
SET SSS  'All seasons'             
/                                  
S01*S52       'Seasons of the year'
 /;                                
* -----------------------------------------------------
