PARAMETER STEPWISEPRICE_GMIDF(YYY,CCC,STEPWISEPRICE_FFF)   'Amount of fuel for which the fuel price from FUELPRICE      INC holds (GJ) (only used for setting amounts)'                        
/                                                                                                                                                                                              
/;                                                                                                                                                                                             
*Not used                                                                                                                                                                                      
