PARAMETER SUBSIDIES_DH(CCC,DHUSER)                             'Consumers subsidy on heat consumption (Money/MWh)'     
*This does not exist in DK                                                                                             
/                                                                                                                      
$ontext                                                                                                                
DENMARK                                                                                                            0   
FINLAND                                                                                                            0   
GERMANY                                                                                                            0   
NORWAY                                                                                                             0   
SWEDEN                                                                                                             0   
ESTONIA                                                                                                            0   
LATVIA                                                                                                             0   
LITHUANIA                                                                                                          0   
POLAND                                                                                                             0   
$offtext                                                                                                               
/;                                                                                                                     
