$onMulti 
TABLE SUBTECHGROUPKPOT(CCCRRRAAA,TECH_GROUP,SUBTECH_GROUP) 'SubTechnology group capacity restriction by geography (MW)' 
      WINDTURBINE_ONSHORE.RG1 WINDTURBINE_ONSHORE.RG2 WINDTURBINE_ONSHORE.RG3 SOLARPV.RG1 SOLARPV.RG2 SOLARPV.RG3 WINDTURBINE_OFFSHORE.RG1 WINDTURBINE_OFFSHORE.RG2 WINDTURBINE_OFFSHORE.RG3
                                                                                                                                                                                            
DK1                    606.23                 2424.91                 5531.14    11560.25    21560.25         eps                      eps                 70240.00                      eps  
DK2                    193.77                  775.09                 2968.86     6936.15    12936.15         eps                      eps                 15200.00                      eps
FIN                   1500.00                 6000.00                 7500.00    14694.37    14694.37         eps                      eps                 34600.00                      eps       
DE4-E                 3274.08                13096.31                16370.39    59768.30    59768.30         eps                      eps                 16581.00                      eps
DE4-N                  984.17                 4305.32                 2388.25    19922.77    19922.77         eps                      eps                 11763.00                      eps
DE4-S                 3467.39                11637.31                14546.63    59768.30    59768.30         eps                      eps                      eps                      eps
DE4-W                 3760.23                12835.78                16044.72    59768.30    59768.30         eps                      eps                 47056.00                      eps
NL                    1030.00                 4120.00                 5150.00    24036.30    24036.30         eps                      eps                 68331.00                      eps       
NO1                    351.09                 1404.36                 1755.45     2329.13     2329.13         eps                      eps                      eps                      eps
NO2                    252.96                 1102.35                 1264.80     2329.13     2329.13         eps                      eps                  9355.00                      eps
NO3                    186.45                  845.75                  932.24     2329.13     2329.13         eps                      eps                  9509.00                      eps
NO4                    559.35                 2237.38                 2796.73     2329.13     2329.13         eps                      eps                  9675.00                      eps
NO5                     50.16                  200.62                  250.78     2329.13     2329.13         eps                      eps                  7000.00                      eps
SE1                    893.39                 3573.57                 4466.97     7328.70     7328.70         eps                      eps                 10750.00                      eps
SE2                   1103.60                 4414.41                 5518.02     7328.70     7328.70         eps                      eps                 10750.00                      eps
SE3                   1099.66                 4398.65                 5498.31     7328.70     7328.70         eps                      eps                 10750.00                      eps
SE4                    403.34                 1613.36                 2016.70     7328.70     7328.70         eps                      eps                 10750.00                      eps
UK                   12000.00                48000.00                60000.00    27251.34    81754.02   163508.04                      eps                165878.00                      eps     
EE                    1840.00                 7360.00                 9200.00    13019.02    13019.02         eps                      eps                 18700.00                      eps    
LV                    2330.00                 9320.00                11650.00    22873.50    22873.50         eps                      eps                 12800.00                      eps  
LT                    2140.00                 8560.00                10700.00    44821.35    44821.35         eps                      eps                  2000.00                      eps      
PL                   15000.00                60000.00                75000.00    30000.85    50000.85         eps                      eps                 11000.00                      eps      
BE                     890.00                 3560.00                 4450.00    10000.55    19229.55         eps                      eps                  7900.00                      eps
FR                   10120.00                40480.00                50600.00    35136.78   105410.35   230820.71                      eps                 53300.00                      eps      
IT                    3869.20                15476.80                19346.00    33366.29   100098.86   150197.72                      eps                 10000.00                      eps      
CH                     100.00                  400.00                  500.00    10000.53    48494.53         eps                      eps                      eps                      eps         
AT                     965.10                 3860.40                 4825.50    31471.46    31471.46         eps                      eps                      eps                      eps  
CZ                    1884.60                 7538.40                 9423.00    10000.27    49420.27         eps                      eps                      eps                      eps    
ES                   53500.00               214000.00               267500.00    32136.78    96410.35   190820.71                      eps                 10000.00                      eps  
PT                    2400.00                 9600.00                12000.00    12680.61    28680.61         eps                      eps                 10000.00                      eps      
SK                     210.00                  840.00                 1050.00    22950.00    22950.00         eps                      eps                      eps                      eps          
HU                      96.90                  240.00                  300.00    30200.00    43200.00         eps                      eps                      eps                      eps       
SI                      60.00                  240.00                  300.00     7600.00     9600.00         eps                      eps                      eps                      eps          
HR                     690.00                 2760.00                 3450.00    15700.00    26700.00         eps                      eps                  3998.00                      eps      
RO                    2040.00                 8160.00                10200.00    40000.00   103600.00         eps                      eps                 22420.00                      eps      
BG                     340.00                 1360.00                 1700.00    41800.00    51800.00         eps                      eps                  2103.00                      eps        
GR                    1152.52                 4610.08                 5762.60    40000.00    66000.00         eps                      eps                  9596.00                      eps
IE                    1358.91                 5435.64                 6794.55    15333.33    15333.33         eps                      eps                 20611.00                      eps
LU                      66.12                  264.46                  330.58      500.00      500.00         eps                      eps                      eps                      eps
AL                     200.00                  800.00                 1000.00     9000.00    13000.00         eps                      eps                      eps                      eps       
ME                      40.00                  160.00                  200.00     5400.00     6400.00         eps                      eps                      eps                      eps            
MK                      40.00                  160.00                  200.00     8500.00    12000.00         eps                      eps                      eps                      eps         
BA                     200.00                  800.00                 1000.00    12000.00    24350.00         eps                      eps                      eps                      eps       
RS                     119.10                  258.05                  200.00      500.00      500.00         eps                      eps                      eps                      eps     
TR                   11400.00                45600.00                57000.00    38715.00   116145.00   232290.00                      eps                 12400.00                      eps   
MT                        eps                     eps                     eps      500.00      500.00         eps                      eps                      eps                      eps
CY                      91.00                  196.00                   16.00    15000.00     5666.67         eps                      eps                      eps                      eps
;

* BE changed by hand because potential lower than installed capacity 1000->7900  10000.55  