                                                                                        
PARAMETER SUBTECH_GROUP_VALUE(SUBTECH_GROUP)              'SubTechnology Groups value'  
/                                                                                       
RG1                           RG1                                                       
RG2                            RG2                                                      
RG3                           RG3                                                       
RG1_OFF1                           RG1_OFF1                                             
RG2_OFF1                           RG2_OFF1                                             
RG3_OFF1                           RG3_OFF1                                             
RG1_OFF2                           RG1_OFF2                                             
RG2_OFF2                           RG2_OFF2                                             
RG3_OFF2                           RG3_OFF2                                             
RG1_OFF3                           RG1_OFF3                                             
RG2_OFF3                           RG2_OFF3                                             
RG3_OFF3                           RG3_OFF3                                             
RG1_OFF4                           RG1_OFF4                                             
RG2_OFF4                           RG2_OFF4                                             
RG3_OFF4                           RG3_OFF4                                             
RG1_OFF5                           RG1_OFF5                                             
RG2_OFF5                           RG2_OFF5                                             
RG3_OFF5                           RG3_OFF5                                             
HUB_OFF                            HUB_OFF                                              
AIR                           AIR                                                       
EXCESSHEAT                           EXCESSHEAT                                         
GROUND                           GROUND                                                 
/;                                                                                      
                                                                                        
