PARAMETER SUBTECH_GROUP_VALUE(SUBTECH_GROUP)              'SubTechnology Groups value'  
/                                                                                       
RG1                           RG1                                                       
RG2                            RG2                                                      
RG3                           RG3                                                                                                    
AIR                           AIR                                                       
EXCESSHEAT                           EXCESSHEAT                                         
GROUND                           GROUND                                                 
/;                                                                                      
