SET SUBTECH_GROUP           'SubTechnology Groups'  
/                                                   
RG1                                                 
RG2                                                 
RG3                                                                                           
AIR
HS                                               
EXCESSHEAT                                          
GROUND                                              
/;                                                  
                                              
