SET T(TTT)  'Time periods within a season in the simulation'                                                                                                                                                                                                                                                                                      
/    
*3 daily time slices, Monday and Saturday                                                                                                                                                                                                                                                                                                                                             
*T001, T010, T019, T100, T109, T115

*3-hour resolution, Monday
T001, T004, T007, T010, T013, T016, T019, T022
/;                                                                                                                                                                                                                                                                                                                                                
