***       Consumer tax on electricity consumption (Money / MWh)                                                       
                                                                                                                      
PARAMETER TAX_DE(CCC,DEUSER)                                    'Consumers tax on electricity consumption (Money/MWh)'
/                                                                                                                     
$ontext                                                                                                               
DENMARK   0                                                                                                           
FINLAND   0                                                                                                           
GERMANY   0                                                                                                           
NORWAY    0                                                                                                           
SWEDEN    0                                                                                                           
ESTONIA   0                                                                                                           
LATVIA    0                                                                                                           
LITHUANIA 0                                                                                                           
POLAND    0                                                                                                           
$offtext                                                                                                              
/;                                                                                                                    
