* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       50_2(Sheet61)
* Range:       $A$70:$E$76
* -----------------------------------------------------
*PARAMETER  TAX_KN(YYY,AAA,G) 'Taxes(+) and subsidies(-) for investment in electricity generation (MMoney/MW)' declared (with a $) in Balmorel version 3.02 (September 2011) but not here,                                                                                              
*should be if the $-condition is to be activated and data should be entered in this file.                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                        
PARAMETER                                                                                                                                                                                  TAX_KN(YYY,AAA,G) 'Tax (neg. subsidy) for investment in electricity generation (mEUR90/MW)'  
/                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
/;                                                                                                                                                                                                                                                                                      
* -----------------------------------------------------
