* -----------------------------------------------------
* XLS2GMS Version 1.5,  August 2002
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    \\nmbu.no\my\home\Documents\Prosjekter\Flex4RES\taxes\tax_data.xlsx
* Sheet:       TAX_DH
* Range:       $A$1:$C$17
* -----------------------------------------------------
***       Consumer tax on heat consumption (Money / MWh)                                                
                                                                                                        
                                                                                                        
PARAMETER TAX_DH(CCC,DHUSER)                             'Consumers tax on heat consumption (Money/MWh)'
/                                                                                                       
$ontext                                                                                                 
DENMARK   0                                                                                             
FINLAND   0                                                                                             
GERMANY   0                                                                                             
NORWAY    0                                                                                             
SWEDEN    0                                                                                             
ESTONIA   0                                                                                             
LATVIA    0                                                                                             
LITHUANIA 0                                                                                             
POLAND    0                                                                                             
$offtext                                                                                                
/;                                                                                                      
* -----------------------------------------------------
