* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       50_2(Sheet61)
* Range:       $A$39:$E$58
* -----------------------------------------------------
PARAMETER TAX_DH(CCC) 'Consumers tax on heat consumption (Money/MWh)'  
/                                                                      
$ontext                                                                
DENMARK   0                                                            
ESTONIA   0                                                            
FINLAND   0                                                            
GERMANY   0                                                            
LATVIA    0                                                            
LITHUANIA 0                                                            
NORWAY    0                                                            
POLAND    0                                                            
RUSSIA    0                                                            
SWEDEN    0                                                            
BELARUS   0                                                            
ESTONIA   0                                                            
LATVIA    0                                                            
LITHUANIA 0                                                            
POLAND    0                                                            
$offtext                                                               
/;                                                                     
* -----------------------------------------------------
