***            Consumer tax on electricity consumption (Money / MWh)                                                                         
***            2012                                                                                                                          
TABLE          TAX_DE(CCC,DEUSER)                                    'Consumers tax on electricity consumption (Money/MWh)'                  
               PII                                                   RESE                                                   OTHER            
;                                                                                                                                            
