* -----------------------------------------------------
* XLS2GMS 2.8      24.7.1 r56632 Released Mar 14, 2016 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       50_2(Sheet61)
* Range:       $A$12:$D$16
* -----------------------------------------------------
PARAMETER TAX_GF(YYY,AAA,G) 'Fuel taxes on generation units (Money/MWh)' 
                                                                         
/                                                                        
                                                                         
/;                                                                       
* -----------------------------------------------------
