ACRONYMS                                  IDVHG_OILB, IDVHG_GASB, IDVHG_WOODPB, IDVHG_STOV, IDVHG_ELB, IDVHG_ELHPA2A, IDVHG_HPA2W, IDVHG_GBHPA2W, IDVHG_SOL, IDVHG_COALB ;

PARAMETER TECH_GROUP_VALUE (TECH_GROUP)    'Technology Groups value'
/
STEAMTURBINE_SUBCRITICAL                  STEAMTURBINE_SUBCRITICAL
RESERVOIR_PMP                             RESERVOIR_PMP
WATERTURBINE                              WATERTURBINE
ENGINE_IC                                 ENGINE_IC
BOILER                                    BOILER
COMBINEDCYCLE                             COMBINEDCYCLE
EXCESS_HEAT                               EXCESS_HEAT
ELECTRICITY_BATTERY                       ELECTRICITY_BATTERY
GEOTHERMAL                                GEOTHERMAL
GASTURBINE                                GASTURBINE
HEATPUMP                                  HEATPUMP
*HEATPUMP_AIR                              HEATPUMP_AIR
*HEATPUMP_GROUND                           HEATPUMP_GROUND
*HEATPUMP_EXCESSHEAT                       HEATPUMP_EXCESSHEAT
PIT                                       PIT
WATERTANK                                 WATERTANK
SOLARPV                                   SOLARPV
*SOLARPV_RESIDENTIAL                       SOLARPV_RESIDENTIAL
*SOLARPV_COMMERCIAL                        SOLARPV_COMMERCIAL
SOLARHEATING                              SOLARHEATING
WINDTURBINE_OFFSHORE                     WINDTURBINE_OFFSHORE
*WINDTURBINE_OFFSHORE_FAR                  WINDTURBINE_OFFSHORE_FAR
*WINDTURBINE_OFFSHORE_NEARSHORE            WINDTURBINE_OFFSHORE_NEARSHORE
WINDTURBINE_ONSHORE                       WINDTURBINE_ONSHORE
/;









