TABLE TECHGROUPKPOT(CCCRRRAAA,TECH_GROUP)       'Technology group capacity restriction by geography (MW)'                         
                                                                                                                                  
                                                                                                                                  
                                                                                                          WINDTURBINE_ONSHORE     
DENMARK                                                                                                   6200                    
;