                                              
                                              
SET TECH_GROUP           'Technology Groups'  
/                                             
STEAMTURBINE_SUBCRITICAL                      
RESERVOIR_PMP                                 
WATERTURBINE                                  
ENGINE_IC                                     
BOILER                                        
COMBINEDCYCLE                                 
EXCESS_HEAT                                   
ELECTRICITY_BATTERY                           
GEOTHERMAL                                    
GASTURBINE                                    
HEATPUMP                                      
DUMMY                                         
PIT                                           
WATERTANK                                     
SOLARPV                                       
SOLARHEATING                                  
WINDTURBINE_ONSHORE                           
WINDTURBINE_OFFSHORE                          
BACKUP_ELECTRICITY                            
BACKUP_HEAT                                   
/;                                            
                                              
