                                                                                
PARAMETER TECH_GROUP_VALUE (TECH_GROUP)              'Technology Groups value'  
/                                                                               
STEAMTURBINE_SUBCRITICAL         STEAMTURBINE_SUBCRITICAL                       
RESERVOIR_PMP                    RESERVOIR_PMP                                  
WATERTURBINE                     WATERTURBINE                                   
ENGINE_IC                        ENGINE_IC                                      
BOILER                           BOILER                                         
COMBINEDCYCLE                    COMBINEDCYCLE                                  
EXCESS_HEAT                      EXCESS_HEAT                                    
ELECTRICITY_BATTERY              ELECTRICITY_BATTERY                            
GEOTHERMAL                       GEOTHERMAL                                     
GASTURBINE                       GASTURBINE                                     
HEATPUMP                         HEATPUMP                                       
HEATPUMP_AIR       HEATPUMP_AIR                                                 
HEATPUMP_GROUND      HEATPUMP_GROUND                                            
HEATPUMP_EXCESSHEAT        HEATPUMP_EXCESSHEAT                                  
PIT                              PIT                                            
WATERTANK                        WATERTANK                                      
SOLARPV                          SOLARPV                                        
SOLARHEATING                     SOLARHEATING                                   
WINDTURBINE_OFFSHORE_FAR         WINDTURBINE_OFFSHORE_FAR                       
WINDTURBINE_OFFSHORE_NEARSHORE   WINDTURBINE_OFFSHORE_NEARSHORE                 
WINDTURBINE_ONSHORE              WINDTURBINE_ONSHORE                            
WINDTURBINE_OFFSHORE_1         WINDTURBINE_OFFSHORE_1                           
WINDTURBINE_OFFSHORE_2         WINDTURBINE_OFFSHORE_2                           
WINDTURBINE_OFFSHORE_3         WINDTURBINE_OFFSHORE_3                           
/;                                                                              
                                                                                
                                                                                
                                                                                
