SET TECH_GROUP           'Technology Groups'
/

ResA
ResB
ResC
ResD

ProA
ProB
ProD

StoA
StoD



Sum

Demand

BioOil

STEAMTURBINE_SUBCRITICAL
STEAMTURBINE_SUPERCRITICAL
RESERVOIR_PMP
WATERTURBINE
ENGINE_IC
BOILER
COMBINEDCYCLE
EXCESS_HEAT
ELECTRICITY_BATTERY
GEOTHERMAL
GASTURBINE
HEATPUMP
DUMMY
PIT
WATERTANK
SOLARPV
SOLARHEATING
WINDTURBINE_ONSHORE
WINDTURBINE_OFFSHORE

EMethanolBuffer
EMethanol_Upgrade
E_FT
AmmoniaBuffer
CO2_PH
CO2_IND
CO2_DAC
CO2_Bio
EME_GasolineBuffer
EME_JetBuffer
EME_LPGBuffer
HTLBuffer
E_FT_JetBuffer
E_FT_DieselBuffer
MethanolBuffer
BioGasolineBuffer
BiodieselBuffer
BioJetBuffer
EthanolBuffer



BioJet
Ethanol


Methane_synthesis
Methanol_synthesis
Gasifier
Biodiesel
SNG
SYNGAS

Pre-process-BG

Biogas

BiogasUpgr
Methanation_Biogas


Biogasoline

Hydrogen


Wood
Straw
Muni_Waste
Wood_Pellets
Manure
Deep_Litter
Food_Waste
Nature_Area

Excess_Heat_OptiFlow

OtherGas

/;
