                                                                               
PARAMETER TECH_GROUP_VALUE(TECH_GROUP)              'Technology Groups value'  
/                                                                              
STEAMTURBINE_SUBCRITICAL         STEAMTURBINE_SUBCRITICAL                      
STEAMTURBINE_SUPERCRITICAL     STEAMTURBINE_SUPERCRITICAL                      
RESERVOIR_PMP                    RESERVOIR_PMP                                 
WATERTURBINE                     WATERTURBINE                                  
ENGINE_IC                        ENGINE_IC                                     
BOILER                           BOILER                                        
COMBINEDCYCLE                    COMBINEDCYCLE                                 
EXCESS_HEAT                      EXCESS_HEAT                                   
ELECTRICITY_BATTERY              ELECTRICITY_BATTERY                           
GEOTHERMAL                       GEOTHERMAL                                    
GASTURBINE                       GASTURBINE                                    
HEATPUMP                         HEATPUMP                                      
PIT                              PIT                                           
DUMMY                    DUMMY                                                 
WATERTANK                        WATERTANK                                     
SOLARPV                               SOLARPV                                  
SOLARHEATING                     SOLARHEATING                                  
WINDTURBINE_ONSHORE              WINDTURBINE_ONSHORE                           
WINDTURBINE_OFFSHORE            WINDTURBINE_OFFSHORE                           
BACKUP_ELECTRICITY            BACKUP_ELECTRICITY                               
BACKUP_HEAT           BACKUP_HEAT                                              
/;                                                                             
