* new parameter, similar to techgroup_deuser
TABLE TECHGROUP_DHUSER(TECH_GROUP,DHUSER)     "assignment of tech groups into user groups for electricity"

                                             SPACEHEAT                                                     HOTWATER  RESH
IDVHG_OILB                                   1                                                             1
IDVHG_GASB                                   1                                                             1
IDVHG_WOODPB                                 1                                                             1
IDVHG_STOV                                   1
IDVHG_ELB                                    1                                                             1
IDVHG_ELHPA2A                                1
IDVHG_HPA2W                                  1                                                             1
IDVHG_GBHPA2W                                1                                                             1
IDVHG_SOL                                                                                                  1
IDVHG_COALB                                  1                                                             1

*IDVHG_GASBSOLH                              1                                                             1
*IDVHG_WOODPBSOLH                            1                                                             1
;
