TABLE TECHGROUPKPOT(CCCRRRAAA,TECH_GROUP)       'Technology group capacity restriction by geography (MW)'                   
                                                                                                          RESERVOIR_PMP     
DK1                                                                                                       eps               
DK2                                                                                                       eps               
FIN                                                                                                       eps               
DE4-E                                                                                                     19320             
DE4-N                                                                                                     952.8             
DE4-S                                                                                                     17304             
DE4-W                                                                                                     9184              
NL                                                                                                        eps               
NO1                                                                                                       3729              
NO2                                                                                                       11317             
NO3                                                                                                       4583              
NO4                                                                                                       5257              
NO5                                                                                                       8116              
SE1                                                                                                       eps               
SE2                                                                                                       eps               
SE3                                                                                                       eps               
SE4                                                                                                       eps               
UK                                                                                                        26884             
EE                                                                                                        eps               
LV                                                                                                        eps               
LT                                                                                                        9000              
PL                                                                                                        16638             
FR                                                                                                        54000             
BE                                                                                                        11772             
;                                                                                                                           
