SET TECH_GROUP           'Technology Groups' 
/                                            
STEAMTURBINE_SUBCRITICAL                     
RESERVOIR_PMP                                
WATERTURBINE                                 
ENGINE_IC                                    
BOILER                                       
COMBINEDCYCLE                                
EXCESS_HEAT                                  
ELECTRICITY_BATTERY                          
GEOTHERMAL                                   
GASTURBINE                                   
HEATPUMP                                     
HEATPUMP_AIR                                 
HEATPUMP_GROUND                              
HEATPUMP_EXCESSHEAT                          
PIT                                          
WATERTANK                                    
SOLARPV                                      
SOLARPV_RESIDENTIAL                          
SOLARPV_COMMERCIAL                           
SOLARHEATING                                 
WINDTURBINE_OFFSHORE_FAR                     
WINDTURBINE_OFFSHORE_NEARSHORE               
WINDTURBINE_ONSHORE                          
                                             
IDVHG_OILB                                   
IDVHG_GASB                                   
IDVHG_WOODPB                                 
IDVHG_STOV                                   
IDVHG_ELB                                    
IDVHG_ELHPA2A                                
IDVHG_HPA2W                                  
IDVHG_GBHPA2W                                
IDVHG_SOL                                    
IDVHG_COALB                                  
*IDVHG_GASBSOLH                              
*IDVHG_WOODPBSOLH                            
/;                                           
                                             
                                             
                                             
                                             
                                             
                                             
                                             
                                             
                                             
                                             
                                             
