SCALAR TRANS_PEAKAVG_RATIO     'Peak to average ratio for demand related to other transport';                                                                                          
*DE ratio(peak/avg) is around 2,  solar production in the summer is arund 3 times higher than in the winter,  wind production in the winter is around 2 times higher than in the summer
TRANS_PEAKAVG_RATIO=1.5;                                                                                                                                                                 
