* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       03(Sheet6)
* Range:       $A$13:$A$16
* -----------------------------------------------------
SET TTT  'All time periods within a season'
/                                          
T001*T168  'Time period of the day'        
/;                                         
* -----------------------------------------------------
