* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       03(Sheet6)
* Range:       $A$21
* -----------------------------------------------------
SET TWEEKEND(TTT) 'Time segments, T, in weekends'    /T121*T168/;
* -----------------------------------------------------
