* Note: CARD(IUCT) must be at least as large as  GDATA( *,'GDUCDTMIN') and as GDATA( *,'GDUCUTMIN'). 
SET  IUCT 'Unit commitment: hour counter '  /IUCT01*IUCT24/;                                         
                                                                                                     
                                                                                                     
