PARAMETER UC_TECH_TYPE_VALUE(UC_TECH_TYPE) 'Names of UC technology types'
/                                                                        
GCND GCND                                                                
GEXT GEXT                                                                
GBPR GBPR                                                                
/;                                                                       
