PARAMETER UC_TECH_GROUP_VALUE(UC_TECH_GROUP)  'Names of UC technology groups'
/                                                                            
STEAMTURBINE_SUBCRITICAL      STEAMTURBINE_SUBCRITICAL                       
GASTURBINE        GASTURBINE                                                 
COMBINEDCYCLE     COMBINEDCYCLE                                              
/;                                                                           
