PARAMETER UC_TECH_GROUP_VALUE(UC_TECH_GROUP)  'Names of UC technology groups'
/                                                                            
STEAMTURBINE_SUBCRITICAL      STEAMTURBINE_SUBCRITICAL                       
STEAMTURBINE_SUPERCRITICAL        STEAMTURBINE_SUPERCRITICAL                 
GASTURBINE        GASTURBINE                                                 
COMBINEDCYCLE     COMBINEDCYCLE                                              
BOILER   BOILER                                                              
/;                                                                           
