SET UC_TECH_GROUP 'Technology group with UC constraints'
 /                                                      
STEAMTURBINE_SUBCRITICAL                                
STEAMTURBINE_SUPERCRITICAL                              
GASTURBINE                                              
COMBINEDCYCLE                                           
BOILER                                                  
/;                                                      
