* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data_T.xls
* Sheet:       54
* Range:       $A$1:$A$3
* -----------------------------------------------------
PARAMETER WAVE_VAR_T(AAA,SSS,TTT)               "Variation of the wave generation"
/                                                                                 
/;                                                                                
* -----------------------------------------------------
