* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       28(Sheet36)
* Range:       $A$343:$B$367
* -----------------------------------------------------
PARAMETER WAVEFLH(AAA)  'Full load hours for wave power (hours)'     
* NOT REAL DATA, DEMONSTRATION ONLY.                                 
/                                                                    
DK2_Medium                                                       816 
DK2_Rural                                                        816 
DK1_MedSmall                                                     816 
DK1_Rural                                                        816 
                                                                     
FinA                                                             1040
GerA                                                             1040
NeA                                                              1040
NO1_A1                                                           1040
NO2_A1                                                           1040
NO3_A1                                                           1040
NO4_A1                                                           1040
NO5_A1                                                           1040
SE1A                                                             1040
SE2A                                                             1040
SE3A                                                             1040
SE4A                                                             1040
UKA                                                              1040
EE_A                                                             1040
LV_A                                                             1040
LT_A                                                             1040
/;                                                                   
* -----------------------------------------------------
