PARAMETER WAVEFLH(AAA)  'Full load hours for wave power (hours)'     
* NOT REAL DATA, DEMONSTRATION ONLY.                                 
/                                                                    
DK2_Medium                                                       816 
DK2_Rural                                                        816 
DK1_MedSmall                                                     816 
DK1_Rural                                                        816 
NO1_A1                                                           1040
NO2_A1                                                           1040
NO3_A1                                                           1040
NO4_A1                                                           1040
NO5_A1                                                           1040
                                                                     
/;                                                                   
