PARAMETER WNDFLH(AAA)  'Full load hours for wind power (hours)'                        
/                                                                                      
DK2_NoDH                                                                           2959
DK1_NoDH                                                                           3199
FinA                                                                               1937
DE4-E_A                                                                            2263
DE4-N_A                                                                            2467
DE4-S_A                                                                            1887
DE4-W_A                                                                            2177
NO1_A1                                                                             2798
NO2_A1                                                                             2798
NO3_A1                                                                             2782
NO4_A1                                                                             3120
NO5_A1                                                                             2798
SE1A                                                                               2533
SE2A                                                                               2533
SE3A                                                                               2212
SE4A                                                                               2012
UKA                                                                                3176
                                                                                       
EE_A                                                                               2020
LV_A                                                                               2019
LT_A                                                                               1932
PL_A                                                                               2286
NeA                                                                                2860
                                                                                       
                                                                                       
DK2_Offshore                                                                       4380
DK1_Offshore                                                                       4466
DE4-E_Offshore_A                                                                   4380
DE4-N_Offshore_A                                                                   4477
DE4-W_Offshore_A                                                                   4477
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
NE_OFFSHORE                                                                        3964
UK_OFFSHORE                                                                        3324
                                                                                       
                                                                                       
/;                                                                                     
                                                                                       
PARAMETER SOLEFLH(AAA)  'Full load hours for solar power'                              
* Same data used for all regions as for Germany                                        
/                                                                                      
DK2_NoDH                                                                           850 
DK1_NoDH                                                                           850 
                                                                                       
FinA                                                                               900 
DE4-E_A                                                                            993 
DE4-N_A                                                                            993 
DE4-S_A                                                                            993 
DE4-W_A                                                                            993 
NeA                                                                                993 
NO1_A1                                                                             900 
NO2_A1                                                                             900 
NO3_A1                                                                             900 
NO4_A1                                                                             900 
NO5_A1                                                                             900 
SE1A                                                                               900 
SE2A                                                                               900 
SE3A                                                                               900 
SE4A                                                                               900 
UKA                                                                                958 
EE_A                                                                               900 
LV_A                                                                               900 
LT_A                                                                               900 
/;                                                                                     
                                                                                       
PARAMETER SOLHFLH(AAA)  'Full load hours for solar heat (hours)'                       
* NOT REAL DATA, DEMONSTRATION ONLY. Same data used for all regions as for Germany     
/                                                                                      
DK2_NoDH                                                                           816 
DK1_NoDH                                                                           816 
                                                                                       
FinA                                                                               1040
DE4-E_A                                                                            1040
DE4-N_A                                                                            1040
DE4-S_A                                                                            1040
DE4-W_A                                                                            1040
NeA                                                                                1040
NO1_A1                                                                             1040
NO2_A1                                                                             1040
NO3_A1                                                                             1040
NO4_A1                                                                             1040
NO5_A1                                                                             1040
SE1A                                                                               1040
SE2A                                                                               1040
SE3A                                                                               1040
SE4A                                                                               1040
UKA                                                                                1040
EE_A                                                                               1040
LV_A                                                                               1040
LT_A                                                                               1040
/;                                                                                     
                                                                                       
                                                                                       
                                                                                       
PARAMETER WAVEFLH(AAA)  'Full load hours for wave power (hours)'                       
* NOT REAL DATA, DEMONSTRATION ONLY.                                                   
/                                                                                      
DK2_Medium                                                                         816 
DK2_Rural                                                                          816 
DK1_MedSmall                                                                       816 
DK1_Rural                                                                          816 
                                                                                       
FinA                                                                               1040
DE4-E_A                                                                            1040
DE4-N_A                                                                            1040
DE4-S_A                                                                            1040
DE4-W_A                                                                            1040
NeA                                                                                1040
NO1_A1                                                                             1040
NO2_A1                                                                             1040
NO3_A1                                                                             1040
NO4_A1                                                                             1040
NO5_A1                                                                             1040
SE1A                                                                               1040
SE2A                                                                               1040
SE3A                                                                               1040
SE4A                                                                               1040
UKA                                                                                1040
EE_A                                                                               1040
LV_A                                                                               1040
LT_A                                                                               1040
/;                                                                                     
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
                                                                                       
