* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       28(Sheet36)
* Range:       $A$28:$B$49
* -----------------------------------------------------
PARAMETER WTRRRFLH(AAA) 'Full load hours for hydro run-of-river plants (hours)'                                              
* Includes the three options "dry", "wet" and "normal" according to which hydrological conditions to analyze                 
/                                                                                                                            
* Average year 2002-2011                                                                                                     
FinA                                                                                                         4200            
GerA                                                                                                         4819.86064070176
NeA                                                                                                          4200            
NO1_A1                                                                                                       4959.64280807429
NO2_A1                                                                                                       4024.96054108283
NO3_A1                                                                                                       3885.88067914058
NO4_A1                                                                                                       3527.4449090607 
NO5_A1                                                                                                       4658.3367394289 
SE1A                                                                                                         4865.15837104072
SE2A                                                                                                         4865.15837104072
SE3A                                                                                                         4865.15837104072
SE4A                                                                                                         4865.15837104072
UKA                                                                                                          3032.18920765027
EE_A                                                                                                         7500            
LV_A                                                                                                         2465            
LT_A                                                                                                         4800            
PL_A                                                                                                         2425            
/;                                                                                                                           
* -----------------------------------------------------
