SET X3VPLACE(X3VPLACE0) "Set of simulatd places with price dependent electricity exchange data"  
/                                                                                                
X3VGERMAN                                                                                        
X3VPOL                                                                                           
/;                                                                                               
