SET X3VX(RRR,X3VPLACE0) "Simulated transmisision lines for price dependent electricity exchange" ; 
X3VX('DK1','X3VGERMAN')=YES;                                                                       
X3VX('DK2','X3VGERMAN')=YES;                                                                       
X3VX('SE1','X3VGERMAN')=YES;                                                                       
 X3VX('SE2','X3VPOL')=YES;                                                                         
