SET RX3VSUBSTI(RRR,X3VPLACE0) "Substitutes in price dependent electricity exchange";                                                                  
*                                                                                     RX3VSUBSTI(RRR,X3VPLACE)=NO; /* This is used if no substitutes*/
*                                                                                     Give the real information, if any:                              
*                                                                                     RX3VSUBSTI('DE_R','X3VGERMAN')=YES;                             
*                                                                                     RX3VSUBSTI('PL_R','X3VPOL')=YES;                                
