SET X3VPLACE0 "Set of possible places with price dependent electricity exchange data" 
/                                                                                     
X3VGERMAN                                                                             
X3VPOL                                                                                
/;                                                                                    
