PARAMETER XMAXINV(IRRRE,IRRRI)   'Max investment in transmission capacity between two regions for each simulated year(each 5th year)'                           
                                                                                                                                                                
/                                                                                                                                                               
                                                                                                                                                       
/;                                                                                                                                                              
                                                                                                                                                                
