SET YMODEL                                    
                                              
/                                             
*ONEYEAR                                      
ONEYEAR,TWOYEAR                               
*ONEYEAR,TWOYEAR,THREEYEAR,FOURYEAR,FIVEYEAR  
                                              
/;                                            
                                              
                                              
