PARAMETER YMODELDELTA(YMODEL)                                                      
                                                                                   
/                                                                                  
*ONEYEAR 0                                                                         
ONEYEAR 0,TWOYEAR 1                                                                
*ONEYEAR 0,TWOYEAR 1,THREEYEAR 1                                                   
                                                                                   
                                                                                   
                                                                                   
                                                                                   
*ONEYEAR  0,TWOYEAR  1,THREEYEAR  1,FOURYEAR  1,FIVEYEAR  1,SIXYEAR  1,SEVENYEAR  1
                                                                                   
*ONEYEAR  0,TWOYEAR  1,THREEYEAR  1,FOURYEAR  1                                    
                                                                                   
                                                                                   
/;                                                                                 
                                                                                   
                                                                                   
                                                                                   
