* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Balmorel_git\Flex4RES_BalModel\base\data\Data.xls
* Sheet:       03(Sheet6)
* Range:       $A$27:$A$34
* -----------------------------------------------------
PARAMETER YVALUE(YYY) "Numerical value of the years' labels"                   
/                                                                              
   2012  2012,     2013  2013,      2014  2014,                                
   2015  2015,     2016  2016,     2017  2017,     2018  2018,      2019  2019,
   2020  2020,     2021  2021,     2022  2022,     2023  2023,      2024  2024,
   2025  2025,     2026  2026,     2027  2027,     2028  2028,      2029  2029,
   2030  2030                                                                  
/;                                                                             
* -----------------------------------------------------
